import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {createServer} from 'vite';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const output=process.env.PUNCH_QA_OUTPUT||'/private/tmp/meetro-63J4E8-C/evidence/layout';mkdirSync(output,{recursive:true});
const vite=await createServer({root:process.cwd(),logLevel:'silent',plugins:[{name:'employee-punch-ports',enforce:'pre',transform(source,id){if(id.endsWith('/EmployeeJobs.jsx'))return source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]\.\.\/utils\/timeEvidenceApi['"];?/,(_,names)=>names.split(',').map(n=>n.trim()).filter(Boolean).map(n=>`const ${n} = (...args) => window.__employeePunchPorts.${n}(...args);`).join('\n'));}}],server:{host:'127.0.0.1',port:0}});await vite.listen();
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const results=[];
try{for(const [width,height]of [[390,844],[393,852],[768,1024],[1024,768],[1440,900]]){
 const page=await browser.newPage({viewport:{width,height},hasTouch:true,isMobile:width<768});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.addInitScript(()=>{window.__gpsCalls=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(ok,fail,options){window.__gpsCalls++;window.__gps={ok,fail,options};}},configurable:true});});
 await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/tests/browser/employeePunchFixture.html`);await page.getByRole('button',{name:'Punch In',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__gpsCalls),0);
 const check=async(state)=>{const status=page.locator('.employee-punch-status');await status.scrollIntoViewIfNeeded();const m=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('.employee-time-page button')].filter(n=>n.getBoundingClientRect().height>0).map(n=>({height:n.getBoundingClientRect().height,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})),status:document.querySelector('.employee-punch-status').getBoundingClientRect().toJSON(),nav:document.querySelector('.employee-shell__nav--mobile')?.getBoundingClientRect().toJSON()}));assert.ok(m.scroll<=width+1,'Horizontal overflow '+width);assert.ok(m.buttons.every(b=>b.height>=44&&b.left>=0&&b.right<=width),'Clipped/small control '+width);if(m.nav?.height)assert.ok(m.status.bottom<=m.nav.top+1,'Status obscured by bottom nav');await page.screenshot({path:`${output}/${state}-${width}.png`,fullPage:true});return m;};
 await check('ready');await page.getByRole('button',{name:'Punch In',exact:true}).click();await page.getByRole('button',{name:'Checking location…',exact:true}).waitFor();assert.equal(await page.locator('.employee-time-clock-button').isDisabled(),true);await check('checking');await page.evaluate(()=>window.__gps.fail({code:1}));await page.getByRole('alert').waitFor();await check('denied');assert.equal(await page.evaluate(()=>window.__employeePunchPorts.calls.length),0);
 await page.getByRole('button',{name:'Punch In',exact:true}).click();await page.evaluate(()=>window.__gps.fail({code:2}));await page.getByText('Your location could not be verified. Check location services and retry.',{exact:true}).waitFor();await check('unavailable');
 await page.evaluate(()=>{window.__normalPunch=window.__employeePunchPorts.clockInTime;window.__employeePunchPorts.clockInTime=async()=>{throw Object.assign(new Error('You are outside the authorized punch location.'),{status:403,code:'PUNCH_OUTSIDE_SITE'});};});await page.getByRole('button',{name:'Punch In',exact:true}).click();await page.evaluate(()=>window.__gps.ok({coords:{latitude:27,longitude:-81,accuracy:8},timestamp:Date.now()}));await page.getByText('You are outside the authorized punch location.',{exact:true}).waitFor();await check('outside');
 await page.evaluate(()=>window.__employeePunchPorts.clockInTime=window.__normalPunch);await page.getByRole('button',{name:'Punch In',exact:true}).click();await page.evaluate(()=>window.__gps.ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));await page.getByRole('button',{name:'Punch Out',exact:true}).waitFor();await check('clocked-in');await page.getByRole('button',{name:'Punch Out',exact:true}).click();await page.evaluate(()=>window.__gps.ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));await page.getByRole('button',{name:'Punch In',exact:true}).waitFor();const m=await check('clocked-out');assert.equal(await page.evaluate(()=>window.__employeePunchPorts.calls.length),2);assert.deepEqual(errors,[]);results.push({width,height,states:['ready','permission pending/checking','denied','unavailable','outside','successful In','successful Out'],native:false,...m,pageErrors:errors});await page.close();
}writeFileSync(`${output}/results.json`,JSON.stringify(results,null,2));console.log('PASS: all five web viewports and seven employee Punch states. Native viewport emulation is not native device certification.');}finally{await browser.close();await vite.close();}
