import assert from 'node:assert/strict';import test from 'node:test';import React,{act} from 'react';import {JSDOM} from 'jsdom';import {createServer} from 'vite';import react from '@vitejs/plugin-react';
import {capturePunchPosition} from '../src/utils/punchPosition.js';import {punchPorts,JOB,ASSIGNMENT} from './fixtures/employeePunch.js';
const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'https://meetro.test/#employeeTime',pretendToBeVisual:true});const prior=Object.fromEntries(['window','document','navigator','IS_REACT_ACT_ENVIRONMENT'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
for(const [key,value]of Object.entries({window:dom.window,document:dom.window.document,navigator:dom.window.navigator,IS_REACT_ACT_ENVIRONMENT:true}))Object.defineProperty(globalThis,key,{value,configurable:true,writable:true});
const {createRoot}=await import('react-dom/client');const vite=await createServer({root:process.cwd(),configFile:false,cacheDir:'/private/tmp/meetro-63J4E8-C/vite-tests',optimizeDeps:{noDiscovery:true},server:{middlewareMode:true,hmr:false,ws:false},plugins:[react(),{name:'employee-punch-fixture',enforce:'pre',transform(source,id){if(id.endsWith('/EmployeeJobs.jsx'))return source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]\.\.\/utils\/timeEvidenceApi['"];?/,(_,names)=>names.split(',').map(n=>n.trim()).filter(Boolean).map(n=>`const ${n} = (...args) => globalThis.__employeePunchPorts.${n}(...args);`).join('\n'));}}]});
const {TimeEvidencePanel}=await vite.ssrLoadModule('/src/pages/EmployeeJobs.jsx');
async function run(callback){const root=createRoot(document.getElementById('root'));const ports=globalThis.__employeePunchPorts=punchPorts();let position,captureCount=0;
 Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition(ok,fail,options){captureCount++;position={ok,fail,options};}}});
 const render=async(props={})=>{await act(async()=>root.render(React.createElement(TimeEvidencePanel,{businessId:7,job:{id:JOB,title:'Kitchen service'},assignment:{id:ASSIGNMENT,activationVersion:1},variant:'full',setPage:()=>{},...props})));await act(async()=>{await new Promise(r=>setTimeout(r,15));});};
 const click=async()=>{await act(async()=>document.querySelector('.employee-time-clock-button').click());};
 try{await render();await callback({ports,root,render,click,position:()=>position,captureCount:()=>captureCount});}finally{await act(async()=>root.unmount());delete globalThis.__employeePunchPorts;}
}
test('strict foreground sample retains real zero and rejects coerced/malformed coordinates and accuracy',async()=>{
 const base={coords:{latitude:0,longitude:0,accuracy:8},timestamp:Date.now()};let options;
 const r=await capturePunchPosition({getCurrentPosition(ok,_,o){options=o;ok(base);}},()=>true);assert.equal(r.latitude,0);assert.equal(r.longitude,0);assert.equal(r.accuracyMeters,8);assert.ok(r.sampledAt.endsWith('Z'));assert.deepEqual(options,{enableHighAccuracy:true,timeout:10000,maximumAge:0});
 for(const change of [{latitude:null},{longitude:null},{latitude:'0'},{latitude:false},{latitude:NaN},{latitude:Infinity},{latitude:91},{accuracy:0},{accuracy:-1}])await assert.rejects(capturePunchPosition({getCurrentPosition(ok){ok({...base,coords:{...base.coords,...change}});}},()=>true),/incomplete/);
 let calls=0;await assert.rejects(capturePunchPosition({getCurrentPosition(){calls++;}},()=>false),/Open Meetro/);assert.equal(calls,0);
});
test('browsing does not collect GPS; explicit In/Out capture exact assignment with no double submission',async()=>run(async({ports,click,position,captureCount})=>{
 assert.equal(captureCount(),0);assert.match(document.querySelector('.employee-time-hero').textContent,/Kitchen service/);assert.match(document.body.textContent,/Location verification is required/);await click();assert.match(document.body.textContent,/Checking location/);assert.equal(document.querySelector('.employee-time-clock-button').disabled,true);await click();assert.equal(captureCount(),1);assert.equal(ports.calls.length,0);
 await act(async()=>position().ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));assert.equal(ports.calls.length,1);assert.equal(ports.calls[0][1].assignmentId,ASSIGNMENT);assert.equal(ports.calls[0][1].assignmentActivationVersion,1);assert.equal(ports.calls[0][1].location.accuracyMeters,8);assert.match(document.body.textContent,/Punch Out/);assert.match(document.body.textContent,/Location verified · Authorized warehouse/);
 await act(async()=>{await new Promise(r=>setTimeout(r,20));});assert.equal(captureCount(),1);await click();await act(async()=>position().ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));assert.equal(ports.calls[1][0],'out');assert.equal(ports.calls[1][1].sessionId,'timer-1');assert.equal(captureCount(),2);assert.match(document.body.textContent,/Punch In/);
}));
for(const code of [1,2,3])test('permission denied/unavailable/timeout '+code+' fails closed without time API',async()=>run(async({ports,click,position})=>{await click();await act(async()=>position().fail({code}));assert.equal(ports.calls.length,0);assert.match(document.querySelector('[role="alert"]').textContent,code===1?/permission/:/could not be verified/);assert.equal(document.querySelector('.employee-time-clock-button').disabled,false);}));
test('outside rejection remains actionable and does not show a success timer',async()=>run(async({ports,click,position})=>{ports.clockInTime=async()=>{throw Object.assign(new Error('You are outside the authorized punch location.'),{status:403,code:'PUNCH_OUTSIDE_SITE'});};await click();await act(async()=>position().ok({coords:{latitude:27,longitude:-81,accuracy:8},timestamp:Date.now()}));assert.match(document.querySelector('[role="alert"]').textContent,/outside/);assert.match(document.body.textContent,/Punch In/);}));
test('uncertain network outcome retries the exact command/sample without creating another operation',async()=>run(async({ports,click,position,captureCount})=>{const normal=ports.clockInTime;const calls=[];ports.clockInTime=async p=>{calls.push(structuredClone(p));if(calls.length===1)throw new Error('Connection unavailable. Retry your punch.');return normal(p);};await click();await act(async()=>position().ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));await click();assert.deepEqual(calls[0],calls[1]);assert.equal(captureCount(),1);}));
test('late sample is ignored after changing assignment',async()=>run(async({ports,click,position,render})=>{await click();const old=position();await render({assignment:{id:'33333333-3333-4333-8333-333333333333',activationVersion:3}});await act(async()=>old.ok({coords:{latitude:26.64,longitude:-81.98,accuracy:8},timestamp:Date.now()}));assert.equal(ports.calls.length,0);}));
test.after(async()=>{await vite.close();dom.window.close();for(const [k,d]of Object.entries(prior)){if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}});
