import assert from "node:assert/strict";
import test from "node:test";
import { t, translations } from "../src/utils/language.js";

const languages = ["en", "es", "fr", "pt-BR"];

const highTrafficKeys = [
  "homeLocalServicesEyebrow",
  "homeMyProjects",
  "homeMyProjectsSubtitle",
  "homeMyProjectsActive",
  "homeMyProjectsHistory",
  "homeLocalServicesSpotlight",
  "homeLocalServicesSubtitle",
  "homeLocalServicesEmpty",
  "homeOpenMessages",
  "communicationCenterTitle",
  "homeSpotlightStoryEyebrow",
  "homeSpotlightStoryBody",
  "homeSpotlightBusinessIntro",
  "homeSpotlightProofLine",
  "homeSpotlightRelationshipHint",
  "homeSpotlightReviewTrust",
  "homeSpotlightWorkProof",
  "homeSpotlightReviewCount",
  "homeSpotlightWorkProofCount",
  "homeSpotlightStoryPlaceholder",
  "homeSpotlightStoryKitchen",
  "homeSpotlightStoryOutdoor",
  "homeSpotlightStoryProtection",
  "homeSpotlightStoryPeaceful",
  "homeSpotlightStoryRelief",
  "homeSpotlightStoryTrust",
  "homeSpotlightStoryCommunity",
  "homeSpotlightStoryRenewal",
  "homeSpotlightStoryDefault",
  "homeRequestDetails",
  "homeServiceDetails",
  "homeOpenRequest",
  "homeViewRecord",
  "homeViewProfile",
  "myRequestsTitle",
  "myRequestsSubtitle",
  "myRequestsPerspectiveEyebrow",
  "myRequestsPerspectiveTitle",
  "myRequestsPerspectiveText",
  "myRequestsEmptyTitle",
  "myRequestsQuoteProposal",
  "myRequestsServiceHistory",
  "myRequestsSaveChanges",
  "wcFilterAll",
  "wcFilterOnSite",
  "wcFilterInProgress",
  "wcCurrentStatus",
  "wcNextStep",
  "wcViewDetails",
  "wcNoQuotesTitle",
  "wcNoActiveWorkTitle",
  "wcThisWeek",
  "wcThisMonth",
  "workCenterQuotesTitle",
  "workCenterActiveWorkTitle",
  "workCenterRevenueTitle",
  "activeJobs",
  "workCenterDashboardTitle",
  "workCenterPurposeStatement",
  "workCenterProfessionalPerspectiveLine",
  "workCenterHeaderEyebrow",
  "workCenterChildScheduleSummary",
  "workCenterChildScheduleEmptySummary",
  "workCenterChildQuotesSummary",
  "workCenterChildQuotesEmptySummary",
  "workCenterChildActiveSummary",
  "workCenterChildActiveEmptySummary",
  "workCenterChildRevenueSummary",
  "workCenterChildHistorySummary",
  "workCenterChildHistoryEmptySummary",
  "workCenterChildHistoryDescription",
  "newOpportunity",
  "newOpportunities",
  "activeJob",
  "visitToday",
  "visitsToday",
  "viewOpportunity",
  "viewOpportunities",
  "opportunityHeaderEyebrow",
  "opportunityDetailDescription",
  "opportunityCurrentStage",
  "opportunityNextStep",
  "awaitingReview",
  "noNewOpportunities",
  "communityTitle",
  "communityEntryTitle",
  "communityEntryHomeCopy",
  "communityEntryBusinessCopy",
  "communityOpenAction",
  "communitySubtitle",
  "communityGuideQuestion",
  "communityPreviewAria",
  "communityBusinessesTitle",
  "communityBusinessesCopy",
  "communityBusinessesEmptyTitle",
  "communityBusinessesEmptyText",
  "communityViewAllBusinesses",
  "communityHiringTitle",
  "communityHiringCopy",
  "communityHiringEmptyTitle",
  "communityHiringEmptyText",
  "communityViewAllHiring",
  "communitySpotlightTitle",
  "communitySpotlightCopy",
  "communitySpotlightEyebrow",
  "communitySpotlightCue",
  "communityExploreSpotlight",
  "communitySpotlightLocalProfessional",
  "communitySpotlightStoryTitle",
  "communitySpotlightStoryText",
  "communitySpotlightStoryFallbackTitle",
  "communitySpotlightStoryFallbackText",
  "communitySpotlightStoryFallbackMeta",
  "communitySpotlightBusinessSingular",
  "communitySpotlightBusinessPlural",
  "communitySpotlightCountMeta",
  "communitySpotlightPageTitle",
  "communitySpotlightPageSubtitle",
  "communitySpotlightStoryAria",
  "communitySpotlightFeaturedEyebrow",
  "communitySpotlightWarmupEyebrow",
  "communitySpotlightWarmupCue",
  "communitySpotlightPrincipleTitle",
  "communitySpotlightPrincipleText",
  "momentsBackToProfile",
  "momentsEyebrow",
  "momentsWelcomeText",
  "momentsPreservationStatementAria",
  "momentsPreservationStatementTitle",
  "momentsPreservationStatementText",
  "momentsPromiseAria",
  "momentsPromiseText",
  "momentsReflectionAria",
  "momentsReflectionLabel",
  "momentsVerifiedReflectionBody",
  "momentsViewMoment",
  "momentsSeeWhatMomentsBecome",
  "momentsStoryInspiration",
  "momentsStoryTakingOver",
  "momentsStoryCanBecome",
  "momentsInspirationText",
  "momentsInspirationAria",
  "momentsFutureMemory",
  "momentsCompleteOwnStory",
  "momentsVerifiedHistory",
  "momentsYourMoments",
  "momentsEmptyTitle",
  "momentsEmptyText",
  "momentsReceiptSaved",
  "momentsBeforeAfterPreviewAria",
  "momentsVerifiedLabel",
];

test("high-traffic Home, My Requests, and Work Center labels exist in four languages", () => {
  for (const key of highTrafficKeys) {
    for (const language of languages) {
      assert.equal(
        typeof translations[language][key],
        "string",
        `Missing ${language} translation for ${key}`
      );
      assert.ok(
        translations[language][key].trim(),
        `Empty ${language} translation for ${key}`
      );
      assert.notEqual(t(key, language), key, `${language} returned raw key ${key}`);
    }
  }
});

test("French and Portuguese use localized high-traffic labels instead of English fallback", () => {
  assert.equal(t("myRequestsTitle", "fr"), "Centre de travail");
  assert.equal(t("myRequestsTitle", "pt-BR"), "Work Center");
  assert.equal(t("workCenterQuotesTitle", "fr"), "Devis / propositions");
  assert.equal(t("workCenterQuotesTitle", "pt-BR"), "Orçamentos / Propostas");
  assert.equal(t("wcNoActiveWorkTitle", "fr"), "Aucun travail actif pour le moment.");
  assert.equal(t("wcNoActiveWorkTitle", "pt-BR"), "Nenhum trabalho ativo agora.");
  assert.equal(t("communityTitle", "fr"), "Communauté");
  assert.equal(t("communityTitle", "pt-BR"), "Comunidade");
  assert.equal(t("momentsYourMoments", "fr"), "Vos Meetro Moments");
  assert.equal(t("momentsYourMoments", "pt-BR"), "Seus Meetro Moments");
});
