import { normalizeLanguage } from "./language.js";

const COPY = Object.freeze({
  en: {
    title: "Ask Meetro",
    close: "Close",
    promptLabel: "What would you like help with?",
    promptPlaceholder: "Add any details you want Meetro to consider.",
    prepare: "Prepare suggestion",
    preparing: "Preparing suggestion",
    unavailable: "Ask Meetro is not connected yet. Your work is unchanged.",
    advisory: "Review every suggestion before adding it to your work.",
    add: "Add",
    addToEvaluation: "Add to Evaluation",
    addFinding: "Add Finding",
    addRecommendation: "Add Recommendation",
    applyToEstimate: "Apply to Estimate",
    useInQuote: "Use in Quote",
    useInInvoice: "Use in Invoice",
    edit: "Edit",
    dismiss: "Dismiss",
    saveEdit: "Save edit",
    observed: "Observed",
    professionalInput: "Professional input",
    needsVerification: "Needs verification",
    suggested: "Suggested",
    price: "Price",
    internalOnly: "Internal only",
    referencePrice: "Reference price",
    notGuaranteed: "Not a guaranteed cost",
    exactContext: "Helping with",
    noSilentChanges: "Nothing changes until you choose an action.",
    evaluation: "Evaluation",
    estimate: "Estimate & Quote",
    invoice: "Invoice",
    jobRequest: "Job Request",
    helpDescribe: "Help Describe This",
    whatCheck: "What Should I Check?",
    analyzePhotos: "Analyze Photos",
    analyzePhoto: "Analyze Photo",
    analyzePhotosWithCount: "Analyze {count} Photos",
    helpMeasurements: "Help with Measurements",
    turnIntoFindings: "Turn This into Findings",
    draftRecommendations: "Draft Recommendations",
    takePhoto: "Take Photo",
    uploadPhotos: "Upload Photos",
    uploadAdditionalPhotos: "Upload Photos",
    selectedPhotoReviewTitle: "Photos to analyze",
    photoCountSummary: "{count} photo(s) selected for analysis",
    uploadPhotoLabelFallback: "Photo",
    removePhoto: "Remove",
    selectPhoto: "Select",
    deselectPhoto: "Selected",
    selectPhotosFirst: "Select at least one confirmed photo to analyze.",
    selectPhotosHelp: "Select up to 5 confirmed photos to analyze.",
    canonicalPhotoTitle: "Evaluation photos",
    photoPosition: "Photo {current} of {total}",
    pendingPhotoTitle: "Adding photos",
    pendingPhotoHelp: "These photos cannot be analyzed until Meetro confirms them.",
    pendingPhoto: "Waiting for confirmation",
    loadingPhotos: "Loading confirmed photos…",
    uploadingPhotos: "Uploading and confirming photos…",
    photosReady: "Photos added. Select confirmed photos when you're ready to analyze them.",
    photoAuthorityUnavailable: "Photo attachment is unavailable until Meetro confirms the current request.",
    photoLimitReached: "This request can contain up to {count} photos.",
    uploadError: "The selected photos could not be uploaded.",
    photoAppendError: "Meetro could not confirm every photo. Confirmed request photos were refreshed.",
    photoRefreshError: "The photos were submitted, but Meetro could not refresh confirmed photo details.",
    estimateMaterials: "Estimate Materials",
    checkPrices: "Check Material Prices",
    estimateLabor: "Estimate Labor",
    prepareQuote: "Prepare Quote",
    helpCreateInvoice: "Help Create Invoice",
    reviewInvoice: "Review Invoice",
    explainBalance: "Explain Remaining Balance",
    startRecording: "Use microphone",
    recording: "Recording",
    stopRecording: "Stop recording",
    cancelRecording: "Cancel recording",
    transcribing: "Preparing transcript",
    transcriptReady: "Transcript ready. Review or edit it before submitting.",
    microphoneDenied: "Microphone access is off. Allow access in device settings or type instead.",
    microphoneUnavailable: "Voice input is unavailable here. You can keep typing.",
  },
  es: {
    title: "Preguntar a Meetro", close: "Cerrar", promptLabel: "¿Con qué necesitas ayuda?",
    promptPlaceholder: "Agrega los detalles que quieres que Meetro considere.", prepare: "Preparar sugerencia",
    preparing: "Preparando sugerencia", unavailable: "Ask Meetro aún no está conectado. Tu trabajo no cambió.",
    advisory: "Revisa cada sugerencia antes de agregarla a tu trabajo.", add: "Agregar",
    addToEvaluation: "Agregar a la evaluación", addFinding: "Agregar hallazgo",
    addRecommendation: "Agregar recomendación", applyToEstimate: "Aplicar al estimado",
    useInQuote: "Usar en la cotización", useInInvoice: "Usar en la factura", edit: "Editar",
    dismiss: "Descartar", saveEdit: "Guardar edición", observed: "Observado",
    professionalInput: "Aporte profesional", needsVerification: "Requiere verificación",
    suggested: "Sugerido", price: "Precio", internalOnly: "Solo interno", referencePrice: "Precio de referencia",
    notGuaranteed: "No es un costo garantizado", exactContext: "Ayudando con",
    noSilentChanges: "Nada cambia hasta que elijas una acción.", evaluation: "Evaluación",
    estimate: "Estimado y cotización", invoice: "Factura", jobRequest: "Solicitud de trabajo",
    helpDescribe: "Ayúdame a describir esto", whatCheck: "¿Qué debo revisar?",
    analyzePhotos: "Analizar fotos", analyzePhoto: "Analizar foto", helpMeasurements: "Ayuda con medidas",
    turnIntoFindings: "Convertir en hallazgos", draftRecommendations: "Redactar recomendaciones",
    analyzePhotosWithCount: "Analizar {count} fotos",
    takePhoto: "Tomar foto",
    uploadPhotos: "Subir fotos",
    uploadAdditionalPhotos: "Subir más fotos",
    selectedPhotoReviewTitle: "Fotos para analizar",
    photoCountSummary: "{count} foto(s) seleccionada(s) para analizar",
    uploadPhotoLabelFallback: "Foto",
    removePhoto: "Eliminar",
    selectPhoto: "Seleccionar",
    deselectPhoto: "Seleccionada",
    selectPhotosFirst: "Selecciona al menos una foto confirmada para analizar.",
    selectPhotosHelp: "Selecciona hasta 5 fotos confirmadas para analizar.",
    canonicalPhotoTitle: "Fotos de evaluación",
    photoPosition: "Foto {current} de {total}",
    pendingPhotoTitle: "Añadiendo fotos",
    pendingPhotoHelp: "Estas fotos no se pueden analizar hasta que Meetro las confirme.",
    pendingPhoto: "Esperando confirmación",
    loadingPhotos: "Cargando fotos confirmadas…",
    uploadingPhotos: "Subiendo y confirmando fotos…",
    photosReady: "Fotos añadidas. Selecciona las fotos confirmadas cuando quieras analizarlas.",
    photoAuthorityUnavailable: "No se pueden adjuntar fotos hasta que Meetro confirme la solicitud actual.",
    photoLimitReached: "Esta solicitud puede contener hasta {count} fotos.",
    uploadError: "No se pudieron subir las fotos seleccionadas.",
    photoAppendError: "Meetro no pudo confirmar todas las fotos. Se actualizaron las fotos confirmadas.",
    photoRefreshError: "Se enviaron las fotos, pero Meetro no pudo actualizar los detalles confirmados.",
    estimateMaterials: "Estimar materiales", checkPrices: "Consultar precios de materiales",
    estimateLabor: "Estimar mano de obra", prepareQuote: "Preparar cotización",
    helpCreateInvoice: "Ayudar a crear factura", reviewInvoice: "Revisar factura",
    explainBalance: "Explicar saldo restante",
    startRecording: "Usar micrófono", recording: "Grabando", stopRecording: "Detener grabación",
    cancelRecording: "Cancelar grabación", transcribing: "Preparando transcripción",
    transcriptReady: "La transcripción está lista. Revísala o edítala antes de enviarla.",
    microphoneDenied: "El acceso al micrófono está desactivado. Permítelo en la configuración o escribe.",
    microphoneUnavailable: "La entrada de voz no está disponible aquí. Puedes seguir escribiendo.",
  },
  fr: {
    title: "Demander à Meetro", close: "Fermer", promptLabel: "Avec quoi souhaitez-vous de l'aide?",
    promptPlaceholder: "Ajoutez les détails que Meetro doit prendre en compte.", prepare: "Préparer la suggestion",
    preparing: "Préparation de la suggestion", unavailable: "Ask Meetro n'est pas encore connecté. Votre travail reste inchangé.",
    advisory: "Examinez chaque suggestion avant de l'ajouter à votre travail.", add: "Ajouter",
    addToEvaluation: "Ajouter à l'évaluation", addFinding: "Ajouter un constat",
    addRecommendation: "Ajouter une recommandation", applyToEstimate: "Appliquer à l'estimation",
    useInQuote: "Utiliser dans le devis", useInInvoice: "Utiliser dans la facture", edit: "Modifier",
    dismiss: "Ignorer", saveEdit: "Enregistrer la modification", observed: "Observé",
    professionalInput: "Saisie professionnelle", needsVerification: "À vérifier",
    suggested: "Suggéré", price: "Prix", internalOnly: "Interne uniquement", referencePrice: "Prix de référence",
    notGuaranteed: "Coût non garanti", exactContext: "Aide pour",
    noSilentChanges: "Rien ne change avant que vous choisissiez une action.", evaluation: "Évaluation",
    estimate: "Estimation et devis", invoice: "Facture", jobRequest: "Demande de service",
    helpDescribe: "Aider à décrire", whatCheck: "Que dois-je vérifier?", analyzePhotos: "Analyser les photos", analyzePhoto: "Analyser la photo",
    helpMeasurements: "Aide aux mesures", turnIntoFindings: "Transformer en constats",
    draftRecommendations: "Rédiger des recommandations", estimateMaterials: "Estimer les matériaux",
    analyzePhotosWithCount: "Analyser {count} photos",
    takePhoto: "Prendre une photo",
    uploadPhotos: "Télécharger des photos",
    uploadAdditionalPhotos: "Téléverser plus de photos",
    selectedPhotoReviewTitle: "Photos à analyser",
    photoCountSummary: "{count} photo(s) sélectionnée(s) pour analyse",
    uploadPhotoLabelFallback: "Photo",
    removePhoto: "Supprimer",
    selectPhoto: "Sélectionner",
    deselectPhoto: "Sélectionnée",
    selectPhotosFirst: "Sélectionnez au moins une photo confirmée à analyser.",
    selectPhotosHelp: "Sélectionnez jusqu'à 5 photos confirmées à analyser.",
    canonicalPhotoTitle: "Photos d'évaluation",
    photoPosition: "Photo {current} sur {total}",
    pendingPhotoTitle: "Ajout de photos",
    pendingPhotoHelp: "Ces photos ne peuvent pas être analysées avant leur confirmation par Meetro.",
    pendingPhoto: "En attente de confirmation",
    loadingPhotos: "Chargement des photos confirmées…",
    uploadingPhotos: "Téléversement et confirmation des photos…",
    photosReady: "Photos ajoutées. Sélectionnez les photos confirmées lorsque vous souhaitez les analyser.",
    photoAuthorityUnavailable: "L'ajout de photos est indisponible tant que Meetro n'a pas confirmé la demande actuelle.",
    photoLimitReached: "Cette demande peut contenir jusqu'à {count} photos.",
    uploadError: "Les photos sélectionnées n'ont pas pu être téléversées.",
    photoAppendError: "Meetro n'a pas pu confirmer toutes les photos. Les photos confirmées ont été actualisées.",
    photoRefreshError: "Les photos ont été envoyées, mais Meetro n'a pas pu actualiser les détails confirmés.",
    checkPrices: "Vérifier les prix des matériaux", estimateLabor: "Estimer la main-d'œuvre",
    prepareQuote: "Préparer le devis", helpCreateInvoice: "Aider à créer la facture",
    reviewInvoice: "Examiner la facture", explainBalance: "Expliquer le solde restant",
    startRecording: "Utiliser le microphone", recording: "Enregistrement", stopRecording: "Arrêter l'enregistrement",
    cancelRecording: "Annuler l'enregistrement", transcribing: "Préparation de la transcription",
    transcriptReady: "La transcription est prête. Vérifiez-la ou modifiez-la avant de l'envoyer.",
    microphoneDenied: "L'accès au microphone est désactivé. Autorisez-le dans les réglages ou saisissez votre texte.",
    microphoneUnavailable: "La saisie vocale n'est pas disponible ici. Vous pouvez continuer à écrire.",
  },
  "pt-BR": {
    title: "Perguntar ao Meetro", close: "Fechar", promptLabel: "Com o que você precisa de ajuda?",
    promptPlaceholder: "Adicione os detalhes que o Meetro deve considerar.", prepare: "Preparar sugestão",
    preparing: "Preparando sugestão", unavailable: "O Ask Meetro ainda não está conectado. Seu trabalho não mudou.",
    advisory: "Revise cada sugestão antes de adicioná-la ao trabalho.", add: "Adicionar",
    addToEvaluation: "Adicionar à avaliação", addFinding: "Adicionar achado",
    addRecommendation: "Adicionar recomendação", applyToEstimate: "Aplicar à estimativa",
    useInQuote: "Usar no orçamento", useInInvoice: "Usar na fatura", edit: "Editar",
    dismiss: "Descartar", saveEdit: "Salvar edição", observed: "Observado",
    professionalInput: "Informação profissional", needsVerification: "Precisa de verificação",
    suggested: "Sugerido", price: "Preço", internalOnly: "Somente interno", referencePrice: "Preço de referência",
    notGuaranteed: "Não é um custo garantido", exactContext: "Ajudando com",
    noSilentChanges: "Nada muda até você escolher uma ação.", evaluation: "Avaliação",
    estimate: "Estimativa e orçamento", invoice: "Fatura", jobRequest: "Solicitação de serviço",
    helpDescribe: "Ajudar a descrever", whatCheck: "O que devo verificar?", analyzePhotos: "Analisar fotos", analyzePhoto: "Analisar foto",
    helpMeasurements: "Ajuda com medidas", turnIntoFindings: "Transformar em achados",
    draftRecommendations: "Redigir recomendações", estimateMaterials: "Estimar materiais",
    analyzePhotosWithCount: "Analisar {count} fotos",
    takePhoto: "Tirar foto",
    uploadPhotos: "Enviar fotos",
    uploadAdditionalPhotos: "Enviar mais fotos",
    selectedPhotoReviewTitle: "Fotos para analisar",
    photoCountSummary: "{count} foto(s) selecionada(s) para análise",
    uploadPhotoLabelFallback: "Foto",
    removePhoto: "Remover",
    selectPhoto: "Selecionar",
    deselectPhoto: "Selecionada",
    selectPhotosFirst: "Selecione pelo menos uma foto confirmada para analisar.",
    selectPhotosHelp: "Selecione até 5 fotos confirmadas para analisar.",
    canonicalPhotoTitle: "Fotos da avaliação",
    photoPosition: "Foto {current} de {total}",
    pendingPhotoTitle: "Adicionando fotos",
    pendingPhotoHelp: "Estas fotos não podem ser analisadas até que a Meetro as confirme.",
    pendingPhoto: "Aguardando confirmação",
    loadingPhotos: "Carregando fotos confirmadas…",
    uploadingPhotos: "Enviando e confirmando fotos…",
    photosReady: "Fotos adicionadas. Selecione as fotos confirmadas quando quiser analisá-las.",
    photoAuthorityUnavailable: "Não é possível anexar fotos até a Meetro confirmar a solicitação atual.",
    photoLimitReached: "Esta solicitação pode conter até {count} fotos.",
    uploadError: "Não foi possível enviar as fotos selecionadas.",
    photoAppendError: "A Meetro não confirmou todas as fotos. As fotos confirmadas foram atualizadas.",
    photoRefreshError: "As fotos foram enviadas, mas a Meetro não conseguiu atualizar os detalhes confirmados.",
    checkPrices: "Verificar preços de materiais", estimateLabor: "Estimar mão de obra",
    prepareQuote: "Preparar orçamento", helpCreateInvoice: "Ajudar a criar fatura",
    reviewInvoice: "Revisar fatura", explainBalance: "Explicar saldo restante",
    startRecording: "Usar microfone", recording: "Gravando", stopRecording: "Parar gravação",
    cancelRecording: "Cancelar gravação", transcribing: "Preparando transcrição",
    transcriptReady: "A transcrição está pronta. Revise ou edite antes de enviar.",
    microphoneDenied: "O acesso ao microfone está desativado. Permita nos ajustes ou digite.",
    microphoneUnavailable: "A entrada de voz não está disponível aqui. Você pode continuar digitando.",
  },
});

export function getAskMeetroWorkflowCopy(language = "en") {
  return COPY[normalizeLanguage(language)] || COPY.en;
}
