import { normalizeLanguage } from "./language.js";

const COPY = Object.freeze({
  en: {
    title: "Ask Meetro",
    close: "Close",
    promptLabel: "What would you like help with?",
    promptPlaceholder: "Add any details you want Meetro to consider.",
    prepare: "Prepare suggestion",
    preparing: "Preparing suggestion",
    unavailable: "Ask Meetro is not connected yet. Your work is unchanged.",
    advisory: "Review every suggestion before adding it to your work.",
    add: "Add",
    addToEvaluation: "Add to Evaluation",
    addFinding: "Add Finding",
    addRecommendation: "Add Recommendation",
    applyToEstimate: "Apply to Estimate",
    useInQuote: "Use in Quote",
    useInInvoice: "Use in Invoice",
    edit: "Edit",
    dismiss: "Dismiss",
    saveEdit: "Save edit",
    observed: "Observed",
    professionalInput: "Professional input",
    needsVerification: "Needs verification",
    suggested: "Suggested",
    price: "Price",
    internalOnly: "Internal only",
    referencePrice: "Reference price",
    notGuaranteed: "Not a guaranteed cost",
    exactContext: "Helping with",
    noSilentChanges: "Nothing changes until you choose an action.",
    evaluation: "Evaluation",
    estimate: "Estimate & Quote",
    invoice: "Invoice",
    jobRequest: "Job Request",
    helpDescribe: "Help Describe This",
    whatCheck: "What Should I Check?",
    analyzePhotos: "Analyze Photos",
    helpMeasurements: "Help with Measurements",
    turnIntoFindings: "Turn This into Findings",
    draftRecommendations: "Draft Recommendations",
    estimateMaterials: "Estimate Materials",
    checkPrices: "Check Material Prices",
    estimateLabor: "Estimate Labor",
    prepareQuote: "Prepare Quote",
    helpCreateInvoice: "Help Create Invoice",
    reviewInvoice: "Review Invoice",
    explainBalance: "Explain Remaining Balance",
    startRecording: "Use microphone",
    recording: "Recording",
    stopRecording: "Stop recording",
    cancelRecording: "Cancel recording",
    transcribing: "Preparing transcript",
    transcriptReady: "Transcript ready. Review or edit it before submitting.",
    microphoneDenied: "Microphone access is off. Allow access in device settings or type instead.",
    microphoneUnavailable: "Voice input is unavailable here. You can keep typing.",
  },
  es: {
    title: "Preguntar a Meetro", close: "Cerrar", promptLabel: "¿Con qué necesitas ayuda?",
    promptPlaceholder: "Agrega los detalles que quieres que Meetro considere.", prepare: "Preparar sugerencia",
    preparing: "Preparando sugerencia", unavailable: "Ask Meetro aún no está conectado. Tu trabajo no cambió.",
    advisory: "Revisa cada sugerencia antes de agregarla a tu trabajo.", add: "Agregar",
    addToEvaluation: "Agregar a la evaluación", addFinding: "Agregar hallazgo",
    addRecommendation: "Agregar recomendación", applyToEstimate: "Aplicar al estimado",
    useInQuote: "Usar en la cotización", useInInvoice: "Usar en la factura", edit: "Editar",
    dismiss: "Descartar", saveEdit: "Guardar edición", observed: "Observado",
    professionalInput: "Aporte profesional", needsVerification: "Requiere verificación",
    suggested: "Sugerido", price: "Precio", internalOnly: "Solo interno", referencePrice: "Precio de referencia",
    notGuaranteed: "No es un costo garantizado", exactContext: "Ayudando con",
    noSilentChanges: "Nada cambia hasta que elijas una acción.", evaluation: "Evaluación",
    estimate: "Estimado y cotización", invoice: "Factura", jobRequest: "Solicitud de trabajo",
    helpDescribe: "Ayúdame a describir esto", whatCheck: "¿Qué debo revisar?",
    analyzePhotos: "Analizar fotos", helpMeasurements: "Ayuda con medidas",
    turnIntoFindings: "Convertir en hallazgos", draftRecommendations: "Redactar recomendaciones",
    estimateMaterials: "Estimar materiales", checkPrices: "Consultar precios de materiales",
    estimateLabor: "Estimar mano de obra", prepareQuote: "Preparar cotización",
    helpCreateInvoice: "Ayudar a crear factura", reviewInvoice: "Revisar factura",
    explainBalance: "Explicar saldo restante",
    startRecording: "Usar micrófono", recording: "Grabando", stopRecording: "Detener grabación",
    cancelRecording: "Cancelar grabación", transcribing: "Preparando transcripción",
    transcriptReady: "La transcripción está lista. Revísala o edítala antes de enviarla.",
    microphoneDenied: "El acceso al micrófono está desactivado. Permítelo en la configuración o escribe.",
    microphoneUnavailable: "La entrada de voz no está disponible aquí. Puedes seguir escribiendo.",
  },
  fr: {
    title: "Demander à Meetro", close: "Fermer", promptLabel: "Avec quoi souhaitez-vous de l'aide?",
    promptPlaceholder: "Ajoutez les détails que Meetro doit prendre en compte.", prepare: "Préparer la suggestion",
    preparing: "Préparation de la suggestion", unavailable: "Ask Meetro n'est pas encore connecté. Votre travail reste inchangé.",
    advisory: "Examinez chaque suggestion avant de l'ajouter à votre travail.", add: "Ajouter",
    addToEvaluation: "Ajouter à l'évaluation", addFinding: "Ajouter un constat",
    addRecommendation: "Ajouter une recommandation", applyToEstimate: "Appliquer à l'estimation",
    useInQuote: "Utiliser dans le devis", useInInvoice: "Utiliser dans la facture", edit: "Modifier",
    dismiss: "Ignorer", saveEdit: "Enregistrer la modification", observed: "Observé",
    professionalInput: "Saisie professionnelle", needsVerification: "À vérifier",
    suggested: "Suggéré", price: "Prix", internalOnly: "Interne uniquement", referencePrice: "Prix de référence",
    notGuaranteed: "Coût non garanti", exactContext: "Aide pour",
    noSilentChanges: "Rien ne change avant que vous choisissiez une action.", evaluation: "Évaluation",
    estimate: "Estimation et devis", invoice: "Facture", jobRequest: "Demande de service",
    helpDescribe: "Aider à décrire", whatCheck: "Que dois-je vérifier?", analyzePhotos: "Analyser les photos",
    helpMeasurements: "Aide aux mesures", turnIntoFindings: "Transformer en constats",
    draftRecommendations: "Rédiger des recommandations", estimateMaterials: "Estimer les matériaux",
    checkPrices: "Vérifier les prix des matériaux", estimateLabor: "Estimer la main-d'œuvre",
    prepareQuote: "Préparer le devis", helpCreateInvoice: "Aider à créer la facture",
    reviewInvoice: "Examiner la facture", explainBalance: "Expliquer le solde restant",
    startRecording: "Utiliser le microphone", recording: "Enregistrement", stopRecording: "Arrêter l'enregistrement",
    cancelRecording: "Annuler l'enregistrement", transcribing: "Préparation de la transcription",
    transcriptReady: "La transcription est prête. Vérifiez-la ou modifiez-la avant de l'envoyer.",
    microphoneDenied: "L'accès au microphone est désactivé. Autorisez-le dans les réglages ou saisissez votre texte.",
    microphoneUnavailable: "La saisie vocale n'est pas disponible ici. Vous pouvez continuer à écrire.",
  },
  "pt-BR": {
    title: "Perguntar ao Meetro", close: "Fechar", promptLabel: "Com o que você precisa de ajuda?",
    promptPlaceholder: "Adicione os detalhes que o Meetro deve considerar.", prepare: "Preparar sugestão",
    preparing: "Preparando sugestão", unavailable: "O Ask Meetro ainda não está conectado. Seu trabalho não mudou.",
    advisory: "Revise cada sugestão antes de adicioná-la ao trabalho.", add: "Adicionar",
    addToEvaluation: "Adicionar à avaliação", addFinding: "Adicionar achado",
    addRecommendation: "Adicionar recomendação", applyToEstimate: "Aplicar à estimativa",
    useInQuote: "Usar no orçamento", useInInvoice: "Usar na fatura", edit: "Editar",
    dismiss: "Descartar", saveEdit: "Salvar edição", observed: "Observado",
    professionalInput: "Informação profissional", needsVerification: "Precisa de verificação",
    suggested: "Sugerido", price: "Preço", internalOnly: "Somente interno", referencePrice: "Preço de referência",
    notGuaranteed: "Não é um custo garantido", exactContext: "Ajudando com",
    noSilentChanges: "Nada muda até você escolher uma ação.", evaluation: "Avaliação",
    estimate: "Estimativa e orçamento", invoice: "Fatura", jobRequest: "Solicitação de serviço",
    helpDescribe: "Ajudar a descrever", whatCheck: "O que devo verificar?", analyzePhotos: "Analisar fotos",
    helpMeasurements: "Ajuda com medidas", turnIntoFindings: "Transformar em achados",
    draftRecommendations: "Redigir recomendações", estimateMaterials: "Estimar materiais",
    checkPrices: "Verificar preços de materiais", estimateLabor: "Estimar mão de obra",
    prepareQuote: "Preparar orçamento", helpCreateInvoice: "Ajudar a criar fatura",
    reviewInvoice: "Revisar fatura", explainBalance: "Explicar saldo restante",
    startRecording: "Usar microfone", recording: "Gravando", stopRecording: "Parar gravação",
    cancelRecording: "Cancelar gravação", transcribing: "Preparando transcrição",
    transcriptReady: "A transcrição está pronta. Revise ou edite antes de enviar.",
    microphoneDenied: "O acesso ao microfone está desativado. Permita nos ajustes ou digite.",
    microphoneUnavailable: "A entrada de voz não está disponível aqui. Você pode continuar digitando.",
  },
});

export function getAskMeetroWorkflowCopy(language = "en") {
  return COPY[normalizeLanguage(language)] || COPY.en;
}
