export const businessDocumentWorkflowLanguage = Object.freeze({
  en: Object.freeze({
    businessDocumentStartNewQuote: "+ Start New Quote",
    businessDocumentStartNewInvoice: "+ Start New Invoice",
    businessDocumentStartingNewQuote: "Starting new Quote…",
    businessDocumentStartingNewInvoice: "Starting new Invoice…",
    businessDocumentNewQuoteReady: "New Quote started. The previous Quote remains in Saved Files.",
    businessDocumentNewInvoiceReady: "New Invoice started. The previous Invoice remains in Saved Files.",
    businessDocumentStartNewSaveFailed: "The current document could not be saved. It remains open, and no new document was created.",
    businessDocumentStartNewCreateFailed: "The new document could not be started. The current saved document remains open.",
    businessDocumentPrefillQuoteDetails: "Customer & Quote Details",
    businessDocumentPrefillInvoiceDetails: "Customer & Invoice Details",
    businessDocumentPrefillDetailsHelp: "Review or edit the same working-document fields Meetro can prefill. Changes remain a working draft until you apply and save them.",
    businessDocumentPrefillRefreshed: "Prefill refreshed from your saved conversation instructions. Review or edit the details below.",
    businessDocumentPrefillReviewHelp: "Enter direct document facts below, or send an explicit instruction for Meetro to prefill the working draft.",
    businessDocumentQuoteDetails: "Quote details",
    businessDocumentInvoiceDetails: "Invoice details",
    businessDocumentFieldCustomer: "Customer",
    businessDocumentFieldCustomerEmail: "Customer email",
    businessDocumentFieldCustomerPhone: "Customer phone",
    businessDocumentFieldCustomerAddress: "Customer address",
    businessDocumentFieldProject: "Project",
    businessDocumentFieldJob: "Job",
    businessDocumentFieldScope: "Scope of Work",
    businessDocumentFieldCustomerDescription: "Customer-facing description",
    businessDocumentFieldEstimatedDuration: "Estimated duration",
    businessDocumentFieldWorkCompleted: "Work completed",
    businessDocumentFieldDueDate: "Due date",
    businessDocumentCloseDetails: "Close details",
    businessDocumentOpenManualEntry: "Open full manual entry",
    businessDocumentBackToPrefill: "Back to Meetro Prefill",
    businessDocumentApplyChanges: "Apply changes",
  }),
  es: Object.freeze({
    businessDocumentStartNewQuote: "+ Iniciar nuevo presupuesto",
    businessDocumentStartNewInvoice: "+ Iniciar nueva factura",
    businessDocumentStartingNewQuote: "Iniciando nuevo presupuesto…",
    businessDocumentStartingNewInvoice: "Iniciando nueva factura…",
    businessDocumentNewQuoteReady: "Nuevo presupuesto iniciado. El presupuesto anterior permanece en Archivos guardados.",
    businessDocumentNewInvoiceReady: "Nueva factura iniciada. La factura anterior permanece en Archivos guardados.",
    businessDocumentStartNewSaveFailed: "No se pudo guardar el documento actual. Permanece abierto y no se creó ningún documento nuevo.",
    businessDocumentStartNewCreateFailed: "No se pudo iniciar el nuevo documento. El documento guardado actual permanece abierto.",
    businessDocumentPrefillQuoteDetails: "Cliente y detalles del presupuesto",
    businessDocumentPrefillInvoiceDetails: "Cliente y detalles de la factura",
    businessDocumentPrefillDetailsHelp: "Revisa o edita los mismos campos del documento de trabajo que Meetro puede completar. Los cambios siguen siendo un borrador hasta que los apliques y guardes.",
    businessDocumentPrefillRefreshed: "La información se actualizó con las instrucciones guardadas de la conversación. Revisa o edita los detalles abajo.",
    businessDocumentPrefillReviewHelp: "Ingresa datos directos del documento abajo o envía una instrucción explícita para que Meetro complete el borrador de trabajo.",
    businessDocumentQuoteDetails: "Detalles del presupuesto",
    businessDocumentInvoiceDetails: "Detalles de la factura",
    businessDocumentFieldCustomer: "Cliente",
    businessDocumentFieldCustomerEmail: "Correo del cliente",
    businessDocumentFieldCustomerPhone: "Teléfono del cliente",
    businessDocumentFieldCustomerAddress: "Dirección del cliente",
    businessDocumentFieldProject: "Proyecto",
    businessDocumentFieldJob: "Trabajo",
    businessDocumentFieldScope: "Alcance del trabajo",
    businessDocumentFieldCustomerDescription: "Descripción para el cliente",
    businessDocumentFieldEstimatedDuration: "Duración estimada",
    businessDocumentFieldWorkCompleted: "Trabajo realizado",
    businessDocumentFieldDueDate: "Fecha de vencimiento",
    businessDocumentCloseDetails: "Cerrar detalles",
    businessDocumentOpenManualEntry: "Abrir entrada manual completa",
    businessDocumentBackToPrefill: "Volver al llenado de Meetro",
    businessDocumentApplyChanges: "Aplicar cambios",
  }),
  fr: Object.freeze({
    businessDocumentStartNewQuote: "+ Commencer un nouveau devis",
    businessDocumentStartNewInvoice: "+ Commencer une nouvelle facture",
    businessDocumentStartingNewQuote: "Création d’un nouveau devis…",
    businessDocumentStartingNewInvoice: "Création d’une nouvelle facture…",
    businessDocumentNewQuoteReady: "Nouveau devis commencé. Le devis précédent reste dans Fichiers enregistrés.",
    businessDocumentNewInvoiceReady: "Nouvelle facture commencée. La facture précédente reste dans Fichiers enregistrés.",
    businessDocumentStartNewSaveFailed: "Le document actuel n’a pas pu être enregistré. Il reste ouvert et aucun nouveau document n’a été créé.",
    businessDocumentStartNewCreateFailed: "Le nouveau document n’a pas pu être créé. Le document enregistré actuel reste ouvert.",
    businessDocumentPrefillQuoteDetails: "Client et détails du devis",
    businessDocumentPrefillInvoiceDetails: "Client et détails de la facture",
    businessDocumentPrefillDetailsHelp: "Vérifiez ou modifiez les mêmes champs du document de travail que Meetro peut préremplir. Les modifications restent un brouillon jusqu’à leur application et leur enregistrement.",
    businessDocumentPrefillRefreshed: "Le préremplissage a été actualisé à partir des instructions enregistrées. Vérifiez ou modifiez les détails ci-dessous.",
    businessDocumentPrefillReviewHelp: "Saisissez les informations du document ci-dessous ou envoyez une instruction explicite pour que Meetro préremplisse le brouillon.",
    businessDocumentQuoteDetails: "Détails du devis",
    businessDocumentInvoiceDetails: "Détails de la facture",
    businessDocumentFieldCustomer: "Client",
    businessDocumentFieldCustomerEmail: "Courriel du client",
    businessDocumentFieldCustomerPhone: "Téléphone du client",
    businessDocumentFieldCustomerAddress: "Adresse du client",
    businessDocumentFieldProject: "Projet",
    businessDocumentFieldJob: "Travail",
    businessDocumentFieldScope: "Étendue des travaux",
    businessDocumentFieldCustomerDescription: "Description destinée au client",
    businessDocumentFieldEstimatedDuration: "Durée estimée",
    businessDocumentFieldWorkCompleted: "Travaux réalisés",
    businessDocumentFieldDueDate: "Date d’échéance",
    businessDocumentCloseDetails: "Fermer les détails",
    businessDocumentOpenManualEntry: "Ouvrir la saisie manuelle complète",
    businessDocumentBackToPrefill: "Retour au préremplissage Meetro",
    businessDocumentApplyChanges: "Appliquer les modifications",
  }),
  "pt-BR": Object.freeze({
    businessDocumentStartNewQuote: "+ Iniciar novo orçamento",
    businessDocumentStartNewInvoice: "+ Iniciar nova fatura",
    businessDocumentStartingNewQuote: "Iniciando novo orçamento…",
    businessDocumentStartingNewInvoice: "Iniciando nova fatura…",
    businessDocumentNewQuoteReady: "Novo orçamento iniciado. O orçamento anterior permanece em Arquivos salvos.",
    businessDocumentNewInvoiceReady: "Nova fatura iniciada. A fatura anterior permanece em Arquivos salvos.",
    businessDocumentStartNewSaveFailed: "Não foi possível salvar o documento atual. Ele permanece aberto e nenhum novo documento foi criado.",
    businessDocumentStartNewCreateFailed: "Não foi possível iniciar o novo documento. O documento salvo atual permanece aberto.",
    businessDocumentPrefillQuoteDetails: "Cliente e detalhes do orçamento",
    businessDocumentPrefillInvoiceDetails: "Cliente e detalhes da fatura",
    businessDocumentPrefillDetailsHelp: "Revise ou edite os mesmos campos do documento de trabalho que o Meetro pode preencher. As alterações continuam como rascunho até serem aplicadas e salvas.",
    businessDocumentPrefillRefreshed: "O preenchimento foi atualizado com as instruções salvas da conversa. Revise ou edite os detalhes abaixo.",
    businessDocumentPrefillReviewHelp: "Insira os dados diretos do documento abaixo ou envie uma instrução explícita para o Meetro preencher o rascunho de trabalho.",
    businessDocumentQuoteDetails: "Detalhes do orçamento",
    businessDocumentInvoiceDetails: "Detalhes da fatura",
    businessDocumentFieldCustomer: "Cliente",
    businessDocumentFieldCustomerEmail: "E-mail do cliente",
    businessDocumentFieldCustomerPhone: "Telefone do cliente",
    businessDocumentFieldCustomerAddress: "Endereço do cliente",
    businessDocumentFieldProject: "Projeto",
    businessDocumentFieldJob: "Serviço",
    businessDocumentFieldScope: "Escopo do trabalho",
    businessDocumentFieldCustomerDescription: "Descrição para o cliente",
    businessDocumentFieldEstimatedDuration: "Duração estimada",
    businessDocumentFieldWorkCompleted: "Trabalho concluído",
    businessDocumentFieldDueDate: "Data de vencimento",
    businessDocumentCloseDetails: "Fechar detalhes",
    businessDocumentOpenManualEntry: "Abrir entrada manual completa",
    businessDocumentBackToPrefill: "Voltar ao preenchimento Meetro",
    businessDocumentApplyChanges: "Aplicar alterações",
  }),
});
