export const businessDocumentCustomerLanguage = Object.freeze({
  en: Object.freeze({
    businessDocumentCustomerTitle: "Customer",
    businessDocumentCustomerNotLinked: "Not linked",
    businessDocumentCustomerSavedContact: "Saved Contact",
    businessDocumentCustomerLinked: "Linked to Contacts",
    businessDocumentCustomerNotLinkedHelp: "Customer information exists only on this working document.",
    businessDocumentCustomerChoose: "Choose saved customer",
    businessDocumentCustomerSave: "Save as Customer Contact",
    businessDocumentCustomerSaveHelp: "Save this customer to Communication Center and link the working document.",
    businessDocumentCustomerSearch: "Search saved customers",
    businessDocumentCustomerSearchPlaceholder: "Name, company, phone, or email",
    businessDocumentCustomerLoading: "Loading saved customers…",
    businessDocumentCustomerEmpty: "No active saved customers match.",
    businessDocumentCustomerUse: "Use this customer",
    businessDocumentCustomerKeep: "Link and keep document details",
    businessDocumentCustomerReplace: "Replace details and link",
    businessDocumentCustomerReplaceWarning: "This document already has customer details. Choose whether to keep them or replace them with the selected Contact snapshot.",
    businessDocumentCustomerClose: "Close customer choices",
    businessDocumentCustomerPerson: "Person",
    businessDocumentCustomerOrganization: "Organization",
    businessDocumentCustomerType: "Customer type",
    businessDocumentCustomerCreate: "Create Customer Contact",
    businessDocumentCustomerCreateAnyway: "Create a new Contact anyway",
    businessDocumentCustomerDuplicateTitle: "Possible saved customer found",
    businessDocumentCustomerDuplicateHelp: "Choose an existing Contact or explicitly create a separate Contact. Meetro will not merge them automatically.",
    businessDocumentCustomerRetry: "Retry customer link",
    businessDocumentCustomerWorking: "Saving customer…",
    businessDocumentCustomerRequired: "Enter a customer name before saving a Contact.",
    businessDocumentCustomerLinkedNotice: "{name} is linked to this working {document}.",
    businessDocumentCustomerArchived: "Archived Contact · existing link preserved",
    businessDocumentCustomerLoadFailed: "Saved customers could not be loaded.",
    businessDocumentCustomerRelationshipFailed: "The Contact is saved, but its Customer Relationship could not be completed. Retry without creating another Contact.",
    businessDocumentCustomerLinkFailed: "The Contact and Customer Relationship are saved, but the document link could not be saved. Retry the link.",
    businessDocumentCustomerCreateFailed: "The Customer Contact could not be saved.",
    businessDocumentCustomerQuoteLabel: "quote",
    businessDocumentCustomerInvoiceLabel: "invoice",
  }),
  es: Object.freeze({
    businessDocumentCustomerTitle: "Cliente", businessDocumentCustomerNotLinked: "Sin vincular", businessDocumentCustomerSavedContact: "Contacto guardado", businessDocumentCustomerLinked: "Vinculado a Contactos", businessDocumentCustomerNotLinkedHelp: "La información del cliente existe solo en este documento de trabajo.", businessDocumentCustomerChoose: "Elegir cliente guardado", businessDocumentCustomerSave: "Guardar como Contacto de cliente", businessDocumentCustomerSaveHelp: "Guarda este cliente en el Centro de Comunicación y vincula el documento de trabajo.", businessDocumentCustomerSearch: "Buscar clientes guardados", businessDocumentCustomerSearchPlaceholder: "Nombre, empresa, teléfono o correo", businessDocumentCustomerLoading: "Cargando clientes guardados…", businessDocumentCustomerEmpty: "No hay clientes guardados activos que coincidan.", businessDocumentCustomerUse: "Usar este cliente", businessDocumentCustomerKeep: "Vincular y conservar los datos", businessDocumentCustomerReplace: "Reemplazar datos y vincular", businessDocumentCustomerReplaceWarning: "Este documento ya tiene datos del cliente. Elige conservarlos o reemplazarlos con la copia actual del Contacto.", businessDocumentCustomerClose: "Cerrar opciones de cliente", businessDocumentCustomerPerson: "Persona", businessDocumentCustomerOrganization: "Organización", businessDocumentCustomerType: "Tipo de cliente", businessDocumentCustomerCreate: "Crear Contacto de cliente", businessDocumentCustomerCreateAnyway: "Crear otro Contacto de todos modos", businessDocumentCustomerDuplicateTitle: "Posible cliente guardado encontrado", businessDocumentCustomerDuplicateHelp: "Elige un Contacto existente o crea otro explícitamente. Meetro no los combinará automáticamente.", businessDocumentCustomerRetry: "Reintentar vínculo del cliente", businessDocumentCustomerWorking: "Guardando cliente…", businessDocumentCustomerRequired: "Ingresa el nombre del cliente antes de guardar un Contacto.", businessDocumentCustomerLinkedNotice: "{name} está vinculado a este {document} de trabajo.", businessDocumentCustomerArchived: "Contacto archivado · vínculo existente conservado", businessDocumentCustomerLoadFailed: "No se pudieron cargar los clientes guardados.", businessDocumentCustomerRelationshipFailed: "El Contacto está guardado, pero no se pudo completar su Relación con el cliente. Reintenta sin crear otro Contacto.", businessDocumentCustomerLinkFailed: "El Contacto y la Relación están guardados, pero no se pudo guardar el vínculo del documento. Reintenta el vínculo.", businessDocumentCustomerCreateFailed: "No se pudo guardar el Contacto de cliente.", businessDocumentCustomerQuoteLabel: "presupuesto", businessDocumentCustomerInvoiceLabel: "factura"
  }),
  fr: Object.freeze({
    businessDocumentCustomerTitle: "Client", businessDocumentCustomerNotLinked: "Non lié", businessDocumentCustomerSavedContact: "Contact enregistré", businessDocumentCustomerLinked: "Lié aux Contacts", businessDocumentCustomerNotLinkedHelp: "Les informations client existent uniquement dans ce document de travail.", businessDocumentCustomerChoose: "Choisir un client enregistré", businessDocumentCustomerSave: "Enregistrer comme Contact client", businessDocumentCustomerSaveHelp: "Enregistrez ce client dans le Centre de communication et liez le document de travail.", businessDocumentCustomerSearch: "Rechercher des clients enregistrés", businessDocumentCustomerSearchPlaceholder: "Nom, entreprise, téléphone ou courriel", businessDocumentCustomerLoading: "Chargement des clients enregistrés…", businessDocumentCustomerEmpty: "Aucun client actif enregistré ne correspond.", businessDocumentCustomerUse: "Utiliser ce client", businessDocumentCustomerKeep: "Lier et conserver les détails", businessDocumentCustomerReplace: "Remplacer les détails et lier", businessDocumentCustomerReplaceWarning: "Ce document contient déjà des détails client. Choisissez de les conserver ou de les remplacer par l’instantané actuel du Contact.", businessDocumentCustomerClose: "Fermer les choix de client", businessDocumentCustomerPerson: "Personne", businessDocumentCustomerOrganization: "Organisation", businessDocumentCustomerType: "Type de client", businessDocumentCustomerCreate: "Créer le Contact client", businessDocumentCustomerCreateAnyway: "Créer quand même un nouveau Contact", businessDocumentCustomerDuplicateTitle: "Client enregistré possible trouvé", businessDocumentCustomerDuplicateHelp: "Choisissez un Contact existant ou créez-en explicitement un autre. Meetro ne les fusionnera pas automatiquement.", businessDocumentCustomerRetry: "Réessayer le lien client", businessDocumentCustomerWorking: "Enregistrement du client…", businessDocumentCustomerRequired: "Saisissez un nom de client avant d’enregistrer un Contact.", businessDocumentCustomerLinkedNotice: "{name} est lié à ce {document} de travail.", businessDocumentCustomerArchived: "Contact archivé · lien existant conservé", businessDocumentCustomerLoadFailed: "Impossible de charger les clients enregistrés.", businessDocumentCustomerRelationshipFailed: "Le Contact est enregistré, mais sa Relation client n’a pas pu être terminée. Réessayez sans créer un autre Contact.", businessDocumentCustomerLinkFailed: "Le Contact et la Relation sont enregistrés, mais le lien du document n’a pas pu être sauvegardé. Réessayez le lien.", businessDocumentCustomerCreateFailed: "Le Contact client n’a pas pu être enregistré.", businessDocumentCustomerQuoteLabel: "devis", businessDocumentCustomerInvoiceLabel: "facture"
  }),
  "pt-BR": Object.freeze({
    businessDocumentCustomerTitle: "Cliente", businessDocumentCustomerNotLinked: "Não vinculado", businessDocumentCustomerSavedContact: "Contato salvo", businessDocumentCustomerLinked: "Vinculado aos Contatos", businessDocumentCustomerNotLinkedHelp: "As informações do cliente existem apenas neste documento de trabalho.", businessDocumentCustomerChoose: "Escolher cliente salvo", businessDocumentCustomerSave: "Salvar como Contato de cliente", businessDocumentCustomerSaveHelp: "Salve este cliente na Central de Comunicação e vincule o documento de trabalho.", businessDocumentCustomerSearch: "Buscar clientes salvos", businessDocumentCustomerSearchPlaceholder: "Nome, empresa, telefone ou e-mail", businessDocumentCustomerLoading: "Carregando clientes salvos…", businessDocumentCustomerEmpty: "Nenhum cliente ativo salvo corresponde.", businessDocumentCustomerUse: "Usar este cliente", businessDocumentCustomerKeep: "Vincular e manter os dados", businessDocumentCustomerReplace: "Substituir dados e vincular", businessDocumentCustomerReplaceWarning: "Este documento já tem dados do cliente. Escolha mantê-los ou substituí-los pelo retrato atual do Contato.", businessDocumentCustomerClose: "Fechar opções de cliente", businessDocumentCustomerPerson: "Pessoa", businessDocumentCustomerOrganization: "Organização", businessDocumentCustomerType: "Tipo de cliente", businessDocumentCustomerCreate: "Criar Contato de cliente", businessDocumentCustomerCreateAnyway: "Criar um novo Contato mesmo assim", businessDocumentCustomerDuplicateTitle: "Possível cliente salvo encontrado", businessDocumentCustomerDuplicateHelp: "Escolha um Contato existente ou crie outro explicitamente. A Meetro não fará a mesclagem automática.", businessDocumentCustomerRetry: "Tentar vínculo do cliente novamente", businessDocumentCustomerWorking: "Salvando cliente…", businessDocumentCustomerRequired: "Informe o nome do cliente antes de salvar um Contato.", businessDocumentCustomerLinkedNotice: "{name} está vinculado a este {document} de trabalho.", businessDocumentCustomerArchived: "Contato arquivado · vínculo existente preservado", businessDocumentCustomerLoadFailed: "Não foi possível carregar os clientes salvos.", businessDocumentCustomerRelationshipFailed: "O Contato foi salvo, mas a Relação com o cliente não pôde ser concluída. Tente novamente sem criar outro Contato.", businessDocumentCustomerLinkFailed: "O Contato e a Relação foram salvos, mas o vínculo do documento não pôde ser salvo. Tente o vínculo novamente.", businessDocumentCustomerCreateFailed: "Não foi possível salvar o Contato de cliente.", businessDocumentCustomerQuoteLabel: "orçamento", businessDocumentCustomerInvoiceLabel: "fatura"
  }),
});
