export const businessDocumentWorkflowLanguage = Object.freeze({
  en: Object.freeze({
    businessDocumentStartNewQuote: "+ Start New Quote",
    businessDocumentStartNewInvoice: "+ Start New Invoice",
    businessDocumentStartingNewQuote: "Starting new Quote…",
    businessDocumentStartingNewInvoice: "Starting new Invoice…",
    businessDocumentNewQuoteReady: "New Quote started. The previous Quote remains in Saved Files.",
    businessDocumentNewInvoiceReady: "New Invoice started. The previous Invoice remains in Saved Files.",
    businessDocumentStartNewSaveFailed: "The current document could not be saved. It remains open, and no new document was created.",
    businessDocumentStartNewCreateFailed: "The new document could not be started. The current saved document remains open.",
  }),
  es: Object.freeze({
    businessDocumentStartNewQuote: "+ Iniciar nuevo presupuesto",
    businessDocumentStartNewInvoice: "+ Iniciar nueva factura",
    businessDocumentStartingNewQuote: "Iniciando nuevo presupuesto…",
    businessDocumentStartingNewInvoice: "Iniciando nueva factura…",
    businessDocumentNewQuoteReady: "Nuevo presupuesto iniciado. El presupuesto anterior permanece en Archivos guardados.",
    businessDocumentNewInvoiceReady: "Nueva factura iniciada. La factura anterior permanece en Archivos guardados.",
    businessDocumentStartNewSaveFailed: "No se pudo guardar el documento actual. Permanece abierto y no se creó ningún documento nuevo.",
    businessDocumentStartNewCreateFailed: "No se pudo iniciar el nuevo documento. El documento guardado actual permanece abierto.",
  }),
  fr: Object.freeze({
    businessDocumentStartNewQuote: "+ Commencer un nouveau devis",
    businessDocumentStartNewInvoice: "+ Commencer une nouvelle facture",
    businessDocumentStartingNewQuote: "Création d’un nouveau devis…",
    businessDocumentStartingNewInvoice: "Création d’une nouvelle facture…",
    businessDocumentNewQuoteReady: "Nouveau devis commencé. Le devis précédent reste dans Fichiers enregistrés.",
    businessDocumentNewInvoiceReady: "Nouvelle facture commencée. La facture précédente reste dans Fichiers enregistrés.",
    businessDocumentStartNewSaveFailed: "Le document actuel n’a pas pu être enregistré. Il reste ouvert et aucun nouveau document n’a été créé.",
    businessDocumentStartNewCreateFailed: "Le nouveau document n’a pas pu être créé. Le document enregistré actuel reste ouvert.",
  }),
  "pt-BR": Object.freeze({
    businessDocumentStartNewQuote: "+ Iniciar novo orçamento",
    businessDocumentStartNewInvoice: "+ Iniciar nova fatura",
    businessDocumentStartingNewQuote: "Iniciando novo orçamento…",
    businessDocumentStartingNewInvoice: "Iniciando nova fatura…",
    businessDocumentNewQuoteReady: "Novo orçamento iniciado. O orçamento anterior permanece em Arquivos salvos.",
    businessDocumentNewInvoiceReady: "Nova fatura iniciada. A fatura anterior permanece em Arquivos salvos.",
    businessDocumentStartNewSaveFailed: "Não foi possível salvar o documento atual. Ele permanece aberto e nenhum novo documento foi criado.",
    businessDocumentStartNewCreateFailed: "Não foi possível iniciar o novo documento. O documento salvo atual permanece aberto.",
  }),
});
