const rows = [
  ["homeUrgent", "Urgent", "Urgente", "Urgent", "Urgente"],
  ["professionalOnTheWay", "Professional on the way", "Profesional en camino", "Professionnel en route", "Profissional a caminho"],
  ["requestAccepted", "Request accepted", "Solicitud aceptada", "Demande acceptée", "Solicitação aceita"],
  ["statusArrived", "Professional arrived", "Profesional llegó", "Le professionnel est arrivé", "O profissional chegou"],
  ["typeMessage", "Type a message...", "Escribe un mensaje...", "Écrivez un message...", "Digite uma mensagem..."],
  ["workStageMaterials", "Materials", "Materiales", "Matériaux", "Materiais"],
  ["workflowNoteWorking", "Work in progress", "Trabajo en progreso", "Travail en cours", "Trabalho em andamento"],
  ["conversationWalkthrough", "Walkthrough", "Recorrido", "Visite guidée", "Vistoria"],
  ["conversationEstimateVisit", "Estimate Visit", "Visita de estimado", "Visite d'estimation", "Visita para orçamento"],
  ["conversationProgressPhoto", "Progress Photo", "Foto de progreso", "Photo d'avancement", "Foto do progresso"],
  ["conversationErrorTitle", "Conversation error", "Error de conversación", "Erreur de conversation", "Erro na conversa"],
  ["conversationErrorBody", "The conversation screen could not load.", "La pantalla de conversación no pudo cargar.", "L'écran de conversation n'a pas pu se charger.", "Não foi possível carregar a tela da conversa."],
  ["conversationBackToCenter", "Back to Communication Center", "Volver al Centro de Comunicación", "Retour au Centre de communication", "Voltar à Central de Comunicação"],
  ["conversationTyping", "Typing...", "Escribiendo...", "Saisie en cours...", "Digitando..."],
  ["conversationActiveNow", "Active now", "Activo ahora", "Actif maintenant", "Ativo agora"],
  ["conversationNotificationsNeeded", "Notifications Needed", "Notificaciones necesarias", "Notifications requises", "Notificações necessárias"],
  ["conversationOpenSettings", "Open Settings", "Abrir Configuración", "Ouvrir les réglages", "Abrir Ajustes"],
  ["conversationContinueWithoutReminders", "Continue Without Reminders", "Continuar sin recordatorios", "Continuer sans rappels", "Continuar sem lembretes"],
  ["conversationRelationshipKicker", "RELATIONSHIP", "RELACIÓN", "RELATION", "RELACIONAMENTO"],
  ["conversationSaveToContacts", "Save to Contacts", "Guardar en Contactos", "Enregistrer dans les contacts", "Salvar nos contatos"],
  ["conversationResourcesKicker", "RESOURCES", "RECURSOS", "RESSOURCES", "RECURSOS"],
  ["conversationConversationKicker", "CONVERSATION", "CONVERSACIÓN", "CONVERSATION", "CONVERSA"],
  ["conversationMarkUnread", "Mark as unread", "Marcar como no leído", "Marquer comme non lu", "Marcar como não lida"],
  ["conversationSavedToHistory", "Saved to History", "Guardado en historial", "Enregistré dans l'historique", "Salvo no histórico"],
  ["conversationSaveToHistory", "Save Conversation to History", "Guardar conversación en historial", "Enregistrer la conversation dans l'historique", "Salvar conversa no histórico"],
  ["conversationSearchAction", "Search", "Buscar en esta conversación", "Rechercher", "Pesquisar"],
  ["conversationClearLocalChat", "Clear local chat", "Limpiar chat local", "Effacer la discussion locale", "Limpar conversa local"],
  ["conversationHideDetails", "Hide ▲", "Ocultar ▲", "Masquer ▲", "Ocultar ▲"],
  ["conversationReviewDetails", "Review Details ▼", "Revisar detalles ▼", "Voir les détails ▼", "Revisar detalhes ▼"],
  ["conversationServiceCompleted", "Service Completed", "Servicio completado", "Service terminé", "Serviço concluído"],
  ["conversationClosurePending", "Closure pending", "Cierre pendiente", "Clôture en attente", "Encerramento pendente"],
  ["conversationScheduleEvaluation", "Schedule Evaluation / Visit", "Programar evaluación / visita", "Planifier une évaluation / visite", "Agendar avaliação / visita"],
  ["conversationScheduleEvaluationHelp", "Add the evaluation or visit details to save it in Work Center and share it in chat.", "Agrega los detalles de la evaluación o visita para guardarla en Work Center y compartirla en el chat.", "Ajoutez les détails de l'évaluation ou de la visite pour les enregistrer dans le Centre de travail et les partager dans la discussion.", "Adicione os detalhes da avaliação ou visita para salvá-los na Central de Trabalho e compartilhá-los no chat."],
  ["conversationAppointmentTitle", "Appointment title", "Título de la cita", "Titre du rendez-vous", "Título do compromisso"],
  ["conversationSearchPlaceholder", "Search in conversation", "Buscar en la conversación", "Rechercher dans la conversation", "Pesquisar na conversa"],
  ["conversationNoSearchMessages", "No messages found in this conversation.", "No se encontró esta conversación", "Aucun message trouvé dans cette conversation.", "Nenhuma mensagem encontrada nesta conversa."],
  ["conversationNoMessages", "No messages yet.", "Aún no hay mensajes en esta conversación.", "Aucun message pour le moment.", "Ainda não há mensagens."],
  ["conversationOpportunityMessagingUnavailable", "Messaging is not available for this request yet. Review the request details here.", "Los mensajes aún no están disponibles para esta solicitud. Revisa los detalles aquí.", "La messagerie n'est pas encore disponible pour cette demande. Consultez les détails ici.", "As mensagens ainda não estão disponíveis para esta solicitação. Revise os detalhes aqui."],
  ["conversationCanonicalLoading", "Loading conversation...", "Cargando conversación...", "Chargement de la conversation...", "Carregando conversa..."],
  ["conversationCanonicalUnavailable", "This conversation is not available.", "Esta conversación no está disponible.", "Cette conversation n'est pas disponible.", "Esta conversa não está disponível."],
  ["conversationCanonicalMessagingUnavailable", "Messaging is not available in this conversation.", "Los mensajes no están disponibles en esta conversación.", "La messagerie n'est pas disponible dans cette conversation.", "As mensagens não estão disponíveis nesta conversa."],
  ["conversationCanonicalClosed", "This conversation is closed. Messages remain available to review.", "Esta conversación está cerrada. Los mensajes siguen disponibles para revisar.", "Cette conversation est fermée. Les messages restent disponibles à la consultation.", "Esta conversa está encerrada. As mensagens continuam disponíveis para consulta."],
  ["conversationCanonicalMessagesUnavailable", "Messages could not be loaded. Try again.", "No se pudieron cargar los mensajes. Inténtalo de nuevo.", "Impossible de charger les messages. Réessayez.", "Não foi possível carregar as mensagens. Tente novamente."],
  ["conversationCanonicalMessageRequired", "Enter a message.", "Escribe un mensaje.", "Saisissez un message.", "Digite uma mensagem."],
  ["conversationCanonicalMessageTooLong", "Messages must be 5,000 characters or fewer.", "Los mensajes deben tener 5,000 caracteres o menos.", "Les messages doivent contenir 5 000 caractères ou moins.", "As mensagens devem ter 5.000 caracteres ou menos."],
  ["conversationCanonicalSendFailed", "Message could not be sent. Try again.", "No se pudo enviar el mensaje. Inténtalo de nuevo.", "Impossible d'envoyer le message. Réessayez.", "Não foi possível enviar a mensagem. Tente novamente."],
  ["conversationCustomerApprovalRequired", "Customer approval required", "Requiere aprobación del cliente", "Approbation du client requise", "Aprovação do cliente necessária"],
  ["conversationMaterialsSent", "Materials sent to customer", "Materiales enviados al cliente", "Matériaux envoyés au client", "Materiais enviados ao cliente"],
  ["conversationTicketCreated", "Ticket Created", "Ticket creado", "Ticket créé", "Chamado criado"],
  ["conversationTenantTicket", "Tenant Ticket", "Ticket de inquilino", "Ticket locataire", "Chamado do inquilino"],
  ["conversationNewTenantTicket", "New Tenant Ticket", "Nuevo ticket de inquilino", "Nouveau ticket locataire", "Novo chamado do inquilino"],
  ["conversationReviewTicket", "Review Ticket", "Revisar ticket", "Vérifier le ticket", "Revisar chamado"],
  ["conversationReviewAction", "Review", "Revisar", "Vérifier", "Revisar"],
  ["conversationSubmitAction", "Submit", "Enviar", "Envoyer", "Enviar"],
  ["conversationSubmitTicket", "Submit Ticket", "Enviar ticket", "Envoyer le ticket", "Enviar chamado"],
  ["conversationTenantTicketCreated", "Tenant Ticket Created", "Ticket de inquilino creado", "Ticket locataire créé", "Chamado do inquilino criado"],
  ["conversationTicketAddedToConversation", "Ticket {ticketId} was added to this conversation.", "El ticket {ticketId} se agregó a esta conversación.", "Le ticket {ticketId} a été ajouté à cette conversation.", "O chamado {ticketId} foi adicionado a esta conversa."],
  ["conversationTicketNumber", "Ticket", "Número", "Ticket", "Chamado"],
  ["conversationPropertyUnit", "Property / Unit", "Propiedad / unidad", "Propriété / Logement", "Propriedade / Unidade"],
  ["conversationIssueType", "Issue Type", "Tipo", "Type de problème", "Tipo de problema"],
  ["conversationPriority", "Priority", "Prioridad", "Priorité", "Prioridade"],
  ["conversationDescription", "Description", "Descripción", "Description", "Descrição"],
  ["conversationDescribeNeedsAttention", "Describe what needs attention.", "Describe qué necesita atención.", "Décrivez ce qui nécessite une intervention.", "Descreva o que precisa de atenção."],
  ["conversationPhotos", "Photos", "Fotos", "Photos", "Fotos"],
  ["conversationPhotoUploadInTools", "Photo upload stays in conversation tools.", "La carga de fotos permanece en las herramientas de conversación.", "Le téléversement de photos reste dans les outils de conversation.", "O envio de fotos permanece nas ferramentas de conversa."],
  ["conversationIssuePlumbing", "Plumbing", "Plomería", "Plomberie", "Encanamento"],
  ["conversationIssueHvac", "HVAC", "Climatización", "CVC", "Climatização"],
  ["conversationIssueElectrical", "Electrical", "Electricidad", "Électricité", "Elétrica"],
  ["conversationIssueAppliance", "Appliance", "Electrodoméstico", "Électroménager", "Eletrodoméstico"],
  ["conversationIssueGeneralMaintenance", "General Maintenance", "Mantenimiento general", "Entretien général", "Manutenção geral"],
  ["conversationIssueOther", "Other", "Otro", "Autre", "Outro"],
  ["conversationPriorityLow", "Low", "Baja", "Faible", "Baixa"],
  ["conversationPriorityNormal", "Normal", "Normal", "Normale", "Normal"],
  ["conversationPriorityHigh", "High", "Alta", "Élevée", "Alta"],
  ["conversationPriorityEmergency", "Emergency", "Emergencia", "Urgence", "Emergência"],
  ["conversationMore", "more", "más", "de plus", "mais"],
  ["conversationApprove", "Approve", "Aprobar", "Approuver", "Aprovar"],
  ["conversationReply", "Reply", "Responder", "Répondre", "Responder"],
  ["conversationCopy", "Copy", "Copiar", "Copier", "Copiar"],
  ["conversationUnsend", "Unsend", "Eliminar", "Annuler l'envoi", "Cancelar envio"],
  ["conversationReplying", "Replying", "Respondiendo", "Réponse à", "Respondendo"],
  ["conversationImageReady", "Image ready to send", "Imagen lista para enviar", "Image prête à envoyer", "Imagem pronta para enviar"],
  ["conversationPhotosComingSoon", "Photos coming soon", "Fotos próximamente", "Photos bientôt disponibles", "Fotos em breve"],
  ["conversationCamera", "Camera", "Cámara", "Appareil photo", "Câmera"],
  ["conversationVoiceMessage", "Voice Message", "Mensaje de voz", "Message vocal", "Mensagem de voz"],
  ["conversationWorkflow", "Workflow", "Flujo de trabajo", "Flux de travail", "Fluxo de trabalho"],
  ["conversationReportIssue", "Report Issue", "Reportar problema", "Signaler un problème", "Relatar problema"],
  ["conversationPrepareInvoice", "Prepare Invoice", "Preparar factura", "Préparer la facture", "Preparar fatura"],
  ["conversationJobRecords", "Job Records", "Registros", "Dossiers du travail", "Registros do trabalho"],
  ["conversationExplainPrompt", "What would you like the professional to know?", "¿Qué te gustaría explicarle al profesional?", "Que souhaitez-vous expliquer au professionnel ?", "O que você gostaria que o profissional soubesse?"],
  ["conversationExplainHelp", "Help explain the issue or work you need done.", "Ayuda a explicar el problema o el trabajo que necesitas.", "Aidez à expliquer le problème ou le travail dont vous avez besoin.", "Ajude a explicar o problema ou o trabalho necessário."],
  ["conversationQuickLeak", "Leak", "Fuga", "Fuite", "Vazamento"],
  ["conversationQuickBroken", "Broken", "Roto", "Cassé", "Quebrado"],
  ["conversationQuickRepair", "Repair", "Reparación", "Réparation", "Reparo"],
  ["conversationExplainPlaceholder", "Explain what is going on...", "Explica lo que está pasando...", "Expliquez ce qui se passe...", "Explique o que está acontecendo..."],
  ["conversationVoiceComingSoon", "Voice notes coming soon.", "Notas de voz próximamente.", "Notes vocales bientôt disponibles.", "Notas de voz em breve."],
  ["conversationClearChatTitle", "Clear chat?", "¿Limpiar chat?", "Effacer la discussion ?", "Limpar conversa?"],
  ["conversationClearChatBody", "This will delete locally saved messages on this device.", "Esto eliminará los mensajes guardados localmente en este dispositivo.", "Cela supprimera les messages enregistrés localement sur cet appareil.", "Isso excluirá as mensagens salvas localmente neste dispositivo."],
  ["conversationClear", "Clear", "Limpiar", "Effacer", "Limpar"],
  ["conversationJobRecord", "Job Record", "Registro del trabajo", "Dossier du travail", "Registro do trabalho"],
  ["conversationSavedWorkflowItems", " saved workflow items", " elementos guardados", " éléments de flux enregistrés", " itens de fluxo salvos"],
  ["conversationJobRecordHelp", "Job Record saves photos, updates, approvals, materials, and important project events into a permanent operating history.", "El Registro del Trabajo guarda fotos, actualizaciones, aprobaciones, materiales y eventos importantes del proyecto en un historial operativo permanente.", "Le Dossier du travail conserve les photos, mises à jour, approbations, matériaux et événements importants du projet dans un historique opérationnel permanent.", "O Registro do trabalho salva fotos, atualizações, aprovações, materiais e eventos importantes do projeto em um histórico operacional permanente."],
  ["conversationReadJobRecord", "Read Job Record", "Leer registro", "Lire le dossier du travail", "Ler registro do trabalho"],
  ["conversationNoJobRecords", "No saved job records yet.", "Aún no hay registros guardados.", "Aucun dossier du travail enregistré.", "Ainda não há registros do trabalho salvos."],
  ["conversationSavedRelationshipMemory", "Saved as relationship memory", "Guardado como memoria de la relación", "Enregistré dans la mémoire de la relation", "Salvo como memória do relacionamento"],
  ["conversationMomentPreview", "Meetro Moment preview", "Vista previa de Meetro Moment", "Aperçu du Meetro Moment", "Prévia do Meetro Moment"],
  ["conversationDocumentationAttached", "Documentation attached", "Documentación adjunta", "Documentation jointe", "Documentação anexada"],
  ["conversationWorkflowSummaryAvailable", "Meetro workflow summary available", "Resumen del flujo de Meetro disponible", "Résumé du flux Meetro disponible", "Resumo do fluxo do Meetro disponível"],
  ["conversationDeleteAppointmentTitle", "Delete appointment?", "¿Eliminar cita?", "Supprimer le rendez-vous ?", "Excluir compromisso?"],
  ["conversationDeleteAppointmentBody", "This appointment will be removed from chat and the local Work Center schedule.", "Esta cita se eliminará del chat y del calendario de trabajo local.", "Ce rendez-vous sera supprimé de la discussion et du calendrier local du Centre de travail.", "Este compromisso será removido do chat e da agenda local da Central de Trabalho."],
  ["conversationAppointmentDetails", "Appointment Details", "Detalles de la cita", "Détails du rendez-vous", "Detalhes do compromisso"],
  ["conversationScheduledAppointment", "Scheduled Appointment", "Cita programada", "Rendez-vous planifié", "Compromisso agendado"],
  ["conversationEditSchedule", "Edit Schedule", "Editar programación", "Modifier le calendrier", "Editar agenda"],
  ["conversationJobPreview", "Job preview", "Vista previa del trabajo", "Aperçu du travail", "Prévia do trabalho"],
  ["conversationJobPreviewHelp", "Photos, notes, and documentation will appear here.", "Fotos, notas y documentación aparecerán aquí.", "Les photos, notes et documents apparaîtront ici.", "Fotos, observações e documentação aparecerão aqui."],
  ["conversationReadSummary", "Read Summary", "Leer resumen", "Lire le résumé", "Ler resumo"],
  ["conversationSaveJobRecord", "Save to Job Record", "Guardar en trabajo", "Enregistrer dans le dossier du travail", "Salvar no registro do trabalho"],
];

const languageIndex = Object.freeze({ en: 1, es: 2, fr: 3, "pt-BR": 4 });

export const conversationWorkflowLanguage = Object.freeze(
  Object.fromEntries(
    Object.entries(languageIndex).map(([language, index]) => [
      language,
      Object.freeze(Object.fromEntries(rows.map(([key, ...copy]) => [key, copy[index - 1]]))),
    ])
  )
);

export const conversationWorkflowEnglishKeyMap = Object.freeze(
  Object.fromEntries(rows.map(([key, english]) => [english, key]))
);
