const rows = [
  ["acceptDispatch", "Accepter l'intervention", "Aceitar atendimento"],
  ["accepted", "Accepté", "Aceito"],
  ["acceptedShort", "Accepter", "Aceitar"],
  ["activeNow", "Actif maintenant", "Ativo agora"],
  ["activeWorkFallback", "Travail actif", "Trabalho ativo"],
  ["appointmentCancelled", "Rendez-vous annulé", "Compromisso cancelado"],
  ["appointmentChangeRequested", "Autre horaire demandé", "Outro horário solicitado"],
  ["appointmentChangeRequestedChatText", "Le client a demandé un autre horaire de rendez-vous.", "O cliente solicitou outro horário para o compromisso."],
  ["appointmentConfirmed", "Rendez-vous confirmé", "Compromisso confirmado"],
  ["appointmentConfirmedChatText", "Rendez-vous confirmé. L'heure prévue convient au client.", "Compromisso confirmado. O horário agendado funciona para o cliente."],
  ["appointmentDifferentTimeMessage", "J'ai besoin d'un autre horaire. Voici ce qui me convient mieux : ", "Preciso de outro horário. Isto funciona melhor para mim: "],
  ["appointmentPendingConfirmation", "Confirmation du client en attente", "Confirmação do cliente pendente"],
  ["appointmentType", "Type de rendez-vous", "Tipo de compromisso"],
  ["arrived", "Arrivé", "Chegou"],
  ["arrivedShort", "Arrivé", "Chegou"],
  ["backToDashboard", "Retour au tableau de bord", "Voltar ao Painel"],
  ["backToHome", "Retour à l'accueil", "Voltar ao Início"],
  ["backToWorkCenter", "Retour au Centre de travail", "Voltar à Central de Trabalho"],
  ["businessDashboardText", "Gérez les clients, les messages, la visibilité du profil et la croissance de votre entreprise au même endroit.", "Gerencie clientes, mensagens, visibilidade do perfil e o crescimento do seu negócio em um só lugar."],
  ["businessGreeting", "Bonjour", "Bom dia"],
  ["businessType", "Type d'entreprise", "Tipo de negócio"],
  ["cancelEdit", "Annuler la modification", "Cancelar edição"],
  ["cancelledJobNote", "Cette demande d'urgence a été annulée.", "Esta solicitação de emergência foi cancelada."],
  ["cleaning", "Nettoyage", "Limpeza"],
  ["closeForm", "Fermer le formulaire", "Fechar formulário"],
  ["closePhotoGallery", "Fermer la galerie de photos", "Fechar galeria de fotos"],
  ["completeEmergency", "Terminer", "Concluir"],
  ["completedJobNote", "Cette intervention d'urgence est terminée.", "Este trabalho de emergência foi concluído."],
  ["completedJobs", "Travaux terminés", "Trabalhos concluídos"],
  ["confirmAppointment", "Confirmer le rendez-vous", "Confirmar compromisso"],
  ["consultation", "Consultation", "Consulta"],
  ["conversation", "Conversation", "Conversa"],
  ["conversationPhoto", "Photo de la conversation", "Foto da conversa"],
  ["currentStatus", "Statut actuel", "Status atual"],
  ["customerLocation", "Emplacement du client", "Localização do cliente"],
  ["delete", "Supprimer", "Excluir"],
  ["deleteVisit", "Supprimer la visite ?", "Excluir visita?"],
  ["emergencyDispatch", "Intervention d'urgence", "Atendimento de emergência"],
  ["emergencyPlumbing", "Plomberie d'urgence", "Encanamento de emergência"],
  ["estimateVisit", "Visite d'estimation", "Visita para orçamento"],
  ["gallery", "Galerie", "Galeria"],
  ["handymanLabel", "Services d'entretien", "Serviços gerais"],
  ["homeActiveRequestsTitle", "Demandes actives", "Solicitações ativas"],
  ["homeHelpToday", "Comment pouvons-nous vous aider aujourd'hui ?", "Como podemos ajudar hoje?"],
  ["homeHelpTodaySubtitle", "Demandez un service, suivez le travail actif, poursuivez les conversations et consultez l'historique.", "Solicite um serviço, acompanhe o trabalho ativo, continue conversas e consulte o histórico."],
  ["homeMessagesAllCaughtUp", "Aucune conversation ne demande votre attention", "Nenhuma conversa precisa de atenção"],
  ["homeMessagesAllCaughtUpText", "Les nouvelles réponses et mises à jour apparaîtront ici.", "Novas respostas e atualizações aparecerão aqui."],
  ["homeMessagesNeedAttentionText", "Ouvrez le Centre de communication pour répondre ou voir la dernière mise à jour.", "Abra a Central de Comunicação para responder ou ver a atualização mais recente."],
  ["homeNoActiveRequestsText", "Demandez un service pour commencer avec un professionnel.", "Solicite um serviço para iniciar com um profissional."],
  ["homeNoActiveRequestsTitle", "Aucune demande active", "Nenhuma solicitação ativa"],
  ["homeWorkflowLabel", "Parcours du propriétaire", "Fluxo do proprietário"],
  ["homeownerWorkflowHome", "Accueil", "Início"],
  ["inProgress", "En cours", "Em andamento"],
  ["live", "En direct", "Ao vivo"],
  ["liveRoutePreview", "Aperçu de l'itinéraire", "Prévia da rota"],
  ["loadingMessages", "Chargement des messages...", "Carregando mensagens..."],
  ["location", "Emplacement", "Localização"],
  ["locationPending", "Emplacement en attente", "Localização pendente"],
  ["manage", "Gérer", "Gerenciar"],
  ["materialsList", "Liste des matériaux", "Lista de materiais"],
  ["messageNeedsAttention", "Attention requise", "Precisa de atenção"],
  ["messageNextStepAppointment", "Confirmer les détails du rendez-vous", "Confirmar detalhes do compromisso"],
  ["messageNextStepClosure", "Résoudre les éléments de clôture", "Resolver itens de encerramento"],
  ["messageNextStepCompletion", "Examiner la mise à jour de fin", "Revisar atualização de conclusão"],
  ["messageNextStepEmergency", "Examiner le statut d'urgence", "Revisar status da emergência"],
  ["messageNextStepOpen", "Continuer la conversation", "Continuar conversa"],
  ["messageNextStepQuote", "Examiner les détails du devis", "Revisar detalhes do orçamento"],
  ["messageNextStepReply", "Ouvrir et répondre", "Abrir e responder"],
  ["messageNextStepSaved", "Examiner l'historique de la relation", "Revisar histórico do relacionamento"],
  ["newLeads", "Nouveaux clients", "Novos clientes"],
  ["nextPhoto", "Photo suivante", "Próxima foto"],
  ["onTheWay", "En route", "A caminho"],
  ["previousPhoto", "Photo précédente", "Foto anterior"],
  ["professionalToCustomer", "Professionnel → Client", "Profissional → Cliente"],
  ["professionalUser", "Utilisateur professionnel", "Usuário profissional"],
  ["projectConversation", "Conversation de service", "Conversa de serviço"],
  ["requestDifferentTime", "Demander un autre horaire", "Solicitar outro horário"],
  ["requestService", "Demander un service", "Solicitar serviço"],
  ["requested", "Demandé", "Solicitado"],
  ["saveAppointment", "Enregistrer le rendez-vous", "Salvar compromisso"],
  ["savedHistory", "Historique enregistré", "Histórico salvo"],
  ["schedule", "Calendrier", "Agenda"],
  ["scheduleNotes", "Notes", "Observações"],
  ["scheduledVisit", "Visite planifiée", "Visita agendada"],
  ["startWork", "Commencer le travail", "Iniciar trabalho"],
  ["status", "Statut", "Status"],
  ["summary", "Résumé", "Resumo"],
  ["tapOpenConversation", "Touchez pour continuer la conversation", "Toque para continuar a conversa"],
  ["time", "Heure", "Horário"],
  ["today", "Aujourd'hui", "Hoje"],
  ["unread", "Non lu", "Não lida"],
  ["viewRoute", "Voir l'itinéraire", "Ver rota"],
  ["virtualMeeting", "Réunion virtuelle", "Reunião virtual"],
  ["walkthrough", "Visite guidée", "Vistoria"],
  ["yourBusiness", "Votre entreprise", "Seu negócio"],
  ["closureCenterCategoryCompliance", "Permis et conformité", "Licenças e conformidade"],
  ["closureCenterCategoryComplianceDescription", "Finalisation des permis, inspections, approbations requises et points de conformité non résolus", "Finalização de licenças, inspeções, aprovações necessárias e itens de conformidade pendentes"],
  ["closureCenterCategoryCustomer", "Client", "Cliente"],
  ["closureCenterCategoryCustomerDescription", "Confirmation ou suivi du client", "Confirmação ou acompanhamento do cliente"],
  ["closureCenterCategoryDocumentation", "Documentation", "Documentação"],
  ["closureCenterCategoryDocumentationDescription", "Documents requis et dossiers de transmission", "Documentos necessários e registros de entrega"],
  ["closureCenterCategoryFinancial", "Finances", "Financeiro"],
  ["closureCenterCategoryFinancialDescription", "Statut du paiement et obligations financières", "Status do pagamento e obrigações financeiras"],
  ["closureCenterCategoryWork", "Travail", "Trabalho"],
  ["closureCenterCategoryWorkDescription", "Détails de fin et preuves du travail", "Detalhes da conclusão e evidências do trabalho"],
  ["closureCenterEvidenceAvailable", "Preuves disponibles", "Evidências disponíveis"],
  ["closureCenterNeedsReview", "Vérification requise", "Precisa de revisão"],
  ["closureCenterNextStep", "Résolvez les obligations restantes.", "Resolva as obrigações pendentes."],
  ["closureCenterNoRecords", "Aucun travail terminé n'est encore prêt pour la vérification de clôture.", "Nenhum trabalho concluído está pronto para revisão de encerramento."],
  ["closureCenterPurpose", "Vérifiez le travail, le paiement, les documents, les permis, les inspections et les obligations avant de placer les projets dans l'historique.", "Verifique trabalho, pagamento, documentos, licenças, inspeções e obrigações antes de mover projetos para o histórico."],
  ["closureCenterReviewDescription", "Examinez les preuves disponibles pour chaque projet terminé. Les informations manquantes restent en attente de vérification.", "Revise as evidências disponíveis de cada projeto concluído. Informações ausentes permanecem pendentes até serem verificadas."],
  ["closureCenterReviewTitle", "Projets en attente de vérification de clôture", "Projetos aguardando revisão de encerramento"],
  ["closureCenterTitle", "Centre de clôture", "Central de Encerramento"],
  ["createActiveJobAction", "Créer un travail actif", "Criar trabalho ativo"],
  ["createCompletion", "Créer la fin du travail", "Criar conclusão"],
  ["customerApprovedStartWork", "Client approuvé — Commencer le travail", "Cliente aprovou — Iniciar trabalho"],
  ["emergencyContinuesInChat", "La coordination de l'urgence se poursuit dans la conversation.", "A coordenação da emergência continua na conversa."],
  ["evaluationOutcomeInstruction", "Consignez les conclusions de l'évaluation et choisissez la prochaine étape appropriée.", "Registre o que a avaliação determinou e escolha a próxima etapa adequada."],
  ["evaluationOutcomeTitle", "Résultat de l'évaluation", "Resultado da avaliação"],
  ["evaluationQuoteRequired", "Évaluation terminée — Devis requis", "Avaliação concluída — Orçamento necessário"],
  ["generateMaterialsList", "Générer la liste des matériaux", "Gerar lista de materiais"],
  ["manualAdd", "Ajout manuel", "Adicionar manualmente"],
  ["manualCustomerConnectSteps", "Pour connecter ce client :\n\n1. Touchez Convertir en projet.\n2. Créez ou envoyez une invitation au projet.\n3. Après acceptation, Meetro activera la discussion, les dossiers, les matériaux et le parcours complet.", "Para conectar este cliente:\n\n1. Toque em Converter em projeto.\n2. Crie ou envie um convite de projeto.\n3. Após a aceitação, o Meetro liberará conversa, registros, materiais e o fluxo completo."],
  ["manualCustomerHowToConnect", "Comment le connecter", "Como conectar"],
  ["manualCustomerWarning", "Client manuel : aucune discussion, aucun dossier automatique, suivi Meetro ou parcours complet avant la conversion en projet Meetro.", "Cliente manual: sem conversa, registros automáticos, acompanhamento Meetro ou fluxo completo até a conversão em projeto Meetro."],
  ["manualScheduleEntry", "Entrée manuelle du calendrier", "Entrada manual no calendário"],
  ["manualScheduleNotice", "Les clients ajoutés manuellement n'auront pas de discussion, de dossiers automatiques, de suivi Meetro ni de parcours complet avant leur conversion en projet Meetro.", "Clientes adicionados manualmente não terão conversa, registros automáticos, acompanhamento Meetro ou fluxo completo até a conversão em projeto Meetro."],
  ["markReceived", "Marquer comme reçu", "Marcar como recebido"],
  ["material", "Matériau", "Material"],
  ["materialsCenter", "Centre des matériaux", "Central de Materiais"],
  ["moveToActiveJob", "Déplacer vers le travail actif", "Mover para trabalho ativo"],
  ["needed", "Nécessaire", "Necessário"],
  ["needsApproval", "Approbation requise", "Precisa de aprovação"],
  ["needsReview", "Vérification requise", "Precisa de revisão"],
  ["nextStepArrive", "Prochaine étape : arriver sur le lieu du travail.", "Próxima etapa: chegar ao local do trabalho."],
  ["nextStepBeginWork", "Prochaine étape : commencer le travail ou faire une pause pour les matériaux.", "Próxima etapa: iniciar o trabalho ou pausar por materiais."],
  ["nextStepContinueWork", "Prochaine étape : poursuivre le travail, informer le client ou documenter la fin.", "Próxima etapa: continuar o trabalho, atualizar o cliente ou documentar a conclusão."],
  ["nextStepResumeMaterials", "Prochaine étape : attendre les matériaux et reprendre le travail.", "Próxima etapa: aguardar os materiais e retomar o trabalho."],
  ["nextStepUpdateStatus", "Prochaine étape : mettre à jour le statut du travail.", "Próxima etapa: atualizar o status do trabalho."],
  ["noScheduledVisits", "Aucune visite planifiée.", "Nenhuma visita agendada."],
  ["openCompletionSheet", "Ouvrir la fiche de fin", "Abrir ficha de conclusão"],
  ["openEmergencyChat", "Continuer la conversation", "Continuar conversa"],
  ["pauseForMaterials", "Pause pour les matériaux", "Pausar por materiais"],
  ["pauseJob", "Mettre le travail en pause", "Pausar trabalho"],
  ["pendingDecisionWarning", "Ce travail attend une décision. Confirmez s'il faut un devis, des matériaux, un acompte ou l'approbation du client avant de l'activer.", "Este trabalho aguarda uma decisão. Confirme se precisa de orçamento, materiais, entrada ou aprovação do cliente antes de ativá-lo."],
  ["pendingOperationalReview", "Vérification opérationnelle en attente", "Revisão operacional pendente"],
  ["prepareJob", "Examiner l'évaluation", "Revisar avaliação"],
  ["propertyManagementClosureNote", "La clôture d'un entretien immobilier peut aussi exiger la confirmation du locataire, l'approbation du propriétaire, la résolution des accès, les documents et les obligations de conformité.", "O encerramento da manutenção pode exigir confirmação do inquilino, aprovação do proprietário, resolução de acesso, documentos e obrigações de conformidade."],
  ["propertyManagementWorkCenterNote", "Utilisez le même Centre de travail pour les demandes des locataires, les évaluations, les fournisseurs, les urgences, la clôture et l'historique de la relation.", "Use a mesma Central de Trabalho para solicitações de inquilinos, avaliações, fornecedores, emergências, encerramento e histórico do relacionamento."],
  ["providedBy", "Fourni par", "Fornecido por"],
  ["quantity", "Quantité", "Quantidade"],
  ["quoteAfterEvaluation", "Créer un devis après l'évaluation", "Criar orçamento após a avaliação"],
  ["quotesNeedAction", "Des devis demandent une action", "Orçamentos precisam de ação"],
  ["received", "Reçu", "Recebido"],
  ["relationshipHistoryDescription", "Les travaux, approbations, documents et événements importants restent disponibles comme mémoire de la relation pour les services futurs.", "Trabalhos, aprovações, documentos e eventos importantes permanecem disponíveis como memória do relacionamento para serviços futuros."],
  ["relationshipHistoryEmpty", "Aucun historique de relation.", "Ainda não há histórico do relacionamento."],
  ["relationshipHistoryEmptyDescription", "Les dossiers durables, approbations, documents et événements importants apparaîtront ici au fil de la relation.", "Registros duradouros, aprovações, documentos e eventos importantes aparecerão aqui conforme o relacionamento evolui."],
  ["relationshipHistoryTitle", "Historique de la relation", "Histórico do relacionamento"],
  ["resumeWork", "Reprendre le travail", "Retomar trabalho"],
  ["reviseQuoteAction", "Réviser le devis", "Revisar orçamento"],
  ["saveMaterial", "Enregistrer le matériau", "Salvar material"],
  ["scheduleEvaluation", "Planifier l'évaluation", "Agendar avaliação"],
  ["scheduledConsultation", "Consultation planifiée", "Consulta agendada"],
  ["scheduledEmergencyDispatch", "Intervention d'urgence planifiée", "Atendimento de emergência agendado"],
  ["scheduledEstimateVisit", "Visite d'estimation planifiée", "Visita para orçamento agendada"],
  ["scheduledVirtualMeeting", "Réunion virtuelle planifiée", "Reunião virtual agendada"],
  ["scheduledVisitsFromChat", "Les visites enregistrées depuis les conversations apparaîtront ici.", "Visitas salvas nas conversas aparecerão aqui."],
  ["scheduledWalkthrough", "Visite guidée planifiée", "Vistoria agendada"],
  ["scheduledWork", "Travail planifié", "Trabalho agendado"],
  ["searchMaterials", "Rechercher des matériaux...", "Pesquisar materiais..."],
  ["started", "Commencé", "Iniciado"],
  ["timeTbd", "Heure à déterminer", "Horário a definir"],
  ["updateAppointment", "Mettre à jour le rendez-vous", "Atualizar compromisso"],
  ["updateMaterial", "Mettre à jour le matériau", "Atualizar material"],
  ["workCenterBadgeReviewPerformance", "Examiner les performances", "Revisar desempenho"],
  ["workCenterClosureTitle", "Clôture", "Encerramento"],
  ["workCenterNextStepLabel", "Prochaine étape", "Próxima etapa"],
  ["workCenterSubtitle", "Voyez ce qui demande votre attention maintenant.", "Veja o que precisa de atenção agora."],
  ["workCenterWorkflowArea", "Zone du parcours", "Área do fluxo"],
  ["workGuidanceMaterials", "Suivez les matériaux demandés, en attente, approuvés, fournis par le client ou l'entreprise et reçus.", "Acompanhe materiais solicitados, pendentes, aprovados, fornecidos pelo cliente ou negócio e recebidos."],
  ["workSchedule", "Calendrier des évaluations", "Agenda de avaliações"],
  ["workTabMaterials", "Matériaux", "Materiais"],
];

export const coreRouteParityLanguage = Object.freeze({
  fr: Object.freeze(Object.fromEntries(rows.map(([key, fr]) => [key, fr]))),
  "pt-BR": Object.freeze(Object.fromEntries(rows.map(([key, , pt]) => [key, pt]))),
});

export const CORE_WORKFLOW_KEYS = Object.freeze(rows.map(([key]) => key));
