export const coreWorkflowLanguage = Object.freeze({
  en: Object.freeze({
    momentsExperienceTitle_homeowner: "Your Meetro Moments",
    momentsExperienceSubtitle_homeowner: "Every completed project becomes part of your home's story.",
    momentsExperienceTitle_business: "Your Meetro Moments",
    momentsExperienceSubtitle_business: "Every completed project becomes part of your business legacy.",
    momentsExperienceTitle_employee: "Your Meetro Moments",
    momentsExperienceSubtitle_employee: "Every accomplishment becomes part of your professional journey.",
    momentsExperienceTitle_community: "Community Meetro Moments",
    momentsExperienceSubtitle_community: "Celebrating the projects that strengthen our community.",
    momentsPrivacyLabel_published: "Published",
    momentsPrivacyMessage_published: "This Moment is published.",
    momentsPrivacyLabel_pending: "Pending confirmation",
    momentsPrivacyMessage_pending: "This Moment is waiting for customer confirmation.",
    momentsPrivacyLabel_private: "Private",
    momentsPrivacyMessage_private: "This Moment is saved privately.",
    momentsPrivacyLabel_hidden: "Hidden",
    momentsPrivacyMessage_hidden: "This Moment is hidden.",
    momentsPrivacyLabel_unavailable: "Not visible",
    momentsPrivacyMessage_unavailable: "This Moment is not visible right now.",
    momentsOpenMomentAria: "Open {title}",
    momentsMomentFallback: "Meetro Moment",
    momentsCompletedDate: "Completed {date}",
    momentsCompletedProject: "Completed Project",
    momentsReviewRating: "{rating}/5 Review",
    momentsWarrantyIncluded: "Warranty Included",
    momentsBefore: "Before",
    momentsAfter: "After",
    momentDetailBack: "Back to Meetro Moments",
    momentDetailUnavailableTitle: "Meetro Moment unavailable",
    momentDetailUnavailableUnverified: "This accomplishment is not ready to appear as a verified Meetro Moment.",
    momentDetailUnavailableProtected: "This Meetro Moment is protected until the right people can see it.",
    momentDetailUnavailableMissing: "This Meetro Moment could not be found.",
    momentDetailProjectType: "Project type",
    momentDetailDuration: "Duration",
    momentDetailWarranty: "Warranty",
    momentDetailReceipt: "Receipt",
    momentDetailPermit: "Permit",
    momentDetailInvestment: "Investment",
    momentDetailLocation: "Project location",
    momentDetailVerified: "Verified Meetro Moment",
    momentDetailMainVisualAria: "Main visual",
    momentDetailHistoryPreserved: "Project history preserved",
    momentDetailWhyItMatters: "Why this moment matters",
    momentDetailPhotoCount: "{count} photos",
    momentDetailStory: "Story",
    momentDetailJourney: "Project Journey",
    momentDetailJourneySubtitle: "From first conversation to closure",
    momentDetailJourney_consultation: "Consultation",
    momentDetailJourney_estimate_quote: "Estimate / Quote",
    momentDetailJourney_approval: "Approval",
    momentDetailJourney_work: "Work",
    momentDetailJourney_completed: "Completed",
    momentDetailJourney_closed: "Closed",
    momentDetailRelated: "Related Moments",
    momentDetailRelationshipHistory: "Relationship History",
    momentDetailVerifiedWork: "Verified work",
    momentDetailRelatedEmpty: "Related Moments will appear as more verified work becomes part of this history.",
    momentDetailRelationshipContext: "Relationship Context",
    momentDetailPeopleConnected: "People connected to this work",
    momentDetailOpenRelationshipHistory: "Open Relationship History",
    momentDetailDetails: "Moment Details",
    momentDetailProjectProof: "Project proof",
    momentDetailProofEmpty: "More proof will appear here when it is confirmed and safe to show.",
    momentDetailConfirmedRating: "{rating}/5 confirmed rating",
  }),
  es: Object.freeze({
    momentsExperienceTitle_homeowner: "Tus Momentos Meetro",
    momentsExperienceSubtitle_homeowner: "Cada proyecto completado se convierte en parte de la historia de tu hogar.",
    momentsExperienceTitle_business: "Tus Momentos Meetro",
    momentsExperienceSubtitle_business: "Cada proyecto completado se convierte en parte del legado de tu negocio.",
    momentsExperienceTitle_employee: "Tus Momentos Meetro",
    momentsExperienceSubtitle_employee: "Cada logro se convierte en parte de tu trayectoria profesional.",
    momentsExperienceTitle_community: "Momentos de la comunidad Meetro",
    momentsExperienceSubtitle_community: "Celebramos los proyectos que fortalecen nuestra comunidad.",
    momentsPrivacyLabel_published: "Publicado",
    momentsPrivacyMessage_published: "Este Momento está publicado.",
    momentsPrivacyLabel_pending: "Confirmación pendiente",
    momentsPrivacyMessage_pending: "Este Momento espera la confirmación del cliente.",
    momentsPrivacyLabel_private: "Privado",
    momentsPrivacyMessage_private: "Este Momento está guardado de forma privada.",
    momentsPrivacyLabel_hidden: "Oculto",
    momentsPrivacyMessage_hidden: "Este Momento está oculto.",
    momentsPrivacyLabel_unavailable: "No visible",
    momentsPrivacyMessage_unavailable: "Este Momento no está visible en este momento.",
    momentsOpenMomentAria: "Abrir {title}",
    momentsMomentFallback: "Momento Meetro",
    momentsCompletedDate: "Completado {date}",
    momentsCompletedProject: "Proyecto completado",
    momentsReviewRating: "Reseña de {rating}/5",
    momentsWarrantyIncluded: "Garantía incluida",
    momentsBefore: "Antes",
    momentsAfter: "Después",
    momentDetailBack: "Volver a Momentos Meetro",
    momentDetailUnavailableTitle: "Momento Meetro no disponible",
    momentDetailUnavailableUnverified: "Este logro aún no está listo para aparecer como un Momento Meetro verificado.",
    momentDetailUnavailableProtected: "Este Momento Meetro está protegido hasta que las personas adecuadas puedan verlo.",
    momentDetailUnavailableMissing: "No se pudo encontrar este Momento Meetro.",
    momentDetailProjectType: "Tipo de proyecto",
    momentDetailDuration: "Duración",
    momentDetailWarranty: "Garantía",
    momentDetailReceipt: "Recibo",
    momentDetailPermit: "Permiso",
    momentDetailInvestment: "Inversión",
    momentDetailLocation: "Ubicación del proyecto",
    momentDetailVerified: "Momento Meetro verificado",
    momentDetailMainVisualAria: "Imagen principal",
    momentDetailHistoryPreserved: "Historial del proyecto conservado",
    momentDetailWhyItMatters: "Por qué importa este momento",
    momentDetailPhotoCount: "{count} fotos",
    momentDetailStory: "Historia",
    momentDetailJourney: "Recorrido del proyecto",
    momentDetailJourneySubtitle: "Desde la primera conversación hasta el cierre",
    momentDetailJourney_consultation: "Consulta",
    momentDetailJourney_estimate_quote: "Estimación / Cotización",
    momentDetailJourney_approval: "Aprobación",
    momentDetailJourney_work: "Trabajo",
    momentDetailJourney_completed: "Completado",
    momentDetailJourney_closed: "Cerrado",
    momentDetailRelated: "Momentos relacionados",
    momentDetailRelationshipHistory: "Historial de la relación",
    momentDetailVerifiedWork: "Trabajo verificado",
    momentDetailRelatedEmpty: "Los Momentos relacionados aparecerán cuando más trabajos verificados formen parte de este historial.",
    momentDetailRelationshipContext: "Contexto de la relación",
    momentDetailPeopleConnected: "Personas vinculadas a este trabajo",
    momentDetailOpenRelationshipHistory: "Abrir historial de la relación",
    momentDetailDetails: "Detalles del Momento",
    momentDetailProjectProof: "Evidencia del proyecto",
    momentDetailProofEmpty: "Aparecerán más pruebas cuando estén confirmadas y sea seguro mostrarlas.",
    momentDetailConfirmedRating: "Calificación confirmada de {rating}/5",
  }),
  fr: Object.freeze({
    momentsExperienceTitle_homeowner: "Vos Moments Meetro",
    momentsExperienceSubtitle_homeowner: "Chaque projet terminé fait partie de l'histoire de votre foyer.",
    momentsExperienceTitle_business: "Vos Moments Meetro",
    momentsExperienceSubtitle_business: "Chaque projet terminé fait partie de l'héritage de votre entreprise.",
    momentsExperienceTitle_employee: "Vos Moments Meetro",
    momentsExperienceSubtitle_employee: "Chaque accomplissement fait partie de votre parcours professionnel.",
    momentsExperienceTitle_community: "Moments de la communauté Meetro",
    momentsExperienceSubtitle_community: "Nous célébrons les projets qui renforcent notre communauté.",
    momentsPrivacyLabel_published: "Publié",
    momentsPrivacyMessage_published: "Ce Moment est publié.",
    momentsPrivacyLabel_pending: "Confirmation en attente",
    momentsPrivacyMessage_pending: "Ce Moment attend la confirmation du client.",
    momentsPrivacyLabel_private: "Privé",
    momentsPrivacyMessage_private: "Ce Moment est enregistré en privé.",
    momentsPrivacyLabel_hidden: "Masqué",
    momentsPrivacyMessage_hidden: "Ce Moment est masqué.",
    momentsPrivacyLabel_unavailable: "Non visible",
    momentsPrivacyMessage_unavailable: "Ce Moment n'est pas visible actuellement.",
    momentsOpenMomentAria: "Ouvrir {title}",
    momentsMomentFallback: "Moment Meetro",
    momentsCompletedDate: "Terminé le {date}",
    momentsCompletedProject: "Projet terminé",
    momentsReviewRating: "Avis {rating}/5",
    momentsWarrantyIncluded: "Garantie incluse",
    momentsBefore: "Avant",
    momentsAfter: "Après",
    momentDetailBack: "Retour aux Moments Meetro",
    momentDetailUnavailableTitle: "Moment Meetro indisponible",
    momentDetailUnavailableUnverified: "Cet accomplissement n'est pas encore prêt à apparaître comme Moment Meetro vérifié.",
    momentDetailUnavailableProtected: "Ce Moment Meetro est protégé jusqu'à ce que les bonnes personnes puissent le voir.",
    momentDetailUnavailableMissing: "Ce Moment Meetro est introuvable.",
    momentDetailProjectType: "Type de projet",
    momentDetailDuration: "Durée",
    momentDetailWarranty: "Garantie",
    momentDetailReceipt: "Reçu",
    momentDetailPermit: "Permis",
    momentDetailInvestment: "Investissement",
    momentDetailLocation: "Lieu du projet",
    momentDetailVerified: "Moment Meetro vérifié",
    momentDetailMainVisualAria: "Visuel principal",
    momentDetailHistoryPreserved: "Historique du projet conservé",
    momentDetailWhyItMatters: "Pourquoi ce moment compte",
    momentDetailPhotoCount: "{count} photos",
    momentDetailStory: "Histoire",
    momentDetailJourney: "Parcours du projet",
    momentDetailJourneySubtitle: "De la première conversation à la clôture",
    momentDetailJourney_consultation: "Consultation",
    momentDetailJourney_estimate_quote: "Estimation / Devis",
    momentDetailJourney_approval: "Approbation",
    momentDetailJourney_work: "Travail",
    momentDetailJourney_completed: "Terminé",
    momentDetailJourney_closed: "Clôturé",
    momentDetailRelated: "Moments associés",
    momentDetailRelationshipHistory: "Historique de la relation",
    momentDetailVerifiedWork: "Travail vérifié",
    momentDetailRelatedEmpty: "Les Moments associés apparaîtront à mesure que d'autres travaux vérifiés rejoindront cet historique.",
    momentDetailRelationshipContext: "Contexte de la relation",
    momentDetailPeopleConnected: "Personnes liées à ce travail",
    momentDetailOpenRelationshipHistory: "Ouvrir l'historique de la relation",
    momentDetailDetails: "Détails du Moment",
    momentDetailProjectProof: "Preuves du projet",
    momentDetailProofEmpty: "D'autres preuves apparaîtront lorsqu'elles seront confirmées et pourront être affichées en toute sécurité.",
    momentDetailConfirmedRating: "Note confirmée de {rating}/5",
  }),
  "pt-BR": Object.freeze({
    momentsExperienceTitle_homeowner: "Seus Momentos Meetro",
    momentsExperienceSubtitle_homeowner: "Cada projeto concluído se torna parte da história da sua casa.",
    momentsExperienceTitle_business: "Seus Momentos Meetro",
    momentsExperienceSubtitle_business: "Cada projeto concluído se torna parte do legado da sua empresa.",
    momentsExperienceTitle_employee: "Seus Momentos Meetro",
    momentsExperienceSubtitle_employee: "Cada conquista se torna parte da sua jornada profissional.",
    momentsExperienceTitle_community: "Momentos da Comunidade Meetro",
    momentsExperienceSubtitle_community: "Celebrando os projetos que fortalecem nossa comunidade.",
    momentsPrivacyLabel_published: "Publicado",
    momentsPrivacyMessage_published: "Este Momento está publicado.",
    momentsPrivacyLabel_pending: "Confirmação pendente",
    momentsPrivacyMessage_pending: "Este Momento aguarda a confirmação do cliente.",
    momentsPrivacyLabel_private: "Privado",
    momentsPrivacyMessage_private: "Este Momento está salvo de forma privada.",
    momentsPrivacyLabel_hidden: "Oculto",
    momentsPrivacyMessage_hidden: "Este Momento está oculto.",
    momentsPrivacyLabel_unavailable: "Não visível",
    momentsPrivacyMessage_unavailable: "Este Momento não está visível agora.",
    momentsOpenMomentAria: "Abrir {title}",
    momentsMomentFallback: "Momento Meetro",
    momentsCompletedDate: "Concluído em {date}",
    momentsCompletedProject: "Projeto concluído",
    momentsReviewRating: "Avaliação {rating}/5",
    momentsWarrantyIncluded: "Garantia incluída",
    momentsBefore: "Antes",
    momentsAfter: "Depois",
    momentDetailBack: "Voltar aos Momentos Meetro",
    momentDetailUnavailableTitle: "Momento Meetro indisponível",
    momentDetailUnavailableUnverified: "Esta conquista ainda não está pronta para aparecer como um Momento Meetro verificado.",
    momentDetailUnavailableProtected: "Este Momento Meetro está protegido até que as pessoas certas possam vê-lo.",
    momentDetailUnavailableMissing: "Este Momento Meetro não foi encontrado.",
    momentDetailProjectType: "Tipo de projeto",
    momentDetailDuration: "Duração",
    momentDetailWarranty: "Garantia",
    momentDetailReceipt: "Recibo",
    momentDetailPermit: "Licença",
    momentDetailInvestment: "Investimento",
    momentDetailLocation: "Local do projeto",
    momentDetailVerified: "Momento Meetro verificado",
    momentDetailMainVisualAria: "Visual principal",
    momentDetailHistoryPreserved: "Histórico do projeto preservado",
    momentDetailWhyItMatters: "Por que este momento importa",
    momentDetailPhotoCount: "{count} fotos",
    momentDetailStory: "História",
    momentDetailJourney: "Jornada do projeto",
    momentDetailJourneySubtitle: "Da primeira conversa ao encerramento",
    momentDetailJourney_consultation: "Consulta",
    momentDetailJourney_estimate_quote: "Estimativa / Orçamento",
    momentDetailJourney_approval: "Aprovação",
    momentDetailJourney_work: "Trabalho",
    momentDetailJourney_completed: "Concluído",
    momentDetailJourney_closed: "Encerrado",
    momentDetailRelated: "Momentos relacionados",
    momentDetailRelationshipHistory: "Histórico do relacionamento",
    momentDetailVerifiedWork: "Trabalho verificado",
    momentDetailRelatedEmpty: "Os Momentos relacionados aparecerão quando mais trabalhos verificados fizerem parte deste histórico.",
    momentDetailRelationshipContext: "Contexto do relacionamento",
    momentDetailPeopleConnected: "Pessoas ligadas a este trabalho",
    momentDetailOpenRelationshipHistory: "Abrir histórico do relacionamento",
    momentDetailDetails: "Detalhes do Momento",
    momentDetailProjectProof: "Comprovação do projeto",
    momentDetailProofEmpty: "Mais provas aparecerão quando forem confirmadas e puderem ser exibidas com segurança.",
    momentDetailConfirmedRating: "Avaliação confirmada de {rating}/5",
  }),
});
