export const customerQuoteLanguage = Object.freeze({
  en: Object.freeze({
    customerQuotesTitle: "Quotes",
    customerQuotesIntro: "Review the work and total provided by your professional.",
    customerQuotesLoading: "Loading Quotes...",
    customerQuotesEmpty: "No Quotes have been issued for this job yet.",
    customerQuotesUnavailable: "Quotes are temporarily unavailable.",
    customerQuoteReview: "Review Quote",
    customerQuoteCloseReview: "Back to job details",
    customerQuoteStatusWaiting: "Waiting for your decision",
    customerQuoteStatusApproved: "Approved",
    customerQuoteStatusDeclined: "Declined",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revised",
    customerQuoteLineageAdditional: "Additional",
    customerQuoteIssued: "Issued",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Work included",
    customerQuoteConditions: "Conditions",
    customerQuoteExclusions: "Not included",
    customerQuoteNoneListed: "None listed",
    customerQuoteQuantity: "Qty",
    customerQuoteApprove: "Approve Quote",
    customerQuoteDecline: "Decline Quote",
    customerQuoteApproveConfirmTitle: "Approve this Quote?",
    customerQuoteApproveConfirmBody:
      "This records your approval for this exact Quote and total.",
    customerQuoteDeclineConfirmTitle: "Decline this Quote?",
    customerQuoteDeclineConfirmBody:
      "This records your decision for this exact Quote. You can continue the conversation about next steps.",
    customerQuoteConfirmApprove: "Confirm approval",
    customerQuoteConfirmDecline: "Confirm decline",
    customerQuoteCancel: "Cancel",
    customerQuoteSaving: "Saving your decision...",
    customerQuoteApprovedSaved: "Your Quote approval was saved.",
    customerQuoteDeclinedSaved: "Your Quote decision was saved.",
    customerQuoteConflictReloaded:
      "This Quote changed before your decision was saved. The latest details are shown.",
    customerQuoteDecisionFailed:
      "Your decision could not be saved. Review the Quote and try again.",
    quoteDeliveryLoading: "Loading delivery options...",
    quoteDeliveryUnavailable: "Delivery options are temporarily unavailable.",
    quoteDeliveryTitle: "Delivery",
    quoteDeliverySending: "Sending...",
    quoteDeliverySendInMeetro: "Send in Meetro",
    quoteDeliveryShareQuote: "Share Quote",
    quoteDeliveryConversationUnavailable: "Meetro delivery is unavailable for this Conversation.",
    quoteDeliverySendFailed: "The Quote could not be sent. Try again.",
    quoteDeliverySent: "Quote sent in Meetro",
    quoteDeliveryViewConversation: "View Conversation",
    quoteDeliverySystemShare: "Share PDF",
    quoteDeliveryEmail: "Email PDF",
    quoteDeliveryCopyDetails: "Copy Quote Details",
    quoteDeliveryCopied: "Quote details copied.",
    quoteDeliveryPdfReady: "Quote PDF ready.",
    quoteDeliveryShareUnavailable: "Sharing is unavailable on this device.",
    quoteDeliveryQuote: "Quote",
    quoteDeliveryBackToConversation: "Back to Conversation",
    quoteDeliveryShareTitle: "Quote from {business}",
    quoteDeliveryShareFrom: "Quote from {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Quote: {lineage}",
    quoteDeliveryShareScope: "Work included:",
  }),
  es: Object.freeze({
    customerQuotesTitle: "Cotizaciones",
    customerQuotesIntro: "Revisa el trabajo y el total proporcionados por tu profesional.",
    customerQuotesLoading: "Cargando cotizaciones...",
    customerQuotesEmpty: "Todavía no se ha emitido una cotización para este trabajo.",
    customerQuotesUnavailable: "Las cotizaciones no están disponibles temporalmente.",
    customerQuoteReview: "Revisar cotización",
    customerQuoteCloseReview: "Volver a los detalles del trabajo",
    customerQuoteStatusWaiting: "Esperando tu decisión",
    customerQuoteStatusApproved: "Aprobada",
    customerQuoteStatusDeclined: "Rechazada",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revisada",
    customerQuoteLineageAdditional: "Adicional",
    customerQuoteIssued: "Emitida",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Trabajo incluido",
    customerQuoteConditions: "Condiciones",
    customerQuoteExclusions: "No incluido",
    customerQuoteNoneListed: "Ninguno indicado",
    customerQuoteQuantity: "Cant.",
    customerQuoteApprove: "Aprobar cotización",
    customerQuoteDecline: "Rechazar cotización",
    customerQuoteApproveConfirmTitle: "¿Aprobar esta cotización?",
    customerQuoteApproveConfirmBody:
      "Esto registra tu aprobación para esta cotización y total exactos.",
    customerQuoteDeclineConfirmTitle: "¿Rechazar esta cotización?",
    customerQuoteDeclineConfirmBody:
      "Esto registra tu decisión para esta cotización exacta. Puedes continuar la conversación sobre los próximos pasos.",
    customerQuoteConfirmApprove: "Confirmar aprobación",
    customerQuoteConfirmDecline: "Confirmar rechazo",
    customerQuoteCancel: "Cancelar",
    customerQuoteSaving: "Guardando tu decisión...",
    customerQuoteApprovedSaved: "Se guardó tu aprobación de la cotización.",
    customerQuoteDeclinedSaved: "Se guardó tu decisión sobre la cotización.",
    customerQuoteConflictReloaded:
      "Esta cotización cambió antes de guardar tu decisión. Se muestran los detalles más recientes.",
    customerQuoteDecisionFailed:
      "No se pudo guardar tu decisión. Revisa la cotización e inténtalo de nuevo.",
    quoteDeliveryLoading: "Cargando opciones de entrega...",
    quoteDeliveryUnavailable: "Las opciones de entrega no están disponibles temporalmente.",
    quoteDeliveryTitle: "Entrega",
    quoteDeliverySending: "Enviando...",
    quoteDeliverySendInMeetro: "Enviar en Meetro",
    quoteDeliveryShareQuote: "Compartir cotización",
    quoteDeliveryConversationUnavailable: "La entrega en Meetro no está disponible para esta conversación.",
    quoteDeliverySendFailed: "No se pudo enviar la cotización. Inténtalo de nuevo.",
    quoteDeliverySent: "Cotización enviada en Meetro",
    quoteDeliveryViewConversation: "Ver conversación",
    quoteDeliverySystemShare: "Compartir PDF",
    quoteDeliveryEmail: "Enviar PDF",
    quoteDeliveryCopyDetails: "Copiar detalles de la cotización",
    quoteDeliveryCopied: "Detalles de la cotización copiados.",
    quoteDeliveryPdfReady: "PDF de la cotización listo.",
    quoteDeliveryShareUnavailable: "La función de compartir no está disponible en este dispositivo.",
    quoteDeliveryQuote: "Cotización",
    quoteDeliveryBackToConversation: "Volver a la conversación",
    quoteDeliveryShareTitle: "Cotización de {business}",
    quoteDeliveryShareFrom: "Cotización de {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Cotización: {lineage}",
    quoteDeliveryShareScope: "Trabajo incluido:",
  }),
  fr: Object.freeze({
    customerQuotesTitle: "Devis",
    customerQuotesIntro: "Examinez les travaux et le total fournis par votre professionnel.",
    customerQuotesLoading: "Chargement des devis...",
    customerQuotesEmpty: "Aucun devis n'a encore été émis pour ce travail.",
    customerQuotesUnavailable: "Les devis sont temporairement indisponibles.",
    customerQuoteReview: "Examiner le devis",
    customerQuoteCloseReview: "Retour aux détails du travail",
    customerQuoteStatusWaiting: "En attente de votre décision",
    customerQuoteStatusApproved: "Approuvé",
    customerQuoteStatusDeclined: "Refusé",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Révisé",
    customerQuoteLineageAdditional: "Supplémentaire",
    customerQuoteIssued: "Émis",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Travaux inclus",
    customerQuoteConditions: "Conditions",
    customerQuoteExclusions: "Non inclus",
    customerQuoteNoneListed: "Aucun élément indiqué",
    customerQuoteQuantity: "Qté",
    customerQuoteApprove: "Approuver le devis",
    customerQuoteDecline: "Refuser le devis",
    customerQuoteApproveConfirmTitle: "Approuver ce devis ?",
    customerQuoteApproveConfirmBody:
      "Ceci enregistre votre approbation pour ce devis et ce total précis.",
    customerQuoteDeclineConfirmTitle: "Refuser ce devis ?",
    customerQuoteDeclineConfirmBody:
      "Ceci enregistre votre décision pour ce devis précis. Vous pouvez poursuivre la conversation sur les prochaines étapes.",
    customerQuoteConfirmApprove: "Confirmer l'approbation",
    customerQuoteConfirmDecline: "Confirmer le refus",
    customerQuoteCancel: "Annuler",
    customerQuoteSaving: "Enregistrement de votre décision...",
    customerQuoteApprovedSaved: "Votre approbation du devis a été enregistrée.",
    customerQuoteDeclinedSaved: "Votre décision sur le devis a été enregistrée.",
    customerQuoteConflictReloaded:
      "Ce devis a changé avant l'enregistrement de votre décision. Les derniers détails sont affichés.",
    customerQuoteDecisionFailed:
      "Votre décision n'a pas pu être enregistrée. Examinez le devis et réessayez.",
    quoteDeliveryLoading: "Chargement des options d’envoi...",
    quoteDeliveryUnavailable: "Les options d’envoi sont temporairement indisponibles.",
    quoteDeliveryTitle: "Envoi",
    quoteDeliverySending: "Envoi en cours...",
    quoteDeliverySendInMeetro: "Envoyer dans Meetro",
    quoteDeliveryShareQuote: "Partager le devis",
    quoteDeliveryConversationUnavailable: "L’envoi dans Meetro n’est pas disponible pour cette conversation.",
    quoteDeliverySendFailed: "Le devis n’a pas pu être envoyé. Réessayez.",
    quoteDeliverySent: "Devis envoyé dans Meetro",
    quoteDeliveryViewConversation: "Voir la conversation",
    quoteDeliverySystemShare: "Partager le PDF",
    quoteDeliveryEmail: "Envoyer le PDF",
    quoteDeliveryCopyDetails: "Copier les détails du devis",
    quoteDeliveryCopied: "Détails du devis copiés.",
    quoteDeliveryPdfReady: "PDF du devis prêt.",
    quoteDeliveryShareUnavailable: "Le partage n’est pas disponible sur cet appareil.",
    quoteDeliveryQuote: "Devis",
    quoteDeliveryBackToConversation: "Retour à la conversation",
    quoteDeliveryShareTitle: "Devis de {business}",
    quoteDeliveryShareFrom: "Devis de {business}",
    quoteDeliveryShareTotal: "Total : {total}",
    quoteDeliveryShareLineage: "Devis : {lineage}",
    quoteDeliveryShareScope: "Travaux inclus :",
  }),
  "pt-BR": Object.freeze({
    customerQuotesTitle: "Orçamentos",
    customerQuotesIntro: "Revise o trabalho e o total fornecidos pelo profissional.",
    customerQuotesLoading: "Carregando orçamentos...",
    customerQuotesEmpty: "Nenhum orçamento foi emitido para este trabalho ainda.",
    customerQuotesUnavailable: "Os orçamentos estão temporariamente indisponíveis.",
    customerQuoteReview: "Revisar orçamento",
    customerQuoteCloseReview: "Voltar aos detalhes do trabalho",
    customerQuoteStatusWaiting: "Aguardando sua decisão",
    customerQuoteStatusApproved: "Aprovado",
    customerQuoteStatusDeclined: "Recusado",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revisado",
    customerQuoteLineageAdditional: "Adicional",
    customerQuoteIssued: "Emitido",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Trabalho incluido",
    customerQuoteConditions: "Condições",
    customerQuoteExclusions: "Não incluído",
    customerQuoteNoneListed: "Nenhum item informado",
    customerQuoteQuantity: "Qtd.",
    customerQuoteApprove: "Aprovar orçamento",
    customerQuoteDecline: "Recusar orçamento",
    customerQuoteApproveConfirmTitle: "Aprovar este orçamento?",
    customerQuoteApproveConfirmBody:
      "Isso registra sua aprovação para este orçamento e total exatos.",
    customerQuoteDeclineConfirmTitle: "Recusar este orçamento?",
    customerQuoteDeclineConfirmBody:
      "Isso registra sua decisão para este orçamento exato. Você pode continuar a conversa sobre os próximos passos.",
    customerQuoteConfirmApprove: "Confirmar aprovação",
    customerQuoteConfirmDecline: "Confirmar recusa",
    customerQuoteCancel: "Cancelar",
    customerQuoteSaving: "Salvando sua decisão...",
    customerQuoteApprovedSaved: "Sua aprovação do orçamento foi salva.",
    customerQuoteDeclinedSaved: "Sua decisão sobre o orçamento foi salva.",
    customerQuoteConflictReloaded:
      "Este orçamento mudou antes de sua decisão ser salva. Os detalhes mais recentes estão sendo exibidos.",
    customerQuoteDecisionFailed:
      "Não foi possível salvar sua decisão. Revise o orçamento e tente novamente.",
    quoteDeliveryLoading: "Carregando opções de envio...",
    quoteDeliveryUnavailable: "As opções de envio estão temporariamente indisponíveis.",
    quoteDeliveryTitle: "Envio",
    quoteDeliverySending: "Enviando...",
    quoteDeliverySendInMeetro: "Enviar no Meetro",
    quoteDeliveryShareQuote: "Compartilhar orçamento",
    quoteDeliveryConversationUnavailable: "O envio pelo Meetro não está disponível para esta conversa.",
    quoteDeliverySendFailed: "Não foi possível enviar o orçamento. Tente novamente.",
    quoteDeliverySent: "Orçamento enviado no Meetro",
    quoteDeliveryViewConversation: "Ver conversa",
    quoteDeliverySystemShare: "Compartilhar PDF",
    quoteDeliveryEmail: "Enviar PDF",
    quoteDeliveryCopyDetails: "Copiar detalhes do orçamento",
    quoteDeliveryCopied: "Detalhes do orçamento copiados.",
    quoteDeliveryPdfReady: "PDF do orçamento pronto.",
    quoteDeliveryShareUnavailable: "O compartilhamento não está disponível neste dispositivo.",
    quoteDeliveryQuote: "Orçamento",
    quoteDeliveryBackToConversation: "Voltar para a conversa",
    quoteDeliveryShareTitle: "Orçamento de {business}",
    quoteDeliveryShareFrom: "Orçamento de {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Orçamento: {lineage}",
    quoteDeliveryShareScope: "Trabalho incluído:",
  }),
});
