export const CUSTOMER_RELATIONSHIPS_LANGUAGES = Object.freeze([
  "en",
  "es",
  "fr",
  "pt-BR",
]);

const copy = Object.freeze({
  en: Object.freeze({
    title: "Customer History",
    description: "Jobs, Quotes, Invoices, documents, photos, and important records for one customer.",
    category: "Business Operations",
    loading: "Loading Customer History...",
    loadErrorTitle: "Customer History could not be loaded",
    loadErrorText: "Try again to load the saved Customer History for your business.",
    retry: "Try Again",
    emptyTitle: "No Customer History yet",
    emptyText: "Customer History appears after you explicitly use a saved Contact as a customer. Viewing this page creates nothing.",
    relationshipList: "Customers",
    openRelationship: "Open Customer History",
    relationshipEstablished: "Customer History started",
    customerSince: "Customer since",
    relationshipActivity: "Customer History",
    overview: "Overview",
    work: "Jobs",
    quotes: "Quotes",
    invoices: "Invoices",
    documentsPhotos: "Documents / Photos",
    loadingActivity: "Loading Customer History...",
    activityErrorTitle: "Activity could not be loaded",
    activityErrorText: "The saved Customer History is still available. Try loading it again.",
    noWork: "No Jobs in this Customer History yet.",
    noQuotes: "No linked Quote activity yet.",
    noInvoices: "No linked invoices yet.",
    noDocumentsPhotos: "No linked documents or photos yet.",
    linkedWork: "Linked Job",
    documentsLabel: "Documents",
    photosLabel: "Photos",
    canonicalQuote: "Canonical Quote",
    canonicalInvoice: "Canonical Invoice",
    requestPhoto: "Request photo",
    provenance: "Source",
    openPhoto: "Open photo",
    completed: "Completed",
    created: "Created",
    issued: "Issued",
    latest: "Latest",
    total: "Total",
    paid: "Paid",
    balance: "Balance",
    decision: "Customer decision",
    quote: "Quote",
    invoice: "Invoice",
    job: "Job",
    activeJobs: "Active Jobs",
    completedJobs: "Completed Jobs",
    openJob: "Open Job",
    nextStep: "Next step",
    historySummary: "History summary",
    photos: "Photos",
    paymentHistory: "Payment history",
    deposits: "Deposits",
    required: "Required",
    applied: "Applied",
    received: "Received",
    deposit: "Deposit",
    depositReceived: "Deposit received",
    invoicePaymentReceived: "Invoice payment received",
    visits: "Visits / Schedule",
    workPerformed: "Work performed",
    scheduled: "Scheduled",
    established: "Established",
    currentContact: "Current Contact Information",
    contactName: "Contact",
    company: "Organization",
    partyType: "Contact type",
    person: "Person",
    organization: "Organization",
    status: "Contact status",
    active: "Active",
    archived: "Archived",
    email: "Email",
    phone: "Phone",
    address: "Address",
    serviceArea: "Service area",
    notAdded: "Not added",
    backToRelationships: "Back to Customers",
    backToBusinessTools: "Back to Business Tools",
    viewContact: "View Contact in Communication Center",
    noRelationshipTitle: "No Customer History yet",
    noRelationshipText: "Customer History has not started for this Contact yet.",
    noRelationshipHelp: "Viewing this Contact does not start Customer History. It starts only when the Contact is explicitly used as a customer.",
    externalContact: "A Meetro account is not required for this Contact.",
    readOnly: "This workspace reads saved Customer History and Contact information. It does not create or change either record.",
  }),
  es: Object.freeze({
    title: "Historial del cliente",
    description: "Trabajos, cotizaciones, facturas, documentos, fotos y registros importantes de un cliente.",
    category: "Operaciones del negocio",
    loading: "Cargando historial del cliente...",
    loadErrorTitle: "No se pudo cargar el historial del cliente",
    loadErrorText: "Intenta de nuevo para cargar el historial del cliente guardado de tu negocio.",
    retry: "Intentar de nuevo",
    emptyTitle: "Aún no hay historial del cliente",
    emptyText: "El historial del cliente aparece después de usar explícitamente un Contacto guardado como cliente. Ver esta página no crea nada.",
    relationshipList: "Clientes",
    openRelationship: "Abrir historial del cliente",
    relationshipEstablished: "Historial del cliente iniciado",
    customerSince: "Cliente desde",
    relationshipActivity: "Historial del cliente",
    overview: "Resumen",
    work: "Trabajos",
    quotes: "Cotizaciones",
    invoices: "Facturas",
    documentsPhotos: "Documentos / Fotos",
    loadingActivity: "Cargando historial del cliente...",
    activityErrorTitle: "No se pudo cargar la actividad",
    activityErrorText: "El historial del cliente guardado sigue disponible. Intenta cargarlo de nuevo.",
    noWork: "Aún no hay trabajos en este historial del cliente.",
    noQuotes: "Aún no hay actividad de cotizaciones vinculada.",
    noInvoices: "Aún no hay facturas vinculadas.",
    noDocumentsPhotos: "Aún no hay documentos ni fotos vinculados.",
    linkedWork: "Trabajo vinculado",
    documentsLabel: "Documentos",
    photosLabel: "Fotos",
    canonicalQuote: "Cotización canónica",
    canonicalInvoice: "Factura canónica",
    requestPhoto: "Foto de la solicitud",
    provenance: "Origen",
    openPhoto: "Abrir foto",
    completed: "Completado",
    created: "Creado",
    issued: "Emitido",
    latest: "Más reciente",
    total: "Total",
    paid: "Pagado",
    balance: "Saldo",
    decision: "Decisión del cliente",
    quote: "Cotización",
    invoice: "Factura",
    job: "Trabajo",
    activeJobs: "Trabajos activos",
    completedJobs: "Trabajos completados",
    openJob: "Abrir trabajo",
    nextStep: "Próximo paso",
    historySummary: "Resumen del historial",
    photos: "Fotos",
    paymentHistory: "Historial de pagos",
    deposits: "Depósitos",
    required: "Requerido",
    applied: "Aplicado",
    received: "Recibido",
    deposit: "Depósito",
    depositReceived: "Depósito recibido",
    invoicePaymentReceived: "Pago de factura recibido",
    visits: "Visitas / Agenda",
    workPerformed: "Trabajo realizado",
    scheduled: "Programado",
    established: "Establecida",
    currentContact: "Información actual del Contacto",
    contactName: "Contacto",
    company: "Organización",
    partyType: "Tipo de Contacto",
    person: "Persona",
    organization: "Organización",
    status: "Estado del Contacto",
    active: "Activo",
    archived: "Archivado",
    email: "Correo electrónico",
    phone: "Teléfono",
    address: "Dirección",
    serviceArea: "Área de servicio",
    notAdded: "No agregado",
    backToRelationships: "Volver a Clientes",
    backToBusinessTools: "Volver a Herramientas del negocio",
    viewContact: "Ver Contacto en el Centro de comunicación",
    noRelationshipTitle: "Aún no hay historial del cliente",
    noRelationshipText: "El historial del cliente aún no ha comenzado para este Contacto.",
    noRelationshipHelp: "Ver este Contacto no inicia el historial. Solo comienza cuando el Contacto se usa explícitamente como cliente.",
    externalContact: "Este Contacto no necesita una cuenta de Meetro.",
    readOnly: "Este espacio lee el historial del cliente y la información guardada del Contacto. No crea ni cambia ninguno de los registros.",
  }),
  fr: Object.freeze({
    title: "Historique client",
    description: "Travaux, devis, factures, documents, photos et dossiers importants pour un client.",
    category: "Opérations de l'entreprise",
    loading: "Chargement de l’historique client...",
    loadErrorTitle: "Impossible de charger l’historique client",
    loadErrorText: "Réessayez pour charger l’historique client enregistré de votre entreprise.",
    retry: "Réessayer",
    emptyTitle: "Aucun historique client pour le moment",
    emptyText: "L’historique client apparaît après l’utilisation explicite d’un Contact enregistré comme client. Consulter cette page ne crée rien.",
    relationshipList: "Clients",
    openRelationship: "Ouvrir l'historique client",
    relationshipEstablished: "Historique client commencé",
    customerSince: "Client depuis",
    relationshipActivity: "Historique client",
    overview: "Vue d’ensemble",
    work: "Travaux",
    quotes: "Devis",
    invoices: "Factures",
    documentsPhotos: "Documents / Photos",
    loadingActivity: "Chargement de l’historique client...",
    activityErrorTitle: "Impossible de charger l’activité",
    activityErrorText: "L’historique client enregistré reste disponible. Réessayez de le charger.",
    noWork: "Aucun travail dans cet historique client pour le moment.",
    noQuotes: "Aucune activité de devis liée pour le moment.",
    noInvoices: "Aucune facture liée pour le moment.",
    noDocumentsPhotos: "Aucun document ni aucune photo liés pour le moment.",
    linkedWork: "Travail lié",
    documentsLabel: "Documents",
    photosLabel: "Photos",
    canonicalQuote: "Devis canonique",
    canonicalInvoice: "Facture canonique",
    requestPhoto: "Photo de la demande",
    provenance: "Source",
    openPhoto: "Ouvrir la photo",
    completed: "Terminé",
    created: "Créé",
    issued: "Émis",
    latest: "Dernière activité",
    total: "Total",
    paid: "Payé",
    balance: "Solde",
    decision: "Décision du client",
    quote: "Devis",
    invoice: "Facture",
    job: "Travail",
    activeJobs: "Travaux en cours",
    completedJobs: "Travaux terminés",
    openJob: "Ouvrir le travail",
    nextStep: "Prochaine étape",
    historySummary: "Résumé de l'historique",
    photos: "Photos",
    paymentHistory: "Historique des paiements",
    deposits: "Acomptes",
    required: "Requis",
    applied: "Appliqué",
    received: "Reçu",
    deposit: "Acompte",
    depositReceived: "Acompte reçu",
    invoicePaymentReceived: "Paiement de facture reçu",
    visits: "Visites / Calendrier",
    workPerformed: "Travail effectué",
    scheduled: "Planifié",
    established: "Établie",
    currentContact: "Coordonnées actuelles du Contact",
    contactName: "Contact",
    company: "Organisation",
    partyType: "Type de Contact",
    person: "Personne",
    organization: "Organisation",
    status: "Statut du Contact",
    active: "Actif",
    archived: "Archivé",
    email: "E-mail",
    phone: "Téléphone",
    address: "Adresse",
    serviceArea: "Zone de service",
    notAdded: "Non renseigné",
    backToRelationships: "Retour aux Clients",
    backToBusinessTools: "Retour aux outils de l'entreprise",
    viewContact: "Voir le Contact dans le Centre de communication",
    noRelationshipTitle: "Aucun historique client pour le moment",
    noRelationshipText: "L’historique client n’a pas encore commencé pour ce Contact.",
    noRelationshipHelp: "Consulter ce Contact ne démarre pas l’historique. Il commence uniquement lorsque le Contact est explicitement utilisé comme client.",
    externalContact: "Ce Contact n'a pas besoin d'un compte Meetro.",
    readOnly: "Cet espace consulte l’historique client et les coordonnées enregistrées. Il ne crée ni ne modifie aucun des deux enregistrements.",
  }),
  "pt-BR": Object.freeze({
    title: "Histórico do cliente",
    description: "Trabalhos, orçamentos, faturas, documentos, fotos e registros importantes de um cliente.",
    category: "Operações do negócio",
    loading: "Carregando histórico do cliente...",
    loadErrorTitle: "Não foi possível carregar o histórico do cliente",
    loadErrorText: "Tente novamente para carregar o histórico do cliente salvo da sua empresa.",
    retry: "Tentar novamente",
    emptyTitle: "Ainda não há histórico do cliente",
    emptyText: "O histórico do cliente aparece depois que você usa explicitamente um Contato salvo como cliente. Visualizar esta página não cria nada.",
    relationshipList: "Clientes",
    openRelationship: "Abrir histórico do cliente",
    relationshipEstablished: "Histórico do cliente iniciado",
    customerSince: "Cliente desde",
    relationshipActivity: "Histórico do cliente",
    overview: "Visão geral",
    work: "Trabalhos",
    quotes: "Orçamentos",
    invoices: "Faturas",
    documentsPhotos: "Documentos / Fotos",
    loadingActivity: "Carregando histórico do cliente...",
    activityErrorTitle: "Não foi possível carregar a atividade",
    activityErrorText: "O histórico do cliente salvo continua disponível. Tente carregá-lo novamente.",
    noWork: "Ainda não há trabalhos neste histórico do cliente.",
    noQuotes: "Ainda não há atividade de orçamentos vinculada.",
    noInvoices: "Ainda não há faturas vinculadas.",
    noDocumentsPhotos: "Ainda não há documentos ou fotos vinculados.",
    linkedWork: "Trabalho vinculado",
    documentsLabel: "Documentos",
    photosLabel: "Fotos",
    canonicalQuote: "Orçamento canônico",
    canonicalInvoice: "Fatura canônica",
    requestPhoto: "Foto da solicitação",
    provenance: "Origem",
    openPhoto: "Abrir foto",
    completed: "Concluído",
    created: "Criado",
    issued: "Emitido",
    latest: "Mais recente",
    total: "Total",
    paid: "Pago",
    balance: "Saldo",
    decision: "Decisão do cliente",
    quote: "Orçamento",
    invoice: "Fatura",
    job: "Trabalho",
    activeJobs: "Trabalhos ativos",
    completedJobs: "Trabalhos concluídos",
    openJob: "Abrir trabalho",
    nextStep: "Próximo passo",
    historySummary: "Resumo do histórico",
    photos: "Fotos",
    paymentHistory: "Histórico de pagamentos",
    deposits: "Depósitos",
    required: "Obrigatório",
    applied: "Aplicado",
    received: "Recebido",
    deposit: "Depósito",
    depositReceived: "Depósito recebido",
    invoicePaymentReceived: "Pagamento de fatura recebido",
    visits: "Visitas / Agenda",
    workPerformed: "Trabalho realizado",
    scheduled: "Agendado",
    established: "Estabelecido",
    currentContact: "Informações atuais do Contato",
    contactName: "Contato",
    company: "Organização",
    partyType: "Tipo de Contato",
    person: "Pessoa",
    organization: "Organização",
    status: "Status do Contato",
    active: "Ativo",
    archived: "Arquivado",
    email: "E-mail",
    phone: "Telefone",
    address: "Endereço",
    serviceArea: "Área de atendimento",
    notAdded: "Não adicionado",
    backToRelationships: "Voltar para Clientes",
    backToBusinessTools: "Voltar para Ferramentas do negócio",
    viewContact: "Ver Contato na Central de comunicação",
    noRelationshipTitle: "Ainda não há histórico do cliente",
    noRelationshipText: "O histórico do cliente ainda não começou para este Contato.",
    noRelationshipHelp: "Visualizar este Contato não inicia o histórico. Ele começa somente quando o Contato é usado explicitamente como cliente.",
    externalContact: "Este Contato não precisa de uma conta Meetro.",
    readOnly: "Este espaço consulta o histórico do cliente e as informações salvas do Contato. Ele não cria nem altera nenhum dos registros.",
  }),
});

export function getCustomerRelationshipsCopy(language = "en") {
  return copy[language] || copy.en;
}
