export const CUSTOMER_RELATIONSHIPS_LANGUAGES = Object.freeze([
  "en",
  "es",
  "fr",
  "pt-BR",
]);

const copy = Object.freeze({
  en: Object.freeze({
    issuedStatus: "Issued",
    approvedStatus: "Approved",
    declinedStatus: "Declined",
    sentStatus: "Sent",
    partiallyPaidStatus: "Partially paid",
    paidStatus: "Paid",
    customerReportReadOnly: "This read-only report contains customer-visible canonical history. It does not change Jobs or business records.",

    professionalHistoryReport: "Professional Customer History Report",
    customerReportError: "Customer History report could not be prepared. Try again.",
    nativeNewJobUnavailable: "New work for a Meetro account customer cannot be started from History.",
    messageCustomer: "Message Customer",
    nativeMessageUnavailable: "No single eligible conversation is available. Open the exact Job to review its communication.",

    originalQuote: "Original", revisedQuote: "Revised", additionalQuote: "Additional",
    title: "Customer History",
    description: "Jobs, Quotes, Invoices, documents, photos, and important records for one customer.",
    category: "Business Operations",
    loading: "Loading Customer History...",
    loadErrorTitle: "Customer History could not be loaded",
    loadErrorText: "Try again to load the saved Customer History for your business.",
    retry: "Try Again",
    emptyTitle: "No Customer History yet",
    emptyText: "Customer History appears after you explicitly use a saved Contact as a customer. Viewing this page creates nothing.",
    relationshipList: "Customers",
    openRelationship: "Open Customer History",
    relationshipEstablished: "Customer History started",
    customerSince: "Customer since",
    relationshipActivity: "Customer History",
    completedWorkDirectory: "All completed work for this business",
    privateContacts: "Private Contacts",
    noPrivateContacts: "No private Contacts are linked to Customer History yet.",
    meetroCustomers: "Meetro Customers",
    nativeSourceLabel: "Meetro customer",
    nativeHistory: "Customer History",
    nativeJobDetail: "Completed Job detail",
    backToNativeHistory: "Back to customer history",
    openNativeCustomer: "Open Meetro customer history",
    openNativeJob: "Open completed Job",
    noNativeCustomers: "No Meetro customers are available for this business yet.",
    noNativeCompletedWork: "No completed work yet.",
    nativeHistoryUnavailable: "Customer history is unavailable. Try again.",
    loadMoreNative: "Load more",
    emergencySource: "Emergency",
    ordinarySource: "Standard Job",
    approvedQuote: "Approved Quote",
    completedWork: "Completed workstreams",
    overview: "Overview",
    work: "Jobs",
    quotes: "Quotes",
    invoices: "Invoices",
    documentsPhotos: "Documents / Photos",
    loadingActivity: "Loading Customer History...",
    activityErrorTitle: "Activity could not be loaded",
    activityErrorText: "The saved Customer History is still available. Try loading it again.",
    noWork: "No Jobs in this Customer History yet.",
    noQuotes: "No linked Quote activity yet.",
    noInvoices: "No linked invoices yet.",
    noDocumentsPhotos: "No linked documents or photos yet.",
    linkedWork: "Linked Job",
    documentsLabel: "Documents",
    photosLabel: "Photos",
    canonicalQuote: "Meetro Quote",
    canonicalInvoice: "Meetro Invoice",
    requestPhoto: "Request photo",
    provenance: "Source",
    openPhoto: "Open photo",
    completed: "Completed",
    created: "Created",
    issued: "Issued",
    latest: "Latest",
    total: "Total",
    paid: "Paid",
    balance: "Balance",
    decision: "Customer decision",
    quote: "Quote",
    invoice: "Invoice",
    job: "Job",
    activeJobs: "Active Jobs",
    completedJobs: "Completed Jobs",
    openJob: "Open Job",
    nextStep: "Next step",
    historySummary: "History summary",
    photos: "Photos",
    paymentHistory: "Payment history",
    deposits: "Deposits",
    required: "Required",
    applied: "Applied",
    received: "Received",
    deposit: "Deposit",
    depositReceived: "Deposit received",
    invoicePaymentReceived: "Invoice payment received",
    visits: "Visits / Schedule",
    workPerformed: "Work performed",
    scheduled: "Scheduled",
    established: "Established",
    currentContact: "Current Contact Information",
    contactName: "Contact",
    company: "Organization",
    partyType: "Contact type",
    person: "Person",
    organization: "Organization",
    status: "Contact status",
    jobStatus: "Job status",
    active: "Active",
    archived: "Archived",
    email: "Email",
    phone: "Phone",
    address: "Address",
    serviceArea: "Service area",
    notAdded: "Not added",
    backToRelationships: "Back to Customers",
    backToBusinessTools: "Back to Business Tools",
    viewContact: "View Contact in Communication Center",
    startNewJob: "Start New Job",
    newJobHeading: "Start a new Job",
    newJobIntro: "Create fresh work for this customer. Previous Job details, Quotes, payments, and schedule do not carry forward.",
    newJobTitle: "Job title",
    newJobTitlePlaceholder: "What work is this Job for?",
    newJobDescription: "Details",
    newJobDescriptionPlaceholder: "Add the new work details",
    newJobLocation: "Service location",
    newJobLocationPlaceholder: "Optional — add the location for this Job",
    newJobLocationHelp: "Leave this blank if the service location will be added later.",
    createJob: "Create Job",
    cancelNewJob: "Cancel",
    creatingJob: "Creating Job...",
    newJobErrorTitle: "The new Job could not be created",
    newJobErrorText: "Review the new Job details and try again.",
    archivedNewJobUnavailable: "Archived customers remain available for history, but new work cannot be started until the Contact is active.",
    noRelationshipTitle: "No Customer History yet",
    noRelationshipText: "Customer History has not started for this Contact yet.",
    noRelationshipHelp: "Viewing this Contact does not start Customer History. It starts only when the Contact is explicitly used as a customer.",
    externalContact: "A Meetro account is not required for this Contact.",
    readOnly: "Customer History and Contact information remain read-only here. Starting a new Job creates a separate Job without changing prior history.",
  }),
  es: Object.freeze({
    issuedStatus: "Emitido",
    approvedStatus: "Aprobado",
    declinedStatus: "Rechazado",
    sentStatus: "Enviado",
    partiallyPaidStatus: "Pagado parcialmente",
    paidStatus: "Pagado",
    customerReportReadOnly: "Este informe de solo lectura contiene el historial canónico visible para el cliente. No modifica trabajos ni registros comerciales.",

    professionalHistoryReport: "Informe del historial de clientes profesionales",
    customerReportError: "No se pudo preparar el informe del historial del cliente. Inténtalo de nuevo.",
    nativeNewJobUnavailable: "No se puede iniciar trabajo nuevo para un cliente con cuenta de Meetro desde el Historial.",
    messageCustomer: "Enviar mensaje al cliente",
    nativeMessageUnavailable: "No hay una única conversación elegible. Abre el trabajo exacto para revisar su comunicación.",

    originalQuote: "Original", revisedQuote: "Revisado", additionalQuote: "Adicional",
    title: "Historial del cliente",
    description: "Trabajos, cotizaciones, facturas, documentos, fotos y registros importantes de un cliente.",
    category: "Operaciones del negocio",
    loading: "Cargando historial del cliente...",
    loadErrorTitle: "No se pudo cargar el historial del cliente",
    loadErrorText: "Intenta de nuevo para cargar el historial del cliente guardado de tu negocio.",
    retry: "Intentar de nuevo",
    emptyTitle: "Aún no hay historial del cliente",
    emptyText: "El historial del cliente aparece después de usar explícitamente un Contacto guardado como cliente. Ver esta página no crea nada.",
    relationshipList: "Clientes",
    openRelationship: "Abrir historial del cliente",
    relationshipEstablished: "Historial del cliente iniciado",
    customerSince: "Cliente desde",
    relationshipActivity: "Historial del cliente",
    completedWorkDirectory: "Todos los trabajos completados de este negocio",
    privateContacts: "Contactos privados",
    noPrivateContacts: "Aún no hay Contactos privados vinculados al historial del cliente.",
    meetroCustomers: "Clientes de Meetro",
    nativeSourceLabel: "Cliente de Meetro",
    nativeHistory: "Historial del cliente",
    nativeJobDetail: "Detalle del trabajo completado",
    backToNativeHistory: "Volver al historial del cliente",
    openNativeCustomer: "Abrir historial del cliente de Meetro",
    openNativeJob: "Abrir trabajo completado",
    noNativeCustomers: "Aún no hay clientes de Meetro disponibles para este negocio.",
    noNativeCompletedWork: "Aún no hay trabajo completado.",
    nativeHistoryUnavailable: "El historial del cliente no está disponible. Inténtalo de nuevo.",
    loadMoreNative: "Cargar más",
    emergencySource: "Emergencia",
    ordinarySource: "Trabajo estándar",
    approvedQuote: "Cotización aprobada",
    completedWork: "Trabajos completados",
    overview: "Resumen",
    work: "Trabajos",
    quotes: "Cotizaciones",
    invoices: "Facturas",
    documentsPhotos: "Documentos / Fotos",
    loadingActivity: "Cargando historial del cliente...",
    activityErrorTitle: "No se pudo cargar la actividad",
    activityErrorText: "El historial del cliente guardado sigue disponible. Intenta cargarlo de nuevo.",
    noWork: "Aún no hay trabajos en este historial del cliente.",
    noQuotes: "Aún no hay actividad de cotizaciones vinculada.",
    noInvoices: "Aún no hay facturas vinculadas.",
    noDocumentsPhotos: "Aún no hay documentos ni fotos vinculados.",
    linkedWork: "Trabajo vinculado",
    documentsLabel: "Documentos",
    photosLabel: "Fotos",
    canonicalQuote: "Cotización de Meetro",
    canonicalInvoice: "Factura de Meetro",
    requestPhoto: "Foto de la solicitud",
    provenance: "Origen",
    openPhoto: "Abrir foto",
    completed: "Completado",
    created: "Creado",
    issued: "Emitido",
    latest: "Más reciente",
    total: "Total",
    paid: "Pagado",
    balance: "Saldo",
    decision: "Decisión del cliente",
    quote: "Cotización",
    invoice: "Factura",
    job: "Trabajo",
    activeJobs: "Trabajos activos",
    completedJobs: "Trabajos completados",
    openJob: "Abrir trabajo",
    nextStep: "Próximo paso",
    historySummary: "Resumen del historial",
    photos: "Fotos",
    paymentHistory: "Historial de pagos",
    deposits: "Depósitos",
    required: "Requerido",
    applied: "Aplicado",
    received: "Recibido",
    deposit: "Depósito",
    depositReceived: "Depósito recibido",
    invoicePaymentReceived: "Pago de factura recibido",
    visits: "Visitas / Agenda",
    workPerformed: "Trabajo realizado",
    scheduled: "Programado",
    established: "Establecida",
    currentContact: "Información actual del Contacto",
    contactName: "Contacto",
    company: "Organización",
    partyType: "Tipo de Contacto",
    person: "Persona",
    organization: "Organización",
    status: "Estado del Contacto",
    jobStatus: "Estado del trabajo",
    active: "Activo",
    archived: "Archivado",
    email: "Correo electrónico",
    phone: "Teléfono",
    address: "Dirección",
    serviceArea: "Área de servicio",
    notAdded: "No agregado",
    backToRelationships: "Volver a Clientes",
    backToBusinessTools: "Volver a Herramientas del negocio",
    viewContact: "Ver Contacto en el Centro de comunicación",
    startNewJob: "Iniciar nuevo trabajo",
    newJobHeading: "Iniciar un nuevo trabajo",
    newJobIntro: "Crea un trabajo nuevo para este cliente. Los detalles, cotizaciones, pagos y agenda anteriores no se transfieren.",
    newJobTitle: "Título del trabajo",
    newJobTitlePlaceholder: "¿Para qué trabajo es este nuevo trabajo?",
    newJobDescription: "Detalles",
    newJobDescriptionPlaceholder: "Agrega los detalles del trabajo nuevo",
    newJobLocation: "Ubicación del servicio",
    newJobLocationPlaceholder: "Opcional — agrega la ubicación de este trabajo",
    newJobLocationHelp: "Déjalo en blanco si la ubicación del servicio se agregará después.",
    createJob: "Crear trabajo",
    cancelNewJob: "Cancelar",
    creatingJob: "Creando trabajo...",
    newJobErrorTitle: "No se pudo crear el nuevo trabajo",
    newJobErrorText: "Revisa los detalles del nuevo trabajo e inténtalo de nuevo.",
    archivedNewJobUnavailable: "Los clientes archivados siguen disponibles para consultar el historial, pero no se puede iniciar trabajo nuevo hasta que el Contacto esté activo.",
    noRelationshipTitle: "Aún no hay historial del cliente",
    noRelationshipText: "El historial del cliente aún no ha comenzado para este Contacto.",
    noRelationshipHelp: "Ver este Contacto no inicia el historial. Solo comienza cuando el Contacto se usa explícitamente como cliente.",
    externalContact: "Este Contacto no necesita una cuenta de Meetro.",
    readOnly: "El historial del cliente y la información del Contacto permanecen de solo lectura aquí. Iniciar un nuevo trabajo crea un trabajo separado sin cambiar el historial anterior.",
  }),
  fr: Object.freeze({
    issuedStatus: "Émis",
    approvedStatus: "Approuvé",
    declinedStatus: "Refusé",
    sentStatus: "Envoyé",
    partiallyPaidStatus: "Partiellement payé",
    paidStatus: "Payé",
    customerReportReadOnly: "Ce rapport en lecture seule contient l’historique canonique visible par le client. Il ne modifie aucun travail ni document professionnel.",

    professionalHistoryReport: "Rapport professionnel de l’historique client",
    customerReportError: "Impossible de préparer le rapport de l’historique client. Réessayez.",
    nativeNewJobUnavailable: "L’historique ne permet pas de commencer de nouveaux travaux pour un client avec un compte Meetro.",
    messageCustomer: "Envoyer un message au client",
    nativeMessageUnavailable: "Aucune conversation admissible unique n’est disponible. Ouvrez le travail concerné pour consulter ses échanges.",

    originalQuote: "D’origine", revisedQuote: "Révisé", additionalQuote: "Supplémentaire",
    title: "Historique client",
    description: "Travaux, devis, factures, documents, photos et dossiers importants pour un client.",
    category: "Opérations de l'entreprise",
    loading: "Chargement de l’historique client...",
    loadErrorTitle: "Impossible de charger l’historique client",
    loadErrorText: "Réessayez pour charger l’historique client enregistré de votre entreprise.",
    retry: "Réessayer",
    emptyTitle: "Aucun historique client pour le moment",
    emptyText: "L’historique client apparaît après l’utilisation explicite d’un Contact enregistré comme client. Consulter cette page ne crée rien.",
    relationshipList: "Clients",
    openRelationship: "Ouvrir l'historique client",
    relationshipEstablished: "Historique client commencé",
    customerSince: "Client depuis",
    relationshipActivity: "Historique client",
    completedWorkDirectory: "Toutes les interventions terminées de cette entreprise",
    privateContacts: "Contacts privés",
    noPrivateContacts: "Aucun Contact privé n'est encore lié à l'historique client.",
    meetroCustomers: "Clients Meetro",
    nativeSourceLabel: "Client Meetro",
    nativeHistory: "Historique client",
    nativeJobDetail: "Détail du travail terminé",
    backToNativeHistory: "Retour à l'historique du client",
    openNativeCustomer: "Ouvrir l'historique du client Meetro",
    openNativeJob: "Ouvrir le travail terminé",
    noNativeCustomers: "Aucun client Meetro disponible pour cette entreprise pour le moment.",
    noNativeCompletedWork: "Aucun travail terminé pour le moment.",
    nativeHistoryUnavailable: "L'historique du client est indisponible. Réessayez.",
    loadMoreNative: "Charger plus",
    emergencySource: "Urgence",
    ordinarySource: "Travail standard",
    approvedQuote: "Devis approuvé",
    completedWork: "Travaux terminés",
    overview: "Vue d’ensemble",
    work: "Travaux",
    quotes: "Devis",
    invoices: "Factures",
    documentsPhotos: "Documents / Photos",
    loadingActivity: "Chargement de l’historique client...",
    activityErrorTitle: "Impossible de charger l’activité",
    activityErrorText: "L’historique client enregistré reste disponible. Réessayez de le charger.",
    noWork: "Aucun travail dans cet historique client pour le moment.",
    noQuotes: "Aucune activité de devis liée pour le moment.",
    noInvoices: "Aucune facture liée pour le moment.",
    noDocumentsPhotos: "Aucun document ni aucune photo liés pour le moment.",
    linkedWork: "Travail lié",
    documentsLabel: "Documents",
    photosLabel: "Photos",
    canonicalQuote: "Devis Meetro",
    canonicalInvoice: "Facture Meetro",
    requestPhoto: "Photo de la demande",
    provenance: "Source",
    openPhoto: "Ouvrir la photo",
    completed: "Terminé",
    created: "Créé",
    issued: "Émis",
    latest: "Dernière activité",
    total: "Total",
    paid: "Payé",
    balance: "Solde",
    decision: "Décision du client",
    quote: "Devis",
    invoice: "Facture",
    job: "Travail",
    activeJobs: "Travaux en cours",
    completedJobs: "Travaux terminés",
    openJob: "Ouvrir le travail",
    nextStep: "Prochaine étape",
    historySummary: "Résumé de l'historique",
    photos: "Photos",
    paymentHistory: "Historique des paiements",
    deposits: "Acomptes",
    required: "Requis",
    applied: "Appliqué",
    received: "Reçu",
    deposit: "Acompte",
    depositReceived: "Acompte reçu",
    invoicePaymentReceived: "Paiement de facture reçu",
    visits: "Visites / Calendrier",
    workPerformed: "Travail effectué",
    scheduled: "Planifié",
    established: "Établie",
    currentContact: "Coordonnées actuelles du Contact",
    contactName: "Contact",
    company: "Organisation",
    partyType: "Type de Contact",
    person: "Personne",
    organization: "Organisation",
    status: "Statut du Contact",
    jobStatus: "Statut du travail",
    active: "Actif",
    archived: "Archivé",
    email: "E-mail",
    phone: "Téléphone",
    address: "Adresse",
    serviceArea: "Zone de service",
    notAdded: "Non renseigné",
    backToRelationships: "Retour aux Clients",
    backToBusinessTools: "Retour aux outils de l'entreprise",
    viewContact: "Voir le Contact dans le Centre de communication",
    startNewJob: "Démarrer un nouveau travail",
    newJobHeading: "Démarrer un nouveau travail",
    newJobIntro: "Créez un nouveau travail pour ce client. Les détails, devis, paiements et horaires précédents ne sont pas repris.",
    newJobTitle: "Titre du travail",
    newJobTitlePlaceholder: "Quel est l'objet de ce nouveau travail ?",
    newJobDescription: "Détails",
    newJobDescriptionPlaceholder: "Ajoutez les détails du nouveau travail",
    newJobLocation: "Lieu du service",
    newJobLocationPlaceholder: "Facultatif — ajoutez le lieu de ce travail",
    newJobLocationHelp: "Laissez ce champ vide si le lieu du service sera ajouté plus tard.",
    createJob: "Créer le travail",
    cancelNewJob: "Annuler",
    creatingJob: "Création du travail...",
    newJobErrorTitle: "Le nouveau travail n'a pas pu être créé",
    newJobErrorText: "Vérifiez les détails du nouveau travail et réessayez.",
    archivedNewJobUnavailable: "Les clients archivés restent disponibles dans l'historique, mais un nouveau travail ne peut pas être démarré tant que le Contact n'est pas actif.",
    noRelationshipTitle: "Aucun historique client pour le moment",
    noRelationshipText: "L’historique client n’a pas encore commencé pour ce Contact.",
    noRelationshipHelp: "Consulter ce Contact ne démarre pas l’historique. Il commence uniquement lorsque le Contact est explicitement utilisé comme client.",
    externalContact: "Ce Contact n'a pas besoin d'un compte Meetro.",
    readOnly: "L’historique client et les coordonnées restent en lecture seule ici. Démarrer un nouveau travail crée un travail distinct sans modifier l’historique précédent.",
  }),
  "pt-BR": Object.freeze({
    issuedStatus: "Emitido",
    approvedStatus: "Aprovado",
    declinedStatus: "Recusado",
    sentStatus: "Enviado",
    partiallyPaidStatus: "Parcialmente pago",
    paidStatus: "Pago",
    customerReportReadOnly: "Este relatório somente leitura contém o histórico canônico visível para o cliente. Ele não altera trabalhos nem registros comerciais.",

    professionalHistoryReport: "Relatório profissional do histórico do cliente",
    customerReportError: "Não foi possível preparar o relatório do histórico do cliente. Tente novamente.",
    nativeNewJobUnavailable: "Não é possível iniciar novo trabalho para um cliente com conta Meetro pelo Histórico.",
    messageCustomer: "Enviar mensagem ao cliente",
    nativeMessageUnavailable: "Não há uma única conversa elegível disponível. Abra o trabalho exato para consultar sua comunicação.",

    originalQuote: "Original", revisedQuote: "Revisado", additionalQuote: "Adicional",
    title: "Histórico do cliente",
    description: "Trabalhos, orçamentos, faturas, documentos, fotos e registros importantes de um cliente.",
    category: "Operações do negócio",
    loading: "Carregando histórico do cliente...",
    loadErrorTitle: "Não foi possível carregar o histórico do cliente",
    loadErrorText: "Tente novamente para carregar o histórico do cliente salvo da sua empresa.",
    retry: "Tentar novamente",
    emptyTitle: "Ainda não há histórico do cliente",
    emptyText: "O histórico do cliente aparece depois que você usa explicitamente um Contato salvo como cliente. Visualizar esta página não cria nada.",
    relationshipList: "Clientes",
    openRelationship: "Abrir histórico do cliente",
    relationshipEstablished: "Histórico do cliente iniciado",
    customerSince: "Cliente desde",
    relationshipActivity: "Histórico do cliente",
    completedWorkDirectory: "Todos os trabalhos concluídos desta empresa",
    privateContacts: "Contatos privados",
    noPrivateContacts: "Ainda não há Contatos privados vinculados ao histórico do cliente.",
    meetroCustomers: "Clientes Meetro",
    nativeSourceLabel: "Cliente Meetro",
    nativeHistory: "Histórico do cliente",
    nativeJobDetail: "Detalhes do trabalho concluído",
    backToNativeHistory: "Voltar ao histórico do cliente",
    openNativeCustomer: "Abrir histórico do cliente Meetro",
    openNativeJob: "Abrir trabalho concluído",
    noNativeCustomers: "Ainda não há clientes Meetro disponíveis para este negócio.",
    noNativeCompletedWork: "Ainda não há trabalho concluído.",
    nativeHistoryUnavailable: "O histórico do cliente está indisponível. Tente novamente.",
    loadMoreNative: "Carregar mais",
    emergencySource: "Emergência",
    ordinarySource: "Trabalho padrão",
    approvedQuote: "Orçamento aprovado",
    completedWork: "Trabalhos concluídos",
    overview: "Visão geral",
    work: "Trabalhos",
    quotes: "Orçamentos",
    invoices: "Faturas",
    documentsPhotos: "Documentos / Fotos",
    loadingActivity: "Carregando histórico do cliente...",
    activityErrorTitle: "Não foi possível carregar a atividade",
    activityErrorText: "O histórico do cliente salvo continua disponível. Tente carregá-lo novamente.",
    noWork: "Ainda não há trabalhos neste histórico do cliente.",
    noQuotes: "Ainda não há atividade de orçamentos vinculada.",
    noInvoices: "Ainda não há faturas vinculadas.",
    noDocumentsPhotos: "Ainda não há documentos ou fotos vinculados.",
    linkedWork: "Trabalho vinculado",
    documentsLabel: "Documentos",
    photosLabel: "Fotos",
    canonicalQuote: "Orçamento Meetro",
    canonicalInvoice: "Fatura Meetro",
    requestPhoto: "Foto da solicitação",
    provenance: "Origem",
    openPhoto: "Abrir foto",
    completed: "Concluído",
    created: "Criado",
    issued: "Emitido",
    latest: "Mais recente",
    total: "Total",
    paid: "Pago",
    balance: "Saldo",
    decision: "Decisão do cliente",
    quote: "Orçamento",
    invoice: "Fatura",
    job: "Trabalho",
    activeJobs: "Trabalhos ativos",
    completedJobs: "Trabalhos concluídos",
    openJob: "Abrir trabalho",
    nextStep: "Próximo passo",
    historySummary: "Resumo do histórico",
    photos: "Fotos",
    paymentHistory: "Histórico de pagamentos",
    deposits: "Depósitos",
    required: "Obrigatório",
    applied: "Aplicado",
    received: "Recebido",
    deposit: "Depósito",
    depositReceived: "Depósito recebido",
    invoicePaymentReceived: "Pagamento de fatura recebido",
    visits: "Visitas / Agenda",
    workPerformed: "Trabalho realizado",
    scheduled: "Agendado",
    established: "Estabelecido",
    currentContact: "Informações atuais do Contato",
    contactName: "Contato",
    company: "Organização",
    partyType: "Tipo de Contato",
    person: "Pessoa",
    organization: "Organização",
    status: "Status do Contato",
    jobStatus: "Status do trabalho",
    active: "Ativo",
    archived: "Arquivado",
    email: "E-mail",
    phone: "Telefone",
    address: "Endereço",
    serviceArea: "Área de atendimento",
    notAdded: "Não adicionado",
    backToRelationships: "Voltar para Clientes",
    backToBusinessTools: "Voltar para Ferramentas do negócio",
    viewContact: "Ver Contato na Central de comunicação",
    startNewJob: "Iniciar novo trabalho",
    newJobHeading: "Iniciar um novo trabalho",
    newJobIntro: "Crie um trabalho novo para este cliente. Detalhes, orçamentos, pagamentos e agenda anteriores não são reaproveitados.",
    newJobTitle: "Título do trabalho",
    newJobTitlePlaceholder: "Qual é o trabalho deste novo serviço?",
    newJobDescription: "Detalhes",
    newJobDescriptionPlaceholder: "Adicione os detalhes do novo trabalho",
    newJobLocation: "Local do serviço",
    newJobLocationPlaceholder: "Opcional — adicione o local deste trabalho",
    newJobLocationHelp: "Deixe em branco se o local do serviço será adicionado depois.",
    createJob: "Criar trabalho",
    cancelNewJob: "Cancelar",
    creatingJob: "Criando trabalho...",
    newJobErrorTitle: "Não foi possível criar o novo trabalho",
    newJobErrorText: "Revise os detalhes do novo trabalho e tente novamente.",
    archivedNewJobUnavailable: "Clientes arquivados continuam disponíveis no histórico, mas um novo trabalho não pode ser iniciado até que o Contato esteja ativo.",
    noRelationshipTitle: "Ainda não há histórico do cliente",
    noRelationshipText: "O histórico do cliente ainda não começou para este Contato.",
    noRelationshipHelp: "Visualizar este Contato não inicia o histórico. Ele começa somente quando o Contato é usado explicitamente como cliente.",
    externalContact: "Este Contato não precisa de uma conta Meetro.",
    readOnly: "Este espaço consulta o histórico do cliente e as informações salvas do Contato. Ele não cria nem altera nenhum dos registros.",
  }),
});

export function getCustomerRelationshipsCopy(language = "en") {
  return copy[language] || copy.en;
}
