export const customerQuoteLanguage = Object.freeze({
  en: Object.freeze({
    customerQuotesTitle: "Quotes",
    customerQuotesIntro: "Review the work and total provided by your professional.",
    customerQuotesLoading: "Loading Quotes...",
    customerQuotesEmpty: "No Quotes have been issued for this job yet.",
    customerQuotesUnavailable: "Quotes are temporarily unavailable.",
    customerQuoteReview: "Review Quote",
    customerQuoteCloseReview: "Back to job details",
    customerQuoteStatusWaiting: "Waiting for your decision",
    customerQuoteStatusApproved: "Quote accepted",
    customerQuoteStatusDeclined: "Declined",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revised",
    customerQuoteLineageAdditional: "Additional",
    customerQuoteIssued: "Issued",
    customerQuoteIssuedBy: "Issued by",
    customerQuoteProject: "Project",
    customerQuoteVersion: "Quote version",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Work included",
    customerQuoteConditions: "Conditions",
    customerQuoteExclusions: "Not included",
    customerQuoteNoneListed: "None listed",
    customerQuoteQuantity: "Qty",
    customerQuoteTerms: "Terms",
    customerQuotePaymentTerms: "Payment and deposit terms",
    customerQuoteEstimatedDuration: "Estimated duration",
    customerQuoteCustomerNotes: "Notes for you",
    customerQuoteAgreementExclusions: "Agreement exclusions",
    customerQuoteAdditionalWorkTerms: "Additional work terms",
    customerQuoteHiddenConditionsTerms: "Hidden conditions terms",
    customerQuoteDiagnosticTerms: "Diagnostic terms",
    customerQuoteCustomerResponsibilities: "Your responsibilities",
    customerQuoteAcceptanceTerms: "Acceptance terms",
    customerQuoteWarrantyTerms: "Warranty terms",
    customerQuoteCancellationTerms: "Cancellation terms",
    customerQuotePreauthorizedAdditionalWorkLimit: "Preauthorized additional work limit",
    customerQuoteAcceptedNext:
      "Your acceptance is recorded. Payment or deposit and scheduling remain separate next steps.",
    customerQuoteApprove: "Accept Quote",
    customerQuoteDecline: "Decline Quote",
    customerQuoteApproveConfirmTitle: "Accept this Quote?",
    customerQuoteApproveConfirmBody:
      "This records your acceptance of this exact Quote, version, terms, and total.",
    customerQuoteDeclineConfirmTitle: "Decline this Quote?",
    customerQuoteDeclineConfirmBody:
      "This records your decision for this exact Quote. You can continue the conversation about next steps.",
    customerQuoteConfirmApprove: "Confirm acceptance",
    customerQuoteConfirmDecline: "Confirm decline",
    customerQuoteCancel: "Cancel",
    customerQuoteSaving: "Saving your decision...",
    customerQuoteApprovedSaved: "Your Quote acceptance was saved.",
    customerQuoteDeclinedSaved: "Your Quote decision was saved.",
    customerQuoteConflictReloaded:
      "This Quote changed before your decision was saved. The latest details are shown.",
    customerQuoteDecisionFailed:
      "Your decision could not be saved. Review the Quote and try again.",
    quoteDeliveryLoading: "Loading delivery options...",
    quoteDeliveryUnavailable: "Delivery options are temporarily unavailable.",
    quoteDeliveryTitle: "Delivery",
    quoteDeliverySending: "Sending...",
    quoteDeliverySendInMeetro: "Send in Meetro",
    quoteDeliverySendAgain: "Send Again",
    quoteDeliverySendCopyAgain: "Send Copy Again",
    quoteDeliveryCancel: "Cancel",
    quoteDeliveryAlreadyDeliveredTitle: "Quote already delivered",
    quoteDeliveryAlreadyDeliveredMessage: "This Quote has already been sent and delivered to the customer. Would you like to send the same Quote again?",
    quoteDeliveryAlreadyAcceptedTitle: "Quote already accepted",
    quoteDeliveryAlreadyAcceptedMessage: "The customer has already accepted this Quote. Sending it again will send another copy only and will not change the accepted agreement.",
    quoteDeliveryAlreadyDeclinedTitle: "Quote already declined",
    quoteDeliveryAlreadyDeclinedMessage: "The customer has already declined this Quote. Sending it again will send another copy of the unchanged Quote only and will not request a new decision.",
    quoteDeliveryShareQuote: "Share Quote",
    quoteDeliveryConversationUnavailable: "Meetro delivery is unavailable for this Conversation.",
    quoteDeliverySendFailed: "The Quote could not be sent. Try again.",
    quoteDeliverySent: "Quote sent in Meetro",
    quoteDeliveryCopySent: "Another Quote copy was sent in Meetro",
    quoteDeliveryViewConversation: "View Conversation",
    quoteDeliverySystemShare: "Share PDF",
    quoteDeliveryEmail: "Email PDF",
    quoteDeliveryCopyDetails: "Copy Quote Details",
    quoteDeliveryCopied: "Quote details copied.",
    quoteDeliveryPdfReady: "Quote PDF ready.",
    quoteDeliveryShareUnavailable: "Sharing is unavailable on this device.",
    quoteDeliveryQuote: "Quote",
    quoteDecisionApprovedTitle: "Quote approved",
    quoteDecisionDeclinedTitle: "Quote declined",
    quoteDecisionApprovedMessage: "{customer} approved {quote} for {total}.",
    quoteDecisionDeclinedMessage: "{customer} declined {quote}.",
    quoteDecisionDepositDue: "Deposit due before scheduling: {amount}",
    quoteDecisionViewQuote: "View Quote",
    quoteDecisionOpenWorkCenter: "Open Work Center",
    quoteDecisionAttentionCategory: "Customer decision",
    quoteDecisionAttentionCanonical: "Current canonical state",
    "alerts.commercial.quoteApproved.title": "Quote approved by customer",
    "alerts.commercial.quoteApproved.message": "Review the approved Quote and its next operational requirement.",
    "alerts.commercial.quoteDeclined.title": "Quote declined by customer",
    "alerts.commercial.quoteDeclined.message": "Review the customer decision before preparing a revision.",
    quoteDeliveryBackToConversation: "Back to Conversation",
    quoteDeliveryShareTitle: "Quote from {business}",
    quoteDeliveryShareFrom: "Quote from {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Quote: {lineage}",
    quoteDeliveryShareScope: "Work included:",
  }),
  es: Object.freeze({
    customerQuotesTitle: "Cotizaciones",
    customerQuotesIntro: "Revisa el trabajo y el total proporcionados por tu profesional.",
    customerQuotesLoading: "Cargando cotizaciones...",
    customerQuotesEmpty: "Todavía no se ha emitido una cotización para este trabajo.",
    customerQuotesUnavailable: "Las cotizaciones no están disponibles temporalmente.",
    customerQuoteReview: "Revisar cotización",
    customerQuoteCloseReview: "Volver a los detalles del trabajo",
    customerQuoteStatusWaiting: "Esperando tu decisión",
    customerQuoteStatusApproved: "Cotización aceptada",
    customerQuoteStatusDeclined: "Rechazada",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revisada",
    customerQuoteLineageAdditional: "Adicional",
    customerQuoteIssued: "Emitida",
    customerQuoteIssuedBy: "Emitida por",
    customerQuoteProject: "Proyecto",
    customerQuoteVersion: "Versión de la cotización",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Trabajo incluido",
    customerQuoteConditions: "Condiciones",
    customerQuoteExclusions: "No incluido",
    customerQuoteNoneListed: "Ninguno indicado",
    customerQuoteQuantity: "Cant.",
    customerQuoteTerms: "Términos",
    customerQuotePaymentTerms: "Términos de pago y depósito",
    customerQuoteEstimatedDuration: "Duración estimada",
    customerQuoteCustomerNotes: "Notas para ti",
    customerQuoteAgreementExclusions: "Exclusiones del acuerdo",
    customerQuoteAdditionalWorkTerms: "Términos de trabajo adicional",
    customerQuoteHiddenConditionsTerms: "Términos de condiciones ocultas",
    customerQuoteDiagnosticTerms: "Términos de diagnóstico",
    customerQuoteCustomerResponsibilities: "Tus responsabilidades",
    customerQuoteAcceptanceTerms: "Términos de aceptación",
    customerQuoteWarrantyTerms: "Términos de garantía",
    customerQuoteCancellationTerms: "Términos de cancelación",
    customerQuotePreauthorizedAdditionalWorkLimit: "Límite preautorizado de trabajo adicional",
    customerQuoteAcceptedNext:
      "Tu aceptación quedó registrada. El pago o depósito y la programación son pasos posteriores separados.",
    customerQuoteApprove: "Aceptar cotización",
    customerQuoteDecline: "Rechazar cotización",
    customerQuoteApproveConfirmTitle: "¿Aceptar esta cotización?",
    customerQuoteApproveConfirmBody:
      "Esto registra tu aceptación de esta cotización, versión, términos y total exactos.",
    customerQuoteDeclineConfirmTitle: "¿Rechazar esta cotización?",
    customerQuoteDeclineConfirmBody:
      "Esto registra tu decisión para esta cotización exacta. Puedes continuar la conversación sobre los próximos pasos.",
    customerQuoteConfirmApprove: "Confirmar aceptación",
    customerQuoteConfirmDecline: "Confirmar rechazo",
    customerQuoteCancel: "Cancelar",
    customerQuoteSaving: "Guardando tu decisión...",
    customerQuoteApprovedSaved: "Se guardó tu aceptación de la cotización.",
    customerQuoteDeclinedSaved: "Se guardó tu decisión sobre la cotización.",
    customerQuoteConflictReloaded:
      "Esta cotización cambió antes de guardar tu decisión. Se muestran los detalles más recientes.",
    customerQuoteDecisionFailed:
      "No se pudo guardar tu decisión. Revisa la cotización e inténtalo de nuevo.",
    quoteDeliveryLoading: "Cargando opciones de entrega...",
    quoteDeliveryUnavailable: "Las opciones de entrega no están disponibles temporalmente.",
    quoteDeliveryTitle: "Entrega",
    quoteDeliverySending: "Enviando...",
    quoteDeliverySendInMeetro: "Enviar en Meetro",
    quoteDeliverySendAgain: "Enviar de nuevo",
    quoteDeliverySendCopyAgain: "Enviar otra copia",
    quoteDeliveryCancel: "Cancelar",
    quoteDeliveryAlreadyDeliveredTitle: "Cotización ya entregada",
    quoteDeliveryAlreadyDeliveredMessage: "Esta cotización ya fue enviada y entregada al cliente. ¿Quieres enviar la misma cotización de nuevo?",
    quoteDeliveryAlreadyAcceptedTitle: "Cotización ya aceptada",
    quoteDeliveryAlreadyAcceptedMessage: "El cliente ya aceptó esta cotización. Enviarla de nuevo solo enviará otra copia y no cambiará el acuerdo aceptado.",
    quoteDeliveryAlreadyDeclinedTitle: "Cotización ya rechazada",
    quoteDeliveryAlreadyDeclinedMessage: "El cliente ya rechazó esta cotización. Enviarla de nuevo solo enviará otra copia sin cambios y no solicitará una nueva decisión.",
    quoteDeliveryShareQuote: "Compartir cotización",
    quoteDeliveryConversationUnavailable: "La entrega en Meetro no está disponible para esta conversación.",
    quoteDeliverySendFailed: "No se pudo enviar la cotización. Inténtalo de nuevo.",
    quoteDeliverySent: "Cotización enviada en Meetro",
    quoteDeliveryCopySent: "Se envió otra copia de la cotización en Meetro",
    quoteDeliveryViewConversation: "Ver conversación",
    quoteDeliverySystemShare: "Compartir PDF",
    quoteDeliveryEmail: "Enviar PDF",
    quoteDeliveryCopyDetails: "Copiar detalles de la cotización",
    quoteDeliveryCopied: "Detalles de la cotización copiados.",
    quoteDeliveryPdfReady: "PDF de la cotización listo.",
    quoteDeliveryShareUnavailable: "La función de compartir no está disponible en este dispositivo.",
    quoteDeliveryQuote: "Cotización",
    quoteDecisionApprovedTitle: "Cotización aprobada",
    quoteDecisionDeclinedTitle: "Cotización rechazada",
    quoteDecisionApprovedMessage: "{customer} aprobó {quote} por {total}.",
    quoteDecisionDeclinedMessage: "{customer} rechazó {quote}.",
    quoteDecisionDepositDue: "Depósito pendiente antes de programar: {amount}",
    quoteDecisionViewQuote: "Ver cotización",
    quoteDecisionOpenWorkCenter: "Abrir Centro de Trabajo",
    quoteDecisionAttentionCategory: "Decisión del cliente",
    quoteDecisionAttentionCanonical: "Estado canónico actual",
    "alerts.commercial.quoteApproved.title": "Cotización aprobada por el cliente",
    "alerts.commercial.quoteApproved.message": "Revisa la cotización aprobada y su siguiente requisito operativo.",
    "alerts.commercial.quoteDeclined.title": "Cotización rechazada por el cliente",
    "alerts.commercial.quoteDeclined.message": "Revisa la decisión del cliente antes de preparar una revisión.",
    quoteDeliveryBackToConversation: "Volver a la conversación",
    quoteDeliveryShareTitle: "Cotización de {business}",
    quoteDeliveryShareFrom: "Cotización de {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Cotización: {lineage}",
    quoteDeliveryShareScope: "Trabajo incluido:",
  }),
  fr: Object.freeze({
    customerQuotesTitle: "Devis",
    customerQuotesIntro: "Examinez les travaux et le total fournis par votre professionnel.",
    customerQuotesLoading: "Chargement des devis...",
    customerQuotesEmpty: "Aucun devis n'a encore été émis pour ce travail.",
    customerQuotesUnavailable: "Les devis sont temporairement indisponibles.",
    customerQuoteReview: "Examiner le devis",
    customerQuoteCloseReview: "Retour aux détails du travail",
    customerQuoteStatusWaiting: "En attente de votre décision",
    customerQuoteStatusApproved: "Devis accepté",
    customerQuoteStatusDeclined: "Refusé",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Révisé",
    customerQuoteLineageAdditional: "Supplémentaire",
    customerQuoteIssued: "Émis",
    customerQuoteIssuedBy: "Émis par",
    customerQuoteProject: "Projet",
    customerQuoteVersion: "Version du devis",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Travaux inclus",
    customerQuoteConditions: "Conditions",
    customerQuoteExclusions: "Non inclus",
    customerQuoteNoneListed: "Aucun élément indiqué",
    customerQuoteQuantity: "Qté",
    customerQuoteTerms: "Conditions",
    customerQuotePaymentTerms: "Conditions de paiement et d’acompte",
    customerQuoteEstimatedDuration: "Durée estimée",
    customerQuoteCustomerNotes: "Notes à votre intention",
    customerQuoteAgreementExclusions: "Exclusions de l’accord",
    customerQuoteAdditionalWorkTerms: "Conditions des travaux supplémentaires",
    customerQuoteHiddenConditionsTerms: "Conditions relatives aux éléments cachés",
    customerQuoteDiagnosticTerms: "Conditions de diagnostic",
    customerQuoteCustomerResponsibilities: "Vos responsabilités",
    customerQuoteAcceptanceTerms: "Conditions d’acceptation",
    customerQuoteWarrantyTerms: "Conditions de garantie",
    customerQuoteCancellationTerms: "Conditions d’annulation",
    customerQuotePreauthorizedAdditionalWorkLimit: "Limite préautorisée des travaux supplémentaires",
    customerQuoteAcceptedNext:
      "Votre acceptation est enregistrée. Le paiement ou l’acompte et la planification restent des étapes distinctes.",
    customerQuoteApprove: "Accepter le devis",
    customerQuoteDecline: "Refuser le devis",
    customerQuoteApproveConfirmTitle: "Accepter ce devis ?",
    customerQuoteApproveConfirmBody:
      "Ceci enregistre votre acceptation de ce devis, de cette version, de ces conditions et de ce total précis.",
    customerQuoteDeclineConfirmTitle: "Refuser ce devis ?",
    customerQuoteDeclineConfirmBody:
      "Ceci enregistre votre décision pour ce devis précis. Vous pouvez poursuivre la conversation sur les prochaines étapes.",
    customerQuoteConfirmApprove: "Confirmer l’acceptation",
    customerQuoteConfirmDecline: "Confirmer le refus",
    customerQuoteCancel: "Annuler",
    customerQuoteSaving: "Enregistrement de votre décision...",
    customerQuoteApprovedSaved: "Votre acceptation du devis a été enregistrée.",
    customerQuoteDeclinedSaved: "Votre décision sur le devis a été enregistrée.",
    customerQuoteConflictReloaded:
      "Ce devis a changé avant l'enregistrement de votre décision. Les derniers détails sont affichés.",
    customerQuoteDecisionFailed:
      "Votre décision n'a pas pu être enregistrée. Examinez le devis et réessayez.",
    quoteDeliveryLoading: "Chargement des options d’envoi...",
    quoteDeliveryUnavailable: "Les options d’envoi sont temporairement indisponibles.",
    quoteDeliveryTitle: "Envoi",
    quoteDeliverySending: "Envoi en cours...",
    quoteDeliverySendInMeetro: "Envoyer dans Meetro",
    quoteDeliverySendAgain: "Renvoyer",
    quoteDeliverySendCopyAgain: "Renvoyer une copie",
    quoteDeliveryCancel: "Annuler",
    quoteDeliveryAlreadyDeliveredTitle: "Devis déjà livré",
    quoteDeliveryAlreadyDeliveredMessage: "Ce devis a déjà été envoyé et livré au client. Voulez-vous renvoyer le même devis ?",
    quoteDeliveryAlreadyAcceptedTitle: "Devis déjà accepté",
    quoteDeliveryAlreadyAcceptedMessage: "Le client a déjà accepté ce devis. Le renvoyer enverra uniquement une autre copie et ne modifiera pas l’accord accepté.",
    quoteDeliveryAlreadyDeclinedTitle: "Devis déjà refusé",
    quoteDeliveryAlreadyDeclinedMessage: "Le client a déjà refusé ce devis. Le renvoyer enverra uniquement une autre copie inchangée et ne demandera pas une nouvelle décision.",
    quoteDeliveryShareQuote: "Partager le devis",
    quoteDeliveryConversationUnavailable: "L’envoi dans Meetro n’est pas disponible pour cette conversation.",
    quoteDeliverySendFailed: "Le devis n’a pas pu être envoyé. Réessayez.",
    quoteDeliverySent: "Devis envoyé dans Meetro",
    quoteDeliveryCopySent: "Une autre copie du devis a été envoyée dans Meetro",
    quoteDeliveryViewConversation: "Voir la conversation",
    quoteDeliverySystemShare: "Partager le PDF",
    quoteDeliveryEmail: "Envoyer le PDF",
    quoteDeliveryCopyDetails: "Copier les détails du devis",
    quoteDeliveryCopied: "Détails du devis copiés.",
    quoteDeliveryPdfReady: "PDF du devis prêt.",
    quoteDeliveryShareUnavailable: "Le partage n’est pas disponible sur cet appareil.",
    quoteDeliveryQuote: "Devis",
    quoteDecisionApprovedTitle: "Devis approuvé",
    quoteDecisionDeclinedTitle: "Devis refusé",
    quoteDecisionApprovedMessage: "{customer} a approuvé {quote} pour {total}.",
    quoteDecisionDeclinedMessage: "{customer} a refusé {quote}.",
    quoteDecisionDepositDue: "Acompte dû avant la planification : {amount}",
    quoteDecisionViewQuote: "Voir le devis",
    quoteDecisionOpenWorkCenter: "Ouvrir le centre de travail",
    quoteDecisionAttentionCategory: "Décision du client",
    quoteDecisionAttentionCanonical: "État canonique actuel",
    "alerts.commercial.quoteApproved.title": "Devis approuvé par le client",
    "alerts.commercial.quoteApproved.message": "Examinez le devis approuvé et sa prochaine exigence opérationnelle.",
    "alerts.commercial.quoteDeclined.title": "Devis refusé par le client",
    "alerts.commercial.quoteDeclined.message": "Examinez la décision du client avant de préparer une révision.",
    quoteDeliveryBackToConversation: "Retour à la conversation",
    quoteDeliveryShareTitle: "Devis de {business}",
    quoteDeliveryShareFrom: "Devis de {business}",
    quoteDeliveryShareTotal: "Total : {total}",
    quoteDeliveryShareLineage: "Devis : {lineage}",
    quoteDeliveryShareScope: "Travaux inclus :",
  }),
  "pt-BR": Object.freeze({
    customerQuotesTitle: "Orçamentos",
    customerQuotesIntro: "Revise o trabalho e o total fornecidos pelo profissional.",
    customerQuotesLoading: "Carregando orçamentos...",
    customerQuotesEmpty: "Nenhum orçamento foi emitido para este trabalho ainda.",
    customerQuotesUnavailable: "Os orçamentos estão temporariamente indisponíveis.",
    customerQuoteReview: "Revisar orçamento",
    customerQuoteCloseReview: "Voltar aos detalhes do trabalho",
    customerQuoteStatusWaiting: "Aguardando sua decisão",
    customerQuoteStatusApproved: "Orçamento aceito",
    customerQuoteStatusDeclined: "Recusado",
    customerQuoteLineageOriginal: "Original",
    customerQuoteLineageRevised: "Revisado",
    customerQuoteLineageAdditional: "Adicional",
    customerQuoteIssued: "Emitido",
    customerQuoteIssuedBy: "Emitido por",
    customerQuoteProject: "Projeto",
    customerQuoteVersion: "Versão do orçamento",
    customerQuoteTotal: "Total",
    customerQuoteScope: "Trabalho incluido",
    customerQuoteConditions: "Condições",
    customerQuoteExclusions: "Não incluído",
    customerQuoteNoneListed: "Nenhum item informado",
    customerQuoteQuantity: "Qtd.",
    customerQuoteTerms: "Termos",
    customerQuotePaymentTerms: "Termos de pagamento e depósito",
    customerQuoteEstimatedDuration: "Duração estimada",
    customerQuoteCustomerNotes: "Observações para você",
    customerQuoteAgreementExclusions: "Exclusões do acordo",
    customerQuoteAdditionalWorkTerms: "Termos de trabalho adicional",
    customerQuoteHiddenConditionsTerms: "Termos de condições ocultas",
    customerQuoteDiagnosticTerms: "Termos de diagnóstico",
    customerQuoteCustomerResponsibilities: "Suas responsabilidades",
    customerQuoteAcceptanceTerms: "Termos de aceitação",
    customerQuoteWarrantyTerms: "Termos de garantia",
    customerQuoteCancellationTerms: "Termos de cancelamento",
    customerQuotePreauthorizedAdditionalWorkLimit: "Limite pré-autorizado de trabalho adicional",
    customerQuoteAcceptedNext:
      "Sua aceitação foi registrada. Pagamento ou depósito e agendamento continuam sendo etapas separadas.",
    customerQuoteApprove: "Aceitar orçamento",
    customerQuoteDecline: "Recusar orçamento",
    customerQuoteApproveConfirmTitle: "Aceitar este orçamento?",
    customerQuoteApproveConfirmBody:
      "Isso registra sua aceitação deste orçamento, versão, termos e total exatos.",
    customerQuoteDeclineConfirmTitle: "Recusar este orçamento?",
    customerQuoteDeclineConfirmBody:
      "Isso registra sua decisão para este orçamento exato. Você pode continuar a conversa sobre os próximos passos.",
    customerQuoteConfirmApprove: "Confirmar aceitação",
    customerQuoteConfirmDecline: "Confirmar recusa",
    customerQuoteCancel: "Cancelar",
    customerQuoteSaving: "Salvando sua decisão...",
    customerQuoteApprovedSaved: "Sua aceitação do orçamento foi salva.",
    customerQuoteDeclinedSaved: "Sua decisão sobre o orçamento foi salva.",
    customerQuoteConflictReloaded:
      "Este orçamento mudou antes de sua decisão ser salva. Os detalhes mais recentes estão sendo exibidos.",
    customerQuoteDecisionFailed:
      "Não foi possível salvar sua decisão. Revise o orçamento e tente novamente.",
    quoteDeliveryLoading: "Carregando opções de envio...",
    quoteDeliveryUnavailable: "As opções de envio estão temporariamente indisponíveis.",
    quoteDeliveryTitle: "Envio",
    quoteDeliverySending: "Enviando...",
    quoteDeliverySendInMeetro: "Enviar no Meetro",
    quoteDeliverySendAgain: "Enviar novamente",
    quoteDeliverySendCopyAgain: "Enviar outra cópia",
    quoteDeliveryCancel: "Cancelar",
    quoteDeliveryAlreadyDeliveredTitle: "Orçamento já entregue",
    quoteDeliveryAlreadyDeliveredMessage: "Este orçamento já foi enviado e entregue ao cliente. Deseja enviar o mesmo orçamento novamente?",
    quoteDeliveryAlreadyAcceptedTitle: "Orçamento já aceito",
    quoteDeliveryAlreadyAcceptedMessage: "O cliente já aceitou este orçamento. Enviá-lo novamente enviará apenas outra cópia e não alterará o acordo aceito.",
    quoteDeliveryAlreadyDeclinedTitle: "Orçamento já recusado",
    quoteDeliveryAlreadyDeclinedMessage: "O cliente já recusou este orçamento. Enviá-lo novamente enviará apenas outra cópia inalterada e não solicitará uma nova decisão.",
    quoteDeliveryShareQuote: "Compartilhar orçamento",
    quoteDeliveryConversationUnavailable: "O envio pelo Meetro não está disponível para esta conversa.",
    quoteDeliverySendFailed: "Não foi possível enviar o orçamento. Tente novamente.",
    quoteDeliverySent: "Orçamento enviado no Meetro",
    quoteDeliveryCopySent: "Outra cópia do orçamento foi enviada no Meetro",
    quoteDeliveryViewConversation: "Ver conversa",
    quoteDeliverySystemShare: "Compartilhar PDF",
    quoteDeliveryEmail: "Enviar PDF",
    quoteDeliveryCopyDetails: "Copiar detalhes do orçamento",
    quoteDeliveryCopied: "Detalhes do orçamento copiados.",
    quoteDeliveryPdfReady: "PDF do orçamento pronto.",
    quoteDeliveryShareUnavailable: "O compartilhamento não está disponível neste dispositivo.",
    quoteDeliveryQuote: "Orçamento",
    quoteDecisionApprovedTitle: "Orçamento aprovado",
    quoteDecisionDeclinedTitle: "Orçamento recusado",
    quoteDecisionApprovedMessage: "{customer} aprovou {quote} por {total}.",
    quoteDecisionDeclinedMessage: "{customer} recusou {quote}.",
    quoteDecisionDepositDue: "Depósito devido antes do agendamento: {amount}",
    quoteDecisionViewQuote: "Ver orçamento",
    quoteDecisionOpenWorkCenter: "Abrir Central de Trabalho",
    quoteDecisionAttentionCategory: "Decisão do cliente",
    quoteDecisionAttentionCanonical: "Estado canônico atual",
    "alerts.commercial.quoteApproved.title": "Orçamento aprovado pelo cliente",
    "alerts.commercial.quoteApproved.message": "Revise o orçamento aprovado e o próximo requisito operacional.",
    "alerts.commercial.quoteDeclined.title": "Orçamento recusado pelo cliente",
    "alerts.commercial.quoteDeclined.message": "Revise a decisão do cliente antes de preparar uma revisão.",
    quoteDeliveryBackToConversation: "Voltar para a conversa",
    quoteDeliveryShareTitle: "Orçamento de {business}",
    quoteDeliveryShareFrom: "Orçamento de {business}",
    quoteDeliveryShareTotal: "Total: {total}",
    quoteDeliveryShareLineage: "Orçamento: {lineage}",
    quoteDeliveryShareScope: "Trabalho incluído:",
  }),
});
