export const CUSTOMER_RELATIONSHIPS_LANGUAGES = Object.freeze([
  "en",
  "es",
  "fr",
  "pt-BR",
]);

const copy = Object.freeze({
  en: Object.freeze({
    title: "Customer Relationships",
    description: "Continuity with customers across work, without turning relationships into a sales pipeline.",
    category: "Business Operations",
    loading: "Loading Customer Relationships...",
    loadErrorTitle: "Customer Relationships could not be loaded",
    loadErrorText: "Try again to load the saved relationship records for your business.",
    retry: "Try Again",
    emptyTitle: "No Customer Relationships yet",
    emptyText: "A Customer Relationship appears after you explicitly use a saved Contact as a customer. Viewing this page creates nothing.",
    relationshipList: "Established Customer Relationships",
    openRelationship: "Open Customer Relationship",
    relationshipEstablished: "Customer Relationship established",
    established: "Established",
    currentContact: "Current Contact Information",
    contactName: "Contact",
    company: "Organization",
    partyType: "Contact type",
    person: "Person",
    organization: "Organization",
    status: "Contact status",
    active: "Active",
    archived: "Archived",
    email: "Email",
    phone: "Phone",
    address: "Address",
    serviceArea: "Service area",
    notAdded: "Not added",
    backToRelationships: "Back to Customer Relationships",
    backToBusinessTools: "Back to Business Tools",
    viewContact: "View Contact in Communication Center",
    noRelationshipTitle: "No Customer Relationship established",
    noRelationshipText: "No Customer Relationship has been established for this Contact yet.",
    noRelationshipHelp: "Viewing this Contact does not create a relationship. Customer Relationships are established only through an explicit customer-use workflow.",
    externalContact: "A Meetro account is not required for this Contact.",
    readOnly: "This workspace reads saved relationship and Contact information. It does not create or change either record.",
  }),
  es: Object.freeze({
    title: "Relaciones con clientes",
    description: "Continuidad con clientes entre trabajos, sin convertir las relaciones en un proceso de ventas.",
    category: "Operaciones del negocio",
    loading: "Cargando relaciones con clientes...",
    loadErrorTitle: "No se pudieron cargar las relaciones con clientes",
    loadErrorText: "Intenta de nuevo para cargar los registros de relaciones guardados de tu negocio.",
    retry: "Intentar de nuevo",
    emptyTitle: "Aún no hay relaciones con clientes",
    emptyText: "Una relación con un cliente aparece después de usar explícitamente un Contacto guardado como cliente. Ver esta página no crea nada.",
    relationshipList: "Relaciones con clientes establecidas",
    openRelationship: "Abrir relación con el cliente",
    relationshipEstablished: "Relación con el cliente establecida",
    established: "Establecida",
    currentContact: "Información actual del Contacto",
    contactName: "Contacto",
    company: "Organización",
    partyType: "Tipo de Contacto",
    person: "Persona",
    organization: "Organización",
    status: "Estado del Contacto",
    active: "Activo",
    archived: "Archivado",
    email: "Correo electrónico",
    phone: "Teléfono",
    address: "Dirección",
    serviceArea: "Área de servicio",
    notAdded: "No agregado",
    backToRelationships: "Volver a Relaciones con clientes",
    backToBusinessTools: "Volver a Herramientas del negocio",
    viewContact: "Ver Contacto en el Centro de comunicación",
    noRelationshipTitle: "No hay una relación con el cliente establecida",
    noRelationshipText: "Aún no se ha establecido una relación con el cliente para este Contacto.",
    noRelationshipHelp: "Ver este Contacto no crea una relación. Las relaciones con clientes se establecen solo mediante un flujo explícito de uso como cliente.",
    externalContact: "Este Contacto no necesita una cuenta de Meetro.",
    readOnly: "Este espacio lee la relación y la información del Contacto guardadas. No crea ni cambia ninguno de los registros.",
  }),
  fr: Object.freeze({
    title: "Relations clients",
    description: "Une continuité avec les clients d'un travail à l'autre, sans transformer les relations en pipeline commercial.",
    category: "Opérations de l'entreprise",
    loading: "Chargement des relations clients...",
    loadErrorTitle: "Impossible de charger les relations clients",
    loadErrorText: "Réessayez pour charger les relations enregistrées de votre entreprise.",
    retry: "Réessayer",
    emptyTitle: "Aucune relation client pour le moment",
    emptyText: "Une relation client apparaît après l'utilisation explicite d'un Contact enregistré comme client. Consulter cette page ne crée rien.",
    relationshipList: "Relations clients établies",
    openRelationship: "Ouvrir la relation client",
    relationshipEstablished: "Relation client établie",
    established: "Établie",
    currentContact: "Coordonnées actuelles du Contact",
    contactName: "Contact",
    company: "Organisation",
    partyType: "Type de Contact",
    person: "Personne",
    organization: "Organisation",
    status: "Statut du Contact",
    active: "Actif",
    archived: "Archivé",
    email: "E-mail",
    phone: "Téléphone",
    address: "Adresse",
    serviceArea: "Zone de service",
    notAdded: "Non renseigné",
    backToRelationships: "Retour aux Relations clients",
    backToBusinessTools: "Retour aux outils de l'entreprise",
    viewContact: "Voir le Contact dans le Centre de communication",
    noRelationshipTitle: "Aucune relation client établie",
    noRelationshipText: "Aucune relation client n'a encore été établie pour ce Contact.",
    noRelationshipHelp: "Consulter ce Contact ne crée pas de relation. Une relation client est établie uniquement par un parcours explicite d'utilisation comme client.",
    externalContact: "Ce Contact n'a pas besoin d'un compte Meetro.",
    readOnly: "Cet espace consulte la relation et les coordonnées enregistrées. Il ne crée ni ne modifie aucun des deux enregistrements.",
  }),
  "pt-BR": Object.freeze({
    title: "Relacionamentos com clientes",
    description: "Continuidade com clientes entre trabalhos, sem transformar relacionamentos em um funil de vendas.",
    category: "Operações do negócio",
    loading: "Carregando relacionamentos com clientes...",
    loadErrorTitle: "Não foi possível carregar os relacionamentos com clientes",
    loadErrorText: "Tente novamente para carregar os relacionamentos salvos da sua empresa.",
    retry: "Tentar novamente",
    emptyTitle: "Ainda não há relacionamentos com clientes",
    emptyText: "Um relacionamento com cliente aparece depois que você usa explicitamente um Contato salvo como cliente. Visualizar esta página não cria nada.",
    relationshipList: "Relacionamentos com clientes estabelecidos",
    openRelationship: "Abrir relacionamento com cliente",
    relationshipEstablished: "Relacionamento com cliente estabelecido",
    established: "Estabelecido",
    currentContact: "Informações atuais do Contato",
    contactName: "Contato",
    company: "Organização",
    partyType: "Tipo de Contato",
    person: "Pessoa",
    organization: "Organização",
    status: "Status do Contato",
    active: "Ativo",
    archived: "Arquivado",
    email: "E-mail",
    phone: "Telefone",
    address: "Endereço",
    serviceArea: "Área de atendimento",
    notAdded: "Não adicionado",
    backToRelationships: "Voltar para Relacionamentos com clientes",
    backToBusinessTools: "Voltar para Ferramentas do negócio",
    viewContact: "Ver Contato na Central de comunicação",
    noRelationshipTitle: "Nenhum relacionamento com cliente estabelecido",
    noRelationshipText: "Ainda não foi estabelecido um relacionamento com cliente para este Contato.",
    noRelationshipHelp: "Visualizar este Contato não cria um relacionamento. Relacionamentos com clientes são estabelecidos apenas por um fluxo explícito de uso como cliente.",
    externalContact: "Este Contato não precisa de uma conta Meetro.",
    readOnly: "Este espaço consulta o relacionamento e as informações salvas do Contato. Ele não cria nem altera nenhum dos registros.",
  }),
});

export function getCustomerRelationshipsCopy(language = "en") {
  return copy[language] || copy.en;
}
