const COPY = Object.freeze({
  en: {
    assessment: "Project assessment",
    evaluation: "Evaluation",
    loading: "Loading",
    saving: "Saving",
    completing: "Completing",
    completed: "Complete",
    draft: "In progress",
    noEvaluation: "No evaluation yet",
    customerConcern: "Customer concern",
    customerDetails: "Customer-provided details",
    unavailable: "Unavailable",
    loadingEvaluation: "Loading evaluation.",
    evaluationUnavailable: "Evaluation is temporarily unavailable.",
    retry: "Retry",
    noEvaluationBody: "Start with what you observed during the visit.",
    startEvaluation: "Start Evaluation",
    observations: "Professional observations",
    noneRecorded: "None recorded.",
    assessmentSummary: "Assessment summary",
    limitations: "Limitations",
    internalNotes: "Internal notes",
    editEvaluation: "Update Evaluation",
    saveEvaluation: "Save Evaluation",
    cancel: "Cancel",
    completeEvaluation: "Complete Evaluation",
    confirmCompletion: "Confirm completion",
    completionHelp: "The Evaluation becomes read-only. Findings can still be documented separately.",
    keepEditing: "Keep editing",
    evaluationSaved: "Evaluation saved.",
    evaluationCompleted: "Evaluation completed.",
    observationsRequired: "Add professional observations before saving.",
    changedElsewhere: "This record changed elsewhere. Current details were reloaded.",
    updateUnavailable: "This update is not available for the current Job stage.",
    whatFound: "What I Found",
    addFinding: "Add Finding",
    loadingFindings: "Loading findings.",
    findingsUnavailable: "Findings are temporarily unavailable.",
    noFindings: "No findings have been recorded yet.",
    finding: "Finding",
    proposed: "Proposed",
    confirmed: "Confirmed",
    needsAttention: "Needs Attention",
    partiallyResolved: "Partially Resolved",
    resolved: "Resolved",
    deferred: "Deferred",
    professionalOnly: "Professional only",
    sharedWithCustomer: "Visible to customer",
    update: "Update",
    confirmFinding: "Confirm Finding",
    findingDetails: "What did you find?",
    shareWithCustomer: "Show this confirmed information to the customer",
    saveFinding: "Save Finding",
    whatRecommend: "What I Recommend",
    addRecommendation: "Add Recommendation",
    loadingRecommendations: "Loading recommendations.",
    recommendationsUnavailable: "Recommendations are temporarily unavailable.",
    noRecommendations: "No recommendations have been recorded yet.",
    primaryRecommendation: "Recommendation",
    alternativeRecommendation: "Alternative",
    recommendationDetails: "What do you recommend?",
    saveRecommendation: "Save Recommendation",
    active: "Recommended",
    accepted: "Accepted",
    declined: "Not proceeding",
    superseded: "Replaced",
    withdrawn: "Withdrawn",
    excluded: "Not in current quote",
    separateProposal: "Separate quote needed",
    customerConstraint: "Customer note",
    notApproval: "This is not customer approval.",
    prepareQuote: "Prepare Quote",
    assessmentUnavailable: "Project assessment is temporarily unavailable.",
    loadingAssessment: "Loading project assessment.",
    professionalFound: "What the professional found",
    professionalRecommends: "What the professional recommends",
    noSharedAssessment: "No customer-facing findings or recommendations yet.",
    evaluationInProgress: "The professional is documenting the evaluation.",
    evaluationComplete: "The evaluation is complete.",
  },
  es: {
    assessment: "Evaluación del proyecto", evaluation: "Evaluación", loading: "Cargando", saving: "Guardando", completing: "Completando", completed: "Completa", draft: "En progreso", noEvaluation: "Sin evaluación", customerConcern: "Necesidad del cliente", customerDetails: "Detalles del cliente", unavailable: "No disponible", loadingEvaluation: "Cargando evaluación.", evaluationUnavailable: "La evaluación no está disponible temporalmente.", retry: "Reintentar", noEvaluationBody: "Comienza con lo observado durante la visita.", startEvaluation: "Iniciar evaluación", observations: "Observaciones profesionales", noneRecorded: "Sin información.", assessmentSummary: "Resumen de evaluación", limitations: "Limitaciones", internalNotes: "Notas internas", editEvaluation: "Actualizar evaluación", saveEvaluation: "Guardar evaluación", cancel: "Cancelar", completeEvaluation: "Completar evaluación", confirmCompletion: "Confirmar finalización", completionHelp: "La evaluación quedará en solo lectura. Los hallazgos se documentan por separado.", keepEditing: "Seguir editando", evaluationSaved: "Evaluación guardada.", evaluationCompleted: "Evaluación completada.", observationsRequired: "Agrega observaciones profesionales antes de guardar.", changedElsewhere: "Este registro cambió. Se cargaron los detalles actuales.", updateUnavailable: "Esta actualización no está disponible en la etapa actual.", whatFound: "Lo que encontré", addFinding: "Agregar hallazgo", loadingFindings: "Cargando hallazgos.", findingsUnavailable: "Los hallazgos no están disponibles temporalmente.", noFindings: "Aún no hay hallazgos.", finding: "Hallazgo", proposed: "Propuesto", confirmed: "Confirmado", needsAttention: "Requiere atención", partiallyResolved: "Parcialmente resuelto", resolved: "Resuelto", deferred: "Pospuesto", professionalOnly: "Solo profesional", sharedWithCustomer: "Visible para el cliente", update: "Actualizar", confirmFinding: "Confirmar hallazgo", findingDetails: "¿Qué encontraste?", shareWithCustomer: "Mostrar esta información confirmada al cliente", saveFinding: "Guardar hallazgo", whatRecommend: "Lo que recomiendo", addRecommendation: "Agregar recomendación", loadingRecommendations: "Cargando recomendaciones.", recommendationsUnavailable: "Las recomendaciones no están disponibles temporalmente.", noRecommendations: "Aún no hay recomendaciones.", primaryRecommendation: "Recomendación", alternativeRecommendation: "Alternativa", recommendationDetails: "¿Qué recomiendas?", saveRecommendation: "Guardar recomendación", active: "Recomendado", accepted: "Aceptado", declined: "No continuará", superseded: "Reemplazada", withdrawn: "Retirada", excluded: "Fuera de la cotización actual", separateProposal: "Requiere cotización separada", customerConstraint: "Nota del cliente", notApproval: "Esto no es aprobación del cliente.", prepareQuote: "Preparar cotización", assessmentUnavailable: "La evaluación del proyecto no está disponible temporalmente.", loadingAssessment: "Cargando evaluación del proyecto.", professionalFound: "Lo que encontró el profesional", professionalRecommends: "Lo que recomienda el profesional", noSharedAssessment: "Aún no hay hallazgos o recomendaciones para el cliente.", evaluationInProgress: "El profesional está documentando la evaluación.", evaluationComplete: "La evaluación está completa.",
  },
  fr: {
    assessment: "Évaluation du projet", evaluation: "Évaluation", loading: "Chargement", saving: "Enregistrement", completing: "Finalisation", completed: "Terminée", draft: "En cours", noEvaluation: "Aucune évaluation", customerConcern: "Besoin du client", customerDetails: "Détails fournis par le client", unavailable: "Indisponible", loadingEvaluation: "Chargement de l’évaluation.", evaluationUnavailable: "L’évaluation est temporairement indisponible.", retry: "Réessayer", noEvaluationBody: "Commencez par les observations faites pendant la visite.", startEvaluation: "Commencer l’évaluation", observations: "Observations professionnelles", noneRecorded: "Aucune information.", assessmentSummary: "Résumé de l’évaluation", limitations: "Limites", internalNotes: "Notes internes", editEvaluation: "Mettre à jour l’évaluation", saveEvaluation: "Enregistrer l’évaluation", cancel: "Annuler", completeEvaluation: "Terminer l’évaluation", confirmCompletion: "Confirmer la fin", completionHelp: "L’évaluation devient non modifiable. Les constats restent documentés séparément.", keepEditing: "Continuer la modification", evaluationSaved: "Évaluation enregistrée.", evaluationCompleted: "Évaluation terminée.", observationsRequired: "Ajoutez des observations avant l’enregistrement.", changedElsewhere: "Cet élément a changé. Les détails actuels ont été rechargés.", updateUnavailable: "Cette mise à jour n’est pas disponible à cette étape.", whatFound: "Ce que j’ai constaté", addFinding: "Ajouter un constat", loadingFindings: "Chargement des constats.", findingsUnavailable: "Les constats sont temporairement indisponibles.", noFindings: "Aucun constat pour le moment.", finding: "Constat", proposed: "Proposé", confirmed: "Confirmé", needsAttention: "À traiter", partiallyResolved: "Partiellement résolu", resolved: "Résolu", deferred: "Reporté", professionalOnly: "Professionnel uniquement", sharedWithCustomer: "Visible par le client", update: "Mettre à jour", confirmFinding: "Confirmer le constat", findingDetails: "Qu’avez-vous constaté ?", shareWithCustomer: "Afficher cette information confirmée au client", saveFinding: "Enregistrer le constat", whatRecommend: "Ce que je recommande", addRecommendation: "Ajouter une recommandation", loadingRecommendations: "Chargement des recommandations.", recommendationsUnavailable: "Les recommandations sont temporairement indisponibles.", noRecommendations: "Aucune recommandation pour le moment.", primaryRecommendation: "Recommandation", alternativeRecommendation: "Alternative", recommendationDetails: "Que recommandez-vous ?", saveRecommendation: "Enregistrer la recommandation", active: "Recommandé", accepted: "Accepté", declined: "Non retenu", superseded: "Remplacé", withdrawn: "Retiré", excluded: "Hors du devis actuel", separateProposal: "Devis séparé requis", customerConstraint: "Note du client", notApproval: "Ceci n’est pas une approbation du client.", prepareQuote: "Préparer le devis", assessmentUnavailable: "L’évaluation du projet est temporairement indisponible.", loadingAssessment: "Chargement de l’évaluation du projet.", professionalFound: "Ce que le professionnel a constaté", professionalRecommends: "Ce que le professionnel recommande", noSharedAssessment: "Aucun constat ou recommandation visible par le client.", evaluationInProgress: "Le professionnel documente l’évaluation.", evaluationComplete: "L’évaluation est terminée.",
  },
  "pt-BR": {
    assessment: "Avaliação do projeto", evaluation: "Avaliação", loading: "Carregando", saving: "Salvando", completing: "Concluindo", completed: "Concluída", draft: "Em andamento", noEvaluation: "Sem avaliação", customerConcern: "Necessidade do cliente", customerDetails: "Detalhes fornecidos pelo cliente", unavailable: "Indisponível", loadingEvaluation: "Carregando avaliação.", evaluationUnavailable: "A avaliação está temporariamente indisponível.", retry: "Tentar novamente", noEvaluationBody: "Comece pelo que foi observado durante a visita.", startEvaluation: "Iniciar avaliação", observations: "Observações profissionais", noneRecorded: "Nada registrado.", assessmentSummary: "Resumo da avaliação", limitations: "Limitações", internalNotes: "Notas internas", editEvaluation: "Atualizar avaliação", saveEvaluation: "Salvar avaliação", cancel: "Cancelar", completeEvaluation: "Concluir avaliação", confirmCompletion: "Confirmar conclusão", completionHelp: "A avaliação ficará somente para leitura. As constatações continuam separadas.", keepEditing: "Continuar editando", evaluationSaved: "Avaliação salva.", evaluationCompleted: "Avaliação concluída.", observationsRequired: "Adicione observações profissionais antes de salvar.", changedElsewhere: "Este registro mudou. Os detalhes atuais foram recarregados.", updateUnavailable: "Esta atualização não está disponível nesta etapa.", whatFound: "O que encontrei", addFinding: "Adicionar constatação", loadingFindings: "Carregando constatações.", findingsUnavailable: "As constatações estão temporariamente indisponíveis.", noFindings: "Ainda não há constatações.", finding: "Constatação", proposed: "Proposta", confirmed: "Confirmada", needsAttention: "Precisa de atenção", partiallyResolved: "Parcialmente resolvida", resolved: "Resolvida", deferred: "Adiada", professionalOnly: "Somente profissional", sharedWithCustomer: "Visível para o cliente", update: "Atualizar", confirmFinding: "Confirmar constatação", findingDetails: "O que você encontrou?", shareWithCustomer: "Mostrar esta informação confirmada ao cliente", saveFinding: "Salvar constatação", whatRecommend: "O que recomendo", addRecommendation: "Adicionar recomendação", loadingRecommendations: "Carregando recomendações.", recommendationsUnavailable: "As recomendações estão temporariamente indisponíveis.", noRecommendations: "Ainda não há recomendações.", primaryRecommendation: "Recomendação", alternativeRecommendation: "Alternativa", recommendationDetails: "O que você recomenda?", saveRecommendation: "Salvar recomendação", active: "Recomendada", accepted: "Aceita", declined: "Não seguirá", superseded: "Substituída", withdrawn: "Retirada", excluded: "Fora do orçamento atual", separateProposal: "Precisa de orçamento separado", customerConstraint: "Nota do cliente", notApproval: "Isto não é aprovação do cliente.", prepareQuote: "Preparar orçamento", assessmentUnavailable: "A avaliação do projeto está temporariamente indisponível.", loadingAssessment: "Carregando avaliação do projeto.", professionalFound: "O que o profissional encontrou", professionalRecommends: "O que o profissional recomenda", noSharedAssessment: "Ainda não há constatações ou recomendações para o cliente.", evaluationInProgress: "O profissional está documentando a avaliação.", evaluationComplete: "A avaliação está concluída.",
  },
});

export function getEfrCopy(language = "en") {
  const normalized = String(language || "en").trim();
  const key = normalized.toLowerCase().startsWith("pt")
    ? "pt-BR"
    : normalized.toLowerCase().startsWith("es")
      ? "es"
      : normalized.toLowerCase().startsWith("fr")
        ? "fr"
        : "en";
  return COPY[key];
}
