const rows = [
  ["fieldNavHome", "Home", "Inicio", "Accueil", "Início"],
  ["fieldNavMyJobs", "My Jobs", "Mis trabajos", "Mes travaux", "Meus trabalhos"],
  ["fieldNavSchedule", "Schedule", "Agenda", "Planning", "Agenda"],
  ["fieldNavTime", "Time", "Tiempo", "Temps", "Tempo"],
  ["fieldNavMessages", "Messages", "Mensajes", "Messages", "Mensagens"],
  ["fieldNavAlerts", "Alerts", "Alertas", "Alertes", "Alertas"],
  ["fieldNavProfile", "Profile", "Perfil", "Profil", "Perfil"],
  ["fieldBrand", "Field", "Campo", "Terrain", "Campo"],
  ["fieldEmployeeRole", "Field Employee", "Empleado de campo", "Employé de terrain", "Funcionário de campo"],
  ["fieldTeamAccess", "Team access", "Acceso al equipo", "Accès à l’équipe", "Acesso à equipe"],
  ["fieldEmployeeNavigation", "Employee navigation", "Navegación del empleado", "Navigation de l’employé", "Navegação do funcionário"],
  ["fieldYourBusiness", "Your business", "Tu negocio", "Votre entreprise", "Sua empresa"],
  ["fieldHomeDescription", "Today’s field work at a glance.", "El trabajo de campo de hoy de un vistazo.", "Le travail de terrain d’aujourd’hui en un coup d’œil.", "O trabalho de campo de hoje em resumo."],
  ["fieldScheduleDescription", "Only Visits attached to your authorized Jobs.", "Solo visitas vinculadas a tus trabajos autorizados.", "Uniquement les visites liées à vos travaux autorisés.", "Somente visitas vinculadas aos seus trabalhos autorizados."],
  ["fieldTimeDescription", "Track your work time throughout the day.", "Registra tu tiempo de trabajo durante el día.", "Suivez votre temps de travail tout au long de la journée.", "Acompanhe seu tempo de trabalho ao longo do dia."],
  ["fieldMessagesDescription", "Team and customer communication for your assigned Jobs.", "Comunicación con el equipo y los clientes para tus trabajos asignados.", "Communication avec l’équipe et les clients pour les travaux qui vous sont attribués.", "Comunicação com a equipe e os clientes para seus trabalhos atribuídos."],
  ["fieldProfileDescription", "Your Team access and account context.", "Tu acceso al equipo y la información de tu cuenta.", "Votre accès à l’équipe et le contexte de votre compte.", "Seu acesso à equipe e o contexto da sua conta."],
  ["fieldAlertsDescription", "Alerts delivered to your exact account.", "Alertas enviadas directamente a tu cuenta.", "Alertes envoyées directement à votre compte.", "Alertas enviados diretamente para sua conta."],
  ["fieldAccessRequired", "Field Employee access is required.", "Se requiere acceso de empleado de campo.", "L’accès Employé de terrain est requis.", "É necessário acesso de funcionário de campo."],
  ["fieldWorkspaceLoading", "Loading your authorized field workspace…", "Cargando tu espacio de trabajo de campo autorizado…", "Chargement de votre espace de travail de terrain autorisé…", "Carregando seu espaço de trabalho de campo autorizado…"],
  ["fieldWorkspaceUnavailable", "Your field workspace is unavailable.", "Tu espacio de trabajo de campo no está disponible.", "Votre espace de travail de terrain est indisponible.", "Seu espaço de trabalho de campo não está disponível."],
  ["fieldTimePending", "Time pending", "Hora pendiente", "Horaire en attente", "Horário pendente"],
  ["fieldServiceLocationPending", "Service location pending", "Ubicación del servicio pendiente", "Lieu d’intervention en attente", "Local do serviço pendente"],
  ["fieldRemote", "Remote", "Remoto", "À distance", "Remoto"],
  ["fieldCustomer", "Customer", "Cliente", "Client", "Cliente"],
  ["fieldCustomerUnavailable", "Customer unavailable", "Cliente no disponible", "Client indisponible", "Cliente indisponível"],
  ["fieldTeamMember", "Team member", "Miembro del equipo", "Membre de l’équipe", "Membro da equipe"],
  ["fieldStatusAssigned", "Assigned", "Asignado", "Attribué", "Atribuído"],
  ["fieldStatusOnMyWay", "On my way", "En camino", "En route", "A caminho"],
  ["fieldStatusArrived", "Arrived", "Llegué", "Arrivé", "Cheguei"],
  ["fieldStatusWorking", "Working", "Trabajando", "En cours", "Trabalhando"],
  ["fieldStatusCompleted", "Field work completed", "Trabajo de campo completado", "Travail de terrain terminé", "Trabalho de campo concluído"],
  ["fieldStatusActive", "Active", "Activo", "Actif", "Ativo"],
  ["fieldStatusInactive", "Inactive", "Inactivo", "Inactif", "Inativo"],
  ["fieldStatusUnassigned", "Unassigned", "Sin asignar", "Non attribué", "Não atribuído"],
  ["fieldVisitEvaluation", "Evaluation", "Evaluación", "Évaluation", "Avaliação"],
  ["fieldVisitApprovedWork", "Approved work", "Trabajo aprobado", "Travail approuvé", "Trabalho aprovado"],
  ["fieldVisitFollowUp", "Follow-up", "Seguimiento", "Suivi", "Acompanhamento"],
  ["fieldVisitScheduled", "Scheduled", "Programada", "Planifiée", "Agendada"],
  ["fieldVisitProposed", "Proposed", "Propuesta", "Proposée", "Proposta"],
  ["fieldVisitAvailable", "Available", "Disponible", "Disponible", "Disponível"],
  ["fieldVisitCompleted", "Completed", "Completada", "Terminée", "Concluída"],
  ["fieldVisitRescheduled", "Rescheduled", "Reprogramada", "Replanifiée", "Reagendada"],
  ["fieldVisitCancelled", "Cancelled", "Cancelada", "Annulée", "Cancelada"],
  ["fieldVisitLocked", "Locked", "Bloqueada", "Verrouillée", "Bloqueada"],
  ["fieldCurrentAssignment", "Current assignment", "Asignación actual", "Affectation actuelle", "Atribuição atual"],
  ["fieldNoActiveAssignment", "No active assignment", "No hay una asignación activa", "Aucune affectation active", "Nenhuma atribuição ativa"],
  ["fieldAssignmentAppears", "When {businessName} assigns work, it will appear here.", "Cuando {businessName} te asigne trabajo, aparecerá aquí.", "Lorsque {businessName} vous attribuera un travail, il apparaîtra ici.", "Quando {businessName} atribuir um trabalho, ele aparecerá aqui."],
  ["fieldOpenJobDetail", "Open Job Detail", "Abrir detalles del trabajo", "Ouvrir les détails du travail", "Abrir detalhes do trabalho"],
  ["fieldTodaysWork", "Today’s work", "Trabajo de hoy", "Travail du jour", "Trabalho de hoje"],
  ["fieldScheduledVisit", "{count} scheduled Visit", "{count} visita programada", "{count} visite planifiée", "{count} visita agendada"],
  ["fieldScheduledVisits", "{count} scheduled Visits", "{count} visitas programadas", "{count} visites planifiées", "{count} visitas agendadas"],
  ["fieldNoScheduledVisits", "No scheduled Visits", "No hay visitas programadas", "Aucune visite planifiée", "Nenhuma visita agendada"],
  ["fieldViewSchedule", "View schedule", "Ver agenda", "Voir le planning", "Ver agenda"],
  ["fieldNextAction", "Next field action", "Próxima acción de campo", "Prochaine action de terrain", "Próxima ação de campo"],
  ["fieldMarkStatus", "Mark {status}", "Marcar {status}", "Marquer {status}", "Marcar {status}"],
  ["fieldNoActionPending", "No action pending", "No hay acciones pendientes", "Aucune action en attente", "Nenhuma ação pendente"],
  ["fieldCurrentStatus", "Current status", "Estado actual", "Statut actuel", "Status atual"],
  ["fieldContinueJobDetail", "Continue in Job Detail", "Continuar en detalles del trabajo", "Continuer dans les détails du travail", "Continuar nos detalhes do trabalho"],
  ["fieldCurrentTimer", "Current timer", "Temporizador actual", "Chronomètre actuel", "Cronômetro atual"],
  ["fieldNotClockedIn", "Not clocked in", "No has registrado la entrada", "Pas encore pointé", "Entrada não registrada"],
  ["fieldStartedAt", "Started {time}", "Iniciado {time}", "Commencé {time}", "Iniciado {time}"],
  ["fieldClockInWhenStarting", "Clock In when you begin authorized work.", "Registra la entrada cuando comiences el trabajo autorizado.", "Pointez à l’arrivée lorsque vous commencez le travail autorisé.", "Registre a entrada quando começar o trabalho autorizado."],
  ["fieldOpenTime", "Open Time", "Abrir tiempo", "Ouvrir Temps", "Abrir tempo"],
  ["fieldRecentUpdate", "Recent internal update", "Actualización interna reciente", "Mise à jour interne récente", "Atualização interna recente"],
  ["fieldNoTeamUpdates", "No Team updates yet", "Aún no hay novedades del equipo", "Aucune mise à jour de l’équipe", "Ainda não há atualizações da equipe"],
  ["fieldInternalMessagesAppear", "Internal Job messages from your business will appear here.", "Los mensajes internos de trabajo de tu negocio aparecerán aquí.", "Les messages internes de votre entreprise apparaîtront ici.", "As mensagens internas de trabalho da sua empresa aparecerão aqui."],
  ["fieldOpenMessages", "Open Messages", "Abrir mensajes", "Ouvrir les messages", "Abrir mensagens"],
  ["fieldAssignedVisits", "Assigned Visits", "Visitas asignadas", "Visites attribuées", "Visitas atribuídas"],
  ["fieldMySchedule", "My Schedule", "Mi agenda", "Mon planning", "Minha agenda"],
  ["fieldNoActiveVisitScheduled", "No active Visit is scheduled for your assigned Jobs.", "No hay una visita activa programada para tus trabajos asignados.", "Aucune visite active n’est planifiée pour vos travaux attribués.", "Nenhuma visita ativa está agendada para seus trabalhos atribuídos."],
  ["fieldInternalOnly", "Internal only", "Solo interno", "Interne uniquement", "Somente interno"],
  ["fieldMessagesTitle", "Field Messages", "Mensajes de campo", "Messages de terrain", "Mensagens de campo"],
  ["fieldMessagesPrivacy", "These updates stay between you and your business Team. Customers do not receive them.", "Estas novedades quedan entre tú y el equipo de tu negocio. Los clientes no las reciben.", "Ces mises à jour restent entre vous et l’équipe de votre entreprise. Les clients ne les reçoivent pas.", "Essas atualizações ficam entre você e a equipe da sua empresa. Os clientes não as recebem."],
  ["fieldMessagesHub", "Communication hub", "Centro de comunicación", "Centre de communication", "Central de comunicação"],
  ["fieldMessagesHubCopy", "Choose an assigned Job, then message your Team privately or the customer visibly.", "Elige un trabajo asignado y luego escribe en privado a tu equipo o de forma visible al cliente.", "Choisissez un travail attribué, puis écrivez en privé à votre équipe ou de façon visible au client.", "Escolha um trabalho atribuído e envie uma mensagem privada para sua equipe ou visível para o cliente."],
  ["fieldMessageAudience", "Message audience", "Destinatario del mensaje", "Audience du message", "Público da mensagem"],
  ["fieldAudienceTeam", "Team", "Equipo", "Équipe", "Equipe"],
  ["fieldAudienceCustomer", "Customer", "Cliente", "Client", "Cliente"],
  ["fieldPrivateToTeam", "Private to your team", "Privado para tu equipo", "Privé pour votre équipe", "Privado para sua equipe"],
  ["fieldVisibleToCustomer", "Visible to customer", "Visible para el cliente", "Visible par le client", "Visível para o cliente"],
  ["fieldMessageCustomer", "Message customer", "Enviar mensaje al cliente", "Écrire au client", "Enviar mensagem ao cliente"],
  ["fieldCustomerMessages", "Customer messages", "Mensajes del cliente", "Messages client", "Mensagens do cliente"],
  ["fieldNoCustomerMessages", "No customer messages yet.", "Aún no hay mensajes del cliente.", "Aucun message client pour le moment.", "Ainda não há mensagens do cliente."],
  ["fieldCustomerConversationUnavailable", "Customer conversation unavailable", "La conversación con el cliente no está disponible", "Conversation client indisponible", "Conversa com o cliente indisponível"],
  ["fieldWriteCustomerMessage", "Write a message to customer", "Escribe un mensaje para el cliente", "Écrivez un message au client", "Escreva uma mensagem para o cliente"],
  ["fieldSendToCustomer", "Send to customer", "Enviar al cliente", "Envoyer au client", "Enviar ao cliente"],
  ["fieldCustomerMessageFailed", "Customer message failed. Your message was not cleared.", "No se pudo enviar el mensaje al cliente. Tu mensaje no se borró.", "L’envoi du message au client a échoué. Votre message n’a pas été effacé.", "Falha ao enviar a mensagem ao cliente. Sua mensagem não foi apagada."],
  ["fieldCustomerMessagesLoading", "Loading customer messages…", "Cargando mensajes del cliente…", "Chargement des messages client…", "Carregando mensagens do cliente…"],
  ["fieldMessagesAssignmentUnavailable", "An exact active Job assignment is required before Team or Customer messaging is available.", "Se requiere una asignación de trabajo activa y exacta antes de usar los mensajes del equipo o del cliente.", "Une affectation active et exacte est requise avant d’accéder aux messages Équipe ou Client.", "É necessária uma atribuição de trabalho ativa e exata antes de usar as mensagens da Equipe ou do Cliente."],
  ["fieldBusiness", "Business", "Negocio", "Entreprise", "Empresa"],
  ["fieldOpenTeamMessages", "Open Team messages", "Abrir mensajes del equipo", "Ouvrir les messages Équipe", "Abrir mensagens da Equipe"],
  ["fieldOpenCustomerMessages", "Open Customer messages", "Abrir mensajes del cliente", "Ouvrir les messages Client", "Abrir mensagens do Cliente"],
  ["fieldOpenJob", "Open Job", "Abrir trabajo", "Ouvrir le travail", "Abrir trabalho"],
  ["fieldNoInternalMessages", "No internal Job messages yet.", "Aún no hay mensajes internos del trabajo.", "Aucun message interne pour le moment.", "Ainda não há mensagens internas do trabalho."],
  ["fieldProfileTeamAccess", "Team Access", "Acceso al equipo", "Accès à l’équipe", "Acesso à equipe"],
  ["fieldProfileRole", "Role", "Rol", "Rôle", "Função"],
  ["fieldProfileAccess", "Access", "Acceso", "Accès", "Acesso"],
  ["fieldProfileAccessManaged", "Access managed by your business", "Acceso administrado por tu negocio", "Accès géré par votre entreprise", "Acesso gerenciado pela sua empresa"],
  ["fieldProfileStatus", "Status", "Estado", "Statut", "Status"],
  ["fieldUsingMeetroAs", "Using Meetro as", "Usando Meetro como", "Utiliser Meetro en tant que", "Usando o Meetro como"],
  ["fieldWorkExperience", "Work — {businessName}", "Trabajo — {businessName}", "Travail — {businessName}", "Trabalho — {businessName}"],
  ["fieldPersonalExperience", "Personal", "Personal", "Personnel", "Pessoal"],
  ["fieldExperienceIdentityCopy", "Your Personal Meetro account and your Work access use the same identity. Switching views does not change your Team permissions.", "Tu cuenta personal de Meetro y tu acceso de trabajo usan la misma identidad. Cambiar de vista no modifica tus permisos del equipo.", "Votre compte Meetro personnel et votre accès professionnel utilisent la même identité. Changer de vue ne modifie pas vos autorisations d’équipe.", "Sua conta pessoal do Meetro e seu acesso de trabalho usam a mesma identidade. Alternar as visualizações não altera suas permissões de equipe."],
  ["fieldBillingManaged", "Subscription plans and Business billing are managed by the Business Owner and are not part of your employee profile.", "Los planes de suscripción y la facturación del negocio son administrados por el propietario y no forman parte de tu perfil de empleado.", "Les abonnements et la facturation de l’entreprise sont gérés par le propriétaire et ne font pas partie de votre profil d’employé.", "Os planos de assinatura e o faturamento da empresa são gerenciados pelo proprietário e não fazem parte do seu perfil de funcionário."],
  ["fieldLanguageTitle", "Language", "Idioma", "Langue", "Idioma"],
  ["fieldLanguageDescription", "Choose the language you want to use in Meetro.", "Elige el idioma que quieres usar en Meetro.", "Choisissez la langue que vous souhaitez utiliser dans Meetro.", "Escolha o idioma que deseja usar no Meetro."],
  ["fieldLanguageSelected", "Selected language: {language}", "Idioma seleccionado: {language}", "Langue sélectionnée : {language}", "Idioma selecionado: {language}"],
  ["fieldMyJobsDescription", "View assigned work, update progress, and message your team.", "Consulta el trabajo asignado, actualiza el progreso y envía mensajes a tu equipo.", "Consultez les travaux attribués, mettez à jour l’avancement et écrivez à votre équipe.", "Veja o trabalho atribuído, atualize o progresso e envie mensagens à sua equipe."],
  ["fieldJobsLoading", "Loading your assigned Jobs…", "Cargando tus trabajos asignados…", "Chargement de vos travaux attribués…", "Carregando seus trabalhos atribuídos…"],
  ["fieldJobsUnavailable", "Your assigned Jobs are unavailable.", "Tus trabajos asignados no están disponibles.", "Vos travaux attribués sont indisponibles.", "Seus trabalhos atribuídos não estão disponíveis."],
  ["fieldNoAssignedJobs", "No assigned Jobs", "No hay trabajos asignados", "Aucun travail attribué", "Nenhum trabalho atribuído"],
  ["fieldNoAssignedJobsCopy", "When an Owner or Manager assigns work to you, the Job details will appear here.", "Cuando un propietario o gerente te asigne trabajo, los detalles aparecerán aquí.", "Lorsqu’un propriétaire ou un responsable vous attribuera un travail, les détails apparaîtront ici.", "Quando um proprietário ou gerente atribuir um trabalho a você, os detalhes aparecerão aqui."],
  ["fieldAssignedJobs", "Assigned Jobs", "Trabajos asignados", "Travaux attribués", "Trabalhos atribuídos"],
  ["fieldScheduledVisitsLabel", "Scheduled Visits", "Visitas programadas", "Visites planifiées", "Visitas agendadas"],
  ["fieldLoading", "Loading…", "Cargando…", "Chargement…", "Carregando…"],
  ["fieldNoJobSelected", "No Job selected", "No se seleccionó un trabajo", "Aucun travail sélectionné", "Nenhum trabalho selecionado"],
  ["fieldAssignedWork", "Assigned work", "Trabajo asignado", "Travail attribué", "Trabalho atribuído"],
  ["fieldSelectJob", "Select a Job", "Selecciona un trabajo", "Sélectionnez un travail", "Selecione um trabalho"],
  ["fieldLoadingStatus", "Loading status", "Cargando estado", "Chargement du statut", "Carregando status"],
  ["fieldJob", "Job", "Trabajo", "Travail", "Trabalho"],
  ["fieldInstructions", "Instructions", "Instrucciones", "Instructions", "Instruções"],
  ["fieldNoInstructions", "No additional Job instructions were recorded.", "No se registraron instrucciones adicionales.", "Aucune instruction supplémentaire n’a été enregistrée.", "Nenhuma instrução adicional foi registrada."],
  ["fieldApprovedWork", "Approved work", "Trabajo aprobado", "Travail approuvé", "Trabalho aprovado"],
  ["fieldQuantity", "Quantity {quantity}", "Cantidad {quantity}", "Quantité {quantity}", "Quantidade {quantity}"],
  ["fieldNoApprovedWork", "No approved work has been added yet.", "Aún no se agregó trabajo aprobado.", "Aucun travail approuvé n’a encore été ajouté.", "Nenhum trabalho aprovado foi adicionado ainda."],
  ["fieldPhotosDocuments", "Photos and documents", "Fotos y documentos", "Photos et documents", "Fotos e documentos"],
  ["fieldJobPhotos", "Job photos", "Fotos del trabajo", "Photos du travail", "Fotos do trabalho"],
  ["fieldJobEvidenceAlt", "Job evidence", "Evidencia del trabajo", "Preuve du travail", "Evidência do trabalho"],
  ["fieldNoJobPhotos", "No Job photos are currently attached.", "Actualmente no hay fotos adjuntas al trabajo.", "Aucune photo n’est actuellement jointe au travail.", "Nenhuma foto está anexada ao trabalho no momento."],
  ["fieldDocuments", "Documents", "Documentos", "Documents", "Documentos"],
  ["fieldApprovedQuote", "Approved Quote", "Cotización aprobada", "Devis approuvé", "Orçamento aprovado"],
  ["fieldDocumentVersion", "Version {version} · {status}", "Versión {version} · {status}", "Version {version} · {status}", "Versão {version} · {status}"],
  ["fieldNoApprovedDocument", "No approved Job document is currently available.", "No hay un documento aprobado disponible en este momento.", "Aucun document approuvé n’est disponible actuellement.", "Nenhum documento aprovado está disponível no momento."],
  ["fieldAssignmentHistory", "Assignment history", "Historial de asignaciones", "Historique des affectations", "Histórico de atribuições"],
  ["fieldAssignmentDetails", "Assignment details", "Detalles de la asignación", "Détails de l’affectation", "Detalhes da atribuição"],
  ["fieldAssignedAt", "Assigned {time}", "Asignado {time}", "Attribué {time}", "Atribuído {time}"],
  ["fieldUpdatedAt", "Updated {time}", "Actualizado {time}", "Mis à jour {time}", "Atualizado {time}"],
  ["fieldNoAssignmentHistory", "No assignment history is available.", "No hay historial de asignaciones disponible.", "Aucun historique d’affectation n’est disponible.", "Nenhum histórico de atribuições está disponível."],
  ["fieldProgressSeparate", "Job progress is tracked separately from assignment history.", "El progreso del trabajo se registra por separado del historial de asignaciones.", "L’avancement du travail est suivi séparément de l’historique des affectations.", "O progresso do trabalho é acompanhado separadamente do histórico de atribuições."],
  ["fieldSchedule", "Schedule", "Agenda", "Planning", "Agenda"],
  ["fieldUpcomingVisits", "Upcoming visits", "Próximas visitas", "Visites à venir", "Próximas visitas"],
  ["fieldNoVisitsScheduled", "No visits are scheduled yet.", "Aún no hay visitas programadas.", "Aucune visite n’est encore planifiée.", "Ainda não há visitas agendadas."],
  ["fieldOperationsAria", "Field operations", "Operaciones de campo", "Opérations de terrain", "Operações de campo"],
  ["fieldJobProgress", "Job progress", "Progreso del trabajo", "Avancement du travail", "Progresso do trabalho"],
  ["fieldUpdateProgressTitle", "Update progress and message your team", "Actualiza el progreso y envía mensajes a tu equipo", "Mettez à jour l’avancement et écrivez à votre équipe", "Atualize o progresso e envie mensagens à sua equipe"],
  ["fieldKeepTeamInformed", "Keep your status current and your team informed.", "Mantén tu estado actualizado y a tu equipo informado.", "Tenez votre statut à jour et votre équipe informée.", "Mantenha seu status atualizado e sua equipe informada."],
  ["fieldUpdatesUnavailable", "Field updates are unavailable.", "Las actualizaciones de campo no están disponibles.", "Les mises à jour de terrain sont indisponibles.", "As atualizações de campo não estão disponíveis."],
  ["fieldStatusUpdateFailed", "Field status could not be updated.", "No se pudo actualizar el estado de campo.", "Le statut de terrain n’a pas pu être mis à jour.", "Não foi possível atualizar o status de campo."],
  ["fieldMessageSendFailed", "The internal Job message could not be sent.", "No se pudo enviar el mensaje interno del trabajo.", "Le message interne n’a pas pu être envoyé.", "Não foi possível enviar a mensagem interna do trabalho."],
  ["fieldLoadingUpdates", "Loading field updates…", "Cargando actualizaciones de campo…", "Chargement des mises à jour de terrain…", "Carregando atualizações de campo…"],
  ["fieldNextStatus", "Next: {status}", "Siguiente: {status}", "Suivant : {status}", "Próximo: {status}"],
  ["fieldNextStep", "Next step", "Siguiente paso", "Étape suivante", "Próximo passo"],
  ["fieldOptionalNote", "Add a note (optional)", "Agrega una nota (opcional)", "Ajouter une note (facultatif)", "Adicione uma observação (opcional)"],
  ["fieldOptionalNotePlaceholder", "Add a quick note for your team", "Agrega una nota breve para tu equipo", "Ajoutez une brève note pour votre équipe", "Adicione uma observação rápida para sua equipe"],
  ["fieldRecording", "Recording…", "Registrando…", "Enregistrement…", "Registrando…"],
  ["fieldWorkMarkedComplete", "Your field work is marked complete. The Job stays open until the business completes it.", "Tu trabajo de campo está marcado como completado. El trabajo permanece abierto hasta que el negocio lo complete.", "Votre travail de terrain est marqué comme terminé. Le travail reste ouvert jusqu’à sa clôture par l’entreprise.", "Seu trabalho de campo está marcado como concluído. O trabalho permanece aberto até que a empresa o conclua."],
  ["fieldTeamMessages", "Team messages", "Mensajes del equipo", "Messages de l’équipe", "Mensagens da equipe"],
  ["fieldMessageYourTeam", "Message your team", "Envía un mensaje a tu equipo", "Écrire à votre équipe", "Envie uma mensagem à sua equipe"],
  ["fieldCustomersDoNotReceive", "Customers do not receive these messages.", "Los clientes no reciben estos mensajes.", "Les clients ne reçoivent pas ces messages.", "Os clientes não recebem essas mensagens."],
  ["fieldInternalMessagesAria", "Internal Job messages", "Mensajes internos del trabajo", "Messages internes du travail", "Mensagens internas do trabalho"],
  ["fieldNoTeamMessages", "No team messages yet.", "Aún no hay mensajes del equipo.", "Aucun message de l’équipe pour le moment.", "Ainda não há mensagens da equipe."],
  ["fieldWriteMessage", "Write a message", "Escribe un mensaje", "Écrire un message", "Escreva uma mensagem"],
  ["fieldWriteMessagePlaceholder", "Write a message to your team", "Escribe un mensaje para tu equipo", "Écrivez un message à votre équipe", "Escreva uma mensagem para sua equipe"],
  ["fieldSending", "Sending…", "Enviando…", "Envoi…", "Enviando…"],
  ["fieldSendMessage", "Send message", "Enviar mensaje", "Envoyer le message", "Enviar mensagem"],
  ["fieldTimeCategory", "Time category", "Categoría de tiempo", "Catégorie de temps", "Categoria de tempo"],
  ["fieldTimeJobWork", "Job Work", "Trabajo en el sitio", "Travail sur mission", "Trabalho no serviço"],
  ["fieldTimeDriving", "Driving", "Conducción", "Conduite", "Direção"],
  ["fieldTimeOffice", "Office", "Oficina", "Bureau", "Escritório"],
  ["fieldTimeSupplies", "Supplies", "Suministros", "Fournitures", "Suprimentos"],
  ["fieldTimeBreak", "Break", "Descanso", "Pause", "Pausa"],
  ["fieldTimeGeneral", "General", "General", "Général", "Geral"],
  ["fieldTimeJobWorkDescription", "Working on an assigned Job", "Trabajando en un trabajo asignado", "Travail sur une mission attribuée", "Trabalhando em um serviço atribuído"],
  ["fieldTimeDrivingDescription", "Driving for work", "Conduciendo por trabajo", "Déplacement professionnel", "Dirigindo a trabalho"],
  ["fieldTimeOfficeDescription", "Office or admin work", "Trabajo de oficina o administrativo", "Travail de bureau ou administratif", "Trabalho de escritório ou administrativo"],
  ["fieldTimeSuppliesDescription", "Picking up or purchasing supplies", "Recogiendo o comprando suministros", "Récupération ou achat de fournitures", "Retirada ou compra de suprimentos"],
  ["fieldTimeBreakDescription", "Meal or rest break", "Pausa para comer o descansar", "Pause repas ou repos", "Pausa para refeição ou descanso"],
  ["fieldTimeGeneralDescription", "Other work activity", "Otra actividad laboral", "Autre activité professionnelle", "Outra atividade de trabalho"],
  ["fieldTimeUnavailable", "Time tracking is unavailable right now.", "El registro de tiempo no está disponible en este momento.", "Le suivi du temps est indisponible pour le moment.", "O registro de tempo não está disponível no momento."],
  ["fieldClockInFailed", "Clock In could not be recorded.", "No se pudo registrar la entrada.", "L’arrivée n’a pas pu être enregistrée.", "Não foi possível registrar a entrada."],
  ["fieldClockOutFailed", "Clock Out could not be recorded.", "No se pudo registrar la salida.", "Le départ n’a pas pu être enregistré.", "Não foi possível registrar a saída."],
  ["fieldCurrentTimerAria", "Current timer", "Temporizador actual", "Chronomètre actuel", "Cronômetro atual"],
  ["fieldChooseThenClockIn", "Choose what you're doing, then clock in.", "Elige lo que estás haciendo y luego registra la entrada.", "Choisissez votre activité, puis pointez à l’arrivée.", "Escolha o que está fazendo e registre a entrada."],
  ["fieldClockIn", "Clock In", "Registrar entrada", "Pointer l’arrivée", "Registrar entrada"],
  ["fieldClockOut", "Clock Out", "Registrar salida", "Pointer le départ", "Registrar saída"],
  ["fieldClockInOutAria", "Clock In and Clock Out", "Registrar entrada y salida", "Pointer l’arrivée et le départ", "Registrar entrada e saída"],
  ["fieldChooseWorkActivity", "Choose your work activity", "Elige tu actividad de trabajo", "Choisissez votre activité professionnelle", "Escolha sua atividade de trabalho"],
  ["fieldChooseWorkActivityCopy", "Select the option that best matches what you're doing.", "Selecciona la opción que mejor corresponda a lo que estás haciendo.", "Sélectionnez l’option qui correspond le mieux à votre activité.", "Selecione a opção que melhor corresponde ao que você está fazendo."],
  ["fieldAssignedJobNeeded", "Assigned Job needed", "Se necesita un trabajo asignado", "Travail attribué requis", "É necessário um trabalho atribuído"],
  ["fieldSelectAssignedJobWarning", "Select an actively assigned Job before recording Job Work.", "Selecciona un trabajo asignado activo antes de registrar trabajo en el sitio.", "Sélectionnez un travail activement attribué avant d’enregistrer le temps de travail.", "Selecione um trabalho atribuído ativo antes de registrar o trabalho no serviço."],
  ["fieldLocationOptional", "Location (optional)", "Ubicación (opcional)", "Localisation (facultatif)", "Localização (opcional)"],
  ["fieldAddLocation", "Add your location", "Agrega tu ubicación", "Ajouter votre localisation", "Adicione sua localização"],
  ["fieldAddLocationCopy", "Turn this on to add your location when you clock in or out.", "Activa esta opción para agregar tu ubicación al registrar la entrada o salida.", "Activez cette option pour ajouter votre localisation lorsque vous pointez à l’arrivée ou au départ.", "Ative esta opção para adicionar sua localização ao registrar a entrada ou a saída."],
  ["fieldLocationOn", "Location on", "Ubicación activada", "Localisation activée", "Localização ativada"],
  ["fieldLocationOff", "Location off", "Ubicación desactivada", "Localisation désactivée", "Localização desativada"],
  ["fieldTimeHistory", "Time history", "Historial de tiempo", "Historique du temps", "Histórico de tempo"],
  ["fieldTimeHistoryCopy", "Review your recent clock-ins and clock-outs", "Revisa tus entradas y salidas recientes", "Consultez vos arrivées et départs récents", "Revise suas entradas e saídas recentes"],
  ["fieldNoTimeRecorded", "No time has been recorded yet.", "Aún no se ha registrado tiempo.", "Aucun temps n’a encore été enregistré.", "Ainda não há tempo registrado."],
  ["fieldOfficialTimeCopy", "Meetro records the official time when you clock in or out.", "Meetro registra la hora oficial cuando registras la entrada o salida.", "Meetro enregistre l’heure officielle lorsque vous pointez à l’arrivée ou au départ.", "O Meetro registra o horário oficial quando você registra a entrada ou a saída."],
  ["fieldClockOutDoesNotComplete", "Clocking out does not mark the Job complete.", "Registrar la salida no marca el trabajo como completado.", "Pointer le départ ne marque pas le travail comme terminé.", "Registrar a saída não marca o trabalho como concluído."],
  ["fieldTimeTracking", "Time tracking", "Registro de tiempo", "Suivi du temps", "Registro de tempo"],
  ["fieldTrackTimeForJob", "Track time for this Job", "Registra tiempo para este trabajo", "Suivre le temps pour ce travail", "Registre o tempo deste trabalho"],
  ["fieldAssignedJob", "Assigned Job", "Trabajo asignado", "Travail attribué", "Trabalho atribuído"],
  ["fieldCategoryTime", "{category} time", "Tiempo de {category}", "Temps : {category}", "Tempo de {category}"],
  ["fieldChangeCategory", "Change category", "Cambiar categoría", "Changer de catégorie", "Alterar categoria"],
  ["fieldAddLocationCompact", "Add location when I clock in or out", "Agregar ubicación al registrar la entrada o salida", "Ajouter la localisation à l’arrivée ou au départ", "Adicionar localização ao registrar a entrada ou a saída"],
  ["fieldCompactTimeAuthority", "Meetro records the official clock-in and clock-out time. View your history on the Time page.", "Meetro registra la hora oficial de entrada y salida. Consulta tu historial en la página Tiempo.", "Meetro enregistre l’heure officielle d’arrivée et de départ. Consultez votre historique sur la page Temps.", "O Meetro registra o horário oficial de entrada e saída. Veja seu histórico na página Tempo."],
  ["fieldNoJobRequired", "No Job required", "No se requiere un trabajo", "Aucun travail requis", "Nenhum trabalho necessário"],
  ["fieldSessionActive", "Active", "Activo", "Actif", "Ativo"],
];

function labelsAt(index) {
  return Object.freeze(
    Object.fromEntries(rows.map(([key, ...labels]) => [key, labels[index]]))
  );
}

export const fieldEmployeeLanguage = Object.freeze({
  en: labelsAt(0),
  es: labelsAt(1),
  fr: labelsAt(2),
  "pt-BR": labelsAt(3),
});
