const COPY = Object.freeze({
  en: {
    title: "Invoices & Payments", summary: "Create Invoices from completed work and preserve Payment truth with each Job.",
    ready: "Ready to Invoice", drafts: "Drafts", waiting: "Waiting for Payment", paid: "Paid",
    outstanding: "Outstanding", create: "Create Invoice", invoice: "Invoice", customer: "Customer",
    completed: "Completed", approvedTotal: "Approved total", dueOnReceipt: "Due on receipt",
    specificDate: "Specific date", dueDate: "Due date", customerNotes: "Customer notes",
    terms: "Payment terms", reviewDraft: "Review Draft", send: "Send Invoice", confirmSend: "Confirm Send",
    cancel: "Cancel", recordPayment: "Record Payment", amount: "Amount received", method: "Payment method",
    receivedDate: "Date received", reference: "Reference or note", cash: "Cash", check: "Check",
    bankTransfer: "Bank transfer", other: "Other", balance: "Balance", total: "Total", payments: "Payment history",
    noPayments: "No Payments recorded yet.", onlineUnavailable: "Online payment is not available through Meetro for this Invoice.",
    share: "Share PDF", email: "Email PDF", copy: "Copy Invoice Details", copied: "Invoice details copied.", pdfReady: "Invoice PDF ready.",
    noPublicLink: "Sharing uses the confirmed Invoice details. No public Invoice link is created.",
    unavailable: "Invoice details are unavailable right now.", empty: "No invoices yet.",
    sent: "Invoice sent in Meetro.", recorded: "Payment recorded.", loading: "Loading Invoice truth...",
    original: "Original", revised: "Revised", additional: "Additional", back: "Back to Work Center",
    backConversation: "Back to Conversation", reviewInvoice: "Review Invoice", invoiceReceived: "Invoice received",
    sendReminder: "Send Reminder", reminderTitle: "Payment Reminder",
    reminderDescription: "Send a reminder using the Invoice's current balance and due status.",
    reminderMessage: "Reminder message (optional)",
    reminderPlaceholder: "Leave blank to use Meetro's current balance and due-date wording.",
    reminderOnly: "Reminder only — this does not mark the Invoice paid or change its balance.",
    confirmReminder: "Send Reminder", sendingReminder: "Sending...",
    reminderSent: "Payment reminder sent. The Invoice balance was not changed.",
  },
  es: {
    title: "Facturas y pagos", summary: "Crea facturas desde trabajos completados y conserva la verdad del pago con cada trabajo.",
    ready: "Listo para facturar", drafts: "Borradores", waiting: "Esperando pago", paid: "Pagado",
    outstanding: "Pendiente", create: "Crear factura", invoice: "Factura", customer: "Cliente",
    completed: "Completado", approvedTotal: "Total aprobado", dueOnReceipt: "Vence al recibir",
    specificDate: "Fecha especifica", dueDate: "Fecha de vencimiento", customerNotes: "Notas para el cliente",
    terms: "Terminos de pago", reviewDraft: "Revisar borrador", send: "Enviar factura", confirmSend: "Confirmar envio",
    cancel: "Cancelar", recordPayment: "Registrar pago", amount: "Monto recibido", method: "Metodo de pago",
    receivedDate: "Fecha recibida", reference: "Referencia o nota", cash: "Efectivo", check: "Cheque",
    bankTransfer: "Transferencia bancaria", other: "Otro", balance: "Saldo", total: "Total", payments: "Historial de pagos",
    noPayments: "Aun no hay pagos registrados.", onlineUnavailable: "El pago en linea no esta disponible mediante Meetro para esta factura.",
    share: "Compartir PDF", email: "Enviar PDF", copy: "Copiar detalles", copied: "Detalles de la factura copiados.", pdfReady: "PDF de la factura listo.",
    noPublicLink: "Se comparten los detalles confirmados. No se crea un enlace publico.",
    unavailable: "Los detalles de la factura no estan disponibles.", empty: "Aun no hay facturas.",
    sent: "Factura enviada en Meetro.", recorded: "Pago registrado.", loading: "Cargando la verdad de la factura...",
    original: "Original", revised: "Revisada", additional: "Adicional", back: "Volver al Centro de Trabajo",
    backConversation: "Volver a la conversacion", reviewInvoice: "Revisar factura", invoiceReceived: "Factura recibida",
    sendReminder: "Enviar recordatorio", reminderTitle: "Recordatorio de pago",
    reminderDescription: "Envia un recordatorio usando el saldo y vencimiento actuales de la factura.",
    reminderMessage: "Mensaje del recordatorio (opcional)",
    reminderPlaceholder: "Dejalo en blanco para usar el saldo y vencimiento actuales de Meetro.",
    reminderOnly: "Solo es un recordatorio — no marca la factura como pagada ni cambia su saldo.",
    confirmReminder: "Enviar recordatorio", sendingReminder: "Enviando...",
    reminderSent: "Recordatorio de pago enviado. El saldo de la factura no cambio.",
  },
  fr: {
    title: "Factures et paiements", summary: "Creez des factures a partir des travaux termines et conservez la verite du paiement avec chaque travail.",
    ready: "Pret a facturer", drafts: "Brouillons", waiting: "En attente de paiement", paid: "Paye",
    outstanding: "Solde du", create: "Creer la facture", invoice: "Facture", customer: "Client",
    completed: "Termine", approvedTotal: "Total approuve", dueOnReceipt: "Du a reception",
    specificDate: "Date precise", dueDate: "Date d'echeance", customerNotes: "Notes au client",
    terms: "Conditions de paiement", reviewDraft: "Revoir le brouillon", send: "Envoyer la facture", confirmSend: "Confirmer l'envoi",
    cancel: "Annuler", recordPayment: "Enregistrer un paiement", amount: "Montant recu", method: "Mode de paiement",
    receivedDate: "Date de reception", reference: "Reference ou note", cash: "Especes", check: "Cheque",
    bankTransfer: "Virement bancaire", other: "Autre", balance: "Solde", total: "Total", payments: "Historique des paiements",
    noPayments: "Aucun paiement enregistre.", onlineUnavailable: "Le paiement en ligne n'est pas disponible dans Meetro pour cette facture.",
    share: "Partager le PDF", email: "Envoyer le PDF", copy: "Copier les details", copied: "Details de la facture copies.", pdfReady: "PDF de la facture pret.",
    noPublicLink: "Le partage utilise les details confirmes. Aucun lien public n'est cree.",
    unavailable: "Les details de la facture sont indisponibles.", empty: "Aucune facture pour le moment.",
    sent: "Facture envoyee dans Meetro.", recorded: "Paiement enregistre.", loading: "Chargement de la facture...",
    original: "Originale", revised: "Revisee", additional: "Supplementaire", back: "Retour au Centre de travail",
    backConversation: "Retour a la conversation", reviewInvoice: "Revoir la facture", invoiceReceived: "Facture recue",
    sendReminder: "Envoyer un rappel", reminderTitle: "Rappel de paiement",
    reminderDescription: "Envoyez un rappel avec le solde et l'echeance actuels de la facture.",
    reminderMessage: "Message du rappel (facultatif)",
    reminderPlaceholder: "Laissez vide pour utiliser le solde et l'echeance actuels de Meetro.",
    reminderOnly: "Rappel uniquement — cela ne marque pas la facture comme payee et ne modifie pas son solde.",
    confirmReminder: "Envoyer le rappel", sendingReminder: "Envoi...",
    reminderSent: "Rappel de paiement envoye. Le solde de la facture n'a pas change.",
  },
  "pt-BR": {
    title: "Faturas e pagamentos", summary: "Crie faturas a partir de trabalhos concluidos e preserve a verdade do pagamento com cada trabalho.",
    ready: "Pronto para faturar", drafts: "Rascunhos", waiting: "Aguardando pagamento", paid: "Pago",
    outstanding: "Pendente", create: "Criar fatura", invoice: "Fatura", customer: "Cliente",
    completed: "Concluido", approvedTotal: "Total aprovado", dueOnReceipt: "Vencimento no recebimento",
    specificDate: "Data especifica", dueDate: "Data de vencimento", customerNotes: "Notas ao cliente",
    terms: "Termos de pagamento", reviewDraft: "Revisar rascunho", send: "Enviar fatura", confirmSend: "Confirmar envio",
    cancel: "Cancelar", recordPayment: "Registrar pagamento", amount: "Valor recebido", method: "Forma de pagamento",
    receivedDate: "Data recebida", reference: "Referencia ou nota", cash: "Dinheiro", check: "Cheque",
    bankTransfer: "Transferencia bancaria", other: "Outro", balance: "Saldo", total: "Total", payments: "Historico de pagamentos",
    noPayments: "Nenhum pagamento registrado.", onlineUnavailable: "O pagamento online nao esta disponivel pelo Meetro para esta fatura.",
    share: "Compartilhar PDF", email: "Enviar PDF", copy: "Copiar detalhes", copied: "Detalhes da fatura copiados.", pdfReady: "PDF da fatura pronto.",
    noPublicLink: "O compartilhamento usa os detalhes confirmados. Nenhum link publico e criado.",
    unavailable: "Os detalhes da fatura estao indisponiveis.", empty: "Ainda nao ha faturas.",
    sent: "Fatura enviada no Meetro.", recorded: "Pagamento registrado.", loading: "Carregando a verdade da fatura...",
    original: "Original", revised: "Revisada", additional: "Adicional", back: "Voltar ao Centro de Trabalho",
    backConversation: "Voltar a conversa", reviewInvoice: "Revisar fatura", invoiceReceived: "Fatura recebida",
    sendReminder: "Enviar lembrete", reminderTitle: "Lembrete de pagamento",
    reminderDescription: "Envie um lembrete usando o saldo e o vencimento atuais da fatura.",
    reminderMessage: "Mensagem do lembrete (opcional)",
    reminderPlaceholder: "Deixe em branco para usar o saldo e o vencimento atuais do Meetro.",
    reminderOnly: "Apenas um lembrete — isso nao marca a fatura como paga nem altera o saldo.",
    confirmReminder: "Enviar lembrete", sendingReminder: "Enviando...",
    reminderSent: "Lembrete de pagamento enviado. O saldo da fatura nao foi alterado.",
  },
});

export function getInvoiceCopy(language = "en") {
  return COPY[language] || COPY.en;
}
