const COPY = Object.freeze({
  en: Object.freeze({
    completionReview: "Completion Review",
    completionPurpose: "Confirm the work record before finishing this Job.",
    work: "Work",
    completed: "Completed",
    outstandingItems: "Outstanding items",
    none: "None",
    customerUpdates: "Customer updates",
    upToDate: "Up to date",
    completeJob: "Complete Job",
    completing: "Completing...",
    confirmTitle: "Complete this Job?",
    confirmBody: "This records the operational Job as completed. Billing remains a separate next step.",
    confirm: "Yes, Complete Job",
    cancel: "Cancel",
    loading: "Loading completion details...",
    unavailable: "Completion details are temporarily unavailable.",
    retry: "Retry",
    notReady: "Finish the outstanding work before completing this Job.",
    commandFailed: "The Job could not be completed. Refresh and review the current work record.",
    workCompleted: "Work Completed",
    completedBody: "The operational Job is complete and its history is preserved.",
    readyToInvoice: "Ready to Invoice",
    history: "Job History",
    historyPurpose: "Review completed jobs and past work.",
    viewHistory: "View History",
    viewJob: "View Job",
    backToHistory: "Back to Job History",
    noHistory: "No completed jobs yet.",
    historyUnavailable: "Job History is temporarily unavailable.",
    completedJobs: "Completed Jobs",
    completedOn: "Completed",
    approvedAmount: "Approved amount",
    originalRequest: "Original request",
    preservedRecord: "Job record",
    preservedRecordBody: "Evaluation, findings, recommendations, approved Quotes, visits, and completed work remain preserved.",
    loadMore: "Load More",
    customerCompletionBody: "The professional recorded the approved work as completed.",
    messageProfessional: "Message Professional",
  }),
  es: Object.freeze({
    completionReview: "Revisión de finalización",
    completionPurpose: "Confirma el registro del trabajo antes de finalizar este trabajo.",
    work: "Trabajo",
    completed: "Completado",
    outstandingItems: "Pendientes",
    none: "Ninguno",
    customerUpdates: "Actualizaciones para el cliente",
    upToDate: "Al día",
    completeJob: "Completar trabajo",
    completing: "Completando...",
    confirmTitle: "¿Completar este trabajo?",
    confirmBody: "Esto registra el trabajo operativo como completado. La facturación sigue siendo un paso separado.",
    confirm: "Sí, completar trabajo",
    cancel: "Cancelar",
    loading: "Cargando detalles de finalización...",
    unavailable: "Los detalles de finalización no están disponibles temporalmente.",
    retry: "Reintentar",
    notReady: "Finaliza el trabajo pendiente antes de completar este trabajo.",
    commandFailed: "No se pudo completar el trabajo. Actualiza y revisa el registro actual.",
    workCompleted: "Trabajo completado",
    completedBody: "El trabajo operativo está completo y su historial está preservado.",
    readyToInvoice: "Listo para facturar",
    history: "Historial de trabajos",
    historyPurpose: "Revisa trabajos completados y trabajos anteriores.",
    viewHistory: "Ver historial",
    viewJob: "Ver trabajo",
    backToHistory: "Volver al historial",
    noHistory: "Aún no hay trabajos completados.",
    historyUnavailable: "El historial no está disponible temporalmente.",
    completedJobs: "Trabajos completados",
    completedOn: "Completado",
    approvedAmount: "Importe aprobado",
    originalRequest: "Solicitud original",
    preservedRecord: "Registro del trabajo",
    preservedRecordBody: "La evaluación, los hallazgos, las recomendaciones, las cotizaciones aprobadas, las visitas y el trabajo completado permanecen preservados.",
    loadMore: "Cargar más",
    customerCompletionBody: "El profesional registró el trabajo aprobado como completado.",
    messageProfessional: "Enviar mensaje al profesional",
  }),
  fr: Object.freeze({
    completionReview: "Vérification de l’achèvement",
    completionPurpose: "Confirmez le dossier de travail avant de terminer cette intervention.",
    work: "Travail",
    completed: "Terminé",
    outstandingItems: "Éléments en attente",
    none: "Aucun",
    customerUpdates: "Mises à jour client",
    upToDate: "À jour",
    completeJob: "Terminer l’intervention",
    completing: "Finalisation...",
    confirmTitle: "Terminer cette intervention ?",
    confirmBody: "Cela enregistre l’intervention comme terminée. La facturation reste une étape distincte.",
    confirm: "Oui, terminer",
    cancel: "Annuler",
    loading: "Chargement des détails d’achèvement...",
    unavailable: "Les détails d’achèvement sont temporairement indisponibles.",
    retry: "Réessayer",
    notReady: "Terminez le travail restant avant de clôturer cette intervention.",
    commandFailed: "L’intervention n’a pas pu être terminée. Actualisez et vérifiez le dossier actuel.",
    workCompleted: "Travail terminé",
    completedBody: "L’intervention est terminée et son historique est conservé.",
    readyToInvoice: "Prêt à facturer",
    history: "Historique des interventions",
    historyPurpose: "Consultez les interventions terminées et le travail passé.",
    viewHistory: "Voir l’historique",
    viewJob: "Voir l’intervention",
    backToHistory: "Retour à l’historique",
    noHistory: "Aucune intervention terminée pour le moment.",
    historyUnavailable: "L’historique est temporairement indisponible.",
    completedJobs: "Interventions terminées",
    completedOn: "Terminé",
    approvedAmount: "Montant approuvé",
    originalRequest: "Demande initiale",
    preservedRecord: "Dossier de l’intervention",
    preservedRecordBody: "L’évaluation, les constats, les recommandations, les devis approuvés, les visites et le travail terminé restent conservés.",
    loadMore: "Afficher plus",
    customerCompletionBody: "Le professionnel a enregistré le travail approuvé comme terminé.",
    messageProfessional: "Écrire au professionnel",
  }),
  "pt-BR": Object.freeze({
    completionReview: "Revisão de conclusão",
    completionPurpose: "Confirme o registro do trabalho antes de concluir este serviço.",
    work: "Trabalho",
    completed: "Concluído",
    outstandingItems: "Itens pendentes",
    none: "Nenhum",
    customerUpdates: "Atualizações para o cliente",
    upToDate: "Em dia",
    completeJob: "Concluir serviço",
    completing: "Concluindo...",
    confirmTitle: "Concluir este serviço?",
    confirmBody: "Isso registra o serviço operacional como concluído. O faturamento permanece uma etapa separada.",
    confirm: "Sim, concluir serviço",
    cancel: "Cancelar",
    loading: "Carregando detalhes da conclusão...",
    unavailable: "Os detalhes da conclusão estão temporariamente indisponíveis.",
    retry: "Tentar novamente",
    notReady: "Conclua o trabalho pendente antes de finalizar este serviço.",
    commandFailed: "Não foi possível concluir o serviço. Atualize e revise o registro atual.",
    workCompleted: "Trabalho concluído",
    completedBody: "O serviço operacional está concluído e seu histórico foi preservado.",
    readyToInvoice: "Pronto para faturar",
    history: "Histórico de serviços",
    historyPurpose: "Revise trabalhos concluídos e trabalhos anteriores.",
    viewHistory: "Ver histórico",
    viewJob: "Ver serviço",
    backToHistory: "Voltar ao histórico",
    noHistory: "Ainda não há serviços concluídos.",
    historyUnavailable: "O histórico está temporariamente indisponível.",
    completedJobs: "Serviços concluídos",
    completedOn: "Concluído",
    approvedAmount: "Valor aprovado",
    originalRequest: "Solicitação original",
    preservedRecord: "Registro do serviço",
    preservedRecordBody: "A avaliação, as constatações, as recomendações, os orçamentos aprovados, as visitas e o trabalho concluído permanecem preservados.",
    loadMore: "Carregar mais",
    customerCompletionBody: "O profissional registrou o trabalho aprovado como concluído.",
    messageProfessional: "Enviar mensagem ao profissional",
  }),
});

export function getJobCompletionCopy(language = "en") {
  return COPY[language] || COPY.en;
}

export const JOB_COMPLETION_LANGUAGES = Object.freeze(Object.keys(COPY));
