import { DEFERRED_TRANSLATION_KEYS } from "./deferredTranslationKeys.js";

export const CANONICAL_LANGUAGE_CODES = Object.freeze(["en", "es", "fr", "pt-BR"]);

export const FOUNDATION_CRITICAL_KEYS = Object.freeze([
  "account",
  "active",
  "available",
  "back",
  "business",
  "businessDashboard",
  "businessProfile",
  "businessTools",
  "cancel",
  "close",
  "communicationCenterTitle",
  "completed",
  "continue",
  "createAccount",
  "customers",
  "dashboard",
  "emailAddress",
  "emergency",
  "failed",
  "hiringCenter",
  "history",
  "home",
  "language",
  "loading",
  "login",
  "logout",
  "messages",
  "messagesSearchPlaceholder",
  "momentsYourMoments",
  "notifications",
  "operations",
  "password",
  "pending",
  "pleaseWait",
  "professional",
  "profile",
  "project",
  "returnHome",
  "retry",
  "save",
  "send",
  "serverError",
  "settings",
  "signIn",
  "somethingWentWrong",
  "teamMembers",
  "tryAgain",
  "unavailable",
  "work",
  "workCenterDashboardTitle",
]);

export const SHARED_INTERFACE_KEYS = Object.freeze([
  "navigationHome",
  "navigationWorkCenter",
  "navigationChat",
  "navigationMoments",
  "navigationProfile",
  "navigationHistory",
  "navigationCommunication",
  "navigationCommunity",
  "navigationDiscover",
  "navigationCurrentWork",
  "navigationHomeStory",
  "navigationBusinessHistory",
  "navigationOperations",
  "navigationProperties",
  "navigationRecords",
  "navigationRelationships",
  "navigationCustomers",
  "navigationProfileAccount",
  "navigationPrimaryDesktop",
  "navigationPrimaryMobile",
  "navigationCloseProfileMenu",
  "actionBack",
  "actionClose",
  "actionCancel",
  "actionContinue",
  "actionRetry",
  "actionTryAgain",
  "actionDone",
  "stateLoading",
  "stateSending",
  "stateSent",
  "stateFailed",
  "stateRetry",
  "stateSaving",
  "stateSaved",
  "statePending",
  "stateApproved",
  "stateRejected",
  "stateAvailable",
  "stateUnavailable",
  "stateActive",
  "stateInactive",
  "stateCompleted",
  "stateClosed",
  "stateEmpty",
  "stateUnauthorized",
  "errorBoundaryTitle",
  "errorBoundaryBody",
  "errorBoundaryReturnHome",
  "appLoadingMeetro",
  "appRestoringSession",
  "appUpdateAvailable",
  "appUpdateAvailableBody",
  "appUpdateNow",
  "appUpdating",
  "appUpdateLater",
  "appUpdateFailed",
  "companionLauncherLabel",
  "companionAskByVoice",
  "companionMicrophone",
  "companionListening",
  "companionVoiceUnavailable",
  "companionYouAsked",
  "companionCurrentScreen",
  "companionSuggestedNextStep",
  "companionReadAloud",
  "companionUnreadNotifications",
  "companionEmergencyTips",
  "companionShowMore",
  "companionShowLess",
  "companionFeedbackButton",
  "companionFeedbackCategory",
  "companionFeedbackNote",
  "companionFeedbackPlaceholder",
  "companionFeedbackSubmit",
  "companionFeedbackSaved",
  "companionFeedbackCount",
  "companionFeedbackCopy",
  "companionFeedbackCopied",
  "accountRoleHomeowner",
  "accountRoleProfessional",
  "accountRolePersonal",
  "accountRoleBusiness",
  "accountSwitchMode",
]);

const deferredSets = Object.fromEntries(
  CANONICAL_LANGUAGE_CODES.map((language) => [
    language,
    new Set(DEFERRED_TRANSLATION_KEYS[language] || []),
  ])
);

export function isDeferredTranslationKey(key, language) {
  return deferredSets[language]?.has(String(key || "")) || false;
}

export function getDeferredTranslationKeys(language) {
  return [...(DEFERRED_TRANSLATION_KEYS[language] || [])];
}
