export const professionalScheduleLanguage = Object.freeze({
  en: Object.freeze({
    professionalScheduleVisitHistory: "View Schedule History",
    professionalScheduleVisitHistoryLoading: "Loading schedule history…",
    professionalScheduleVisitHistoryUnavailable: "Schedule history is temporarily unavailable.",
    professionalScheduleVisitHistoryEmpty: "No schedule history has been recorded.",
    professionalScheduleHistoryProposed: "Visit proposed",
    professionalScheduleHistoryScheduleProposed: "New schedule proposed",
    professionalScheduleHistoryChangeRequested: "Schedule change requested",
    professionalScheduleHistoryUpdated: "Schedule updated",
    professionalScheduleHistoryConfirmed: "Visit confirmed",
    professionalScheduleHistoryExternalConfirmed: "External confirmation recorded",
    professionalScheduleHistoryCancelled: "Visit cancelled",
    professionalScheduleHistoryStarted: "Visit started",
    professionalScheduleHistoryCompleted: "Visit completed",
    professionalScheduleHistoryVersionSchedule: "Schedule at this step",
    professionalScheduleTitle: "Schedule",
    professionalScheduleNeedsScheduling: "Needs Scheduling",
    professionalScheduleUpcoming: "Upcoming",
    professionalScheduleWaiting: "Waiting on Customer",
    professionalScheduleChangeRequested: "Change Requested",
    professionalScheduleHistory: "History",
    professionalScheduleHistoryEmpty: "No completed or cancelled visits yet.",
    professionalScheduleViewHistory: "View History",
    professionalScheduleLoadMore: "Load More",
    professionalScheduleLoading: "Loading Schedule…",
    professionalScheduleUnavailable: "Schedule is temporarily unavailable.",
    professionalScheduleRetry: "Try Again",
    professionalScheduleEmpty: "No scheduled work yet.",
    professionalScheduleEmptyDetail: "Scheduled evaluations and approved work will appear here.",
    professionalScheduleReadyCount: "{count} ready to schedule",
    professionalScheduleWaitingCount: "{count} waiting on customer",
    professionalScheduleChangeCount: "{count} change requested",
    professionalScheduleUpcomingCount: "{count} upcoming",
    professionalScheduleScheduleEvaluation: "Schedule Evaluation",
    professionalScheduleScheduleWork: "Schedule Work",
    professionalScheduleDepositRequired: "Deposit required",
    professionalScheduleDepositRequiredDetail: "The required deposit must be satisfied before this work can be scheduled.",
    professionalScheduleEvaluationVisit: "Evaluation Visit",
    professionalScheduleApprovedWork: "Approved Work",
    professionalScheduleWaitingMessage: "Waiting for customer confirmation",
    professionalScheduleChangeMessage: "Customer requested another time",
    professionalScheduleReschedule: "Reschedule",
    professionalScheduleCancel: "Cancel Visit",
    professionalScheduleComplete: "Complete Visit",
    professionalScheduleCompleted: "Visit completed",
    professionalScheduleCancelled: "Visit cancelled",
    professionalScheduleViewJob: "View Job",
    professionalScheduleDate: "Date",
    professionalScheduleArrivalTime: "Arrival time",
    professionalScheduleStartTime: "Start time",
    professionalScheduleEndTime: "End time",
    professionalScheduleEndTimeOptional: "End time — optional",
    professionalScheduleTimeZone: "Timezone",
    professionalScheduleTimeZoneDisplay: "Times shown in {timeZone}",
    professionalScheduleLocalTime: "local time",
    professionalScheduleLocation: "Location",
    professionalScheduleCustomerLocation: "Customer service location",
    professionalScheduleRemote: "Remote",
    professionalScheduleSave: "Save Schedule",
    professionalScheduleCancelEdit: "Close",
    professionalScheduleSaving: "Saving…",
    professionalScheduleSaved: "Schedule updated.",
    professionalScheduleActivationFailed: "Scheduling could not be started. No visit was created.",
    professionalScheduleConflict: "This visit changed elsewhere. The latest schedule was loaded; review it before trying again.",
    professionalScheduleInvalidTime: "Choose a valid date, time, location, and optional end time.",
    professionalScheduleAppointmentOccurred: "The appointment occurred.",
    professionalScheduleServiceArea: "Service area",
    professionalScheduleExactLocation: "Service location",
    professionalScheduleRefreshWarning: "The latest refresh failed. Previously confirmed Schedule information is still shown.",
    professionalScheduleSendInMeetro: "Send in Meetro",
    professionalScheduleShare: "Share Schedule",
    professionalScheduleEmail: "Email Schedule",
    professionalScheduleSentInMeetro: "Schedule sent in Meetro.",
    professionalScheduleShared: "Schedule shared.",
    professionalScheduleCopied: "Schedule details copied.",
    professionalScheduleShareFailed: "The confirmed Schedule could not be shared.",
    professionalScheduleShareTitle: "{purpose} schedule",
    professionalScheduleShareHeading: "{purpose}",
    professionalScheduleShareDate: "Date: {date}",
    professionalScheduleShareTime: "Time: {time}",
    professionalScheduleShareLocation: "Location: {location}",
  }),
  es: Object.freeze({
    professionalScheduleVisitHistory: "Ver historial del horario",
    professionalScheduleVisitHistoryLoading: "Cargando historial del horario…",
    professionalScheduleVisitHistoryUnavailable: "El historial del horario no está disponible temporalmente.",
    professionalScheduleVisitHistoryEmpty: "No se ha registrado historial del horario.",
    professionalScheduleHistoryProposed: "Visita propuesta",
    professionalScheduleHistoryScheduleProposed: "Nuevo horario propuesto",
    professionalScheduleHistoryChangeRequested: "Cambio de horario solicitado",
    professionalScheduleHistoryUpdated: "Horario actualizado",
    professionalScheduleHistoryConfirmed: "Visita confirmada",
    professionalScheduleHistoryExternalConfirmed: "Confirmación externa registrada",
    professionalScheduleHistoryCancelled: "Visita cancelada",
    professionalScheduleHistoryStarted: "Visita iniciada",
    professionalScheduleHistoryCompleted: "Visita completada",
    professionalScheduleHistoryVersionSchedule: "Horario en este paso",
    professionalScheduleTitle: "Agenda",
    professionalScheduleNeedsScheduling: "Necesita programación",
    professionalScheduleUpcoming: "Próximas visitas",
    professionalScheduleWaiting: "Esperando al cliente",
    professionalScheduleChangeRequested: "Cambio solicitado",
    professionalScheduleHistory: "Historial",
    professionalScheduleHistoryEmpty: "Aún no hay visitas completadas o canceladas.",
    professionalScheduleViewHistory: "Ver historial",
    professionalScheduleLoadMore: "Cargar más",
    professionalScheduleLoading: "Cargando la agenda…",
    professionalScheduleUnavailable: "La agenda no está disponible temporalmente.",
    professionalScheduleRetry: "Intentar de nuevo",
    professionalScheduleEmpty: "Aún no hay trabajo programado.",
    professionalScheduleEmptyDetail: "Las evaluaciones y el trabajo aprobado aparecerán aquí.",
    professionalScheduleReadyCount: "{count} listo para programar",
    professionalScheduleWaitingCount: "{count} esperando al cliente",
    professionalScheduleChangeCount: "{count} cambio solicitado",
    professionalScheduleUpcomingCount: "{count} próximo",
    professionalScheduleScheduleEvaluation: "Programar evaluación",
    professionalScheduleScheduleWork: "Programar trabajo",
    professionalScheduleDepositRequired: "Depósito requerido",
    professionalScheduleDepositRequiredDetail: "El depósito requerido debe estar cubierto antes de programar este trabajo.",
    professionalScheduleEvaluationVisit: "Visita de evaluación",
    professionalScheduleApprovedWork: "Trabajo aprobado",
    professionalScheduleWaitingMessage: "Esperando la confirmación del cliente",
    professionalScheduleChangeMessage: "El cliente solicitó otro horario",
    professionalScheduleReschedule: "Reprogramar",
    professionalScheduleCancel: "Cancelar visita",
    professionalScheduleComplete: "Completar visita",
    professionalScheduleCompleted: "Visita completada",
    professionalScheduleCancelled: "Visita cancelada",
    professionalScheduleViewJob: "Ver trabajo",
    professionalScheduleDate: "Fecha",
    professionalScheduleArrivalTime: "Hora de llegada",
    professionalScheduleStartTime: "Hora de inicio",
    professionalScheduleEndTime: "Hora de finalización",
    professionalScheduleEndTimeOptional: "Hora de finalización — opcional",
    professionalScheduleTimeZone: "Zona horaria",
    professionalScheduleTimeZoneDisplay: "Horarios mostrados en {timeZone}",
    professionalScheduleLocalTime: "hora local",
    professionalScheduleLocation: "Ubicación",
    professionalScheduleCustomerLocation: "Ubicación de servicio del cliente",
    professionalScheduleRemote: "Remota",
    professionalScheduleSave: "Guardar horario",
    professionalScheduleCancelEdit: "Cerrar",
    professionalScheduleSaving: "Guardando…",
    professionalScheduleSaved: "Agenda actualizada.",
    professionalScheduleActivationFailed: "No se pudo iniciar la programación. No se creó ninguna visita.",
    professionalScheduleConflict: "Esta visita cambió en otro lugar. Se cargó la agenda más reciente; revísela antes de intentarlo de nuevo.",
    professionalScheduleInvalidTime: "Elija una fecha, hora, ubicación y hora de finalización opcional válidas.",
    professionalScheduleAppointmentOccurred: "La cita ocurrió.",
    professionalScheduleServiceArea: "Área de servicio",
    professionalScheduleExactLocation: "Ubicación del servicio",
    professionalScheduleRefreshWarning: "La actualización falló. Se sigue mostrando la agenda confirmada anteriormente.",
    professionalScheduleSendInMeetro: "Enviar en Meetro",
    professionalScheduleShare: "Compartir agenda",
    professionalScheduleEmail: "Enviar agenda por correo",
    professionalScheduleSentInMeetro: "Agenda enviada en Meetro.",
    professionalScheduleShared: "Agenda compartida.",
    professionalScheduleCopied: "Detalles de la agenda copiados.",
    professionalScheduleShareFailed: "No se pudo compartir la agenda confirmada.",
    professionalScheduleShareTitle: "Agenda de {purpose}",
    professionalScheduleShareHeading: "{purpose}",
    professionalScheduleShareDate: "Fecha: {date}",
    professionalScheduleShareTime: "Hora: {time}",
    professionalScheduleShareLocation: "Ubicación: {location}",
  }),
  fr: Object.freeze({
    professionalScheduleVisitHistory: "Voir l’historique de l’horaire",
    professionalScheduleVisitHistoryLoading: "Chargement de l’historique…",
    professionalScheduleVisitHistoryUnavailable: "L’historique de l’horaire est temporairement indisponible.",
    professionalScheduleVisitHistoryEmpty: "Aucun historique de l’horaire enregistré.",
    professionalScheduleHistoryProposed: "Visite proposée",
    professionalScheduleHistoryScheduleProposed: "Nouvel horaire proposé",
    professionalScheduleHistoryChangeRequested: "Modification d’horaire demandée",
    professionalScheduleHistoryUpdated: "Horaire mis à jour",
    professionalScheduleHistoryConfirmed: "Visite confirmée",
    professionalScheduleHistoryExternalConfirmed: "Confirmation externe enregistrée",
    professionalScheduleHistoryCancelled: "Visite annulée",
    professionalScheduleHistoryStarted: "Visite commencée",
    professionalScheduleHistoryCompleted: "Visite terminée",
    professionalScheduleHistoryVersionSchedule: "Horaire à cette étape",
    professionalScheduleTitle: "Horaire",
    professionalScheduleNeedsScheduling: "À planifier",
    professionalScheduleUpcoming: "À venir",
    professionalScheduleWaiting: "En attente du client",
    professionalScheduleChangeRequested: "Modification demandée",
    professionalScheduleHistory: "Historique",
    professionalScheduleHistoryEmpty: "Aucune visite terminée ou annulée pour le moment.",
    professionalScheduleViewHistory: "Voir l’historique",
    professionalScheduleLoadMore: "Charger plus",
    professionalScheduleLoading: "Chargement de l’horaire…",
    professionalScheduleUnavailable: "L’horaire est temporairement indisponible.",
    professionalScheduleRetry: "Réessayer",
    professionalScheduleEmpty: "Aucun travail planifié pour le moment.",
    professionalScheduleEmptyDetail: "Les évaluations et les travaux approuvés apparaîtront ici.",
    professionalScheduleReadyCount: "{count} prêt à planifier",
    professionalScheduleWaitingCount: "{count} en attente du client",
    professionalScheduleChangeCount: "{count} modification demandée",
    professionalScheduleUpcomingCount: "{count} à venir",
    professionalScheduleScheduleEvaluation: "Planifier l’évaluation",
    professionalScheduleScheduleWork: "Planifier les travaux",
    professionalScheduleDepositRequired: "Acompte requis",
    professionalScheduleDepositRequiredDetail: "L’acompte requis doit être réglé avant de pouvoir planifier ces travaux.",
    professionalScheduleEvaluationVisit: "Visite d’évaluation",
    professionalScheduleApprovedWork: "Travaux approuvés",
    professionalScheduleWaitingMessage: "En attente de la confirmation du client",
    professionalScheduleChangeMessage: "Le client a demandé un autre horaire",
    professionalScheduleReschedule: "Replanifier",
    professionalScheduleCancel: "Annuler la visite",
    professionalScheduleComplete: "Terminer la visite",
    professionalScheduleCompleted: "Visite terminée",
    professionalScheduleCancelled: "Visite annulée",
    professionalScheduleViewJob: "Voir le travail",
    professionalScheduleDate: "Date",
    professionalScheduleArrivalTime: "Heure d’arrivée",
    professionalScheduleStartTime: "Heure de début",
    professionalScheduleEndTime: "Heure de fin",
    professionalScheduleEndTimeOptional: "Heure de fin — facultative",
    professionalScheduleTimeZone: "Fuseau horaire",
    professionalScheduleTimeZoneDisplay: "Heures affichées en {timeZone}",
    professionalScheduleLocalTime: "heure locale",
    professionalScheduleLocation: "Lieu",
    professionalScheduleCustomerLocation: "Lieu de service du client",
    professionalScheduleRemote: "À distance",
    professionalScheduleSave: "Enregistrer l’horaire",
    professionalScheduleCancelEdit: "Fermer",
    professionalScheduleSaving: "Enregistrement…",
    professionalScheduleSaved: "Horaire mis à jour.",
    professionalScheduleActivationFailed: "La planification n’a pas pu démarrer. Aucune visite n’a été créée.",
    professionalScheduleConflict: "Cette visite a été modifiée ailleurs. Le dernier horaire a été chargé; vérifiez-le avant de réessayer.",
    professionalScheduleInvalidTime: "Choisissez une date, une heure, un lieu et une heure de fin facultative valides.",
    professionalScheduleAppointmentOccurred: "Le rendez-vous a eu lieu.",
    professionalScheduleServiceArea: "Zone de service",
    professionalScheduleExactLocation: "Lieu de service",
    professionalScheduleRefreshWarning: "L’actualisation a échoué. L’horaire précédemment confirmé reste affiché.",
    professionalScheduleSendInMeetro: "Envoyer dans Meetro",
    professionalScheduleShare: "Partager l’horaire",
    professionalScheduleEmail: "Envoyer l’horaire par courriel",
    professionalScheduleSentInMeetro: "Horaire envoyé dans Meetro.",
    professionalScheduleShared: "Horaire partagé.",
    professionalScheduleCopied: "Détails de l’horaire copiés.",
    professionalScheduleShareFailed: "L’horaire confirmé n’a pas pu être partagé.",
    professionalScheduleShareTitle: "Horaire — {purpose}",
    professionalScheduleShareHeading: "{purpose}",
    professionalScheduleShareDate: "Date : {date}",
    professionalScheduleShareTime: "Heure : {time}",
    professionalScheduleShareLocation: "Lieu : {location}",
  }),
  "pt-BR": Object.freeze({
    professionalScheduleVisitHistory: "Ver histórico do agendamento",
    professionalScheduleVisitHistoryLoading: "Carregando histórico do agendamento…",
    professionalScheduleVisitHistoryUnavailable: "O histórico do agendamento está temporariamente indisponível.",
    professionalScheduleVisitHistoryEmpty: "Nenhum histórico do agendamento foi registrado.",
    professionalScheduleHistoryProposed: "Visita proposta",
    professionalScheduleHistoryScheduleProposed: "Novo horário proposto",
    professionalScheduleHistoryChangeRequested: "Alteração de horário solicitada",
    professionalScheduleHistoryUpdated: "Horário atualizado",
    professionalScheduleHistoryConfirmed: "Visita confirmada",
    professionalScheduleHistoryExternalConfirmed: "Confirmação externa registrada",
    professionalScheduleHistoryCancelled: "Visita cancelada",
    professionalScheduleHistoryStarted: "Visita iniciada",
    professionalScheduleHistoryCompleted: "Visita concluída",
    professionalScheduleHistoryVersionSchedule: "Horário nesta etapa",
    professionalScheduleTitle: "Agenda",
    professionalScheduleNeedsScheduling: "Precisa de agendamento",
    professionalScheduleUpcoming: "Próximos",
    professionalScheduleWaiting: "Aguardando o cliente",
    professionalScheduleChangeRequested: "Alteração solicitada",
    professionalScheduleHistory: "Histórico",
    professionalScheduleHistoryEmpty: "Ainda não há visitas concluídas ou canceladas.",
    professionalScheduleViewHistory: "Ver histórico",
    professionalScheduleLoadMore: "Carregar mais",
    professionalScheduleLoading: "Carregando a agenda…",
    professionalScheduleUnavailable: "A agenda está temporariamente indisponível.",
    professionalScheduleRetry: "Tentar novamente",
    professionalScheduleEmpty: "Ainda não há trabalho agendado.",
    professionalScheduleEmptyDetail: "Avaliações e trabalhos aprovados aparecerão aqui.",
    professionalScheduleReadyCount: "{count} pronto para agendar",
    professionalScheduleWaitingCount: "{count} aguardando o cliente",
    professionalScheduleChangeCount: "{count} alteração solicitada",
    professionalScheduleUpcomingCount: "{count} próximo",
    professionalScheduleScheduleEvaluation: "Agendar avaliação",
    professionalScheduleScheduleWork: "Agendar trabalho",
    professionalScheduleDepositRequired: "Depósito necessário",
    professionalScheduleDepositRequiredDetail: "O depósito necessário deve ser pago antes de agendar este trabalho.",
    professionalScheduleEvaluationVisit: "Visita de avaliação",
    professionalScheduleApprovedWork: "Trabalho aprovado",
    professionalScheduleWaitingMessage: "Aguardando a confirmação do cliente",
    professionalScheduleChangeMessage: "O cliente solicitou outro horário",
    professionalScheduleReschedule: "Reagendar",
    professionalScheduleCancel: "Cancelar visita",
    professionalScheduleComplete: "Concluir visita",
    professionalScheduleCompleted: "Visita concluída",
    professionalScheduleCancelled: "Visita cancelada",
    professionalScheduleViewJob: "Ver trabalho",
    professionalScheduleDate: "Data",
    professionalScheduleArrivalTime: "Horário de chegada",
    professionalScheduleStartTime: "Hora de início",
    professionalScheduleEndTime: "Hora de término",
    professionalScheduleEndTimeOptional: "Hora de término — opcional",
    professionalScheduleTimeZone: "Fuso horário",
    professionalScheduleTimeZoneDisplay: "Horários exibidos em {timeZone}",
    professionalScheduleLocalTime: "horário local",
    professionalScheduleLocation: "Local",
    professionalScheduleCustomerLocation: "Local de atendimento do cliente",
    professionalScheduleRemote: "Remota",
    professionalScheduleSave: "Salvar agenda",
    professionalScheduleCancelEdit: "Fechar",
    professionalScheduleSaving: "Salvando…",
    professionalScheduleSaved: "Agenda atualizada.",
    professionalScheduleActivationFailed: "Não foi possível iniciar o agendamento. Nenhuma visita foi criada.",
    professionalScheduleConflict: "Esta visita mudou em outro lugar. A agenda mais recente foi carregada; revise-a antes de tentar novamente.",
    professionalScheduleInvalidTime: "Escolha uma data, horário, local e horário de término opcional válidos.",
    professionalScheduleAppointmentOccurred: "O compromisso ocorreu.",
    professionalScheduleServiceArea: "Área de atendimento",
    professionalScheduleExactLocation: "Local do serviço",
    professionalScheduleRefreshWarning: "A atualização falhou. A agenda confirmada anteriormente continua sendo exibida.",
    professionalScheduleSendInMeetro: "Enviar no Meetro",
    professionalScheduleShare: "Compartilhar agenda",
    professionalScheduleEmail: "Enviar agenda por e-mail",
    professionalScheduleSentInMeetro: "Agenda enviada no Meetro.",
    professionalScheduleShared: "Agenda compartilhada.",
    professionalScheduleCopied: "Detalhes da agenda copiados.",
    professionalScheduleShareFailed: "Não foi possível compartilhar a agenda confirmada.",
    professionalScheduleShareTitle: "Agenda de {purpose}",
    professionalScheduleShareHeading: "{purpose}",
    professionalScheduleShareDate: "Data: {date}",
    professionalScheduleShareTime: "Horário: {time}",
    professionalScheduleShareLocation: "Local: {location}",
  }),
});
