export const professionalScheduleLanguage = Object.freeze({
  en: Object.freeze({
    professionalScheduleTitle: "Schedule",
    professionalScheduleNeedsScheduling: "Needs Scheduling",
    professionalScheduleUpcoming: "Upcoming",
    professionalScheduleWaiting: "Waiting on Customer",
    professionalScheduleChangeRequested: "Change Requested",
    professionalScheduleHistory: "History",
    professionalScheduleHistoryEmpty: "No completed or cancelled visits yet.",
    professionalScheduleViewHistory: "View History",
    professionalScheduleLoadMore: "Load More",
    professionalScheduleLoading: "Loading Schedule…",
    professionalScheduleUnavailable: "Schedule is temporarily unavailable.",
    professionalScheduleRetry: "Try Again",
    professionalScheduleEmpty: "No scheduled work yet.",
    professionalScheduleEmptyDetail: "Scheduled evaluations and approved work will appear here.",
    professionalScheduleReadyCount: "{count} ready to schedule",
    professionalScheduleWaitingCount: "{count} waiting on customer",
    professionalScheduleChangeCount: "{count} change requested",
    professionalScheduleUpcomingCount: "{count} upcoming",
    professionalScheduleScheduleEvaluation: "Schedule Evaluation",
    professionalScheduleScheduleWork: "Schedule Work",
    professionalScheduleEvaluationVisit: "Evaluation Visit",
    professionalScheduleApprovedWork: "Approved Work",
    professionalScheduleWaitingMessage: "Waiting for customer confirmation",
    professionalScheduleChangeMessage: "Customer requested another time",
    professionalScheduleReschedule: "Reschedule",
    professionalScheduleCancel: "Cancel Visit",
    professionalScheduleComplete: "Complete Visit",
    professionalScheduleCompleted: "Visit completed",
    professionalScheduleCancelled: "Visit cancelled",
    professionalScheduleViewJob: "View Job",
    professionalScheduleDate: "Date",
    professionalScheduleStartTime: "Start time",
    professionalScheduleEndTime: "End time",
    professionalScheduleTimeZone: "Timezone",
    professionalScheduleLocation: "Location",
    professionalScheduleCustomerLocation: "Customer service location",
    professionalScheduleRemote: "Remote",
    professionalScheduleSave: "Save Schedule",
    professionalScheduleCancelEdit: "Close",
    professionalScheduleSaving: "Saving…",
    professionalScheduleSaved: "Schedule updated.",
    professionalScheduleActivationFailed: "Scheduling could not be started. No visit was created.",
    professionalScheduleConflict: "This visit changed elsewhere. The latest schedule was loaded; review it before trying again.",
    professionalScheduleInvalidTime: "Choose a valid start and end time.",
    professionalScheduleAppointmentOccurred: "The appointment occurred.",
    professionalScheduleServiceArea: "Service area",
    professionalScheduleExactLocation: "Service location",
    professionalScheduleRefreshWarning: "The latest refresh failed. Previously confirmed Schedule information is still shown.",
  }),
  es: Object.freeze({
    professionalScheduleTitle: "Agenda",
    professionalScheduleNeedsScheduling: "Necesita programación",
    professionalScheduleUpcoming: "Próximas visitas",
    professionalScheduleWaiting: "Esperando al cliente",
    professionalScheduleChangeRequested: "Cambio solicitado",
    professionalScheduleHistory: "Historial",
    professionalScheduleHistoryEmpty: "Aún no hay visitas completadas o canceladas.",
    professionalScheduleViewHistory: "Ver historial",
    professionalScheduleLoadMore: "Cargar más",
    professionalScheduleLoading: "Cargando la agenda…",
    professionalScheduleUnavailable: "La agenda no está disponible temporalmente.",
    professionalScheduleRetry: "Intentar de nuevo",
    professionalScheduleEmpty: "Aún no hay trabajo programado.",
    professionalScheduleEmptyDetail: "Las evaluaciones y el trabajo aprobado aparecerán aquí.",
    professionalScheduleReadyCount: "{count} listo para programar",
    professionalScheduleWaitingCount: "{count} esperando al cliente",
    professionalScheduleChangeCount: "{count} cambio solicitado",
    professionalScheduleUpcomingCount: "{count} próximo",
    professionalScheduleScheduleEvaluation: "Programar evaluación",
    professionalScheduleScheduleWork: "Programar trabajo",
    professionalScheduleEvaluationVisit: "Visita de evaluación",
    professionalScheduleApprovedWork: "Trabajo aprobado",
    professionalScheduleWaitingMessage: "Esperando la confirmación del cliente",
    professionalScheduleChangeMessage: "El cliente solicitó otro horario",
    professionalScheduleReschedule: "Reprogramar",
    professionalScheduleCancel: "Cancelar visita",
    professionalScheduleComplete: "Completar visita",
    professionalScheduleCompleted: "Visita completada",
    professionalScheduleCancelled: "Visita cancelada",
    professionalScheduleViewJob: "Ver trabajo",
    professionalScheduleDate: "Fecha",
    professionalScheduleStartTime: "Hora de inicio",
    professionalScheduleEndTime: "Hora de finalización",
    professionalScheduleTimeZone: "Zona horaria",
    professionalScheduleLocation: "Ubicación",
    professionalScheduleCustomerLocation: "Ubicación de servicio del cliente",
    professionalScheduleRemote: "Remota",
    professionalScheduleSave: "Guardar horario",
    professionalScheduleCancelEdit: "Cerrar",
    professionalScheduleSaving: "Guardando…",
    professionalScheduleSaved: "Agenda actualizada.",
    professionalScheduleActivationFailed: "No se pudo iniciar la programación. No se creó ninguna visita.",
    professionalScheduleConflict: "Esta visita cambió en otro lugar. Se cargó la agenda más reciente; revísela antes de intentarlo de nuevo.",
    professionalScheduleInvalidTime: "Elija una hora de inicio y finalización válidas.",
    professionalScheduleAppointmentOccurred: "La cita ocurrió.",
    professionalScheduleServiceArea: "Área de servicio",
    professionalScheduleExactLocation: "Ubicación del servicio",
    professionalScheduleRefreshWarning: "La actualización falló. Se sigue mostrando la agenda confirmada anteriormente.",
  }),
  fr: Object.freeze({
    professionalScheduleTitle: "Horaire",
    professionalScheduleNeedsScheduling: "À planifier",
    professionalScheduleUpcoming: "À venir",
    professionalScheduleWaiting: "En attente du client",
    professionalScheduleChangeRequested: "Modification demandée",
    professionalScheduleHistory: "Historique",
    professionalScheduleHistoryEmpty: "Aucune visite terminée ou annulée pour le moment.",
    professionalScheduleViewHistory: "Voir l’historique",
    professionalScheduleLoadMore: "Charger plus",
    professionalScheduleLoading: "Chargement de l’horaire…",
    professionalScheduleUnavailable: "L’horaire est temporairement indisponible.",
    professionalScheduleRetry: "Réessayer",
    professionalScheduleEmpty: "Aucun travail planifié pour le moment.",
    professionalScheduleEmptyDetail: "Les évaluations et les travaux approuvés apparaîtront ici.",
    professionalScheduleReadyCount: "{count} prêt à planifier",
    professionalScheduleWaitingCount: "{count} en attente du client",
    professionalScheduleChangeCount: "{count} modification demandée",
    professionalScheduleUpcomingCount: "{count} à venir",
    professionalScheduleScheduleEvaluation: "Planifier l’évaluation",
    professionalScheduleScheduleWork: "Planifier les travaux",
    professionalScheduleEvaluationVisit: "Visite d’évaluation",
    professionalScheduleApprovedWork: "Travaux approuvés",
    professionalScheduleWaitingMessage: "En attente de la confirmation du client",
    professionalScheduleChangeMessage: "Le client a demandé un autre horaire",
    professionalScheduleReschedule: "Replanifier",
    professionalScheduleCancel: "Annuler la visite",
    professionalScheduleComplete: "Terminer la visite",
    professionalScheduleCompleted: "Visite terminée",
    professionalScheduleCancelled: "Visite annulée",
    professionalScheduleViewJob: "Voir le travail",
    professionalScheduleDate: "Date",
    professionalScheduleStartTime: "Heure de début",
    professionalScheduleEndTime: "Heure de fin",
    professionalScheduleTimeZone: "Fuseau horaire",
    professionalScheduleLocation: "Lieu",
    professionalScheduleCustomerLocation: "Lieu de service du client",
    professionalScheduleRemote: "À distance",
    professionalScheduleSave: "Enregistrer l’horaire",
    professionalScheduleCancelEdit: "Fermer",
    professionalScheduleSaving: "Enregistrement…",
    professionalScheduleSaved: "Horaire mis à jour.",
    professionalScheduleActivationFailed: "La planification n’a pas pu démarrer. Aucune visite n’a été créée.",
    professionalScheduleConflict: "Cette visite a été modifiée ailleurs. Le dernier horaire a été chargé; vérifiez-le avant de réessayer.",
    professionalScheduleInvalidTime: "Choisissez des heures de début et de fin valides.",
    professionalScheduleAppointmentOccurred: "Le rendez-vous a eu lieu.",
    professionalScheduleServiceArea: "Zone de service",
    professionalScheduleExactLocation: "Lieu de service",
    professionalScheduleRefreshWarning: "L’actualisation a échoué. L’horaire précédemment confirmé reste affiché.",
  }),
  "pt-BR": Object.freeze({
    professionalScheduleTitle: "Agenda",
    professionalScheduleNeedsScheduling: "Precisa de agendamento",
    professionalScheduleUpcoming: "Próximos",
    professionalScheduleWaiting: "Aguardando o cliente",
    professionalScheduleChangeRequested: "Alteração solicitada",
    professionalScheduleHistory: "Histórico",
    professionalScheduleHistoryEmpty: "Ainda não há visitas concluídas ou canceladas.",
    professionalScheduleViewHistory: "Ver histórico",
    professionalScheduleLoadMore: "Carregar mais",
    professionalScheduleLoading: "Carregando a agenda…",
    professionalScheduleUnavailable: "A agenda está temporariamente indisponível.",
    professionalScheduleRetry: "Tentar novamente",
    professionalScheduleEmpty: "Ainda não há trabalho agendado.",
    professionalScheduleEmptyDetail: "Avaliações e trabalhos aprovados aparecerão aqui.",
    professionalScheduleReadyCount: "{count} pronto para agendar",
    professionalScheduleWaitingCount: "{count} aguardando o cliente",
    professionalScheduleChangeCount: "{count} alteração solicitada",
    professionalScheduleUpcomingCount: "{count} próximo",
    professionalScheduleScheduleEvaluation: "Agendar avaliação",
    professionalScheduleScheduleWork: "Agendar trabalho",
    professionalScheduleEvaluationVisit: "Visita de avaliação",
    professionalScheduleApprovedWork: "Trabalho aprovado",
    professionalScheduleWaitingMessage: "Aguardando a confirmação do cliente",
    professionalScheduleChangeMessage: "O cliente solicitou outro horário",
    professionalScheduleReschedule: "Reagendar",
    professionalScheduleCancel: "Cancelar visita",
    professionalScheduleComplete: "Concluir visita",
    professionalScheduleCompleted: "Visita concluída",
    professionalScheduleCancelled: "Visita cancelada",
    professionalScheduleViewJob: "Ver trabalho",
    professionalScheduleDate: "Data",
    professionalScheduleStartTime: "Hora de início",
    professionalScheduleEndTime: "Hora de término",
    professionalScheduleTimeZone: "Fuso horário",
    professionalScheduleLocation: "Local",
    professionalScheduleCustomerLocation: "Local de atendimento do cliente",
    professionalScheduleRemote: "Remota",
    professionalScheduleSave: "Salvar agenda",
    professionalScheduleCancelEdit: "Fechar",
    professionalScheduleSaving: "Salvando…",
    professionalScheduleSaved: "Agenda atualizada.",
    professionalScheduleActivationFailed: "Não foi possível iniciar o agendamento. Nenhuma visita foi criada.",
    professionalScheduleConflict: "Esta visita mudou em outro lugar. A agenda mais recente foi carregada; revise-a antes de tentar novamente.",
    professionalScheduleInvalidTime: "Escolha horários válidos de início e término.",
    professionalScheduleAppointmentOccurred: "O compromisso ocorreu.",
    professionalScheduleServiceArea: "Área de atendimento",
    professionalScheduleExactLocation: "Local do serviço",
    professionalScheduleRefreshWarning: "A atualização falhou. A agenda confirmada anteriormente continua sendo exibida.",
  }),
});
