const QUICK_QUOTE_CONVERSATION_COPY = Object.freeze({
  en: Object.freeze({
    createTitle: "Start Job Analysis",
    reviewTitle: "Job Analysis",
    entryGuidanceTitle: "Tell Meetro about the job in your own words.",
    entryGuidanceBody: "Meetro will privately analyze the job details and evidence. Nothing is turned into a Quote or shared with the customer at this stage.",
    reviewGuidanceTitle: "Review Meetro’s private job analysis.",
    reviewGuidanceBody: "Your details are enough to continue. Meetro’s suggestions are optional.",
    workingPrivately: "Working privately with Meetro",
    sourceInformation: "Professional job details",
    yourJobDetails: "Your Job Details",
    continueWithMyDetails: "Continue with My Details",
    useMeetroSuggestions: "Use Meetro Suggestions",
    optionalSuggestionsHelp: "Optional ideas to improve the estimate. Open a group and use only what helps.",
    canonicalJobRequired: "To continue to a governed Internal Estimate, open this work from an existing Job in Work Center. Meetro will not create a Job silently.",
    readyToContinue: "Ready to continue",
    connectToJob: "Connect this work to a Job before creating the Internal Estimate.",
    attachExistingJob: "Attach to Existing Job",
    createJob: "Create a Job",
    createJobComingNext: "Coming next",
    back: "Back",
    searchJobs: "Search eligible Jobs",
    searchJobsPlaceholder: "Job, customer, service, or city",
    loadingEligibleJobs: "Loading eligible Jobs…",
    noEligibleJobs: "No eligible active Jobs are available. Create a Job is coming next; Meetro will not create one silently.",
    jobConnectionFailed: "Meetro could not connect this work to that Job. Your Job authority may have changed.",
    jobListUnavailable: "Eligible Jobs are temporarily unavailable.",
    backToJobAnalysis: "Back to Job Analysis",
    privateInternal: "Private internal workflow",
    internalEstimateTitle: "Internal Estimate",
    quoteReviewTitle: "Quote Review",
    internalEstimateHelp: "Review the private working estimate for your business.",
    quoteReviewHelp: "Review the advisory Quote composition before creating a Draft Quote.",
    noQuotePricingPromotion: "Internal Estimate costs do not become customer Quote pricing.",
    connectedJob: "Connected Job",
    costsFromDetails: "Costs from your details",
    confirmPrivateCosts: "Confirm these private Internal Estimate amounts.",
    materialsTotal: "Materials total",
    laborTotal: "Labor total",
    confirmAmounts: "Confirm amounts",
    privateCostConfirmationHelp: "These are private internal costs. Customer Quote pricing will be confirmed separately.",
    categoryCostConflict: "More than one total was found for the same category. Update your job details so each category has one clear total.",
    analysisNeedsUpdating: "Analysis needs updating",
    analyzeUpdated: "Analyze Updated Information",
    backToJobDetails: "Back to Job Details",
    returnToJobAnalysis: "Return to Job Analysis",
    discardTitle: "Discard this job analysis?",
    discardBody: "Your private photos, conversation, reviewed solution, and materials list will be removed.",
    fullDetailsLabel: "Edit full quote details",
    fullDetailsGuidance: "Need more control? Open the full quote form to review or edit every field. Changes stay synced with your Quote Review.",
    assistant: "Ask Meetro",
    promptLabel: "Tell Meetro about the job",
    promptPlaceholder: "Describe the job, what the customer reported, what you observed, measurements, and anything Meetro should consider.",
    speak: "Speak",
    type: "Type",
    addPhotos: "Add Photos",
    photos: "Photos",
    noPhotos: "No photos added yet",
    remove: "Remove",
    removePhoto: (position) => `Remove photo ${position}`,
    photoDraftNotice: "Photos are private working evidence for this job analysis and are not attached to a customer Quote.",
    photoLimit: "Up to 5 photos can be reviewed in this private job analysis.",
    photoInvalid: "Some photos could not be added. Use JPEG, PNG, or WebP images up to 10 MB each.",
    photoUploading: "Uploading photos for private job analysis…",
    photoUploadFailed: "The selected photos could not be uploaded for private job analysis. Try again.",
    photoCleanupFailed: "Meetro could not confirm removal of this private analysis photo. Try again.",
    photoUnavailable: "Job Analysis photo upload is unavailable in this environment.",
    addAnotherPhoto: "Add another",
    photoChangedNotice: "Analysis needs updating because the job evidence changed.",
    photoAnalysisFailed: "Ask Meetro could not review these photos. Try again.",
    photoReviewFailed: "Meetro could not record that photo review decision. Try again.",
    photoEvidenceTitle: "Meetro job analysis",
    photoEvidenceHelp: "These suggestions are optional and remain private until you choose what to use.",
    analysisConversationTitle: "Analysis conversation",
    analysisConversationHelp: "Continue privately with Meetro. Follow-up messages stay in this Job Analysis and do not change the Quote.",
    professionalTurnLabel: "You",
    followUpLabel: "Continue the analysis",
    followUpPlaceholder: "Add a clarification, answer a question, or tell Meetro what to consider next.",
    sendFollowUp: "Send",
    continuingAnalysis: "Meetro is responding…",
    questionsForProfessional: "Questions to confirm",
    observed: "Observed",
    needsVerification: "Needs Verification",
    recommendedSolution: "Recommended Solution",
    thingsToVerify: "Things to Verify",
    repairSuggestions: "Repair Suggestions",
    materialSuggestions: "Material Suggestions",
    reviewedResultTitle: "Professional Review",
    reviewedResultHelp: "Only items you accepted or edited appear below. This remains private and does not change the Quote.",
    reviewedSolution: "Reviewed Solution",
    materialsList: "Materials List",
    reviewedResultLoadFailed: "Your review was saved, but Meetro could not refresh the reviewed result. Try again.",
    useSuggestion: "Use",
    editAndUse: "Edit & Use",
    dismissSuggestion: "Dismiss",
    saveAndUse: "Save & Use",
    photoAccepted: "Accepted after your review",
    photoEdited: "Edited and accepted after your review",
    photoRejected: "Dismissed",
    photoLimitations: "Photo limitations",
    photoStages: ["Review photos", "Separate observations", "Flag verification", "Suggest repairs", "Suggest materials"],
    prepare: "Analyze Job",
    working: "Meetro is working…",
    workingHelp: "Meetro is reviewing your private job details and evidence.",
    stages: ["Review job details", "Separate observations", "Flag verification", "Consider repair options", "Consider material categories"],
    customer: "Customer",
    scope: "Scope of Work",
    materials: "Materials",
    laborDuration: "Labor / Duration",
    paymentTerms: "Payment Terms",
    notes: "Notes / Conditions",
    total: "Total",
    notProvided: "Not added yet",
    noMaterials: "No materials added yet",
    materialsAllowance: "Materials allowance",
    askRevise: "Ask Meetro to revise",
    editDetails: "Edit details",
    previewPdf: "Preview PDF",
    sharePdf: "Share PDF",
    revisionTitle: "What should Meetro change?",
    revisionHelp: "Your explicit instruction updates only the matching parts of this draft.",
    revise: "Update Quote",
    cancel: "Cancel",
    backToReview: "Back to Quote Review",
    draftTruth: "Private job analysis only. Nothing here creates, saves, issues, or shares a Quote.",
    organizedFromInstructions: "Working privately with Meetro",
  }),
  es: Object.freeze({
    createTitle: "Iniciar análisis del trabajo",
    reviewTitle: "Análisis del trabajo",
    entryGuidanceTitle: "Cuéntale a Meetro sobre el trabajo con tus propias palabras.",
    entryGuidanceBody: "Meetro analizará en privado los detalles y la evidencia del trabajo. En esta etapa no se crea una cotización ni se comparte nada con el cliente.",
    reviewGuidanceTitle: "Revisa el análisis privado del trabajo de Meetro.",
    reviewGuidanceBody: "Tus detalles son suficientes para continuar. Las sugerencias de Meetro son opcionales.",
    workingPrivately: "Trabajando en privado con Meetro",
    sourceInformation: "Detalles profesionales del trabajo",
    yourJobDetails: "Tus detalles del trabajo",
    continueWithMyDetails: "Continuar con mis detalles",
    useMeetroSuggestions: "Usar sugerencias de Meetro",
    optionalSuggestionsHelp: "Ideas opcionales para mejorar el estimado. Abre un grupo y usa solo lo que te ayude.",
    canonicalJobRequired: "Para continuar a un estimado interno gobernado, abre este trabajo desde un trabajo existente en el Centro de trabajo. Meetro no creará un trabajo de forma silenciosa.",
    readyToContinue: "Listo para continuar",
    connectToJob: "Conecta este trabajo a un trabajo antes de crear el estimado interno.",
    attachExistingJob: "Conectar a un trabajo existente",
    createJob: "Crear un trabajo",
    createJobComingNext: "Próximamente",
    back: "Volver",
    searchJobs: "Buscar trabajos elegibles",
    searchJobsPlaceholder: "Trabajo, cliente, servicio o ciudad",
    loadingEligibleJobs: "Cargando trabajos elegibles…",
    noEligibleJobs: "No hay trabajos activos elegibles. Crear un trabajo estará disponible próximamente; Meetro no creará uno de forma silenciosa.",
    jobConnectionFailed: "Meetro no pudo conectar este trabajo. Es posible que tu autoridad haya cambiado.",
    jobListUnavailable: "Los trabajos elegibles no están disponibles temporalmente.",
    backToJobAnalysis: "Volver al Análisis del trabajo",
    privateInternal: "Flujo interno privado",
    internalEstimateTitle: "Estimado interno",
    quoteReviewTitle: "Revisión de cotización",
    internalEstimateHelp: "Revisa el estimado de trabajo privado para tu negocio.",
    quoteReviewHelp: "Revisa la composición consultiva antes de crear un borrador de cotización.",
    noQuotePricingPromotion: "Los costos del estimado interno no se convierten en precios de la cotización del cliente.",
    connectedJob: "Trabajo conectado",
    costsFromDetails: "Costos de tus detalles",
    confirmPrivateCosts: "Confirma estos importes privados del estimado interno.",
    materialsTotal: "Total de materiales",
    laborTotal: "Total de mano de obra",
    confirmAmounts: "Confirmar importes",
    privateCostConfirmationHelp: "Estos son costos internos privados. El precio de la cotización del cliente se confirmará por separado.",
    categoryCostConflict: "Se encontró más de un total para la misma categoría. Actualiza los detalles para dejar un solo total claro por categoría.",
    analysisNeedsUpdating: "El análisis necesita actualizarse",
    analyzeUpdated: "Analizar información actualizada",
    backToJobDetails: "Volver a Detalles del trabajo",
    returnToJobAnalysis: "Volver al Análisis del trabajo",
    discardTitle: "¿Descartar este análisis del trabajo?",
    discardBody: "Tus fotos privadas, conversación, solución revisada y lista de materiales serán eliminadas.",
    fullDetailsLabel: "Editar todos los detalles de la cotización",
    fullDetailsGuidance: "¿Necesitas más control? Abre el formulario completo para revisar o editar cada campo. Los cambios se mantienen sincronizados con la revisión.",
    assistant: "Ask Meetro",
    promptLabel: "Cuéntale a Meetro sobre el trabajo",
    promptPlaceholder: "Describe el trabajo, lo que informó el cliente, lo que observaste, las medidas y cualquier detalle que Meetro deba considerar.",
    speak: "Hablar",
    type: "Escribir",
    addPhotos: "Agregar fotos",
    photos: "Fotos",
    noPhotos: "Aún no hay fotos",
    remove: "Eliminar",
    removePhoto: (position) => `Eliminar foto ${position}`,
    photoDraftNotice: "Las fotos son evidencia privada de trabajo para este análisis y no se adjuntan a una cotización del cliente.",
    photoLimit: "Puedes revisar hasta 5 fotos en este análisis privado del trabajo.",
    photoInvalid: "Algunas fotos no se pudieron agregar. Usa imágenes JPEG, PNG o WebP de hasta 10 MB cada una.",
    photoUploading: "Subiendo fotos para el análisis privado del trabajo…",
    photoUploadFailed: "Las fotos seleccionadas no se pudieron subir para el análisis privado del trabajo. Inténtalo de nuevo.",
    photoCleanupFailed: "Meetro no pudo confirmar la eliminación de esta foto privada del análisis. Inténtalo de nuevo.",
    photoUnavailable: "La carga de fotos para el Análisis del trabajo no está disponible en este entorno.",
    addAnotherPhoto: "Agregar otra",
    photoChangedNotice: "El análisis necesita actualizarse porque cambió la evidencia del trabajo.",
    photoAnalysisFailed: "Ask Meetro no pudo revisar estas fotos. Inténtalo de nuevo.",
    photoReviewFailed: "Meetro no pudo registrar esa decisión de revisión. Inténtalo de nuevo.",
    photoEvidenceTitle: "Análisis del trabajo de Meetro",
    photoEvidenceHelp: "Estas sugerencias son opcionales y permanecen privadas hasta que elijas cuáles usar.",
    analysisConversationTitle: "Conversación del análisis",
    analysisConversationHelp: "Continúa en privado con Meetro. Los mensajes de seguimiento permanecen en este Análisis del trabajo y no cambian la cotización.",
    professionalTurnLabel: "Tú",
    followUpLabel: "Continuar el análisis",
    followUpPlaceholder: "Agrega una aclaración, responde una pregunta o dile a Meetro qué debe considerar después.",
    sendFollowUp: "Enviar",
    continuingAnalysis: "Meetro está respondiendo…",
    questionsForProfessional: "Preguntas por confirmar",
    observed: "Observado",
    needsVerification: "Necesita verificación",
    recommendedSolution: "Solución recomendada",
    thingsToVerify: "Aspectos por verificar",
    repairSuggestions: "Sugerencias de reparación",
    materialSuggestions: "Sugerencias de materiales",
    reviewedResultTitle: "Revisión profesional",
    reviewedResultHelp: "Solo los elementos que aceptaste o editaste aparecen abajo. Esto sigue siendo privado y no cambia la cotización.",
    reviewedSolution: "Solución revisada",
    materialsList: "Lista de materiales",
    reviewedResultLoadFailed: "Tu revisión se guardó, pero Meetro no pudo actualizar el resultado revisado. Inténtalo de nuevo.",
    useSuggestion: "Usar",
    editAndUse: "Editar y usar",
    dismissSuggestion: "Descartar",
    saveAndUse: "Guardar y usar",
    photoAccepted: "Aceptado después de tu revisión",
    photoEdited: "Editado y aceptado después de tu revisión",
    photoRejected: "Descartado",
    photoLimitations: "Limitaciones de la foto",
    photoStages: ["Revisar fotos", "Separar observaciones", "Marcar verificaciones", "Sugerir reparaciones", "Sugerir materiales"],
    prepare: "Analizar trabajo",
    working: "Meetro está trabajando…",
    workingHelp: "Meetro está revisando en privado los detalles y la evidencia del trabajo.",
    stages: ["Revisar detalles", "Separar observaciones", "Marcar verificaciones", "Considerar reparaciones", "Considerar materiales"],
    customer: "Cliente",
    scope: "Alcance del trabajo",
    materials: "Materiales",
    laborDuration: "Mano de obra / Duración",
    paymentTerms: "Términos de pago",
    notes: "Notas / Condiciones",
    total: "Total",
    notProvided: "Aún no agregado",
    noMaterials: "Aún no hay materiales",
    materialsAllowance: "Provisión de materiales",
    askRevise: "Pedir cambios a Meetro",
    editDetails: "Editar detalles",
    previewPdf: "Vista previa PDF",
    sharePdf: "Compartir PDF",
    revisionTitle: "¿Qué debe cambiar Meetro?",
    revisionHelp: "Tu instrucción explícita actualiza solo las partes correspondientes del borrador.",
    revise: "Actualizar cotización",
    cancel: "Cancelar",
    backToReview: "Volver a revisar la cotización",
    draftTruth: "Solo análisis privado del trabajo. Nada aquí crea, guarda, emite ni comparte una cotización.",
    organizedFromInstructions: "Trabajando en privado con Meetro",
  }),
  fr: Object.freeze({
    createTitle: "Démarrer l’analyse du travail",
    reviewTitle: "Analyse du travail",
    entryGuidanceTitle: "Décrivez le travail à Meetro avec vos propres mots.",
    entryGuidanceBody: "Meetro analysera en privé les détails et les éléments du travail. Aucun devis n’est créé ni partagé avec le client à ce stade.",
    reviewGuidanceTitle: "Vérifiez l’analyse privée du travail de Meetro.",
    reviewGuidanceBody: "Vos détails suffisent pour continuer. Les suggestions de Meetro sont facultatives.",
    workingPrivately: "Travail privé avec Meetro",
    sourceInformation: "Détails professionnels du travail",
    yourJobDetails: "Vos détails du travail",
    continueWithMyDetails: "Continuer avec mes détails",
    useMeetroSuggestions: "Utiliser les suggestions de Meetro",
    optionalSuggestionsHelp: "Des idées facultatives pour améliorer l’estimation. Ouvrez un groupe et utilisez seulement ce qui vous aide.",
    canonicalJobRequired: "Pour continuer vers une estimation interne gouvernée, ouvrez ce travail depuis un travail existant dans le Centre de travail. Meetro ne créera pas de travail silencieusement.",
    readyToContinue: "Prêt à continuer",
    connectToJob: "Reliez ce travail à un Job avant de créer l’estimation interne.",
    attachExistingJob: "Relier à un Job existant",
    createJob: "Créer un Job",
    createJobComingNext: "Bientôt disponible",
    back: "Retour",
    searchJobs: "Rechercher les Jobs admissibles",
    searchJobsPlaceholder: "Job, client, service ou ville",
    loadingEligibleJobs: "Chargement des Jobs admissibles…",
    noEligibleJobs: "Aucun Job actif admissible n’est disponible. La création d’un Job arrive bientôt; Meetro n’en créera pas silencieusement.",
    jobConnectionFailed: "Meetro n’a pas pu relier ce travail à ce Job. Votre autorité a peut-être changé.",
    jobListUnavailable: "Les Jobs admissibles sont temporairement indisponibles.",
    backToJobAnalysis: "Retour à l’analyse du travail",
    privateInternal: "Flux interne privé",
    internalEstimateTitle: "Estimation interne",
    quoteReviewTitle: "Révision du devis",
    internalEstimateHelp: "Vérifiez l’estimation de travail privée pour votre entreprise.",
    quoteReviewHelp: "Vérifiez la composition consultative avant de créer un brouillon de devis.",
    noQuotePricingPromotion: "Les coûts de l’estimation interne ne deviennent pas les prix du devis client.",
    connectedJob: "Job relié",
    costsFromDetails: "Coûts tirés de vos détails",
    confirmPrivateCosts: "Confirmez ces montants privés de l’estimation interne.",
    materialsTotal: "Total des matériaux",
    laborTotal: "Total de la main-d’œuvre",
    confirmAmounts: "Confirmer les montants",
    privateCostConfirmationHelp: "Ces coûts sont privés et internes. Le prix du devis client sera confirmé séparément.",
    categoryCostConflict: "Plusieurs totaux ont été trouvés pour la même catégorie. Modifiez les détails afin de conserver un seul total clair par catégorie.",
    analysisNeedsUpdating: "L’analyse doit être mise à jour",
    analyzeUpdated: "Analyser les informations mises à jour",
    backToJobDetails: "Retour aux détails du travail",
    returnToJobAnalysis: "Retour à l’analyse du travail",
    discardTitle: "Abandonner cette analyse du travail ?",
    discardBody: "Vos photos privées, la conversation, la solution révisée et la liste des matériaux seront supprimées.",
    fullDetailsLabel: "Modifier tous les détails du devis",
    fullDetailsGuidance: "Besoin de plus de contrôle ? Ouvrez le formulaire complet pour vérifier ou modifier chaque champ. Les changements restent synchronisés avec l’aperçu du devis.",
    assistant: "Ask Meetro",
    promptLabel: "Décrivez le travail à Meetro",
    promptPlaceholder: "Décrivez le travail, ce que le client a signalé, vos observations, les mesures et tout élément que Meetro doit prendre en compte.",
    speak: "Parler",
    type: "Écrire",
    addPhotos: "Ajouter des photos",
    photos: "Photos",
    noPhotos: "Aucune photo ajoutée",
    remove: "Supprimer",
    removePhoto: (position) => `Supprimer la photo ${position}`,
    photoDraftNotice: "Les photos sont des éléments de travail privés pour cette analyse et ne sont pas jointes à un devis client.",
    photoLimit: "Vous pouvez examiner jusqu’à 5 photos dans cette analyse privée du travail.",
    photoInvalid: "Certaines photos n’ont pas pu être ajoutées. Utilisez des images JPEG, PNG ou WebP de 10 Mo maximum chacune.",
    photoUploading: "Téléversement des photos pour l’analyse privée du travail…",
    photoUploadFailed: "Les photos sélectionnées n’ont pas pu être téléversées pour l’analyse privée du travail. Réessayez.",
    photoCleanupFailed: "Meetro n’a pas pu confirmer la suppression de cette photo privée de l’analyse. Réessayez.",
    photoUnavailable: "Le téléversement de photos pour l’Analyse du travail n’est pas disponible dans cet environnement.",
    addAnotherPhoto: "Ajouter une autre",
    photoChangedNotice: "L’analyse doit être mise à jour car les éléments du travail ont changé.",
    photoAnalysisFailed: "Ask Meetro n’a pas pu examiner ces photos. Réessayez.",
    photoReviewFailed: "Meetro n’a pas pu enregistrer cette décision de révision. Réessayez.",
    photoEvidenceTitle: "Analyse du travail Meetro",
    photoEvidenceHelp: "Ces suggestions sont facultatives et restent privées jusqu’à ce que vous choisissiez quoi utiliser.",
    analysisConversationTitle: "Conversation d’analyse",
    analysisConversationHelp: "Continuez en privé avec Meetro. Les messages de suivi restent dans cette Analyse du travail et ne modifient pas le devis.",
    professionalTurnLabel: "Vous",
    followUpLabel: "Continuer l’analyse",
    followUpPlaceholder: "Ajoutez une précision, répondez à une question ou indiquez à Meetro ce qu’il doit considérer ensuite.",
    sendFollowUp: "Envoyer",
    continuingAnalysis: "Meetro répond…",
    questionsForProfessional: "Questions à confirmer",
    observed: "Observé",
    needsVerification: "À vérifier",
    recommendedSolution: "Solution recommandée",
    thingsToVerify: "Éléments à vérifier",
    repairSuggestions: "Suggestions de réparation",
    materialSuggestions: "Suggestions de matériaux",
    reviewedResultTitle: "Révision professionnelle",
    reviewedResultHelp: "Seuls les éléments que vous avez acceptés ou modifiés apparaissent ci-dessous. Cela reste privé et ne modifie pas le devis.",
    reviewedSolution: "Solution révisée",
    materialsList: "Liste des matériaux",
    reviewedResultLoadFailed: "Votre révision a été enregistrée, mais Meetro n’a pas pu actualiser le résultat révisé. Réessayez.",
    useSuggestion: "Utiliser",
    editAndUse: "Modifier et utiliser",
    dismissSuggestion: "Ignorer",
    saveAndUse: "Enregistrer et utiliser",
    photoAccepted: "Accepté après votre révision",
    photoEdited: "Modifié et accepté après votre révision",
    photoRejected: "Ignoré",
    photoLimitations: "Limites de la photo",
    photoStages: ["Examiner les photos", "Séparer les observations", "Signaler les vérifications", "Suggérer les réparations", "Suggérer les matériaux"],
    prepare: "Analyser le travail",
    working: "Meetro travaille…",
    workingHelp: "Meetro examine en privé les détails et les éléments du travail.",
    stages: ["Examiner les détails", "Séparer les observations", "Signaler les vérifications", "Considérer les réparations", "Considérer les matériaux"],
    customer: "Client",
    scope: "Étendue des travaux",
    materials: "Matériaux",
    laborDuration: "Main-d'œuvre / Durée",
    paymentTerms: "Conditions de paiement",
    notes: "Notes / Conditions",
    total: "Total",
    notProvided: "Pas encore ajouté",
    noMaterials: "Aucun matériau ajouté",
    materialsAllowance: "Provision pour matériaux",
    askRevise: "Demander une révision à Meetro",
    editDetails: "Modifier les détails",
    previewPdf: "Aperçu PDF",
    sharePdf: "Partager le PDF",
    revisionTitle: "Que doit modifier Meetro ?",
    revisionHelp: "Votre instruction explicite ne met à jour que les parties correspondantes du brouillon.",
    revise: "Mettre à jour le devis",
    cancel: "Annuler",
    backToReview: "Retour à la révision du devis",
    draftTruth: "Analyse privée du travail uniquement. Rien ici ne crée, enregistre, émet ou partage un devis.",
    organizedFromInstructions: "Travail privé avec Meetro",
  }),
  "pt-BR": Object.freeze({
    createTitle: "Iniciar análise do trabalho",
    reviewTitle: "Análise do trabalho",
    entryGuidanceTitle: "Conte à Meetro sobre o trabalho com suas próprias palavras.",
    entryGuidanceBody: "O Meetro analisará em privado os detalhes e as evidências do trabalho. Nenhum orçamento é criado ou compartilhado com o cliente nesta etapa.",
    reviewGuidanceTitle: "Revise a análise privada do trabalho do Meetro.",
    reviewGuidanceBody: "Seus detalhes são suficientes para continuar. As sugestões do Meetro são opcionais.",
    workingPrivately: "Trabalhando em privado com Meetro",
    sourceInformation: "Detalhes profissionais do trabalho",
    yourJobDetails: "Seus detalhes do trabalho",
    continueWithMyDetails: "Continuar com meus detalhes",
    useMeetroSuggestions: "Usar sugestões do Meetro",
    optionalSuggestionsHelp: "Ideias opcionais para melhorar a estimativa. Abra um grupo e use apenas o que ajudar.",
    canonicalJobRequired: "Para continuar para uma estimativa interna governada, abra este trabalho a partir de um trabalho existente no Centro de trabalho. O Meetro não criará um trabalho silenciosamente.",
    readyToContinue: "Pronto para continuar",
    connectToJob: "Conecte este trabalho a um Job antes de criar a estimativa interna.",
    attachExistingJob: "Conectar a um Job existente",
    createJob: "Criar um Job",
    createJobComingNext: "Em breve",
    back: "Voltar",
    searchJobs: "Pesquisar Jobs elegíveis",
    searchJobsPlaceholder: "Job, cliente, serviço ou cidade",
    loadingEligibleJobs: "Carregando Jobs elegíveis…",
    noEligibleJobs: "Nenhum Job ativo elegível está disponível. Criar um Job estará disponível em breve; o Meetro não criará um silenciosamente.",
    jobConnectionFailed: "O Meetro não conseguiu conectar este trabalho ao Job. Sua autoridade pode ter mudado.",
    jobListUnavailable: "Os Jobs elegíveis estão temporariamente indisponíveis.",
    backToJobAnalysis: "Voltar à Análise do trabalho",
    privateInternal: "Fluxo interno privado",
    internalEstimateTitle: "Estimativa interna",
    quoteReviewTitle: "Revisão do orçamento",
    internalEstimateHelp: "Revise a estimativa de trabalho privada para sua empresa.",
    quoteReviewHelp: "Revise a composição consultiva antes de criar um rascunho de orçamento.",
    noQuotePricingPromotion: "Os custos da estimativa interna não se tornam preços do orçamento do cliente.",
    connectedJob: "Job conectado",
    costsFromDetails: "Custos dos seus detalhes",
    confirmPrivateCosts: "Confirme estes valores privados da estimativa interna.",
    materialsTotal: "Total de materiais",
    laborTotal: "Total de mão de obra",
    confirmAmounts: "Confirmar valores",
    privateCostConfirmationHelp: "Estes são custos internos privados. O preço do orçamento do cliente será confirmado separadamente.",
    categoryCostConflict: "Foi encontrado mais de um total para a mesma categoria. Atualize os detalhes para manter um único total claro por categoria.",
    analysisNeedsUpdating: "A análise precisa ser atualizada",
    analyzeUpdated: "Analisar informações atualizadas",
    backToJobDetails: "Voltar aos Detalhes do trabalho",
    returnToJobAnalysis: "Voltar à Análise do trabalho",
    discardTitle: "Descartar esta análise do trabalho?",
    discardBody: "Suas fotos privadas, conversa, solução revisada e lista de materiais serão removidas.",
    fullDetailsLabel: "Editar todos os detalhes do orçamento",
    fullDetailsGuidance: "Precisa de mais controle? Abra o formulário completo para revisar ou editar todos os campos. As alterações permanecem sincronizadas com a revisão.",
    assistant: "Ask Meetro",
    promptLabel: "Conte ao Meetro sobre o trabalho",
    promptPlaceholder: "Descreva o trabalho, o que o cliente informou, o que você observou, medidas e qualquer detalhe que o Meetro deva considerar.",
    speak: "Falar",
    type: "Digitar",
    addPhotos: "Adicionar fotos",
    photos: "Fotos",
    noPhotos: "Nenhuma foto adicionada",
    remove: "Remover",
    removePhoto: (position) => `Remover foto ${position}`,
    photoDraftNotice: "As fotos são evidências privadas de trabalho para esta análise e não são anexadas a um orçamento do cliente.",
    photoLimit: "Você pode revisar até 5 fotos nesta análise privada do trabalho.",
    photoInvalid: "Algumas fotos não puderam ser adicionadas. Use imagens JPEG, PNG ou WebP de até 10 MB cada.",
    photoUploading: "Enviando fotos para a análise privada do trabalho…",
    photoUploadFailed: "As fotos selecionadas não puderam ser enviadas para a análise privada do trabalho. Tente novamente.",
    photoCleanupFailed: "O Meetro não conseguiu confirmar a remoção desta foto privada da análise. Tente novamente.",
    photoUnavailable: "O envio de fotos para a Análise do trabalho não está disponível neste ambiente.",
    addAnotherPhoto: "Adicionar outra",
    photoChangedNotice: "A análise precisa ser atualizada porque as evidências do trabalho mudaram.",
    photoAnalysisFailed: "O Ask Meetro não conseguiu revisar estas fotos. Tente novamente.",
    photoReviewFailed: "O Meetro não conseguiu registrar essa decisão de revisão. Tente novamente.",
    photoEvidenceTitle: "Análise do trabalho do Meetro",
    photoEvidenceHelp: "Estas sugestões são opcionais e permanecem privadas até você escolher o que usar.",
    analysisConversationTitle: "Conversa da análise",
    analysisConversationHelp: "Continue em privado com o Meetro. As mensagens de acompanhamento permanecem nesta Análise do trabalho e não alteram o orçamento.",
    professionalTurnLabel: "Você",
    followUpLabel: "Continuar a análise",
    followUpPlaceholder: "Adicione um esclarecimento, responda a uma pergunta ou diga ao Meetro o que considerar em seguida.",
    sendFollowUp: "Enviar",
    continuingAnalysis: "O Meetro está respondendo…",
    questionsForProfessional: "Perguntas para confirmar",
    observed: "Observado",
    needsVerification: "Precisa de verificação",
    recommendedSolution: "Solução recomendada",
    thingsToVerify: "Itens para verificar",
    repairSuggestions: "Sugestões de reparo",
    materialSuggestions: "Sugestões de materiais",
    reviewedResultTitle: "Revisão profissional",
    reviewedResultHelp: "Apenas os itens que você aceitou ou editou aparecem abaixo. Isso permanece privado e não altera o orçamento.",
    reviewedSolution: "Solução revisada",
    materialsList: "Lista de materiais",
    reviewedResultLoadFailed: "Sua revisão foi salva, mas o Meetro não conseguiu atualizar o resultado revisado. Tente novamente.",
    useSuggestion: "Usar",
    editAndUse: "Editar e usar",
    dismissSuggestion: "Descartar",
    saveAndUse: "Salvar e usar",
    photoAccepted: "Aceito após sua revisão",
    photoEdited: "Editado e aceito após sua revisão",
    photoRejected: "Descartado",
    photoLimitations: "Limitações da foto",
    photoStages: ["Revisar fotos", "Separar observações", "Marcar verificações", "Sugerir reparos", "Sugerir materiais"],
    prepare: "Analisar trabalho",
    working: "O Meetro está trabalhando…",
    workingHelp: "O Meetro está revisando em privado os detalhes e as evidências do trabalho.",
    stages: ["Revisar detalhes", "Separar observações", "Marcar verificações", "Considerar reparos", "Considerar materiais"],
    customer: "Cliente",
    scope: "Escopo do trabalho",
    materials: "Materiais",
    laborDuration: "Mão de obra / Duração",
    paymentTerms: "Condições de pagamento",
    notes: "Notas / Condições",
    total: "Total",
    notProvided: "Ainda não adicionado",
    noMaterials: "Nenhum material adicionado",
    materialsAllowance: "Provisão de materiais",
    askRevise: "Pedir revisão ao Meetro",
    editDetails: "Editar detalhes",
    previewPdf: "Pré-visualizar PDF",
    sharePdf: "Compartilhar PDF",
    revisionTitle: "O que o Meetro deve alterar?",
    revisionHelp: "Sua instrução explícita atualiza somente as partes correspondentes deste rascunho.",
    revise: "Atualizar orçamento",
    cancel: "Cancelar",
    backToReview: "Voltar à revisão do orçamento",
    draftTruth: "Somente análise privada do trabalho. Nada aqui cria, salva, emite ou compartilha um orçamento.",
    organizedFromInstructions: "Trabalhando em privado com Meetro",
  }),
});

export const QUICK_QUOTE_CONVERSATION_LANGUAGES = Object.freeze([
  "en",
  "es",
  "fr",
  "pt-BR",
]);

export function getQuickQuoteConversationCopy(language = "en") {
  return QUICK_QUOTE_CONVERSATION_COPY[language] || QUICK_QUOTE_CONVERSATION_COPY.en;
}
