const QUICK_QUOTE_CONVERSATION_COPY = Object.freeze({
  en: Object.freeze({
    createTitle: "Create Quick Quote",
    reviewTitle: "Quote Ready for Review",
    entryGuidanceTitle: "Tell Meetro about the job in your own words.",
    entryGuidanceBody: "Meetro will organize the details and prepare your quote. You’ll review everything before anything is shared.",
    reviewGuidanceTitle: "Review what Meetro prepared.",
    reviewGuidanceBody: "Ask Meetro to make changes, edit any detail yourself, or preview the customer PDF.",
    fullDetailsLabel: "Edit full quote details",
    fullDetailsGuidance: "Need more control? Open the full quote form to review or edit every field. Changes stay synced with your Quote Review.",
    assistant: "Ask Meetro",
    promptLabel: "Tell Meetro about the job",
    promptPlaceholder: "Describe the work, timing, materials, and any price or deposit you have already decided.",
    speak: "Speak",
    type: "Type",
    addPhotos: "Add Photos",
    photos: "Photos",
    noPhotos: "No photos added yet",
    remove: "Remove",
    removePhoto: (position) => `Remove photo ${position}`,
    photoDraftNotice: "Photos are available for this draft review only and are not saved with the quote yet.",
    photoLimit: "Up to 5 photos can be reviewed in a Quick Quote draft.",
    photoInvalid: "Some photos could not be added. Use JPEG, PNG, or WebP images up to 10 MB each.",
    photoUploading: "Uploading photos for private draft review…",
    photoUploadFailed: "The selected photos could not be uploaded for private draft review. Try again.",
    photoCleanupFailed: "Meetro could not confirm removal of this private draft photo. Try again.",
    photoUnavailable: "Quick Quote photo upload is unavailable in this environment.",
    addAnotherPhoto: "Add another",
    photoChangedNotice: "Photos changed. Prepare the quote again so Ask Meetro can review the current photo set.",
    photoAnalysisFailed: "Ask Meetro could not review these photos. Try again.",
    photoReviewFailed: "Meetro could not record that photo review decision. Try again.",
    photoEvidenceTitle: "Ask Meetro photo review",
    photoEvidenceHelp: "These are private working-photo suggestions. Review each item before using it in the working quote.",
    observed: "Observed",
    needsVerification: "Needs Verification",
    repairSuggestions: "Repair Suggestions",
    materialSuggestions: "Material Suggestions",
    useSuggestion: "Use",
    editAndUse: "Edit & Use",
    dismissSuggestion: "Dismiss",
    saveAndUse: "Save & Use",
    photoAccepted: "Used after your review",
    photoEdited: "Edited and used after your review",
    photoRejected: "Dismissed",
    photoLimitations: "Photo limitations",
    photoStages: ["Review photos", "Separate observations", "Flag verification", "Suggest repairs", "Suggest materials"],
    prepare: "Prepare Quote",
    working: "Meetro is working…",
    workingHelp: "Your structured draft is being organized for review.",
    stages: ["Analyze notes", "Organize scope", "Capture labor", "Capture materials", "Draft terms"],
    customer: "Customer",
    scope: "Scope of Work",
    materials: "Materials",
    laborDuration: "Labor / Duration",
    paymentTerms: "Payment Terms",
    notes: "Notes / Conditions",
    total: "Total",
    notProvided: "Not added yet",
    noMaterials: "No materials added yet",
    materialsAllowance: "Materials allowance",
    askRevise: "Ask Meetro to revise",
    editDetails: "Edit details",
    previewPdf: "Preview PDF",
    sharePdf: "Share PDF",
    revisionTitle: "What should Meetro change?",
    revisionHelp: "Your explicit instruction updates only the matching parts of this draft.",
    revise: "Update Quote",
    cancel: "Cancel",
    backToReview: "Back to Quote Review",
    draftTruth: "Draft preview only. This Quick Quote is not saved, issued, delivered, or approved.",
    organizedFromInstructions: "Organized from your instructions",
  }),
  es: Object.freeze({
    createTitle: "Crear cotización rápida",
    reviewTitle: "Cotización lista para revisar",
    entryGuidanceTitle: "Cuéntale a Meetro sobre el trabajo con tus propias palabras.",
    entryGuidanceBody: "Meetro organizará los detalles y preparará tu cotización. Revisarás todo antes de compartirla.",
    reviewGuidanceTitle: "Revisa lo que Meetro preparó.",
    reviewGuidanceBody: "Pídele cambios a Meetro, edita cualquier detalle o revisa el PDF para el cliente.",
    fullDetailsLabel: "Editar todos los detalles de la cotización",
    fullDetailsGuidance: "¿Necesitas más control? Abre el formulario completo para revisar o editar cada campo. Los cambios se mantienen sincronizados con la revisión.",
    assistant: "Ask Meetro",
    promptLabel: "Cuéntale a Meetro sobre el trabajo",
    promptPlaceholder: "Describe el trabajo, el tiempo, los materiales y cualquier precio o depósito que ya decidiste.",
    speak: "Hablar",
    type: "Escribir",
    addPhotos: "Agregar fotos",
    photos: "Fotos",
    noPhotos: "Aún no hay fotos",
    remove: "Eliminar",
    removePhoto: (position) => `Eliminar foto ${position}`,
    photoDraftNotice: "Las fotos están disponibles solo para revisar este borrador y todavía no se guardan con la cotización.",
    photoLimit: "Puedes revisar hasta 5 fotos en un borrador de Cotización rápida.",
    photoInvalid: "Algunas fotos no se pudieron agregar. Usa imágenes JPEG, PNG o WebP de hasta 10 MB cada una.",
    photoUploading: "Subiendo fotos para la revisión privada del borrador…",
    photoUploadFailed: "Las fotos seleccionadas no se pudieron subir para la revisión privada del borrador. Inténtalo de nuevo.",
    photoCleanupFailed: "Meetro no pudo confirmar la eliminación de esta foto privada del borrador. Inténtalo de nuevo.",
    photoUnavailable: "La carga de fotos para Cotización rápida no está disponible en este entorno.",
    addAnotherPhoto: "Agregar otra",
    photoChangedNotice: "Las fotos cambiaron. Prepara la cotización otra vez para que Ask Meetro revise el conjunto actual.",
    photoAnalysisFailed: "Ask Meetro no pudo revisar estas fotos. Inténtalo de nuevo.",
    photoReviewFailed: "Meetro no pudo registrar esa decisión de revisión. Inténtalo de nuevo.",
    photoEvidenceTitle: "Revisión de fotos de Ask Meetro",
    photoEvidenceHelp: "Estas son sugerencias privadas basadas en fotos de trabajo. Revisa cada elemento antes de usarlo en la cotización.",
    observed: "Observado",
    needsVerification: "Necesita verificación",
    repairSuggestions: "Sugerencias de reparación",
    materialSuggestions: "Sugerencias de materiales",
    useSuggestion: "Usar",
    editAndUse: "Editar y usar",
    dismissSuggestion: "Descartar",
    saveAndUse: "Guardar y usar",
    photoAccepted: "Usado después de tu revisión",
    photoEdited: "Editado y usado después de tu revisión",
    photoRejected: "Descartado",
    photoLimitations: "Limitaciones de la foto",
    photoStages: ["Revisar fotos", "Separar observaciones", "Marcar verificaciones", "Sugerir reparaciones", "Sugerir materiales"],
    prepare: "Preparar cotización",
    working: "Meetro está trabajando…",
    workingHelp: "Tu borrador estructurado se está organizando para revisión.",
    stages: ["Analizar notas", "Organizar alcance", "Capturar mano de obra", "Capturar materiales", "Redactar términos"],
    customer: "Cliente",
    scope: "Alcance del trabajo",
    materials: "Materiales",
    laborDuration: "Mano de obra / Duración",
    paymentTerms: "Términos de pago",
    notes: "Notas / Condiciones",
    total: "Total",
    notProvided: "Aún no agregado",
    noMaterials: "Aún no hay materiales",
    materialsAllowance: "Provisión de materiales",
    askRevise: "Pedir cambios a Meetro",
    editDetails: "Editar detalles",
    previewPdf: "Vista previa PDF",
    sharePdf: "Compartir PDF",
    revisionTitle: "¿Qué debe cambiar Meetro?",
    revisionHelp: "Tu instrucción explícita actualiza solo las partes correspondientes del borrador.",
    revise: "Actualizar cotización",
    cancel: "Cancelar",
    backToReview: "Volver a revisar la cotización",
    draftTruth: "Solo vista previa. Esta cotización rápida no está guardada, emitida, entregada ni aprobada.",
    organizedFromInstructions: "Organizado según tus instrucciones",
  }),
  fr: Object.freeze({
    createTitle: "Créer un devis rapide",
    reviewTitle: "Devis prêt à réviser",
    entryGuidanceTitle: "Décrivez le travail à Meetro avec vos propres mots.",
    entryGuidanceBody: "Meetro organisera les détails et préparera votre devis. Vous vérifierez tout avant tout partage.",
    reviewGuidanceTitle: "Vérifiez ce que Meetro a préparé.",
    reviewGuidanceBody: "Demandez des modifications à Meetro, modifiez vous-même un détail ou prévisualisez le PDF client.",
    fullDetailsLabel: "Modifier tous les détails du devis",
    fullDetailsGuidance: "Besoin de plus de contrôle ? Ouvrez le formulaire complet pour vérifier ou modifier chaque champ. Les changements restent synchronisés avec l’aperçu du devis.",
    assistant: "Ask Meetro",
    promptLabel: "Décrivez le travail à Meetro",
    promptPlaceholder: "Décrivez les travaux, le délai, les matériaux et tout prix ou acompte déjà décidé.",
    speak: "Parler",
    type: "Écrire",
    addPhotos: "Ajouter des photos",
    photos: "Photos",
    noPhotos: "Aucune photo ajoutée",
    remove: "Supprimer",
    removePhoto: (position) => `Supprimer la photo ${position}`,
    photoDraftNotice: "Les photos sont disponibles uniquement pour la révision de ce brouillon et ne sont pas encore enregistrées avec le devis.",
    photoLimit: "Vous pouvez réviser jusqu’à 5 photos dans un brouillon de devis rapide.",
    photoInvalid: "Certaines photos n’ont pas pu être ajoutées. Utilisez des images JPEG, PNG ou WebP de 10 Mo maximum chacune.",
    photoUploading: "Téléversement des photos pour la révision privée du brouillon…",
    photoUploadFailed: "Les photos sélectionnées n’ont pas pu être téléversées pour la révision privée du brouillon. Réessayez.",
    photoCleanupFailed: "Meetro n’a pas pu confirmer la suppression de cette photo privée du brouillon. Réessayez.",
    photoUnavailable: "Le téléversement de photos pour le devis rapide n’est pas disponible dans cet environnement.",
    addAnotherPhoto: "Ajouter une autre",
    photoChangedNotice: "Les photos ont changé. Préparez de nouveau le devis afin qu’Ask Meetro examine l’ensemble actuel.",
    photoAnalysisFailed: "Ask Meetro n’a pas pu examiner ces photos. Réessayez.",
    photoReviewFailed: "Meetro n’a pas pu enregistrer cette décision de révision. Réessayez.",
    photoEvidenceTitle: "Révision photo Ask Meetro",
    photoEvidenceHelp: "Il s’agit de suggestions privées basées sur les photos de travail. Révisez chaque élément avant de l’utiliser dans le devis.",
    observed: "Observé",
    needsVerification: "À vérifier",
    repairSuggestions: "Suggestions de réparation",
    materialSuggestions: "Suggestions de matériaux",
    useSuggestion: "Utiliser",
    editAndUse: "Modifier et utiliser",
    dismissSuggestion: "Ignorer",
    saveAndUse: "Enregistrer et utiliser",
    photoAccepted: "Utilisé après votre révision",
    photoEdited: "Modifié et utilisé après votre révision",
    photoRejected: "Ignoré",
    photoLimitations: "Limites de la photo",
    photoStages: ["Examiner les photos", "Séparer les observations", "Signaler les vérifications", "Suggérer les réparations", "Suggérer les matériaux"],
    prepare: "Préparer le devis",
    working: "Meetro travaille…",
    workingHelp: "Votre brouillon structuré est organisé pour révision.",
    stages: ["Analyser les notes", "Organiser l'étendue", "Saisir la main-d'œuvre", "Saisir les matériaux", "Rédiger les conditions"],
    customer: "Client",
    scope: "Étendue des travaux",
    materials: "Matériaux",
    laborDuration: "Main-d'œuvre / Durée",
    paymentTerms: "Conditions de paiement",
    notes: "Notes / Conditions",
    total: "Total",
    notProvided: "Pas encore ajouté",
    noMaterials: "Aucun matériau ajouté",
    materialsAllowance: "Provision pour matériaux",
    askRevise: "Demander une révision à Meetro",
    editDetails: "Modifier les détails",
    previewPdf: "Aperçu PDF",
    sharePdf: "Partager le PDF",
    revisionTitle: "Que doit modifier Meetro ?",
    revisionHelp: "Votre instruction explicite ne met à jour que les parties correspondantes du brouillon.",
    revise: "Mettre à jour le devis",
    cancel: "Annuler",
    backToReview: "Retour à la révision du devis",
    draftTruth: "Aperçu uniquement. Ce devis rapide n'est ni enregistré, ni émis, ni livré, ni approuvé.",
    organizedFromInstructions: "Organisé selon vos instructions",
  }),
  "pt-BR": Object.freeze({
    createTitle: "Criar orçamento rápido",
    reviewTitle: "Orçamento pronto para revisão",
    entryGuidanceTitle: "Conte à Meetro sobre o trabalho com suas próprias palavras.",
    entryGuidanceBody: "A Meetro organizará os detalhes e preparará seu orçamento. Você revisará tudo antes de qualquer compartilhamento.",
    reviewGuidanceTitle: "Revise o que a Meetro preparou.",
    reviewGuidanceBody: "Peça alterações à Meetro, edite qualquer detalhe ou visualize o PDF do cliente.",
    fullDetailsLabel: "Editar todos os detalhes do orçamento",
    fullDetailsGuidance: "Precisa de mais controle? Abra o formulário completo para revisar ou editar todos os campos. As alterações permanecem sincronizadas com a revisão.",
    assistant: "Ask Meetro",
    promptLabel: "Conte ao Meetro sobre o trabalho",
    promptPlaceholder: "Descreva o trabalho, o prazo, os materiais e qualquer preço ou depósito já decidido.",
    speak: "Falar",
    type: "Digitar",
    addPhotos: "Adicionar fotos",
    photos: "Fotos",
    noPhotos: "Nenhuma foto adicionada",
    remove: "Remover",
    removePhoto: (position) => `Remover foto ${position}`,
    photoDraftNotice: "As fotos estão disponíveis apenas para revisar este rascunho e ainda não são salvas com o orçamento.",
    photoLimit: "Você pode revisar até 5 fotos em um rascunho de Orçamento rápido.",
    photoInvalid: "Algumas fotos não puderam ser adicionadas. Use imagens JPEG, PNG ou WebP de até 10 MB cada.",
    photoUploading: "Enviando fotos para a revisão privada do rascunho…",
    photoUploadFailed: "As fotos selecionadas não puderam ser enviadas para a revisão privada do rascunho. Tente novamente.",
    photoCleanupFailed: "O Meetro não conseguiu confirmar a remoção desta foto privada do rascunho. Tente novamente.",
    photoUnavailable: "O envio de fotos para o Orçamento rápido não está disponível neste ambiente.",
    addAnotherPhoto: "Adicionar outra",
    photoChangedNotice: "As fotos mudaram. Prepare o orçamento novamente para que o Ask Meetro revise o conjunto atual.",
    photoAnalysisFailed: "O Ask Meetro não conseguiu revisar estas fotos. Tente novamente.",
    photoReviewFailed: "O Meetro não conseguiu registrar essa decisão de revisão. Tente novamente.",
    photoEvidenceTitle: "Revisão de fotos do Ask Meetro",
    photoEvidenceHelp: "Estas são sugestões privadas baseadas nas fotos de trabalho. Revise cada item antes de usá-lo no orçamento.",
    observed: "Observado",
    needsVerification: "Precisa de verificação",
    repairSuggestions: "Sugestões de reparo",
    materialSuggestions: "Sugestões de materiais",
    useSuggestion: "Usar",
    editAndUse: "Editar e usar",
    dismissSuggestion: "Descartar",
    saveAndUse: "Salvar e usar",
    photoAccepted: "Usado após sua revisão",
    photoEdited: "Editado e usado após sua revisão",
    photoRejected: "Descartado",
    photoLimitations: "Limitações da foto",
    photoStages: ["Revisar fotos", "Separar observações", "Marcar verificações", "Sugerir reparos", "Sugerir materiais"],
    prepare: "Preparar orçamento",
    working: "O Meetro está trabalhando…",
    workingHelp: "Seu rascunho estruturado está sendo organizado para revisão.",
    stages: ["Analisar notas", "Organizar escopo", "Registrar mão de obra", "Registrar materiais", "Redigir termos"],
    customer: "Cliente",
    scope: "Escopo do trabalho",
    materials: "Materiais",
    laborDuration: "Mão de obra / Duração",
    paymentTerms: "Condições de pagamento",
    notes: "Notas / Condições",
    total: "Total",
    notProvided: "Ainda não adicionado",
    noMaterials: "Nenhum material adicionado",
    materialsAllowance: "Provisão de materiais",
    askRevise: "Pedir revisão ao Meetro",
    editDetails: "Editar detalhes",
    previewPdf: "Pré-visualizar PDF",
    sharePdf: "Compartilhar PDF",
    revisionTitle: "O que o Meetro deve alterar?",
    revisionHelp: "Sua instrução explícita atualiza somente as partes correspondentes deste rascunho.",
    revise: "Atualizar orçamento",
    cancel: "Cancelar",
    backToReview: "Voltar à revisão do orçamento",
    draftTruth: "Somente prévia. Este orçamento rápido não foi salvo, emitido, entregue nem aprovado.",
    organizedFromInstructions: "Organizado conforme suas instruções",
  }),
});

export const QUICK_QUOTE_CONVERSATION_LANGUAGES = Object.freeze([
  "en",
  "es",
  "fr",
  "pt-BR",
]);

export function getQuickQuoteConversationCopy(language = "en") {
  return QUICK_QUOTE_CONVERSATION_COPY[language] || QUICK_QUOTE_CONVERSATION_COPY.en;
}
