const COPY = Object.freeze({
  en: Object.freeze({
    workPlan: "Work Plan",
    workspaceEyebrow: "Approved work",
    workspacePurpose: "Organize and complete the work approved for this Job.",
    cardPurpose: "Track approved work and what still needs attention.",
    viewWorkPlan: "View Work Plan",
    backToWorkCenter: "Back to Work Center",
    workItems: "Work Items",
    workAreas: "Work areas",
    completed: "Completed",
    remaining: "Remaining",
    needsAttention: "Needs Attention",
    readyToStart: "Ready to Start",
    inProgress: "In Progress",
    readyForCompletionReview: "Ready for Completion Review",
    readyForCompletionReviewBody:
      "The approved work is complete and ready for the next review. This does not close the Job.",
    loading: "Loading Work Plan...",
    unavailable: "The Work Plan is temporarily unavailable.",
    retry: "Retry",
    noApprovedWork: "No approved work yet.",
    addWorkItem: "Add Work Item",
    workItemDescription: "Work item description",
    startWork: "Start Work",
    updateWork: "Update Work",
    markComplete: "Mark Complete",
    completeWorkArea: "Complete Work Area",
    addUpdate: "Add Update",
    customerUpdate: "Customer Update",
    customerUpdateHint: "Share this update in the customer's Project Journey.",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving...",
    blockers: "What needs attention",
    progressUpdates: "Progress Updates",
    noUpdates: "No progress updates yet.",
    openJob: "Open Work Plan",
    jobCount: "{count} Jobs",
    itemCount: "{count} work items",
    completedCount: "{count} completed",
    remainingCount: "{count} remaining",
    summaryProgress: "{completed} of {total} work items completed",
    customerPurpose: "See what is underway, what is complete, and what remains.",
    customerNoProgress: "No customer updates have been shared yet.",
    commandFailed: "That Work Plan action could not be completed. Refresh and try again.",
  }),
  es: Object.freeze({
    workPlan: "Plan de trabajo",
    workspaceEyebrow: "Trabajo aprobado",
    workspacePurpose: "Organiza y completa el trabajo aprobado para este trabajo.",
    cardPurpose: "Sigue el trabajo aprobado y lo que aun requiere atencion.",
    viewWorkPlan: "Ver plan de trabajo",
    backToWorkCenter: "Volver al Centro de trabajo",
    workItems: "Tareas",
    workAreas: "Areas de trabajo",
    completed: "Completado",
    remaining: "Restante",
    needsAttention: "Requiere atencion",
    readyToStart: "Listo para comenzar",
    inProgress: "En progreso",
    readyForCompletionReview: "Listo para revision de finalizacion",
    readyForCompletionReviewBody:
      "El trabajo aprobado esta completo y listo para la proxima revision. Esto no cierra el trabajo.",
    loading: "Cargando plan de trabajo...",
    unavailable: "El plan de trabajo no esta disponible temporalmente.",
    retry: "Reintentar",
    noApprovedWork: "Aun no hay trabajo aprobado.",
    addWorkItem: "Agregar tarea",
    workItemDescription: "Descripcion de la tarea",
    startWork: "Comenzar trabajo",
    updateWork: "Actualizar trabajo",
    markComplete: "Marcar como completado",
    completeWorkArea: "Completar area de trabajo",
    addUpdate: "Agregar actualizacion",
    customerUpdate: "Actualizacion para el cliente",
    customerUpdateHint: "Comparte esta actualizacion en el recorrido del proyecto del cliente.",
    save: "Guardar",
    cancel: "Cancelar",
    saving: "Guardando...",
    blockers: "Lo que requiere atencion",
    progressUpdates: "Actualizaciones de progreso",
    noUpdates: "Aun no hay actualizaciones de progreso.",
    openJob: "Abrir plan de trabajo",
    jobCount: "{count} trabajos",
    itemCount: "{count} tareas",
    completedCount: "{count} completadas",
    remainingCount: "{count} restantes",
    summaryProgress: "{completed} de {total} tareas completadas",
    customerPurpose: "Consulta lo que esta en curso, lo completado y lo pendiente.",
    customerNoProgress: "Aun no se compartieron actualizaciones con el cliente.",
    commandFailed: "No se pudo completar esa accion. Actualiza e intentalo de nuevo.",
  }),
  fr: Object.freeze({
    workPlan: "Plan de travail",
    workspaceEyebrow: "Travail approuve",
    workspacePurpose: "Organisez et terminez le travail approuve pour ce chantier.",
    cardPurpose: "Suivez le travail approuve et ce qui demande encore votre attention.",
    viewWorkPlan: "Voir le plan de travail",
    backToWorkCenter: "Retour au Centre de travail",
    workItems: "Taches",
    workAreas: "Zones de travail",
    completed: "Termine",
    remaining: "Restant",
    needsAttention: "Attention requise",
    readyToStart: "Pret a commencer",
    inProgress: "En cours",
    readyForCompletionReview: "Pret pour la revision de fin",
    readyForCompletionReviewBody:
      "Le travail approuve est termine et pret pour la prochaine revision. Cela ne cloture pas le chantier.",
    loading: "Chargement du plan de travail...",
    unavailable: "Le plan de travail est temporairement indisponible.",
    retry: "Reessayer",
    noApprovedWork: "Aucun travail approuve pour le moment.",
    addWorkItem: "Ajouter une tache",
    workItemDescription: "Description de la tache",
    startWork: "Commencer le travail",
    updateWork: "Mettre a jour le travail",
    markComplete: "Marquer comme termine",
    completeWorkArea: "Terminer la zone de travail",
    addUpdate: "Ajouter une mise a jour",
    customerUpdate: "Mise a jour client",
    customerUpdateHint: "Partagez cette mise a jour dans le parcours du projet client.",
    save: "Enregistrer",
    cancel: "Annuler",
    saving: "Enregistrement...",
    blockers: "Ce qui demande de l'attention",
    progressUpdates: "Mises a jour de progression",
    noUpdates: "Aucune mise a jour de progression.",
    openJob: "Ouvrir le plan de travail",
    jobCount: "{count} chantiers",
    itemCount: "{count} taches",
    completedCount: "{count} terminees",
    remainingCount: "{count} restantes",
    summaryProgress: "{completed} sur {total} taches terminees",
    customerPurpose: "Voyez ce qui est en cours, termine et restant.",
    customerNoProgress: "Aucune mise a jour client n'a encore ete partagee.",
    commandFailed: "Cette action n'a pas pu etre terminee. Actualisez et reessayez.",
  }),
  "pt-BR": Object.freeze({
    workPlan: "Plano de trabalho",
    workspaceEyebrow: "Trabalho aprovado",
    workspacePurpose: "Organize e conclua o trabalho aprovado para este servico.",
    cardPurpose: "Acompanhe o trabalho aprovado e o que ainda precisa de atencao.",
    viewWorkPlan: "Ver plano de trabalho",
    backToWorkCenter: "Voltar ao Centro de trabalho",
    workItems: "Itens de trabalho",
    workAreas: "Areas de trabalho",
    completed: "Concluido",
    remaining: "Restante",
    needsAttention: "Precisa de atencao",
    readyToStart: "Pronto para iniciar",
    inProgress: "Em andamento",
    readyForCompletionReview: "Pronto para revisao de conclusao",
    readyForCompletionReviewBody:
      "O trabalho aprovado foi concluido e esta pronto para a proxima revisao. Isso nao encerra o servico.",
    loading: "Carregando plano de trabalho...",
    unavailable: "O plano de trabalho esta temporariamente indisponivel.",
    retry: "Tentar novamente",
    noApprovedWork: "Nenhum trabalho aprovado ainda.",
    addWorkItem: "Adicionar item de trabalho",
    workItemDescription: "Descricao do item de trabalho",
    startWork: "Iniciar trabalho",
    updateWork: "Atualizar trabalho",
    markComplete: "Marcar como concluido",
    completeWorkArea: "Concluir area de trabalho",
    addUpdate: "Adicionar atualizacao",
    customerUpdate: "Atualizacao para o cliente",
    customerUpdateHint: "Compartilhe esta atualizacao na Jornada do Projeto do cliente.",
    save: "Salvar",
    cancel: "Cancelar",
    saving: "Salvando...",
    blockers: "O que precisa de atencao",
    progressUpdates: "Atualizacoes de progresso",
    noUpdates: "Ainda nao ha atualizacoes de progresso.",
    openJob: "Abrir plano de trabalho",
    jobCount: "{count} servicos",
    itemCount: "{count} itens de trabalho",
    completedCount: "{count} concluidos",
    remainingCount: "{count} restantes",
    summaryProgress: "{completed} de {total} itens concluidos",
    customerPurpose: "Veja o que esta em andamento, concluido e pendente.",
    customerNoProgress: "Nenhuma atualizacao foi compartilhada com o cliente.",
    commandFailed: "Nao foi possivel concluir essa acao. Atualize e tente novamente.",
  }),
});

function interpolate(value, variables = {}) {
  return Object.entries(variables).reduce(
    (result, [key, replacement]) =>
      result.replaceAll(`{${key}}`, String(replacement)),
    value
  );
}

export function getWorkPlanCopy(language = "en") {
  const locale = COPY[language] ? language : "en";
  const copy = COPY[locale];
  return Object.freeze({
    ...copy,
    format(key, variables) {
      return interpolate(copy[key] || COPY.en[key] || key, variables);
    },
  });
}

export const WORK_PLAN_LANGUAGES = Object.freeze(Object.keys(COPY));
