const COPY = Object.freeze({
  en: Object.freeze({
    title: "Materials & Preparation", eyebrow: "Approved-work planning",
    purpose: "Plan materials, tools, equipment, and preparation for this Job.",
    loading: "Loading Materials & Preparation...", unavailable: "Materials & Preparation is temporarily unavailable.",
    retry: "Retry", emptyTitle: "No Materials & Preparation plan yet",
    emptyBody: "Create the canonical plan from the approved customer decision. Viewing this section does not create a plan.",
    createPlan: "Create plan", creating: "Creating...", commandFailed: "That action could not be completed. Refresh and try again.",
    planning: "Planning", acquisition: "Acquisition", preparation: "Preparation", deposit: "Deposit",
    requiredReady: "Required items ready", customerPending: "Customer item pending", blocked: "Needs attention",
    itemCount: "Plan items", purchaseTotal: "Recorded internal purchase cost", version: "Version",
    depositLocked: "Committed actions are locked until the canonical deposit status is satisfied or no deposit is required.",
    depositOpen: "Committed actions are available under the current canonical deposit status.",
    workStartNotice: "Required-for-work-start is planning information here. This screen does not enforce Work start.",
    editPlan: "Edit plan", closeEditor: "Close editor", savePlan: "Save plan", saving: "Saving...",
    planningState: "Planning state", workStartPolicy: "Work-start policy", internalNotes: "Internal notes",
    none: "None", requiredItemsReady: "Required items ready", addItem: "Add plan item", remove: "Remove",
    description: "Description", kind: "Kind", quantity: "Quantity", unit: "Unit", provider: "Provided by",
    business: "Business", customer: "Customer", visibility: "Visibility", businessOnly: "Business only",
    customerVisible: "Customer visible", requiredForStart: "Required for Work start", estimatedCost: "Estimated internal cost",
    currency: "Currency", material: "Material", tool: "Tool", equipment: "Equipment", preparationTask: "Preparation task",
    sourceAccepted: "Accepted quote item", sourceElaboration: "Plan elaboration", commercialTreatment: "Commercial treatment",
    included: "Included in accepted total", notBillable: "Not customer billable", customerSupplied: "Customer supplied",
    approvalRequired: "Approval required", separatelyAccepted: "Separately accepted", allowance: "Allowance",
    acquisitionState: "Acquisition", preparationState: "Preparation", readyForStart: "Ready for Work start",
    purchaseEvidence: "Purchase evidence", records: "records", purchased: "Purchased", partiallyPurchased: "Partially purchased",
    ready: "Ready", notStarted: "Not started", inProgress: "In progress", customerItemPendingState: "Customer item pending",
    recordPurchase: "Record purchase", allocateInventory: "Allocate inventory", markReceived: "Mark received",
    markStaged: "Mark staged", markToolReady: "Mark tool ready", markEquipmentReady: "Mark equipment ready",
    prepStarted: "Preparation started", prepReady: "Preparation ready", prepBlocked: "Preparation blocked",
    purchaseTitle: "Record material purchase", vendor: "Vendor", purchasedAt: "Purchased at",
    externalReference: "External reference", internalCost: "Internal purchase cost", record: "Record", cancel: "Cancel",
    note: "Internal note", blockedReason: "Describe what is blocking preparation.", confirmBlocked: "Record blocker",
    noItems: "No plan items yet.", privateCosts: "Internal cost details are business-only.", refreshed: "Canonical status refreshed.",
    invalidForm: "Complete the required fields before saving.", noDecision: "An approved customer decision is not available for this Job.",
  }),
  es: Object.freeze({
    title: "Materiales y preparacion", eyebrow: "Planificacion del trabajo aprobado",
    purpose: "Planifica materiales, herramientas, equipos y preparacion para este trabajo.",
    loading: "Cargando materiales y preparacion...", unavailable: "Materiales y preparacion no esta disponible temporalmente.",
    retry: "Reintentar", emptyTitle: "Aun no hay un plan de materiales y preparacion",
    emptyBody: "Crea el plan canonico desde la decision aprobada del cliente. Ver esta seccion no crea un plan.",
    createPlan: "Crear plan", creating: "Creando...", commandFailed: "No se pudo completar la accion. Actualiza e intentalo de nuevo.",
    planning: "Planificacion", acquisition: "Adquisicion", preparation: "Preparacion", deposit: "Deposito",
    requiredReady: "Elementos requeridos listos", customerPending: "Elemento del cliente pendiente", blocked: "Requiere atencion",
    itemCount: "Elementos del plan", purchaseTotal: "Costo interno de compras registrado", version: "Version",
    depositLocked: "Las acciones comprometidas estan bloqueadas hasta que el deposito canonico este satisfecho o no sea requerido.",
    depositOpen: "Las acciones comprometidas estan disponibles segun el estado canonico actual del deposito.",
    workStartNotice: "Requerido para iniciar es informacion de planificacion. Esta pantalla no impone el inicio del trabajo.",
    editPlan: "Editar plan", closeEditor: "Cerrar editor", savePlan: "Guardar plan", saving: "Guardando...",
    planningState: "Estado de planificacion", workStartPolicy: "Politica de inicio", internalNotes: "Notas internas",
    none: "Ninguna", requiredItemsReady: "Elementos requeridos listos", addItem: "Agregar elemento", remove: "Eliminar",
    description: "Descripcion", kind: "Tipo", quantity: "Cantidad", unit: "Unidad", provider: "Provisto por",
    business: "Empresa", customer: "Cliente", visibility: "Visibilidad", businessOnly: "Solo empresa",
    customerVisible: "Visible para el cliente", requiredForStart: "Requerido para iniciar", estimatedCost: "Costo interno estimado",
    currency: "Moneda", material: "Material", tool: "Herramienta", equipment: "Equipo", preparationTask: "Tarea de preparacion",
    sourceAccepted: "Elemento de cotizacion aceptado", sourceElaboration: "Detalle del plan", commercialTreatment: "Tratamiento comercial",
    included: "Incluido en el total aceptado", notBillable: "No facturable al cliente", customerSupplied: "Provisto por el cliente",
    approvalRequired: "Requiere aprobacion", separatelyAccepted: "Aceptado por separado", allowance: "Asignacion",
    acquisitionState: "Adquisicion", preparationState: "Preparacion", readyForStart: "Listo para iniciar",
    purchaseEvidence: "Evidencia de compra", records: "registros", purchased: "Comprado", partiallyPurchased: "Comprado parcialmente",
    ready: "Listo", notStarted: "No iniciado", inProgress: "En progreso", customerItemPendingState: "Elemento del cliente pendiente",
    recordPurchase: "Registrar compra", allocateInventory: "Asignar inventario", markReceived: "Marcar recibido",
    markStaged: "Marcar preparado", markToolReady: "Marcar herramienta lista", markEquipmentReady: "Marcar equipo listo",
    prepStarted: "Preparacion iniciada", prepReady: "Preparacion lista", prepBlocked: "Preparacion bloqueada",
    purchaseTitle: "Registrar compra de material", vendor: "Proveedor", purchasedAt: "Comprado el",
    externalReference: "Referencia externa", internalCost: "Costo interno de compra", record: "Registrar", cancel: "Cancelar",
    note: "Nota interna", blockedReason: "Describe que bloquea la preparacion.", confirmBlocked: "Registrar bloqueo",
    noItems: "Aun no hay elementos.", privateCosts: "Los costos internos son visibles solo para la empresa.", refreshed: "Estado canonico actualizado.",
    invalidForm: "Completa los campos requeridos antes de guardar.", noDecision: "No hay una decision aprobada del cliente para este trabajo.",
  }),
  fr: Object.freeze({
    title: "Materiaux et preparation", eyebrow: "Planification du travail approuve",
    purpose: "Planifiez les materiaux, outils, equipements et la preparation de cette intervention.",
    loading: "Chargement des materiaux et de la preparation...", unavailable: "Les materiaux et la preparation sont temporairement indisponibles.",
    retry: "Reessayer", emptyTitle: "Aucun plan de materiaux et de preparation",
    emptyBody: "Creez le plan canonique a partir de la decision client approuvee. La consultation ne cree pas de plan.",
    createPlan: "Creer le plan", creating: "Creation...", commandFailed: "Cette action n'a pas pu etre terminee. Actualisez puis reessayez.",
    planning: "Planification", acquisition: "Acquisition", preparation: "Preparation", deposit: "Acompte",
    requiredReady: "Elements requis prets", customerPending: "Element client en attente", blocked: "Attention requise",
    itemCount: "Elements du plan", purchaseTotal: "Cout d'achat interne enregistre", version: "Version",
    depositLocked: "Les actions engageantes sont verrouillees jusqu'a ce que l'acompte canonique soit satisfait ou non requis.",
    depositOpen: "Les actions engageantes sont disponibles selon l'etat canonique actuel de l'acompte.",
    workStartNotice: "Requis pour commencer est une information de planification. Cet ecran n'impose pas le debut du travail.",
    editPlan: "Modifier le plan", closeEditor: "Fermer l'editeur", savePlan: "Enregistrer", saving: "Enregistrement...",
    planningState: "Etat de planification", workStartPolicy: "Regle de demarrage", internalNotes: "Notes internes",
    none: "Aucune", requiredItemsReady: "Elements requis prets", addItem: "Ajouter un element", remove: "Supprimer",
    description: "Description", kind: "Type", quantity: "Quantite", unit: "Unite", provider: "Fourni par",
    business: "Entreprise", customer: "Client", visibility: "Visibilite", businessOnly: "Entreprise uniquement",
    customerVisible: "Visible par le client", requiredForStart: "Requis pour commencer", estimatedCost: "Cout interne estime",
    currency: "Devise", material: "Materiau", tool: "Outil", equipment: "Equipement", preparationTask: "Tache de preparation",
    sourceAccepted: "Element du devis accepte", sourceElaboration: "Detail du plan", commercialTreatment: "Traitement commercial",
    included: "Inclus dans le total accepte", notBillable: "Non facturable au client", customerSupplied: "Fourni par le client",
    approvalRequired: "Approbation requise", separatelyAccepted: "Accepte separement", allowance: "Provision",
    acquisitionState: "Acquisition", preparationState: "Preparation", readyForStart: "Pret a commencer",
    purchaseEvidence: "Preuve d'achat", records: "enregistrements", purchased: "Achete", partiallyPurchased: "Partiellement achete",
    ready: "Pret", notStarted: "Non commence", inProgress: "En cours", customerItemPendingState: "Element client en attente",
    recordPurchase: "Enregistrer l'achat", allocateInventory: "Affecter le stock", markReceived: "Marquer recu",
    markStaged: "Marquer prepare", markToolReady: "Marquer l'outil pret", markEquipmentReady: "Marquer l'equipement pret",
    prepStarted: "Preparation commencee", prepReady: "Preparation prete", prepBlocked: "Preparation bloquee",
    purchaseTitle: "Enregistrer l'achat de materiau", vendor: "Fournisseur", purchasedAt: "Achete le",
    externalReference: "Reference externe", internalCost: "Cout d'achat interne", record: "Enregistrer", cancel: "Annuler",
    note: "Note interne", blockedReason: "Decrivez ce qui bloque la preparation.", confirmBlocked: "Enregistrer le blocage",
    noItems: "Aucun element pour le moment.", privateCosts: "Les couts internes sont reserves a l'entreprise.", refreshed: "Etat canonique actualise.",
    invalidForm: "Renseignez les champs obligatoires avant d'enregistrer.", noDecision: "Aucune decision client approuvee n'est disponible pour cette intervention.",
  }),
  "pt-BR": Object.freeze({
    title: "Materiais e preparacao", eyebrow: "Planejamento do trabalho aprovado",
    purpose: "Planeje materiais, ferramentas, equipamentos e preparacao para este trabalho.",
    loading: "Carregando materiais e preparacao...", unavailable: "Materiais e preparacao estao temporariamente indisponiveis.",
    retry: "Tentar novamente", emptyTitle: "Ainda nao ha plano de materiais e preparacao",
    emptyBody: "Crie o plano canonico a partir da decisao aprovada do cliente. Visualizar esta secao nao cria um plano.",
    createPlan: "Criar plano", creating: "Criando...", commandFailed: "Nao foi possivel concluir a acao. Atualize e tente novamente.",
    planning: "Planejamento", acquisition: "Aquisicao", preparation: "Preparacao", deposit: "Deposito",
    requiredReady: "Itens obrigatorios prontos", customerPending: "Item do cliente pendente", blocked: "Precisa de atencao",
    itemCount: "Itens do plano", purchaseTotal: "Custo interno de compras registrado", version: "Versao",
    depositLocked: "As acoes com compromisso ficam bloqueadas ate que o deposito canonico esteja satisfeito ou nao seja necessario.",
    depositOpen: "As acoes com compromisso estao disponiveis conforme o status canonico atual do deposito.",
    workStartNotice: "Obrigatorio para iniciar e informacao de planejamento. Esta tela nao controla o inicio do trabalho.",
    editPlan: "Editar plano", closeEditor: "Fechar editor", savePlan: "Salvar plano", saving: "Salvando...",
    planningState: "Status do planejamento", workStartPolicy: "Politica de inicio", internalNotes: "Notas internas",
    none: "Nenhuma", requiredItemsReady: "Itens obrigatorios prontos", addItem: "Adicionar item", remove: "Remover",
    description: "Descricao", kind: "Tipo", quantity: "Quantidade", unit: "Unidade", provider: "Fornecido por",
    business: "Empresa", customer: "Cliente", visibility: "Visibilidade", businessOnly: "Somente empresa",
    customerVisible: "Visivel para o cliente", requiredForStart: "Obrigatorio para iniciar", estimatedCost: "Custo interno estimado",
    currency: "Moeda", material: "Material", tool: "Ferramenta", equipment: "Equipamento", preparationTask: "Tarefa de preparacao",
    sourceAccepted: "Item do orcamento aceito", sourceElaboration: "Detalhe do plano", commercialTreatment: "Tratamento comercial",
    included: "Incluido no total aceito", notBillable: "Nao faturavel ao cliente", customerSupplied: "Fornecido pelo cliente",
    approvalRequired: "Aprovacao necessaria", separatelyAccepted: "Aceito separadamente", allowance: "Provisao",
    acquisitionState: "Aquisicao", preparationState: "Preparacao", readyForStart: "Pronto para iniciar",
    purchaseEvidence: "Evidencia de compra", records: "registros", purchased: "Comprado", partiallyPurchased: "Parcialmente comprado",
    ready: "Pronto", notStarted: "Nao iniciado", inProgress: "Em andamento", customerItemPendingState: "Item do cliente pendente",
    recordPurchase: "Registrar compra", allocateInventory: "Alocar estoque", markReceived: "Marcar recebido",
    markStaged: "Marcar preparado", markToolReady: "Marcar ferramenta pronta", markEquipmentReady: "Marcar equipamento pronto",
    prepStarted: "Preparacao iniciada", prepReady: "Preparacao pronta", prepBlocked: "Preparacao bloqueada",
    purchaseTitle: "Registrar compra de material", vendor: "Fornecedor", purchasedAt: "Comprado em",
    externalReference: "Referencia externa", internalCost: "Custo interno da compra", record: "Registrar", cancel: "Cancelar",
    note: "Nota interna", blockedReason: "Descreva o que bloqueia a preparacao.", confirmBlocked: "Registrar bloqueio",
    noItems: "Ainda nao ha itens.", privateCosts: "Os custos internos sao exclusivos da empresa.", refreshed: "Status canonico atualizado.",
    invalidForm: "Preencha os campos obrigatorios antes de salvar.", noDecision: "Nao ha uma decisao aprovada do cliente para este trabalho.",
  }),
});

export const WORK_PREPARATION_LANGUAGES = Object.freeze(["en", "es", "fr", "pt-BR"]);

export function getWorkPreparationCopy(language = "en") {
  return COPY[language] || COPY.en;
}
