const COPY = Object.freeze({
  en: Object.freeze({
    workCenter: "Work Center",
    opportunitiesEyebrow: "New work",
    opportunitiesDescription: "Review new customer requests and decide what to do next.",
    opportunitiesEmptyTitle: "No new opportunities",
    opportunitiesEmptyBody: "New customer requests will appear here when they match your services.",
    currentJobsEyebrow: "Active work",
    currentJobsDescription: "Continue customer work and focus on the next step for each Job.",
    currentJobsEmptyTitle: "No current jobs",
    currentJobsEmptyBody: "Accepted customer work will appear here when a Job is ready to begin.",
    workPlanDescription: "Track approved work and what still needs attention.",
    workPlanEmptyTitle: "No approved work yet",
    workPlanEmptyBody: "Approved work items will appear here once work has been prepared from an approved quote.",
    jobs: "Jobs",
    scheduleEyebrow: "Customer visits",
    scheduleDescription: "Plan visits and keep customer scheduling in one place.",
    scheduleEmptyTitle: "No visits scheduled",
    scheduleEmptyBody: "Customer visits will appear here when evaluation or approved work is ready to schedule.",
    quotesEyebrow: "Customer pricing",
    quotesDescription: "Prepare quotes and follow customer decisions.",
    quotesEmptyTitle: "No quotes yet",
    quotesEmptyBody: "Draft and issued quotes will appear here as customer work is priced.",
    historyEyebrow: "Completed work",
    historyDescription: "Review completed jobs and past work.",
    historyEmptyTitle: "No completed jobs yet",
    historyEmptyBody: "Completed jobs will appear here once work has been finished and closed.",
    financeEyebrow: "Billing",
    financeDescription: "Create invoices and track money still due.",
    financeEmptyTitle: "No invoices yet",
    financeEmptyBody: "Invoices will appear here when completed or billable work is ready.",
    visits: "Visits",
    visitsSummary: "Plan and review customer appointments.",
    evaluation: "Evaluation",
    evaluationSummary: "Record what you observed and assessed.",
    findings: "What I Found & Recommendations",
    findingsSummary: "Review findings and the work you recommend.",
    workPlan: "Work Plan",
    workPlanSummary: "Everything you need before starting this job.",
    materialsPreparation: "Materials & Preparation",
    materialsPreparationSummary: "Plan materials, tools, equipment, and readiness.",
    quotes: "Quotes & Approvals",
    quotesSummary: "Review pricing and customer decisions.",
    completionInvoice: "Completion & Invoice",
    completionInvoiceSummary: "Review completed work and continue to billing.",
    openInvoices: "Open Invoices & Payments",
    jobDetails: "Job details",
    confirmed: "Confirmed",
    loading: "Loading",
    unavailable: "Unavailable",
    currentStatus: "Current status",
    nextStep: "Next step",
    whoActsNext: "Who acts next",
    quoteDetails: "View quote details",
    scope: "Scope",
    quoteTotal: "Quote total",
    customerDecision: "Customer decision",
    issued: "Issued",
    noScope: "No scope items recorded",
    noDecision: "No decision recorded",
    includedInTotal: "Included in quote total",
    separateProposal: "Additional proposal - not included in this total",
    excludedFromTotal: "Excluded from quote total",
    quantity: "Quantity",
    unit: "Unit",
    lineTotal: "Line total",
    originalQuote: "Original Quote",
    revisedQuote: "Revised Quote",
    additionalQuote: "Additional Quote",
  }),
  es: Object.freeze({
    workCenter: "Centro de trabajo",
    opportunitiesEyebrow: "Nuevo trabajo",
    opportunitiesDescription: "Revisa nuevas solicitudes de clientes y decide que hacer despues.",
    opportunitiesEmptyTitle: "No hay oportunidades nuevas",
    opportunitiesEmptyBody: "Las nuevas solicitudes apareceran aqui cuando coincidan con tus servicios.",
    currentJobsEyebrow: "Trabajo activo",
    currentJobsDescription: "Continua el trabajo del cliente y enfocate en el siguiente paso de cada trabajo.",
    currentJobsEmptyTitle: "No hay trabajos actuales",
    currentJobsEmptyBody: "El trabajo aceptado aparecera aqui cuando este listo para comenzar.",
    workPlanDescription: "Sigue el trabajo aprobado y lo que aun requiere atencion.",
    workPlanEmptyTitle: "Aun no hay trabajo aprobado",
    workPlanEmptyBody: "Las tareas aprobadas apareceran aqui cuando se preparen desde una cotizacion aprobada.",
    jobs: "Trabajos",
    scheduleEyebrow: "Visitas de clientes",
    scheduleDescription: "Planifica visitas y manten la agenda del cliente en un solo lugar.",
    scheduleEmptyTitle: "No hay visitas programadas",
    scheduleEmptyBody: "Las visitas apareceran cuando una evaluacion o trabajo aprobado este listo para programar.",
    quotesEyebrow: "Precios para clientes",
    quotesDescription: "Prepara cotizaciones y sigue las decisiones del cliente.",
    quotesEmptyTitle: "Aun no hay cotizaciones",
    quotesEmptyBody: "Los borradores y cotizaciones emitidas apareceran aqui al definir el precio del trabajo.",
    historyEyebrow: "Trabajo completado",
    historyDescription: "Revisa trabajos completados y trabajos anteriores.",
    historyEmptyTitle: "Aun no hay trabajos completados",
    historyEmptyBody: "Los trabajos completados apareceran aqui cuando el trabajo finalice y se cierre.",
    financeEyebrow: "Facturacion",
    financeDescription: "Crea facturas y sigue el dinero pendiente.",
    financeEmptyTitle: "Aun no hay facturas",
    financeEmptyBody: "Las facturas apareceran cuando haya trabajo completado o facturable.",
    visits: "Visitas", visitsSummary: "Planifica y revisa citas con clientes.",
    evaluation: "Evaluacion", evaluationSummary: "Registra lo que observaste y evaluaste.",
    findings: "Lo que encontre y recomendaciones", findingsSummary: "Revisa hallazgos y el trabajo recomendado.",
    workPlan: "Plan de trabajo", workPlanSummary: "Sigue el trabajo aprobado y su progreso.",
    materialsPreparation: "Materiales y preparacion", materialsPreparationSummary: "Planifica materiales, herramientas, equipos y preparacion.",
    quotes: "Cotizaciones y aprobaciones", quotesSummary: "Revisa precios y decisiones del cliente.",
    completionInvoice: "Finalizacion y factura", completionInvoiceSummary: "Revisa el trabajo completado y continua a facturacion.",
    openInvoices: "Abrir facturas y pagos", jobDetails: "Detalles del trabajo", confirmed: "Confirmado",
    loading: "Cargando", unavailable: "No disponible", currentStatus: "Estado actual", nextStep: "Siguiente paso",
    whoActsNext: "Quien actua despues", quoteDetails: "Ver detalles de la cotizacion", scope: "Alcance",
    quoteTotal: "Total de la cotizacion", customerDecision: "Decision del cliente", issued: "Emitida", noScope: "No hay elementos de alcance registrados",
    noDecision: "No hay decision registrada", includedInTotal: "Incluido en el total de la cotizacion",
    separateProposal: "Propuesta adicional - no incluida en este total", excludedFromTotal: "Excluido del total de la cotizacion",
    quantity: "Cantidad", unit: "Unidad", lineTotal: "Total de linea", originalQuote: "Cotizacion original",
    revisedQuote: "Cotizacion revisada", additionalQuote: "Cotizacion adicional",
  }),
  fr: Object.freeze({
    workCenter: "Centre de travail",
    opportunitiesEyebrow: "Nouveau travail",
    opportunitiesDescription: "Examinez les nouvelles demandes et choisissez la prochaine etape.",
    opportunitiesEmptyTitle: "Aucune nouvelle opportunite",
    opportunitiesEmptyBody: "Les nouvelles demandes apparaitront ici lorsqu'elles correspondent a vos services.",
    currentJobsEyebrow: "Travail actif",
    currentJobsDescription: "Poursuivez le travail client et concentrez-vous sur la prochaine etape.",
    currentJobsEmptyTitle: "Aucun travail en cours",
    currentJobsEmptyBody: "Le travail accepte apparaitra ici lorsqu'une intervention est prete a commencer.",
    workPlanDescription: "Suivez le travail approuve et ce qui demande encore votre attention.",
    workPlanEmptyTitle: "Aucun travail approuve pour le moment",
    workPlanEmptyBody: "Les taches approuvees apparaitront ici une fois preparees depuis un devis approuve.",
    jobs: "Interventions",
    scheduleEyebrow: "Visites client",
    scheduleDescription: "Planifiez les visites et gardez les rendez-vous client au meme endroit.",
    scheduleEmptyTitle: "Aucune visite planifiee",
    scheduleEmptyBody: "Les visites apparaitront lorsqu'une evaluation ou un travail approuve sera pret a planifier.",
    quotesEyebrow: "Tarification client",
    quotesDescription: "Preparez les devis et suivez les decisions du client.",
    quotesEmptyTitle: "Aucun devis pour le moment",
    quotesEmptyBody: "Les brouillons et devis emis apparaitront ici lors de la tarification du travail.",
    historyEyebrow: "Travail termine",
    historyDescription: "Consultez les interventions terminees et le travail passe.",
    historyEmptyTitle: "Aucune intervention terminee",
    historyEmptyBody: "Les interventions terminees apparaitront ici une fois le travail fini et cloture.",
    financeEyebrow: "Facturation",
    financeDescription: "Creez des factures et suivez les montants encore dus.",
    financeEmptyTitle: "Aucune facture pour le moment",
    financeEmptyBody: "Les factures apparaitront lorsqu'un travail termine ou facturable sera pret.",
    visits: "Visites", visitsSummary: "Planifiez et examinez les rendez-vous client.",
    evaluation: "Evaluation", evaluationSummary: "Consignez vos observations et votre evaluation.",
    findings: "Constats et recommandations", findingsSummary: "Examinez les constats et le travail recommande.",
    workPlan: "Plan de travail", workPlanSummary: "Suivez le travail approuve et son avancement.",
    materialsPreparation: "Materiaux et preparation", materialsPreparationSummary: "Planifiez les materiaux, outils, equipements et la preparation.",
    quotes: "Devis et approbations", quotesSummary: "Examinez les prix et les decisions du client.",
    completionInvoice: "Achevement et facture", completionInvoiceSummary: "Examinez le travail termine et passez a la facturation.",
    openInvoices: "Ouvrir les factures et paiements", jobDetails: "Details de l'intervention", confirmed: "Confirme",
    loading: "Chargement", unavailable: "Indisponible", currentStatus: "Etat actuel", nextStep: "Prochaine etape",
    whoActsNext: "Prochaine personne a agir", quoteDetails: "Voir les details du devis", scope: "Etendue",
    quoteTotal: "Total du devis", customerDecision: "Decision du client", issued: "Emis", noScope: "Aucun element d'etendue enregistre",
    noDecision: "Aucune decision enregistree", includedInTotal: "Inclus dans le total du devis",
    separateProposal: "Proposition supplementaire - non incluse dans ce total", excludedFromTotal: "Exclu du total du devis",
    quantity: "Quantite", unit: "Unite", lineTotal: "Total de la ligne", originalQuote: "Devis initial",
    revisedQuote: "Devis revise", additionalQuote: "Devis supplementaire",
  }),
  "pt-BR": Object.freeze({
    workCenter: "Centro de trabalho",
    opportunitiesEyebrow: "Novo trabalho",
    opportunitiesDescription: "Revise novas solicitacoes de clientes e decida o proximo passo.",
    opportunitiesEmptyTitle: "Nenhuma nova oportunidade",
    opportunitiesEmptyBody: "Novas solicitacoes aparecerao aqui quando corresponderem aos seus servicos.",
    currentJobsEyebrow: "Trabalho ativo",
    currentJobsDescription: "Continue o trabalho do cliente e foque no proximo passo de cada servico.",
    currentJobsEmptyTitle: "Nenhum trabalho atual",
    currentJobsEmptyBody: "O trabalho aceito aparecera aqui quando estiver pronto para comecar.",
    workPlanDescription: "Acompanhe o trabalho aprovado e o que ainda precisa de atencao.",
    workPlanEmptyTitle: "Nenhum trabalho aprovado ainda",
    workPlanEmptyBody: "As tarefas aprovadas aparecerao aqui quando forem preparadas a partir de um orcamento aprovado.",
    jobs: "Trabalhos",
    scheduleEyebrow: "Visitas de clientes",
    scheduleDescription: "Planeje visitas e mantenha os agendamentos do cliente em um so lugar.",
    scheduleEmptyTitle: "Nenhuma visita agendada",
    scheduleEmptyBody: "As visitas aparecerao quando uma avaliacao ou trabalho aprovado estiver pronto para agendar.",
    quotesEyebrow: "Precos para clientes",
    quotesDescription: "Prepare orcamentos e acompanhe as decisoes do cliente.",
    quotesEmptyTitle: "Nenhum orcamento ainda",
    quotesEmptyBody: "Rascunhos e orcamentos emitidos aparecerao aqui durante a definicao do preco.",
    historyEyebrow: "Trabalho concluido",
    historyDescription: "Revise trabalhos concluidos e trabalhos anteriores.",
    historyEmptyTitle: "Nenhum trabalho concluido ainda",
    historyEmptyBody: "Os trabalhos concluidos aparecerao aqui depois que o trabalho for finalizado e encerrado.",
    financeEyebrow: "Faturamento",
    financeDescription: "Crie faturas e acompanhe valores ainda devidos.",
    financeEmptyTitle: "Nenhuma fatura ainda",
    financeEmptyBody: "As faturas aparecerao quando houver trabalho concluido ou faturavel pronto.",
    visits: "Visitas", visitsSummary: "Planeje e revise compromissos com clientes.",
    evaluation: "Avaliacao", evaluationSummary: "Registre o que voce observou e avaliou.",
    findings: "O que encontrei e recomendacoes", findingsSummary: "Revise descobertas e o trabalho recomendado.",
    workPlan: "Plano de trabalho", workPlanSummary: "Acompanhe o trabalho aprovado e o progresso.",
    materialsPreparation: "Materiais e preparacao", materialsPreparationSummary: "Planeje materiais, ferramentas, equipamentos e preparacao.",
    quotes: "Orcamentos e aprovacoes", quotesSummary: "Revise precos e decisoes do cliente.",
    completionInvoice: "Conclusao e fatura", completionInvoiceSummary: "Revise o trabalho concluido e continue para o faturamento.",
    openInvoices: "Abrir faturas e pagamentos", jobDetails: "Detalhes do trabalho", confirmed: "Confirmado",
    loading: "Carregando", unavailable: "Indisponivel", currentStatus: "Status atual", nextStep: "Proximo passo",
    whoActsNext: "Quem age depois", quoteDetails: "Ver detalhes do orcamento", scope: "Escopo",
    quoteTotal: "Total do orcamento", customerDecision: "Decisao do cliente", issued: "Emitido", noScope: "Nenhum item de escopo registrado",
    noDecision: "Nenhuma decisao registrada", includedInTotal: "Incluido no total do orcamento",
    separateProposal: "Proposta adicional - nao incluida neste total", excludedFromTotal: "Excluido do total do orcamento",
    quantity: "Quantidade", unit: "Unidade", lineTotal: "Total da linha", originalQuote: "Orcamento original",
    revisedQuote: "Orcamento revisado", additionalQuote: "Orcamento adicional",
  }),
});

const NEXT_ACTION_SECTION = Object.freeze({
  START_OR_CONTINUE_EVALUATION: "evaluation",
  REVIEW_FINDINGS: "findings",
  PREPARE_RECOMMENDATIONS: "findings",
  BUILD_QUOTE: "quotes",
  REVIEW_DRAFT_QUOTE: "quotes",
  WAIT_FOR_CUSTOMER_DECISION: "quotes",
  REVIEW_DECLINED_QUOTE: "quotes",
  REVIEW_ACTIVE_WORK: "workPlan",
  REVIEW_BLOCKED_WORK: "workPlan",
  REVIEW_WORKSTREAM_COMPLETION: "workPlan",
  READY_TO_INVOICE: "completionInvoice",
});

export const WORK_CENTER_WORKSPACE_LANGUAGES = Object.freeze(["en", "es", "fr", "pt-BR"]);

export function getWorkCenterWorkspaceCopy(language = "en") {
  return COPY[language] || COPY.en;
}

export function resolveWorkCenterSectionForNextAction(nextActionCode = "", stageCode = "", nextActionLabel = "") {
  const action = String(nextActionCode || "").trim();
  const stage = String(stageCode || "").trim();
  const label = String(nextActionLabel || "").trim();
  if (action === "REVIEW_ACTIVE_WORK" && (stage === "WORK_READY" || /schedule/i.test(label))) return "visits";
  return NEXT_ACTION_SECTION[action] || "visits";
}
