// UI labels only. Record identities, stage keys and financial rules stay with
// their existing owners. Never pass customer-authored content through this map.
const rows = [
  ['visitSchedulingUnavailable','Scheduling isn’t available for this job right now.','La programación no está disponible para este trabajo en este momento.','La planification n’est pas disponible pour ce travail pour le moment.','O agendamento não está disponível para este trabalho no momento.'],
  ['quoteReference','This quote preview is read-only. Open the Quote to make changes.','Esta vista de la cotización es de solo lectura. Abre la cotización para hacer cambios.','Cet aperçu du devis est en lecture seule. Ouvrez le devis pour le modifier.','Esta prévia do orçamento é somente leitura. Abra o orçamento para alterá-lo.'],
  ['priorPayments','Payments applied before Invoice','Pagos aplicados antes de la factura','Paiements appliqués avant la facture','Pagamentos aplicados antes da fatura'],
  ['priorPaymentsHelp','Includes earlier deposit and payment records, separate from the Invoice payments below.','Incluye depósitos y pagos anteriores, separados de los pagos de la factura que aparecen abajo.','Comprend les acomptes et paiements antérieurs, distincts des paiements de la facture ci-dessous.','Inclui depósitos e pagamentos anteriores, separados dos pagamentos da fatura abaixo.'],
  ['subtitle','Manage new opportunities and keep active jobs moving.','Gestiona nuevas oportunidades y haz avanzar los trabajos activos.','Gérez les nouvelles opportunités et faites avancer les travaux en cours.','Gerencie novas oportunidades e mantenha os trabalhos em andamento.'],
  ['filterViews','Filter & Views','Filtros y vistas','Filtres et vues','Filtros e visualizações'],
  ['filterAccessible','Filter and views','Filtros y vistas','Filtres et vues','Filtros e visualizações'],
  ['filterStage','Filter by stage','Filtrar por etapa','Filtrer par étape','Filtrar por etapa'],
  ['jobStage','Job stage','Etapa del trabajo','Étape du travail','Etapa do trabalho'],
  ['views','Work Center Views','Vistas del centro de trabajo','Vues du centre de travail','Visualizações do centro de trabalho'],
  ['all','All Active Jobs','Todos los trabajos activos','Tous les travaux en cours','Todos os trabalhos em andamento'],
  ['history','Job History','Historial de trabajos','Historique des travaux','Histórico de trabalhos'],
  ['revenue','Revenue','Ingresos','Revenus','Receita'],
  ['revenueHelp','View revenue and payment activity','Consulta ingresos y actividad de pagos','Consultez les revenus et les paiements','Veja a receita e a atividade de pagamentos'],
  ['viewRevenue','View Revenue','Ver ingresos','Voir les revenus','Ver receita'],
  ['activeJobs','Active Jobs','Trabajos activos','Travaux en cours','Trabalhos em andamento'],
  ['search','Search active jobs','Buscar trabajos activos','Rechercher des travaux en cours','Buscar trabalhos em andamento'],
  ['searchPlaceholder','Search customers or jobs…','Buscar clientes o trabajos…','Rechercher des clients ou travaux…','Buscar clientes ou trabalhos…'],
  ['noMatch','No jobs match this view','No hay trabajos en esta vista','Aucun travail ne correspond à cette vue','Nenhum trabalho corresponde a esta visualização'],
  ['noMatchHelp','Try another search or choose a different stage.','Prueba otra búsqueda o elige otra etapa.','Essayez une autre recherche ou choisissez une autre étape.','Tente outra busca ou escolha outra etapa.'],
  ['opportunities','Opportunities','Oportunidades','Opportunités','Oportunidades'],
  ['opportunitiesHelp','Review and respond to customer requests.','Revisa y responde a las solicitudes de clientes.','Consultez les demandes des clients et répondez-y.','Analise e responda às solicitações dos clientes.'],
  ['viewOpportunities','View Opportunities','Ver oportunidades','Voir les opportunités','Ver oportunidades'],
  ['new','New','Nuevas','Nouvelles','Novas'],
  ['awaiting','Awaiting Response','Esperando respuesta','En attente de réponse','Aguardando resposta'],
  ['scheduled','Scheduled','Programados','Planifiés','Agendados'],
  ['notScheduled','Not scheduled','Sin programar','Non planifié','Não agendado'],
  ['location','Customer location','Ubicación del cliente','Lieu du client','Local do cliente'],
  ['nextStep','Next step','Siguiente paso','Prochaine étape','Próxima etapa'],
  ['nextUp','Next up','Le toca a','À qui de jouer','Próxima ação'],
  ['you','You','Ti','Vous','Você'],
  ['customer','Customer','Cliente','Client','Cliente'],
  ['unavailable','Unavailable','No disponible','Indisponible','Indisponível'],
  ['progress','Job progress','Avance del trabajo','Avancement du travail','Progresso do trabalho'],
  ['progressCount','{count} of 7 completed','{count} de 7 completadas','{count} sur 7 terminées','{count} de 7 concluídas'],
  ['approvedSchedule','Approved — ready to schedule','Aprobado — listo para programar','Approuvé — prêt à planifier','Aprovado — pronto para agendar'],
  ['scheduleJob','Schedule this job','Programar este trabajo','Planifier ce travail','Agendar este trabalho'],
  ['readyComplete','Work finished — ready to complete the job','Trabajo terminado — listo para completar','Travail terminé — prêt à finaliser','Serviço terminado — pronto para concluir'],
  ['invoiceGate','Complete this job first. Then you can prepare the final invoice.','Completa este trabajo primero. Después podrás preparar la factura final.','Terminez d’abord ce travail. Vous pourrez ensuite préparer la facture finale.','Conclua este trabalho primeiro. Depois você poderá preparar a fatura final.'],
  ['quoteGate','Complete Evaluation before preparing a Quote.','Completa la evaluación antes de preparar una cotización.','Terminez l’évaluation avant de préparer un devis.','Conclua a avaliação antes de preparar um orçamento.'],
  ['depositSummary','Review the deposit required for the approved Quote.','Revisa el depósito de la cotización aprobada.','Consultez l’acompte du devis approuvé.','Confira o depósito do orçamento aprovado.'],
  ['depositGate','The deposit becomes available after Quote approval.','El depósito estará disponible después de aprobar la cotización.','L’acompte sera disponible après l’approbation du devis.','O depósito ficará disponível após a aprovação do orçamento.'],
  ['scheduleGate','Resolve the deposit requirement before scheduling.','Resuelve el requisito de depósito antes de programar.','Réglez la demande d’acompte avant de planifier.','Resolva a exigência de depósito antes de agendar.'],
  ['workPlanGate','Confirm the schedule before preparing the Work Plan.','Confirma el horario antes de preparar el plan de trabajo.','Confirmez le planning avant de préparer le plan de travail.','Confirme o agendamento antes de preparar o plano de trabalho.'],
  ['completeSummary','Review the work, then choose Complete Job.','Revisa el trabajo y elige Completar trabajo.','Vérifiez le travail, puis choisissez Terminer le travail.','Revise o trabalho e escolha Concluir trabalho.'],
  ['jobComplete','This job is complete.','Este trabajo está completo.','Ce travail est terminé.','Este trabalho está concluído.'],
  ['completeGate','Finish the Work Plan before completing this job.','Termina el plan de trabajo antes de completar este trabajo.','Terminez le plan de travail avant de finaliser ce travail.','Termine o plano de trabalho antes de concluir este trabalho.'],
  ['depositUnavailable','Deposit details are not available yet.','Los detalles del depósito aún no están disponibles.','Les détails de l’acompte ne sont pas encore disponibles.','Os detalhes do depósito ainda não estão disponíveis.'],
  ['depositCustomerCreated','Customer created. Approve a Quote with a deposit before sending this request.','Cliente creado. Aprueba una cotización con depósito antes de enviar esta solicitud.','Client créé. Approuvez un devis avec acompte avant d’envoyer cette demande.','Cliente criado. Aprove um orçamento com depósito antes de enviar esta solicitação.'],
  ['depositSendLocked','To send this request, first approve a Quote with an unpaid deposit.','Para enviar esta solicitud, aprueba primero una cotización con depósito pendiente.','Pour envoyer cette demande, approuvez d’abord un devis avec un acompte impayé.','Para enviar esta solicitação, aprove primeiro um orçamento com depósito pendente.'],
  ['depositPdfLocked','To create a PDF, first approve a Quote with an unpaid deposit.','Para crear un PDF, aprueba primero una cotización con depósito pendiente.','Pour créer un PDF, approuvez d’abord un devis avec un acompte impayé.','Para criar um PDF, aprove primeiro um orçamento com depósito pendente.'],
  ['quoteAccess','You cannot view Quotes with this account.','No puedes ver cotizaciones con esta cuenta.','Ce compte ne permet pas de consulter les devis.','Esta conta não permite visualizar orçamentos.'],
  ['visitChange','Customer proposed a new time. Approve it or suggest a change.','El cliente propuso otro horario. Apruébalo o sugiere un cambio.','Le client a proposé un autre horaire. Acceptez-le ou proposez un changement.','O cliente propôs outro horário. Aprove ou sugira uma alteração.'],
  ['evaluationSaved','Evaluation saved.','Evaluación guardada.','Évaluation enregistrée.','Avaliação salva.'],
  ['evaluationComplete','Evaluation completed.','Evaluación completada.','Évaluation terminée.','Avaliação concluída.'],
  ['evaluationNotice','Evaluation saved. Quote and authorization are not available here yet.','Evaluación guardada. La cotización y autorización aún no están disponibles aquí.','Évaluation enregistrée. Le devis et l’autorisation ne sont pas encore disponibles ici.','Avaliação salva. O orçamento e a autorização ainda não estão disponíveis aqui.'],
  ['evaluation','Evaluation','Evaluación','Évaluation','Avaliação'],
  ['quote','Quote','Cotización','Devis','Orçamento'],
  ['deposit','Deposit','Depósito','Acompte','Depósito'],
  ['schedule','Schedule','Agenda','Planning','Agenda'],
  ['workPlan','Work Plan','Plan de trabajo','Plan de travail','Plano de trabalho'],
  ['completeJob','Complete Job','Completar trabajo','Terminer le travail','Concluir trabalho'],
  ['invoice','Invoice','Factura','Facture','Fatura'],
];
export const workCenterPresentationLanguage = Object.fromEntries(
  ['en','es','fr','pt-BR'].map((language,index)=>[language,Object.fromEntries(rows.map(([key,...labels])=>[`wc52${key}`,labels[index]]))])
);
