import test from "node:test";
import assert from "node:assert/strict";
import { askCompanionGateway } from "../intelligence/gateway.js";
import { collectDecisionIntelligence, decisionEngine } from "../intelligence/decision/index.js";

const context = (overrides = {}) => ({
  capabilities: { selectedCapability: { capabilityId: "workflow.prepare_quote", name: "Prepare Quote", domain: "workflow" }, alternatives: [], status: "available", authorization: { permissionStatus: "allowed" }, prerequisites: { missing: [] }, requiredInputs: { missing: [] }, supportingEngines: ["workflow", "knowledge"], execution: { performed: false, executableNow: false, requiresExplicitApproval: true } },
  validation: { status: "supported", overallConfidence: "high", responseMode: "definitive", warnings: [], missingEvidence: [], scopeConflicts: [], evidence: { supportingEngineIds: ["workflow", "capability"], references: [{ evidenceId: "workflow:one" }] }, responseConstraints: { clarificationRequired: false, blockedTopics: [] } },
  ...overrides,
});

test("decision engine contract remains advisory", () => { assert.equal(decisionEngine.id, "decision"); assert.equal(typeof decisionEngine.collectContext, "function"); });
test("missing validated capability returns unsupported without recommendation", async () => { const result = await collectDecisionIntelligence({ collected: {} }); assert.equal(result.recommendationMode, "unsupported"); assert.equal(result.recommendedOption, null); });
test("supported validated option is recommended with evidence and approval", async () => { const result = await collectDecisionIntelligence({ collected: context() }); assert.equal(result.recommendationMode, "recommended"); assert.equal(result.recommendedOption, "decision:workflow.prepare_quote"); assert.equal(result.approvalRequired, true); assert.deepEqual(result.supportingEvidence, ["workflow:one"]); });
test("alternatives produce deterministic option comparison and tradeoffs", async () => { const c = context(); c.capabilities.alternatives = [{ capabilityId: "workflow.review_proposal", label: "Review Proposal", mode: "read_only" }]; const result = await collectDecisionIntelligence({ collected: c }); assert.equal(result.recommendationMode, "alternative"); assert.deepEqual(result.options.map((item) => item.optionId), [...result.options.map((item) => item.optionId)].sort()); assert.equal(result.tradeoffs.length, 1); });
test("ambiguity requires clarification and does not recommend", async () => { const c = context(); c.capabilities.status = "ambiguous"; c.validation.responseConstraints.clarificationRequired = true; const result = await collectDecisionIntelligence({ collected: c }); assert.equal(result.recommendationMode, "clarification_required"); assert.equal(result.recommendedOption, null); });
test("blocked validation rejects options", async () => { const c = context(); c.validation.status = "blocked"; c.validation.responseMode = "blocked"; const result = await collectDecisionIntelligence({ collected: c }); assert.equal(result.recommendationMode, "blocked"); assert.equal(result.recommendedOption, null); assert.equal(result.options[0].blocked, true); });
test("conflict stale and insufficient evidence return no safe option", async () => { for (const status of ["conflicted", "stale_only", "insufficient_evidence"]) { const c = context(); c.validation.status = status; c.validation.overallConfidence = "withheld"; const result = await collectDecisionIntelligence({ collected: c }); assert.equal(result.recommendationMode, "no_safe_option"); } });
test("unauthorized capability is never recommended", async () => { const c = context(); c.capabilities.authorization.permissionStatus = "denied"; c.validation.status = "blocked"; const result = await collectDecisionIntelligence({ collected: c }); assert.equal(result.recommendedOption, null); assert.equal(result.approvalRequired, false); });
test("decision analysis does not mutate inputs or log private data", async () => { const c = context({ memory: [{ value: "SECRET" }] }); const before = structuredClone(c); const logs = []; await collectDecisionIntelligence({ request: { requestId: "r", message: "PRIVATE" }, collected: c, logger: { info(event, fields) { logs.push({ event, fields }); } } }); assert.deepEqual(c, before); assert.doesNotMatch(JSON.stringify(logs), /SECRET|PRIVATE/); });
test("Gateway sends decision once while UI and usage remain unchanged", async () => { let calls = 0; let payload; const usage = []; const result = await askCompanionGateway({ user: { id: "u", accountType: "standard" }, body: { question: "What happens next?", feature: "ask_meetro" }, backendContext: { activeWorkflow: { workflowId: "wf", status: "evaluation", evaluationStatus: "saved" } }, providers: { openai: { name: "openai", async complete(input) { calls += 1; payload = JSON.parse(input.messages[1].content); return { answer: "Review the supported option." }; } } }, recordUsage(event) { usage.push(event); }, logger: null }); assert.equal(calls, 1); assert.equal(usage.length, 1); assert.ok(payload.decision.recommendationMode); assert.equal(payload.decision.execution.performed, false); assert.equal(result.decision, undefined); });

