import test from "node:test";
import assert from "node:assert/strict";
import { askCompanionGateway } from "../intelligence/gateway.js";
import { collectRecommendationIntelligence, recommendationEngine } from "../intelligence/recommendation/index.js";

const option = (overrides = {}) => ({ optionId: "decision:workflow.prepare_quote", title: "Prepare Quote", capabilityId: "workflow.prepare_quote", supportingEngines: ["workflow", "capability"], supportingEvidence: ["workflow:one"], constraints: [], prerequisites: [], permissionStatus: "allowed", validationStatus: "supported", confidence: "high", approvalRequired: true, blocked: false, ...overrides });
const context = (overrides = {}) => ({ workflow: { workflowId: "wf", currentStage: "evaluation", blocked: false, completion: {} }, validation: { status: "supported", overallConfidence: "high", responseConstraints: { clarificationRequired: false }, warnings: [] }, decision: { options: [option()], recommendedOption: "decision:workflow.prepare_quote", recommendationMode: "recommended", confidence: "high", warnings: [] }, ...overrides });

test("recommendation engine is registered as advisory", () => { assert.equal(recommendationEngine.id, "recommendation"); assert.equal(typeof recommendationEngine.collectContext, "function"); });
test("missing Decision or Validation returns no safe recommendation", async () => { const result = await collectRecommendationIntelligence({ collected: {} }); assert.equal(result.recommendationMode, "no_safe_recommendation"); assert.equal(result.highestPriority, null); });
test("validated selected option becomes evidence-backed priority", async () => { const result = await collectRecommendationIntelligence({ collected: context() }); assert.equal(result.recommendationMode, "recommended"); assert.equal(result.recommendations[0].priority, "high"); assert.equal(result.recommendations[0].requiresExplicitApproval, true); assert.deepEqual(result.recommendations[0].supportingEvidence, ["workflow:one"]); });
test("emergency recommendation receives critical priority deterministically", async () => { const c = context({ workflow: { workflowType: "emergency", blocked: false, completion: {} } }); const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.recommendations[0].priority, "critical"); });
test("alternatives are deferred and ordering is deterministic", async () => { const c = context(); c.decision.options.push(option({ optionId: "decision:workflow.review_proposal", capabilityId: "workflow.review_proposal", title: "Review", approvalRequired: false })); const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.deferredRecommendations.length, 1); assert.deepEqual([...result.recommendations, ...result.deferredRecommendations].map((item) => item.recommendationId), ["recommendation:decision:workflow.prepare_quote", "recommendation:decision:workflow.review_proposal"]); });
test("blocked and unauthorized options are never recommended", async () => { const c = context(); c.validation.status = "blocked"; c.decision.recommendationMode = "blocked"; c.decision.options[0].blocked = true; const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.recommendationMode, "blocked"); assert.equal(result.recommendations.length, 0); assert.equal(result.blockedRecommendations.length, 1); });
test("ambiguity requires clarification without priority inflation", async () => { const c = context(); c.validation.responseConstraints.clarificationRequired = true; c.decision.recommendationMode = "clarification_required"; const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.recommendationMode, "clarification_required"); assert.equal(result.highestPriority, null); assert.equal(result.confidence, "withheld"); });
test("finished workflow can produce no-action outcome", async () => { const c = context({ workflow: { completion: { finished: true } } }); c.decision.recommendedOption = null; c.decision.options = []; c.decision.recommendationMode = "no_safe_option"; const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.recommendationMode, "no_action"); });
test("insufficient evidence produces no safe recommendation", async () => { const c = context(); c.validation.status = "insufficient_evidence"; c.decision.recommendationMode = "no_safe_option"; c.decision.recommendedOption = null; const result = await collectRecommendationIntelligence({ collected: c }); assert.equal(result.recommendationMode, "no_safe_recommendation"); assert.equal(result.recommendations.length, 0); });
test("recommendation does not mutate context or log private data", async () => { const c = context({ memory: [{ value: "SECRET" }] }); const before = structuredClone(c); const logs = []; await collectRecommendationIntelligence({ request: { requestId: "r", message: "PRIVATE" }, collected: c, logger: { info(event, fields) { logs.push({ event, fields }); } } }); assert.deepEqual(c, before); assert.doesNotMatch(JSON.stringify(logs), /SECRET|PRIVATE/); });
test("Gateway sends recommendations once and UI remains provider blind", async () => { let calls = 0; let payload; const usage = []; const result = await askCompanionGateway({ user: { id: "u", accountType: "standard" }, body: { question: "What happens next?", feature: "ask_meetro" }, backendContext: { activeWorkflow: { workflowId: "wf", status: "evaluation", evaluationStatus: "saved" } }, providers: { openai: { name: "openai", async complete(input) { calls += 1; payload = JSON.parse(input.messages[1].content); return { answer: "Review what deserves attention." }; } } }, recordUsage(event) { usage.push(event); }, logger: null }); assert.equal(calls, 1); assert.equal(usage.length, 1); assert.ok(payload.recommendation.recommendationMode); assert.equal(payload.recommendation.execution.performed, false); assert.equal(result.recommendation, undefined); });

